### ISSUE TITLE
Lost my created containers

### ISSUE THREAD

**Issue by deimidis** [mozilla/multi-account-containers#949] opened 2017-11-10 18:01 UTC
After reboot nightly today, custom Containers disappeared from the list, and now only standard appear. My custom Containers were converted to the "standard one" with the same Color and Icon (but different name)

58.0a1 (2017-11-10) (64-bits) on Manjaro Linux (but installed through tar.gz downloaded from Mozilla's website). Multi-Account Containers addon: 4.0.3

**Comment by drod3763** [comment] 2017-11-10 22:16
Same here. All my containers gone. I didn't even get a conversion, just the basic four you start with.

**Comment by TheSweetLily** [comment] 2017-11-10 23:56
Can also confirm. 

I tried re-creating them but they get lost on each restart.

**Comment by hwine** [comment] 2017-11-11 00:07
same on macOS 10.12.6 -- I didn't realize how bad I was hooked on them - withdrawal is not fun

**Comment by thurloat** [comment] 2017-11-11 02:10
Chiming in with 58.0a1 (2017-11-10) (64-bits)  on Windows 10

@hwine same story here, love my container tabs.

**Comment by btric-development** [comment] 2017-11-11 04:52
Same here, lost on each restart.

**Comment by cole-h** [comment] 2017-11-11 09:15
Likewise. Any way to get these back? I do happen to have a recent backup of my entire profile; is there any way to only move the container settings?

**Comment by fvsch** [comment] 2017-11-11 10:53
> Same here, lost on each restart.

Can confirm this part as well.

Steps to reproduce, with latest Nightly (20171110100139) and Multi-Account Containers 4.0.3.

1. Remove default containers.
2. Create a few custom containers.
3. Restart Nightly.

Result: containers created in step 2 are lost.

**Comment by zaleb** [comment] 2017-11-11 16:31
User Agent: Mozilla/5.0 (Windows NT 6.3; Win64; x64; rv:58.0) Gecko/20100101 Firefox/58.0
Build ID: 20171111100349

I have experienced the same behavior with the last 2 nightly updates I have run.

Further Information:
The containers actually appear to be intact however the Manage Containers page is reset to the 4 defaults. If I add the 3 additional containers I utilize, then all of the state within them appear to still exist and their functionality is normal at that point. Also the labels don't matter at all, I renamed the 4 defaults however their state is carried over despite them reverting back to the original default names; it would seem that the containers are simply referenced by their array index. 

Moreover, I use Cookie AutoDelete https://addons.mozilla.org/en-US/firefox/addon/cookie-autodelete/ which has container support and the results are the same here. The array position of the containers simply maps over despite whether they have been renamed (reset to defaults).

The underlying bug seems to simply be that the container label/icon settings are cleared out, however the underlying containers themselves still exist and make it through the nightly update.

**Comment by grahamperrin** [comment] 2017-11-11 23:14
Are symptoms reproducible if you use Firefox (without the extension) to manage the containers?

**Comment by rgamici** [comment] 2017-11-12 00:32
> Are symptoms reproducible if you use Firefox (without the extension) to manage the containers?
Yes.
I reported on bugzilla before knowing about this github (and the extension), and zaleb comment was posted on that thread as well.

**Comment by Radagast** [comment] 2017-11-12 01:48
I mentioned this in the Reddit thread regarding this:

> For what it's worth, I'm not using Cookie-AutoDelete and my containers are fine. I have 14 individual containers and I'm using the Multi-Accounts Container addon. Nightly has updated.

On Linux and Windows 10.

I didn't mention, I deleted the default containers and just use my own.

Build ID: 20171111100349

**Comment by rhssk** [comment] 2017-11-12 08:17
Looks like @Radagast is right. I tried disabling Cookie AutoDelete and restoring the old containers.json from backup. The containers are fine after restarting Nightly. After further testing it looks like the problem is Cookie AutoDelete "Enable Support for Firefox's Container Tabs" setting.

**Comment by arashpayan** [comment] 2017-11-12 08:39
Here's another data point. I'm running Nightly on Ubuntu 16.04.03. No Cookie AutoDelete extension installed.

After nightly updates itself, all my containers are gone and the defaults containers are only present. As others have noted, my session data is still present in the containers, because if I delete the default containers and recreate my containers with their original names again, I'm able to access my session data. However, the feature that catches your requests and asks you if you want to load the page in your specific container, doesn't work anymore. I need to open the container tabs first and then load the page.

**Comment by cole-h** [comment] 2017-11-12 08:42
@rhssk Interesting; I tried to both disable CAD and just turn off the Containers support and my Containers are still resetting after each restart. When I have more time on my hands I will do a full test of all my addons but for now I don't think it is EXCLUSIVELY CAD causing the problem. Also, @rgamici would you mind linking your bugzilla report so I (and others) may follow it?

**Comment by fvsch** [comment] 2017-11-12 10:22
I’m having this bug without Cookie Auto Delete (never used that extension).
But I do have Nightly set to forget cookies at the end of the session:

<img width="600" alt="Screen shot of preferences" src="https://user-images.githubusercontent.com/243601/32697854-fd45c994-c799-11e7-8e87-8fddf09a8297.png">

Also can someone link to the relevant bugzilla bug(s)?

**Comment by bunnybooboo** [comment] 2017-11-12 10:50
Referenced bugzilla bug:
https://bugzilla.mozilla.org/show_bug.cgi?id=1416468
but do note that the preferred workflow for containers bugs is via Github

**Comment by Radagast** [comment] 2017-11-12 14:16
I perhaps should have mentioned that I block cookies and only allow a select few.

**Comment by bunnybooboo** [comment] 2017-11-12 14:51
I'd like to add further detail here. I don't believe my containers are being reset each time I restart the browser. It seems to me at least, this resetting behaviour is only experienced when restarting the browser **after a Nightly update** has been implemented. Restarting my laptop (and I'm on a fully encrypted LVM) even in a new volume after a hard reset (by pulling the power) - does not reproduce this bug [Testing further].

**Comment by danemacmillan** [comment] 2017-11-12 16:56
This has happened for each update I ran this weekend--two in total. All of my custom containers are gone, and the defaults are restored with their original color and icon.

**Comment by drod3763** [comment] 2017-11-12 19:36
I can confirm that its reset upon each restart. This has made containers totally useless to me at this time.

**Comment by jaybaeta** [comment] 2017-11-13 04:00
I've been experiencing this as well for the past three days, and the issue is still present in the latest Nightly update (58.0a1 build 20171112100435).

**Comment by lissyx** [comment] 2017-11-13 10:16
For me, it regressed between 20171105220721 and 20171112220346

**Comment by shadowbottle** [comment] 2017-11-13 14:15
No CAD, never used it. Same thing. And just happened again on 58.0a1 (2017-11-12) (64-bit) 20171112220346. Sucks, cause I was using a custom container to isolate Facebook and now it's been dumped in with the rest of my tabs.

**Comment by Kourai** [comment] 2017-11-13 14:58
For me, it started this weekend, and the last firefox update (59.0a1 20171113100232) didn't solve it.
Reproduce both on Windows and Linux versions.

**Comment by Softvision-MariusComan** [comment] 2017-11-13 17:31
I have managed to reproduce this issue on Windows 10 x64, Ubuntu 14.04 x64, Mac 10.12.6 with the latest Nightly (58.0a1) build installed. 
The issue is 100% reproducible if you have the "about:preferences#containers" page opened when you restart the browser. 
However the issue is also reproducible without the "about:preferences#containers" page opened, but is intermittent.
To reproduce the issue please use the following STR:

**[Prerequisites]:**
- Have a Firefox profile with the latest "Multi-Account Containers" add-on version (4.0.3 custom built on 11.13.2017) installed.
- Have at least 1 custom container created.

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites 
2. Open the "about:preferences#containers" page.
3. Restart the browser and observe the behavior.

**[Expected result]:**
- The custom containers are still displayed.

**[Actual result]:**
- Only the default containers are displayed.

**[Regression window]:**
Last good revision: 6d174f463c1a70aa68e4f2292bd0aee6297c4947
First bad revision: 31b7eb1946621744296146e50b719b326dde10c9
Pushlog:
https://hg.mozilla.org/integration/mozilla-inbound/pushloghtml?fromchange=6d174f463c1a70aa68e4f2292bd0aee6297c4947&tochange=31b7eb1946621744296146e50b719b326dde10c9

**[Notes]:**
- If you choose to delete the default containers, after restart they will be re-displayed.
- Attached a screen recording of the issue:
![rec of the issue](https://user-images.githubusercontent.com/31243259/32739606-132549d2-c8a9-11e7-9753-60a3d50ebd32.gif)

**Comment by cole-h** [comment] 2017-11-13 17:50
@Softvision-MariusComan Also reproducible on Nightly 59 (as expected). Thanks for dealing with the STR, as the rest of us forgot.

**Comment by lissyx** [comment] 2017-11-13 17:52
@bakulf Looks like @Softvision-MariusComan did the mozregress before I could, and it's bug https://bugzilla.mozilla.org/show_bug.cgi?id=1347515 as you feared.

**Comment by KwanEsq** [comment] 2017-11-13 21:27
If anyone here needs a work-around until it's fixed, you can turn off session auto-restore and restore manually from the app menu on restart, the bug only occurs during auto-restore, I believe.
(But it should hopefully be fixed soonish)

**Comment by cole-h** [comment] 2017-11-13 23:13
@KwanEsq That worked; many thanks! Only downside is all my default sites seem to have been forgotten.

**Comment by bunnybooboo** [comment] 2017-11-14 09:41
IIRC this breakage happened somewhere between 20171109* and 20171110* as I update twice daily and use Nightly as my everyday browser. Not sure how to edit MozRegression persistence to preserve containers so can't be more helpful right now.

**Comment by xolve** [comment] 2017-11-14 13:38
Seems to be fixed in latest nightly. Older containers are lost, but new ones I added are there.

**Comment by bkatbeh** [comment] 2017-11-14 13:40
@xolve same here

**Comment by staabm** [comment] 2017-11-14 16:28
any recovery path to get the config back? I had a lot of tabs configured in different containers and all this is gone... :-/

**Comment by KwanEsq** [comment] 2017-11-14 17:09
@staabm if you mean existing tabs, they are still in their containers, they just don't have styling.  If you recreate the containers, they will be styled again. Try and recreate containers in the same order though, otherwise tabs won't be in the container you expect.  Although you can just create containers one at a time, see which tabs are in them, then rename them appropriately. (The tab bar styling won't initially return though, you'll have to check the address bar)

If you mean the "Always open in ${container}" settings for different domains, I'm afraid those are gone, and I do not think retrievable.

**Comment by arashpayan** [comment] 2017-11-15 02:34
I just restarted to the latest nightly update, and my containers remained intact. I tested 2 default pages and they both correctly redirected to their appropriate container.

Thank you so much for the speedy fix! :)

**Comment by rhssk** [comment] 2017-11-15 07:12
@staabm AFAIK containers and their properties are stored in `containers.json` file. "Always open in X" settings are found in `browser-extension-data/@testpilot-containers/storage.js` file. In my case updating Nightly to the newest version and restoring both files from backup were enough.

**Comment by staabm** [comment] 2017-11-15 08:10
@rhssk does FF automatically create backups of this files when updating major versions or did you have backups on your own of this thingsß

**Comment by rhssk** [comment] 2017-11-15 09:40
@staabm Don't think so, I used my own backups. Don't know what OS you're using but on Linux it's fairly easy to automate profile backups before upgrading Nightly with a package manager. For example, [alpm-hooks](https://www.archlinux.org/pacman/alpm-hooks.5.html) for Arch Linux and  [DPkg::Pre-Invoke](https://unix.stackexchange.com/questions/76294/hook-a-script-to-apt-get/76297#76297) for Debian.

**Comment by groovecoder** [comment] 2017-11-16 16:05
Should be fixed by https://github.com/mozilla/multi-account-containers/commit/a7be3c9935ac42469a1030c3714c656d6e6d0948 in the latest 4.1.0 release. It's available here on GitHub and in the review queue on AMO now.

**Comment by bkatbeh** [comment] 2017-12-04 09:36
Same issue again after updating nightly to the latest version!

**Comment by kubrickfr** [comment] 2017-12-04 16:27
yep, this has happened again...

**Comment by groovecoder** [comment] 2017-12-04 16:31
Hmm ... re-opening for @jonathanKingston and/or @bakulf.

**Comment by lissyx** [comment] 2017-12-04 16:35
@bkatbeh @kubrickfr Can you document more which update you are on? With 20171203220339 I have no issue (nightly/linux).

**Comment by kubrickfr** [comment] 2017-12-04 16:37
@lissyx 20171204100103 for me

**Comment by cole-h** [comment] 2017-12-04 18:58
Could this be related to https://bugzilla.mozilla.org/show_bug.cgi?id=1419591 ?

**Comment by bkatbeh** [comment] 2017-12-04 19:52
@lissyx 20171204100103 on Mac

**Comment by groovecoder** [comment] 2017-12-05 16:35
@SoftVision-EmilPasca - can you reproduce this on latest Nightly with latest Containers add-on installed?

**Comment by SoftVision-EmilPasca** [comment] 2017-12-06 13:45
I had tested this issue on Windows 10 x64, Mac 10.12 and Ubuntu 14.04 x64 with the latest Nightly (59.0a1-20171205220055) and the latest Multi-Account Containers (4.1.0) and haven't managed to reproduce the issue.

I have tested this having a new clean Firefox profile and Multi-Account Containers installed with a few custom containers created and whenever restarting or updating the browser to the latest Nightly version, the custom container tabs aren't deleted.

I have also tried to reproduce this with an older Firefox profile, with the latest Containers and also other add-ons installed and haven't been able to reproduce this. 
@groovecoder Will investigate this further and come back with the results.

**Comment by groovecoder** [comment] 2017-12-19 18:24
No reports for 15 days. Looks like everyone has the fix. Please re-open if you see this again.

**Closed by groovecoder** 2017-12-19 18:24 UTC
Labels: bug, needs: Testing, P1 bug

**Comment by half0wl** [comment] 2017-12-24 07:20
This just happened to me when I updated to FF 58.0b12 (64-bit). I'm on macOS 10.13.1 and Multi-Account Containers 4.1.0. All my custom containers disappeared and only the basic four are present (Personal, Work, Banking, Shopping). 

Just a heads up since I'm unable to reproduce this and everything currently works as expected, so I'm assuming this only happened when I updated FF.

(Apologies for re-opening this if this issue isn't related — I didn't want to create a new ticket.)

**Comment by seniorivn** [comment] 2018-06-01 10:05
This just happened to me when I updated to FF 60.0.1 (64-bit). I'm on Linux  and Multi-Account Containers 6.0.0. All my custom containers disappeared and only the basic four are present (Personal, Work, Banking, Shopping).

**Comment by apaijmans** [comment] 2018-06-18 11:48
I ran into the same issue: all custom containers are deleted after restarting Firefox. In my case I think it had to do with the cookies settings I used in Firefox ("keep until I close Firefox"). After changing the settings to "keep until they expire", the custom containers are still there after restarting Firefox. I would like to delete cookies after each session though, so it would be great if this could be fixed somehow?

**Comment by wsot** [comment] 2018-10-08 12:56
Just lost all of my containers after restarting Firefox too. This is not the first time it has happened, but I frequently use Firefox and it has only happened twice now. In neither case did I change any settings.

However, I think Firefox did just update, and I use a single Firefox installation with two separate profiles so it may have been something to do with the update and profile combination.
62.0.3 (64-bit) on OSX

**Comment by seniorivn** [comment] 2018-10-09 10:57
@wsot happens to me regularly now, feels like bad design

**Comment by groovecoder** [comment] 2018-10-09 15:02
I've only noticed this happen when I switch channels with the same profile - e.g., from Nightly to Release, or Release to Beta, etc. Or sometimes when my channel gets a fresh update - e.g., when Nightly goes from 63 to 64.

Anyone else notice that's when it seems to happen?

**Comment by jacekmusial** [comment] 2018-11-02 18:06
I have experienced this "clearing" of the containers. Using only one nightly in the W10.

**Comment by Xorok** [comment] 2019-02-04 19:03
> I've only noticed this happen when I switch channels with the same profile - e.g., from Nightly to Release, or Release to Beta, etc. Or sometimes when my channel gets a fresh update - e.g., when Nightly goes from 63 to 64.
> 
> Anyone else notice that's when it seems to happen?

I've had the same thing happen to me today :/
Accidentally clicked on the regular Firefox icon instead of Nightly and now all my containers are gone...
About 20 or more...

**Comment by escapewindow** [comment] 2019-02-04 19:07
https://blog.nightly.mozilla.org/2019/01/14/moving-to-a-profile-per-install-architecture/ ?
If this is the issue, running Nightly should give you your containers back.

**Comment by Xorok** [comment] 2019-02-04 22:20
No, it didn't. I had to recreate them.

Regular Firefox still opens with the same profile as Nightly on my machine, the default profile as seen in the profile manager. Probably because I have had several profiles to begin with when this change was rolled out?

> Users who already have created manually separate profile for different installations will not notice the change (this has been the advised procedure on Nightly for a while).

How was this change implemented? How can I limit my profiles to Nightly or Release channel? Does it work by passing `-p` on the default shortcuts that the Firefox (Nightly) installer creates?

**Comment by AluisioASG** [comment] 2019-02-05 12:59
@Xorok when I tested after the upgrade, it looked like each install can have a different default set in its profile manager. Maybe you can fix it that way?

**Comment by wjessop** [comment] 2019-05-04 00:32
Just lost all my containers. Seems one of the Firefox windows crashed and now there is no option to use or create containers. Restarted Firefox, still no options.

**Comment by sbssk8** [comment] 2019-05-04 14:21
Same, today I lost all my containers. I had about 14 containers and now I just have Personal, Work, Banking and Shopping. Strang that work still keeps my hidden tabs but got the original name "Work" and I lost all my cookies.

**Comment by T3chminator** [comment] 2019-05-04 19:34
Is there an alternative to this shit?

**Comment by 3j9fkyahunqoxwqu** [comment] 2019-05-04 22:43
I also had same issue but fortunately after several hours of being unable to do my work, finally my browser get the studies and the addons enabled again but lost all my +10 containers.
I am creating all of them now :\ 
Its OK, all people may do mistakes but i hope firefox plan more in the future so this problems become lower.

**Comment by raulcano** [comment] 2019-05-05 01:12
This just happened to me as well.
For a few hours the Multi-containers addon was considered not having the Mozilla signature and disabled. After reboot, the addon was re-enabled , but the settings are in default now, so I lost all my containers. Not cool.

**Comment by Temporalin** [comment] 2019-05-05 12:25
Also happened to me.

I left Firefox downloading a file, I logged in the computer after a day without using it, and there was a message about some add-on being problematic or something (sorry, I don't exactly remember what it said). There was a link to "know more" and a new tab opened, it was a submenu of the add-ons config, but nothing appeared about that problematic addon.

I restarted Firefox, everything looked the same but when I'm about to open one hidden container, I see it's not there.

I was able to recover my tabs from `%appdata%\Mozilla\Firefox\Profiles\<<<my-profile>>>\browser-extension-data\@testpilot-containers\storage.js.migrated`, but I don't know what caused this or how to restore it without parsing the JSON file and reopen everything by hand.

**Comment by andrewmcguinness** [comment] 2019-05-05 14:22
People suffering from this early may 2019 (including me) -- seems to be a side-effect of the issue at https://blog.mozilla.org/addons/2019/05/04/update-regarding-add-ons-in-firefox/
Bug https://bugzilla.mozilla.org/show_bug.cgi?id=1548973

**Comment by walkenzoy** [comment] 2019-05-05 20:44
Been hitting this too, due to the extensions signing issue listed above.

I did not have a storage.migrated file to recover from.

I did end up recovering my container tabs: By clicking "edit containers" in the extension, then clearing out the name field, then clicking on it, I was presented with an auto-complete list of container names I had previously created, and re-creating the containers restored their previous contents.

**Comment by vsrawat** [comment] 2019-05-06 16:03
Yesterday, my ff had disabled all add-ons and was refusing to download and install addons afresh, as reported by many users. Then the problem rectified on its own.

But today I noticed that all my containers are gone.

How do I restore them. I have backup of my ff profile from about a week ago. Which folders/ files to restore from that so as to get back all my containers?

Thanks.

**Comment by KwanEsq** [comment] 2019-05-06 16:12
> How do I restore them. I have backup of my ff profile from about a week ago. Which folders/ files to restore from that so as to get back all my containers?
> 
> Thanks.

In your backups should be a file named "containers.json".  If you copy that into your current profile (with Firefox closed), replacing the file there, it should restore the container definitions.

**Comment by Whoareyouagain** [comment] 2019-05-06 17:41
I have the same issue again because of extension signed issue. This is the second time my container setting is wiped. It is getting annoying when I have everything set up the way it is. I have 8 different containers set up for specific sites and they are vital for what I do. And now I have to redo everything again which can take me up to an hour to set it back up. Since it is becoming an issue, then this addon need to create a backup file to prevent this issue coming back up. 

@groovecoder Can you please reopen this issue?

**Comment by T3chminator** [comment] 2019-05-06 20:00
> 
> 
> > How do I restore them. I have backup of my ff profile from about a week ago. Which folders/ files to restore from that so as to get back all my containers?
> > Thanks.
> 
> In your backups should be a file named "containers.json". If you copy that into your current profile (with Firefox closed), replacing the file there, it should restore the container definitions.

This might be the answer to restoring the containers. May I know where to find this 'containers.json' file?

**Comment by T3chminator** [comment] 2019-05-06 20:00
@Whoareyouagain Could you please let me know where to find the 'containers.json' file?

**Comment by kingjr** [comment] 2019-05-10 21:10
@T3chminator `/your/home/folder/.mozilla/firefox/<random_string>.default/containers.json`

**Comment by DrButthead** [comment] 2019-10-07 08:41
I have come across the same issue - FF version: 69.0.2

**Comment by j-cr** [comment] 2020-10-26 07:27
Same on 68.9, sigh.

**Comment by ejain** [comment] 2021-11-27 04:34
94.0.2. I had briefly disabled the extension to investigate a memory issue, not sure if that caused the containers.json to reset.

**Comment by T3chminator** [comment] 2021-11-27 08:20
They are available now so probably it is what you said about maintenance
which means clicking on that reset button does not remove them all which is
good.

**Comment by Jieiku** [comment] 2022-11-08 19:44
> 94.0.2. I had briefly disabled the extension to investigate a memory issue, not sure if that caused the containers.json to reset.

I have experienced all my custom containers being removed after disabling the extension and then turning it back on, it has only happened once so far, if I see it happen again and can reproduce it I will post back.

**Comment by Korb** [comment] 2024-08-16 07:22
> I have experienced all my custom containers being removed after disabling the extension and then turning it back on,

This exact situation happened to me on 2021-03-28. I'm sorry that the process of fixing this critical bug took at least **five years**.
