### ISSUE TITLE
Multi-account container button having a random long delay showing containers list

### ISSUE THREAD

**Issue by mantrax314** [mozilla/multi-account-containers#2447] opened 2022-11-17 22:08 UTC
### Before submitting a bug report

- [X] I updated to the latest version of Multi-Account Container and tested if I can reproduce the issue
- [X] I searched for existing reports to see if it hasn't already been reported

### Step to reproduce

Firefox Version: 108.0b2 (64-bit)
Open Firefox, click in Multi-account container button

### Actual behavior

The containers list took very much time to load

### Expected behavior

The containers list should show immediately 

### Additional informations

It just happened after updating to Firefox Version: 108.0b2 (64-bit) (MacOS)

**Comment by michrogit** [comment] 2022-11-18 09:26
I can confirm. Firefox version: 108.0b2 (64-bit), macOS (Big Sur 11.7). When I click on the "Multi-Account Containers" button in the toolbar I can't see the list and other options, everything is totally white. I have to wait, click, wait and then it works... The delay happens randomly but with an annoying frequency.

**Comment by dannycolin** [comment] 2022-11-24 00:08
@mantrax314 and @michrogit could you record a performance profile and share it here? You can find the instructions at https://profiler.firefox.com/docs/#/./guide-getting-started

**Comment by michrogit** [comment] 2022-11-24 10:08
@dannycolin, I'm not an expert and I'm at work right now, so I read the instructions very quickly and maybe I did something wrong... Could this help? Do I need to make a different or longer registration? What should I do during registration? Let me know if that's enough.

https://share.firefox.dev/3VrmzxR

**Comment by dannycolin** [comment] 2022-11-25 17:32
@michrogit That looks like a good recorded profile to me. I'll investigate it on my side and ask the pref team for guidance since I'm not an expert in reading this kind of debugging report myself. With the Thanksgiving holiday in the US, we might only get feedback next week. I'll keep you posted. Thanks again :).

**Comment by dannycolin** [comment] 2022-11-25 19:47
Quick follow-up: It might be a related to [bug 1800992](https://bugzilla.mozilla.org/show_bug.cgi?id=1800992) that has a fix scheduled to land in 108.0b7.

**Comment by dannycolin** [comment] 2022-12-06 23:51
Now that 108.0b7 is out, do you still experience this issue?

**Comment by michrogit** [comment] 2022-12-07 09:34
@dannycolin, I updated my beta today from version 108.0b7 (now the version is 108) I don't experience the issue anymore. The problem seems solved.

**Comment by dannycolin** [comment] 2022-12-07 17:12
Great! Glad the patch upstream seems to have solved it. I'm going to close this issue now but don't hesitate to file a new one if a similar issue resurface again in the future.

**Closed by dannycolin** 2022-12-07 17:12 UTC
Labels: bug, Component: Panel
