### ISSUE TITLE
[Feature request] Add ability to do rules with wildcard domains

### ISSUE THREAD

**Issue by bagasse** [mozilla/multi-account-containers#1588] opened 2019-11-28 14:20 UTC
- Multi-Account Containers Version: 6.1.1
- Operating System + Version: Fedora 30
- Firefox Version: 70.0.1
- Other installed Add-ons + Version + Enabled/Disabled-Status:

Ability to make wildcard rules like (*.example.com) would be very nice to make one rules instead of multiples (eg: to open all corporate site in the same container without adding them one by one)

### Actual behavior
You can only make rule like:

"following urls will be opened in 'work' container":
* www.example.com
* foo.example.com
* bar.exmaple.com
* baz.example.com
* foo.example2.com
* [...]

### Expected behavior

"following urls will be opened in 'work' container":
* "*.example.com"
* foo.example2.com
* [...]

**Comment by kendallcorner** [comment] 2019-12-04 16:52
This looks like a duplicate of #473. Please vote or discuss on that issue. I'll close this, but feel free to reopen if you think it's a different issue.

**Closed by kendallcorner** 2019-12-04 16:52 UTC
