### ISSUE TITLE
Feature request:

### ISSUE THREAD

**Issue by ecotechie** [mozilla/multi-account-containers#2302] opened 2022-03-04 20:42 UTC
It would be very handy if there was a setting to allow for opening a new tab in the same container that the current tab is in. I see that I can use the middle button to open a link and it will open on the same kind of container, but if I'm in a container tab and then Ctrl + t to open a new tab, I have to manually set the container again. I now there are shortcuts per container, but this would make for an added/easier workflow.

**Comment by achernyakevich-sc** [comment] 2022-03-05 07:01
It looks as duplicate of series of other issues. Probably it will be easier or you to close this one and vote for the old one that there many discussions about. :)

**Comment by dannycolin** [comment] 2022-06-07 00:45
Duplicate of #2054.

**Closed by dannycolin** 2022-06-07 00:45 UTC
