### ISSUE TITLE
Enabling Containers causes Jerky Animation in Opening and Closing Tabs

### ISSUE THREAD

**Issue by mrdokenny** [mozilla/multi-account-containers#444] opened 2017-04-10 14:40 UTC
Steps to reproduce:
1. Open up a lot of tabs using the + button
2. Close a bunch of tabs using the X button

Actual Result:
Tab Animation for closing and opening is not smooth 

Expected Result:
Tab Animation should be smooth. Also, disabling Containers resolves this issue. One of the older versions didn't have this issue as well.

**Comment by jonathanKingston** [comment] 2017-04-11 02:14
Looks like we might need @kjozwiak to look into replicating this if it was caused by a latest update.

**Comment by Stis** [comment] 2017-04-18 13:12
52.0.2 x64 on Win Seven.
Fresh profile, Containers 2.2.0

The... smoothless? lack of smooth? (I miss vocabulary here) is also noticeable with using CTRL+T and CTRL+W.

**Comment by kjozwiak** [comment] 2017-04-19 05:05
@jonathanKingston, using Win 10 x64, I'm definitely seeing more jank/slowdowns with 2.2.0 compared to 2.1.2 when it comes to creating and closing tabs. Using the [fx profiler](https://perf-html.io/), I did notice that `this.PromiseWalker.scheduleWalkerLoop` is taking a considerable amount of more time under 2.2.0. Example:

* first tab opened under 2.1.2, `this.PromiseWalker.scheduleWalkerLoop` took 27ms
* second tab opened under 2.1.2, `this.PromiseWalker.scheduleWalkerLoop` took 22ms

* first tab opened under 2.2.0, `this.PromiseWalker.scheduleWalkerLoop` took 96ms
* second tab opened under 2.2.0, `this.PromiseWalker.scheduleWalkerLoop` took 81ms

I'm not sure if the above is related to the slow down @mrdokenny and @Stis are seeing. When I was testing this on my Win 10 desktop machine, both 2.2.0 and 2.1.2 looked pretty janky in general which we already knew was an issue. However, 2.2.0 does get a lot slower at times.

@jonathanKingston, mind taking  a look at the stacks in the profiles that I attached below and see if you can spot something that might be causing the jank? Let me know if there's anything that I can help with here... It's going to be hard to get some solid STR as this is pretty subjective and depends on the machine you're running this on... With my macOS machine, it's definitely a lot faster than the Windows machine.

Profiles:

* https://perfht.ml/2oKhXWP -> opening two container tabs using 2.2.0
* https://perfht.ml/2oKbknA -> opening two container tabs using 2.1.2

**Comment by mrdokenny** [comment] 2017-05-03 03:25
Any update on this? @jonathanKingston

**Comment by jonathanKingston** [comment] 2017-05-03 14:55
@mrdokenny I'm currently on PTO at the moment. However I have been working on making the extension use less SDK at the moment as I wasn't able to capture where the issues were seeing from @kjozwiak's comments.

The move to using less SDK code might actually fix the perf in the process anyway.

**Comment by mrdokenny** [comment] 2017-05-03 17:10
@jonathanKingston Hopefully that works cause another side effect that I'm seeing on another weaker computer is slow new tab page loads when using multiple processes.

**Comment by groovecoder** [comment] 2017-12-05 16:46
We are off of slow SDK code and this bug appears to be fixed.

**Closed by groovecoder** 2017-12-05 16:46 UTC
Labels: bug, needs: Testing
