### ISSUE TITLE
Ability to backup config to a file

### ISSUE THREAD

**Issue by skank** [mozilla/multi-account-containers#1427] opened 2019-05-26 07:32 UTC
Recent events has caused users to lose their configs.
The config is rather cumbersome with a lot of clicking etc.

Ideally we should be able to export settings to a file.
As an example uBlock & uMatrix has this very essential feature.

**Comment by julien-garrigue** [comment] 2019-05-29 16:15
Ah yes, that would be very very useful to save the config somewhere. Thank you

**Comment by cdev45** [comment] 2019-11-03 20:46
Hi Team. I LOVE this Firefox Add-on, however we need the ability to backup our settings during device formats, device transfers, etc. Starting from scratch is a nightmare. Thank you!

**Comment by kendallcorner** [comment] 2019-12-06 21:49
Linking to the original #1282 , but I'm leaving this open since a PR is submitted on it.

**Comment by dannycolin** [comment] 2022-08-23 23:48
Duplicate of #1282

**Closed by dannycolin** 2022-08-23 23:48 UTC
Labels: Feature Request
