### ISSUE TITLE
YT could not be opened after update (6.1.1 to 6.2.0) and closed other tabs

### ISSUE THREAD

**Issue by giveitaway212** [mozilla/multi-account-containers#1634] opened 2020-02-13 18:32 UTC
- Multi-Account Containers Version: Version 6.2.0
- Operating System + Version: Win 10
- Firefox Version: 68.0
- Other installed Add-ons + Version + Enabled/Disabled-Status: UBO + Dark Night Mode

### Actual behavior
Any URL used by YouTube® could not be opened in private windows after updating from Version 6.1.1 to Version 6.2.0. In addition, if there were opened two tabs other than YouTube®, and a third  tab was opened in which any YouTube® was typed, this third tab did not open YouTube® but closed the second tab instead. The URLS could be typed in the URL bar, but nothing happened on submission. 

### Expected behavior
YouTube® associated URLS open in private windows.

### Steps to reproduce
1. Update from version 6.1.1 to version 6.2.0 (under the above-mentioned conditions)
2. Open a private window 
3. Type and try to submit any YouTube® URL

### Notes
Downgrading version 6.2.0 to version 6.1.1 worked fine. And, yes, it worked and now works again in private windows. 

Thank you very much.

**Comment by kendallcorner** [comment] 2020-02-13 22:13
Thanks for filing this. I am not able to reproduce, and this is very strange since the add-on is disabled in private windows. I would say it's not the add-on, but downgrading seems to work for you, which does point toward the addon. If you are happy with the downgrade for now, I would just wait to see if anyone else is having this issue.  If you want to try to upgrade ASAP, you could try upgrading again and/or refreshing your profile: https://support.mozilla.org/en-US/kb/refresh-firefox-reset-add-ons-and-settings

**Comment by whoisrich** [comment] 2020-02-14 11:22
I had the exact same issue, it's not YT specific.  After the recent update with sync support, the container extension started running in private mode, even though it shouldn't.

If I had a site set to prompt for a container, the prompt would show up in a private window.  If the site was always open, it would hang or close the private window.

Removing, restarting Firefox, installing the extension seems to have fixed it, with no loss of settings, but obviously something went wrong in the updating process.  I am using Firefox 68.1.0esr at work.

**Comment by dannycolin** [comment] 2023-01-06 04:19
Closing since refreshing the profile seems to have solved the issue. If you can still reproduce in the latest MAC and Firefox version, please don't hesitate to mention it and I'll reopen this bug report.

**Closed by dannycolin** 2023-01-06 04:19 UTC
