### ISSUE TITLE
Please reopen and handle #1450 - "Installation aborted because the add-on appears to be corrupt"

### ISSUE THREAD

**Issue by gilad-cohen** [mozilla/multi-account-containers#1793] opened 2020-07-12 19:37 UTC
Problem is still reproduced though for some reason [the issue](https://github.com/mozilla/multi-account-containers/issues/1450) is closed.

**Comment by dannycolin** [comment] 2023-01-01 00:40
If you mean that it still happen in Tor Browser, that is expected since Tor always run in private mode and Multi-Account Container doesn't support it. Closing for now but I can reopen if you're able to reproduce in a regular session in Firefox.

**Closed by dannycolin** 2023-01-01 00:40 UTC
