### ISSUE TITLE
Allow to include paths in Always open site in container

### ISSUE THREAD

**Issue by ThomasBleijendaal** [mozilla/multi-account-containers#2049] opened 2021-05-11 09:41 UTC
Currently, only host names can be added to the list of Sites assigned to a container. For some sites, it is highly useful to open certain paths in certain containers, for example:

- dev.azure.com/ClientA -> Container A
- dev.azure.com/ClientB -> Container B

Now I cannot configure this, and if I configure dev.azure.com to be always be opened in Container A, I cannot reach dev.azure.com/ClientB since it must be accessed by an account which is logged in in Container B. If I open dev.azure.com/ClientB in Container B, the tab closes and the and the site is opened in Container A, which is not allowed to access that Azure DevOps account.

**Comment by grahamperrin** [comment] 2021-05-12 20:53
▶ #691

Please, can you close this duplicate issue? Thank you.

**Comment by dannycolin** [comment] 2022-12-28 01:22
Duplicate of #691

**Closed by dannycolin** 2022-12-28 01:22 UTC
