### ISSUE TITLE
[Feature Request] Regex: Allow editing rules in regular expression?

### ISSUE THREAD

**Issue by Endle** [mozilla/multi-account-containers#1183] opened 2018-04-05 22:35 UTC
### Actual behavior

Added <google.com> to  containerA

### Expected behavior

I can add a rule `*.google*.com`  
So all my visits to <mail.google.com> , <translate.google.com> will be handled within containerA

**Comment by benjamink** [comment] 2018-05-20 13:45
Yes please.

**Comment by emilio-aburto** [comment] 2018-06-14 09:28
Pleaaase <3

**Comment by castillar** [comment] 2018-12-11 20:08
Implementing this could fit neatly with implementing issue 1317 (https://github.com/mozilla/multi-account-containers/issues/1317)--the ability to manually add sites or wildcards to a container list would be *enormously* useful.

**Comment by dueyfinster** [comment] 2019-08-09 08:08
I will close the request on Mozilla for the same: https://bugzilla.mozilla.org/show_bug.cgi?id=1572403

**Comment by dannycolin** [comment] 2019-09-17 15:00
FYI, there's an addon that let you use regex https://addons.mozilla.org/en-US/firefox/addon/containerise

Also, there's an issue (#473) and a PR (#1475)  to add a wildcard subdomains functionality.

**Comment by kendallcorner** [comment] 2019-12-05 21:48
Hi. This looks like a duplicate of #473. Please vote (:+1:) or discuss on that issue to show your interest. I'll close this, but feel free to reopen if you think it's a different issue.

**Closed by kendallcorner** 2019-12-05 21:48 UTC
