### ISSUE TITLE
"Remember my decision for this site" checkbox on Open this site in your assigned container? page does not work

### ISSUE THREAD

**Issue by mglick-wd** [mozilla/multi-account-containers#2293] opened 2022-02-17 14:03 UTC
- Multi-Account Containers Version: 8.0.1
- Operating System + Version: Windows 10
- Firefox Version: 96.0 (64-bit)
- Other installed Add-ons + Version + Enabled/Disabled-Status:

### Actual behavior
Checking the "Remember my decision for this site" checkbox on the "Open this site in your assigned container" page and then clicking on the "Open in Current container" button does not remember my decision. I continuously encounter this page every time I visit the site.

### Expected behavior
Remember my decision

### Steps to reproduce
1. Go to page not in a container (regular browser) that the containers once visited
2. Encounter "Open this site in your assigned container" page. Click on checkbox, click on "Open in current container"
3. Close browser and go to step 1. #2 happens again.

**Comment by achernyakevich-sc** [comment] 2022-02-18 06:51
This issue look like duplicate of others, you could search and close it.

In few words, this is not a bug but misinterpretation of the existing functionality by you. I know that developers could create a better label for the checkbox to explain real functionality behind of it. :)

Right now this feature works the following way - the checkbox state is used only to check that when you assigned some container to be automatically used to open particular site/domain not accidentally but intentionally. So by marking checkbox and opening in the assigned container you confirm that next time you don't need to be asked again. For all other cases it is just ignored.

Back to labels... Probably more correct label for the checkbox could be "Remember my decision for this site if I will open this site in your assigned container". :)

From other side I would propose to redesign whole dialog so that it will include only one button and selectbox. Dialog would be named "Confirm my choice". Selectbox would contain the following options (probably order could be different):

* `Open this site in your assigned container`
* `Open this site in your assigned container and do not ask again`
* `Open in Current container`
* `Open in Current container and forget about assigned container`

At the bottom button "Confirm" should be place.

As result we will have clear and straightforward UI that will clearly expose what need to be done and what end user would expect. If the last one options in the selectbox is hard to implement then it could be not included to the list.

I think this UI will prevent reporting again and again issues like this. :)

**Comment by achernyakevich-sc** [comment] 2022-02-18 07:24
@mglick-wd I just created #2294. I think if this will be implemented then your problem will be gone. I would like to propose you to close your issue and vote for that new one. :)

**Comment by mglick-wd** [comment] 2022-02-18 13:24
Thanks for the detailed explanation and proposed solution.

The issue I’m having is that I did accidentally open a site in a container (when I didn’t mean to), and now I’m always faced with this screen every time I visit it. Is the only solution for me to uninstall the add-in and reinstall it?

Michael Glick
Senior Vice President | Information Technology
Walker & Dunlop
P: 301-215-5591<tel:301-215-5591> M: 240-452-0225<tel:240-452-0225>
***@***.***

**Closed** 2022-02-18 13:26 UTC
