### ISSUE TITLE
extension storage: siteContainerMap@@_: (always open empty URL in a container)

### ISSUE THREAD

**Issue by grahamperrin** [mozilla/multi-account-containers#2031] opened 2021-04-25 08:46 UTC
This smells wrong: 

`siteContainerMap@@_:"{"userContextId":"1","neverAsk":false,"identityMacAddonUUID":"871e3bb7-4120-4a0f-bacc-7e7adee97f5b"}"`

![2021-04-25 09:27:25](https://user-images.githubusercontent.com/192271/115986698-6b1c3980-a5a9-11eb-94ac-36bf90543d50.png)

Whilst I don't imagine any problem from this particular entry (if I treat the line as essentially a cosmetic bug, not substantial): 

* is it symptomatic of **an environment** in which _substantial_ bugs might be more easily exposed? 

– that's a question for any developer with technical knowledge of the extension and/or [extension storage](https://developer.mozilla.org/en-US/docs/Tools/Storage_Inspector/Extension_Storage). 

Visualise, for example, an environment with 100% use of all CPUs plus thrashing of the hard disk drive that's used for the operating system, applications, user data and swap.

**Comment by dannycolin** [comment] 2022-12-28 03:17
What's the issue exactly here? Do you have a step-to-reproduce for ending up with a blank site assigned to a container?

**Comment by dannycolin** [comment] 2023-01-09 00:29
Closing since we don't have a step-to-reproduce

**Closed by dannycolin** 2023-01-09 00:29 UTC
