### ISSUE TITLE
all container settings lost

### ISSUE THREAD

**Issue by staabm** [mozilla/multi-account-containers#964] opened 2017-11-14 15:32 UTC
Recently with a auto update in my firefox nightly it seems my whole settings of the firefox containers experiment are resetted back to default. I guess the problem started with the update to FF59.

I am running on Win10x64.

all the containers I created for myself and attached tabs to them seem no longer present.

is this a known problem? anything I can do about it? any way to restore my container settings?

**Comment by SoftVision-EmilPasca** [comment] 2017-11-14 15:50
Hi @staabm, thanks for reporting this issue. However, this is a duplicate of https://github.com/mozilla/multi-account-containers/issues/949.

**Closed by SoftVision-EmilPasca** 2017-11-14 15:50 UTC
