### ISSUE TITLE
containers gone on disabling/ enabling add-on

### ISSUE THREAD

**Issue by vsrawat** [mozilla/multi-account-containers#1455] opened 2019-07-09 07:18 UTC
I had some problem with fb on fb, I started ff in safe mode, that disables all extensions and then I enabled them one by one and found the cause of the problem.

however I found that all my defined multi-containers are gone on disabling/ enabling this add-on.

Why should it happen? 
Disabling is not removing an add-on, disabling doesn't mean you should delete all content without asking the user or without even informing him?

I copied containers.json from my backup to my ff profiles folder and got container names back. But all websites assosiations I had defined across the months and years was still gone, and websites were opening in default ff setting of no container and I was not even getting aware that websites are not using containers. I don't know what other files are to be restored from back up to get that functionalty back.

Overall, yours is an excellent idea implemented in most shabby way.

I am giving up on your add-on, and shall have less troubles in my life.

**Comment by ganomi46** [comment] 2019-08-11 09:11
This is really annoying. I have to constantly recreate containers when going into safe mode.

**Comment by grahamperrin** [comment] 2021-04-30 11:24
> … constantly … safe mode. …

Not consistently reproducible. Here's a contained tab first in normal mode, then in safe mode: 

https://user-images.githubusercontent.com/192271/116688715-fd0fb200-a9ae-11eb-8333-d4949290ded6.mp4

Can someone provide steps to make this (safe mode case) consistently reproducible?

**Comment by Minigugus** [comment] 2022-01-14 16:33
@grahamperrin I think safe mode meant incognito mode here, not the real safe mode. Anyway the problem is now fixed since incognito is disabled.

https://github.com/mozilla/multi-account-containers/blob/19600a6f2d2b0bf3be3b12cee120d80dcb43e20b/src/manifest.json#L5

Also, some years ago the extension storage were reset whenever the extension was disabled, which was quite annoying, but I don't know whether that issue is fixed by now.

**Comment by dannycolin** [comment] 2022-10-11 22:42
Duplicate of #1236

**Closed by dannycolin** 2022-10-11 22:42 UTC
Labels: bug
