### ISSUE TITLE
Container broke: "old" and "new" tabs both listed, cannot show or hide

### ISSUE THREAD

**Issue by Koli0842** [mozilla/multi-account-containers#918] opened 2017-10-25 16:15 UTC
One of my containers randomly broke, from now on: Work tabs.
(If i recall correctly,) My work tabs randomly opened as another instance, i closed them back in to not have duplicates.
After probably days, I wanted to hide Work tabs, but there was only "Show tabs".
Restarting the browser doesn't help, "Show tabs" works once, opens the hidden work tabs, but stays as "Show tabs".
The ones "stuck" are the old open tabs, they do not update, and stay listed after i close them.
The ones I am using, cannot be hidden, as theres no Hide tabs option, but update and show up correctly.
When i click Show Tabs after a restart, the "stuck" tabs are still listed as not opened, and they open and get listed as opened aswell

The last work tab I opened was a local html file, which might cause it (?)

I have no idea how to reproduce the bug, or how to supply some data to help investigate.

Firefox 57.0b10
Containers 4.0.3

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/MAC-617)

**Comment by groovecoder** [comment] 2018-01-23 18:57
@SoftVision-EmilPasca - can you help us with some steps-to-reproduce this bug with hiding+showing container tabs?

**Comment by Koli0842** [comment] 2018-01-23 20:55
I'm afraid I cannot, but I have some additional details.
It only happened twice, and last time I couldn't get the addon to work at all, not even after reinstalling.
Using CCleaner I looked at Firefox extensions, and it showed both 4.0.3 and 5.0.1 installed, or 4.0.3 after I uninstalled from the browser. There were no obvious signs of the older install.
If I remember well, it was 4.0.3 that was first published on GitHub, and I originally had it installed from there, then later moved to AMO.
It might rather be a bug in the way Firefox handles extensions, and it got confused by me trying to install one i already had from a different source?
If you could give me steps to like, save the state of the extension, if it's in form of a directory under my profile or something, I could do that if it happens again.

**Comment by SoftVision-EmilPasca** [comment] 2018-01-25 17:24
I think I've managed to reproduce the issue you were reffering to @koli0842, can you please confirm that it is the one as described below:

[Affected versions]:
- Nightly build (60.0a1)
- Firefox Multi-Account Containers (5.0.1)

[Affected Platforms]:
- All Windows
- All Mac OS
- All Linux

[Prerequisites]:
- Have a Firefox profile with the latest "Firefox Multi Account Containers" add-on version (5.0.1) installed.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites.
2. Open a "Work" container tab and navigate to any website.
3. Open a "Work" container tab and drag a local file into it.
4. Click on the "View Work container" button and choose the "Hide this container" option.
5. Click on the "View Work container" button and choose the "Show this container" option.
6. Click on the "View Work container" button and observe the "Containers" panel.


[Expected result]:
- Each opened container tab is displayed in a list.

[Actual result]:
- Besides the opened container tabs list the previously hidden "Work" container tabs are still displayed.

[Notes]
- Attached a screen recording of the issue:
![containers_issue](https://user-images.githubusercontent.com/20083658/35402436-4345acfc-0205-11e8-93d1-f026eb46f245.gif)

**Comment by Koli0842** [comment] 2018-01-25 17:29
Yes, I can confirm, it looked and acted exactly like this, and I definitely did open local resources around the time it occurred

**Comment by schra** [comment] 2020-12-20 16:52
In #1717 (which is a duplicate of this issue) the root of this bug is described:

> Hide/Show tabs in this container actually closes and reopens tabs instead of hiding/showing, meaning it cannot reopen (show) privileged tabs (file, chrome, about, etc.)

**Comment by dannycolin** [comment] 2022-12-20 02:04
This is because the tab is actually closed instead of really hidden and we can't open a privileged URL (e.g. `file:///`) from the addon. Fixing #802 by correctly hiding the tabs instead of closing them will fix this issue.

**Comment by dannycolin** [comment] 2022-12-20 02:05
duplicate of #802

**Closed by dannycolin** 2022-12-20 02:05 UTC
Labels: bug, Needs: STR, Status: Obsolete
