### ISSUE TITLE
Inconsistent terminology ("containers" vs. "context")

### ISSUE THREAD

**Issue by attis** [mozilla/multi-account-containers#324] opened 2017-03-03 09:09 UTC
In most places the feature is called "container" but in right-click menu on a link it is called "open in a new tab in new context". It would make more sense to call this "open in a new tab in a container" - since it is not necessarily going to be a *new* container I would drop that word too.

**Comment by Softvision-VladBacia** [comment] 2017-03-03 10:17
@attis , Thank you for reporting this. 

I've tried to reproduce the issue but couldn't. Could you be more specific where do yo encounter the issue? Can you give me a little more info related to your Operating System and Firefox version? Are there additional steps in order to reproduce the issue?

This is the context menu for me:

![container right-click](https://cloud.githubusercontent.com/assets/9248513/23547231/17b43290-000b-11e7-8508-9723df4cfece.jpg)

**Comment by attis** [comment] 2017-03-03 10:29
Ah! In that case the issue is in Polish translation for this feature. If translated back into English it literally says "Open link in New Tab in New Context". This is outdated (and ridiculously long, by the way) ;)

 <img width="711" alt="screenshot" src="https://cloud.githubusercontent.com/assets/591754/23547726/95ea815c-0004-11e7-8763-bcdeeb5eef77.png">

**Comment by jonathanKingston** [comment] 2017-03-05 17:37
Pretty sure this will be a bug in the platform translation of polish as I don't think we touch this link in the code either.

**Comment by kjozwiak** [comment] 2017-03-30 21:34
@attis, as @jonathanKingston mentioned above, this looks like it's most likely a platform issue rather than a container experiment issue. If you're still seeing this, could you please create a new bugzilla issue using the template [here](https://bugzilla.mozilla.org/enter_bug.cgi?assigned_to=nobody@mozilla.org&blocked=ContextualIdentity&bug_file_loc=http://&bug_ignored=0&bug_severity=normal&bug_status=NEW&cc=tanvi@mozilla.com,kjozwiak@mozilla.com&cf_blocking_b2g=---&cf_blocking_fennec=---&cf_feature_b2g=---&cf_fx_iteration=---&cf_fx_points=---&cf_status_b2g_2_0=---&cf_status_b2g_2_0m=---&cf_status_b2g_2_1=---&cf_status_b2g_2_1_s=---&cf_status_b2g_2_2=---&cf_status_b2g_2_2r=---&cf_status_b2g_2_5=---&cf_status_b2g_2_6=---&cf_status_b2g_master=---&cf_status_firefox47=---&cf_status_firefox48=---&cf_status_firefox49=---&cf_status_firefox50=---&cf_status_firefox_esr38=---&cf_status_firefox_esr45=---&cf_status_thunderbird_esr38=---&cf_status_thunderbird_esr45=---&cf_tracking_b2g=---&cf_tracking_e10s=---&cf_tracking_firefox47=---&cf_tracking_firefox48=---&cf_tracking_firefox49=---&cf_tracking_firefox50=---&cf_tracking_firefox_esr38=---&cf_tracking_firefox_esr45=---&cf_tracking_firefox_relnote=---&cf_tracking_relnote_b2g=---&cf_tracking_thunderbird_esr38=---&cf_tracking_thunderbird_esr45=---&component=DOM:%20Security&contenttypemethod=autodetect&contenttypeselection=text/plain&defined_groups=1&flag_type-203=X&flag_type-37=X&flag_type-4=X&flag_type-41=X&flag_type-5=X&flag_type-607=X&flag_type-720=X&flag_type-721=X&flag_type-737=X&flag_type-781=X&flag_type-787=X&flag_type-799=X&flag_type-800=X&flag_type-803=X&flag_type-835=X&flag_type-846=X&flag_type-855=X&flag_type-863=X&flag_type-864=X&flag_type-875=X&flag_type-889=X&flag_type-892=X&flag_type-901=X&flag_type-905=X&flag_type-908=X&form_name=enter_bug&maketemplate=Remember%20values%20as%20bookmarkable%20template&op_sys=Unspecified&priority=--&product=Core&rep_platform=Unspecified&status_whiteboard=[userContextId][domsecurity-backlog]&target_milestone=---&version=unspecified). Once you've created a bug, I'll try pinging the correct people who handle localization issues.

**Comment by kendallcorner** [comment] 2019-12-03 21:03
Hi. We're currently triaging the Multi Account Container issues. This was never reconfirmed, so I'm going to close it. If you don't feel the underlying issue has been resolved, feel free to reopen it with updated steps to reproduce.

**Closed by kendallcorner** 2019-12-03 21:03 UTC
Labels: bug, l10n
