### ISSUE TITLE
New Tab Container cannot be updated

### ISSUE THREAD

**Issue by mpirhayati** [mozilla/multi-account-containers#2397] opened 2022-07-25 12:41 UTC
### Before submitting a bug report

- [X] I updated to the latest version of Multi-Account Container and tested if I can reproduce the issue
- [X] I searched for existing reports to see if it hasn't already been reported

### Step to reproduce

1. click on Firefox Multi-Account Containers extension logo on menu bar.
2. click Manage Containers
3. change the arrangement of containers
4. right click on "open a new tab" button (+)
5. the containers arrangement is not updated.

### Actual behavior

Despite the change in the containers arrangement from "Manage Containers", but the containers arrangement do not update when i hold click on new tab button  (+).  

### Expected behavior

the containers arrangement do not update when i hold click on new tab button  (+). 

### Provide a copy of Troubleshooting Information page

```plain text
Despite the change in the containers arrangement from "Manage Containers", but the containers arrangement do not update when i hold click on new tab button  (+).
```

**Comment by dannycolin** [comment] 2022-07-25 23:10
Duplicate of #1952

**Closed by dannycolin** 2022-07-25 23:10 UTC
Labels: bug
