### ISSUE TITLE
Containers management and behaiviour

### ISSUE THREAD

**Issue by vrtareg** [mozilla/multi-account-containers#1855] opened 2020-08-26 20:41 UTC
Hi

Thanks a lot for great add-on.

Sorry if this has been already asked but I haven't found that.

I have installed add-on and trying to do the following:

- Is there a possibility to manually re-order containers in container list? If there is an already request for this I would like to follow it.

- Is there a possibility to limit container to a wildcard of websites? I would like to have 2 containers for `https://*.somedomain.com` so I can use them for 2 separate accounts?

If there are already opened requests for these I would like to follow them.

Found followings:

- **Add ability to reorganize Containers #330** 
- **Feature: Reordering containers #1843**

Thanks,
Areg

**Comment by hub2git** [comment] 2020-09-08 15:21
@vrtareg I'm a fellow user like you. I'd like to know what you mean by your second bullet point.

>     * Is there a possibility to limit container to a wildcard of websites? I would like to have 2 containers for `https://*.somedomain.com` so I can use them for 2 separate accounts?

What do you want to see when you type foo.somedomain.com into your Firefox browser? Do you want Firefox to open two new tabs, one for ContainerA and another for ContainerB?

**Comment by groovecoder** [comment] 2020-09-09 19:23
Closing as Dupe of #330 and #691.

**Closed by groovecoder** 2020-09-09 19:23 UTC
Labels: duplicate

**Comment by vrtareg** [comment] 2020-09-11 13:03
> 
> 
> @vrtareg I'm a fellow user like you. I'd like to know what you mean by your second bullet point.
> 
> > * Is there a possibility to limit container to a wildcard of websites? I would like to have 2 containers for `https://*.somedomain.com` so I can use them for 2 separate accounts?
> 
> What do you want to see when you type foo.somedomain.com into your Firefox browser? Do you want Firefox to open two new tabs, one for ContainerA and another for ContainerB?

Hi @hub2git 

Looks like I have figured out what to do.

Apparently I have 3 accounts on same site: personal, work 1 and work 2
I was trying to open something like you suggested but then understood that it is not good solution.
Instead I have browser to handle my main personal account, then I created 2 containers for Work 1 and 2
If I need I open same link in Work 1 or 2 and problem solved.
So trick is that browser is always Container 0 ...

Hope this helps.

Regards,
Areg
