### ISSUE TITLE
Containers cannot be placed in a custom order.

### ISSUE THREAD

**Issue by rodukov** [mozilla/multi-account-containers#2412] opened 2022-09-11 15:46 UTC
### Before submitting a bug report

- [x] I updated to the latest version of Multi-Account Container and tested if I can reproduce the issue
- [X] I searched for existing reports to see if it hasn't already been reported

### Step to reproduce

1) I opened the extension;
2) Clicked 'Manage Containers';
3) Placed the containers in the desired order;
4) **Right click to open new tab, to select a container in this way.**
![image](https://user-images.githubusercontent.com/101352977/189536404-97403cd7-7893-45ae-a58d-84c209ed26f5.png)

### Actual behavior

Containers are not sorted. They are sorted **by creation date**, not by how I arranged them.

### Expected behavior

Containers should be **sorted as I ordered them**, not by creation date.

**Comment by dannycolin** [comment] 2022-09-13 01:37
Duplicate of #1958

**Closed by dannycolin** 2022-09-13 01:37 UTC
Labels: bug
