### ISSUE TITLE
"Container" menu wrapping when disabling/enabling feature several times under about:addons

### ISSUE THREAD

**Issue by kjozwiak** [mozilla/multi-account-containers#187] opened 2017-02-14 22:07 UTC
Disabling the "Containers Experiment" several times via about:addons while the menu is still opened will cause the menu to start wrapping. The menu will repeat itself several times causing major performance issues when attempting to open the menu. Restarting the browser fixes the issue.

> Example: https://youtu.be/uBMjvZ3CpmE

STR: (assumes you have the containers add-on installed)

* load about:addons and click on "Extensions"
* click on the "Container" button and while the menu is opened, select "Disable" under about:addons
* re-enable the "Containers Experiment" extension and repeat the above step 2-3 times

<img width="308" alt="screen shot 2017-02-14 at 4 45 17 pm" src="https://cloud.githubusercontent.com/assets/2602313/22950961/6f58c0f8-f2d5-11e6-8f64-d41d23df622f.png">

**Comment by bakulf** [comment] 2017-02-17 07:53
I cannot reproduce it. @jonathanKingston @groovecoder can you?

**Comment by kjozwiak** [comment] 2017-02-17 17:48
@bakulf, you'll have to move the Container icon closer to the URL bar from it's current position so you can press the "Disable" button while the container menu is visible.

<img width="485" alt="screen shot 2017-02-17 at 12 45 30 pm" src="https://cloud.githubusercontent.com/assets/2602313/23076641/493b5232-f50f-11e6-97ec-736203879ea6.png">

**Comment by Paarmita** [comment] 2018-09-23 15:01
@groovecoder @kjozwiak @jonathanKingston When I click on disable, the pop-up window gets closed in my case, so I'm not been able to see series of popups as shown. I clicked disable several times but the window gets closed.
Can u plz help in reproducing this, so I could work on it?

**Comment by yatri1609** [comment] 2018-09-24 07:30
@kjozwiak I am not able to reproduce this issue even after trying it several times.

**Comment by kjozwiak** [comment] 2018-09-25 03:02
@Paarmita @yatri1609 I'm no longer working on the Mozilla project but I'm assuming this might have been fixed at some point. If you can't reproduce using the STR, it's most likely fixed and not an issue anymore.

**Comment by ShivangiKakkar** [comment] 2018-09-27 19:32
I too tried to reproduce this. It seems to be fixed now. @groovecoder Maybe we can close this one. Thanks! :)

**Comment by jonathanKingston** [comment] 2019-01-08 00:01
Hey @kjozwiak, this looks like this issue is solved, thanks for responding. As always I appreciate the help you gave us on this!

**Closed by jonathanKingston** 2019-01-08 00:01 UTC
Labels: Container Panel, bug, good first bug

**Comment by kjozwiak** [comment] 2019-01-08 02:13
no worries @jonathanKingston! Glad you guys are still working on this here and there!
