### ISSUE TITLE
Feature Request: Settings option to always open new tab in current container 

### ISSUE THREAD

**Issue by jaredramirez** [mozilla/multi-account-containers#2054] opened 2021-05-19 17:20 UTC
Hey, it's be great to auto-open a a new tab (with cmd-t, cmd-click, or the new tab button) in the same container as the current tab.  For cmd-click, I can right-click and open my tab in a specific container and for cmd-t I can use a shortcut, but I find that often I want to keep the context I'm in without having to go through the extra step of picking _which_ container I want to open as typically I want to open in the same context.

**Comment by paked** [comment] 2022-07-16 04:13
If there would be interest in merging this feature in. I'd be happy to implement it (I might just implement it anyway tbh).

**Comment by dannycolin** [comment] 2022-08-06 00:58
The only solution currently is to middle click on the new tab button. To change the behavior of ctrl + t, we'd need to implement it directly in Firefox. However, we could implement a customizable shortcut for that. I'll close this as a duplicate of #462.

**Closed by dannycolin** 2022-08-06 00:58 UTC
Labels: Feature Request
