### ISSUE TITLE
Disable right click events in the "Long press" context menu

### ISSUE THREAD

**Issue by Softvision-MariusComan** [mozilla/multi-account-containers#947] opened 2017-11-10 15:17 UTC
**[Affected versions]:**
- Firefox 56 and up

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- Have a Firefox profile with the latest "Multi-Account Containers" add-on version (4.0.3 custom built on 11.10.2017) installed.

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites and long press the "Open a new tab" button ("+") 
2. Right click in the context menu and observe the behavior.

**[Expected result]:**
- Nothing happens.

**[Actual result]:**
- The "Tab Strip" context menu is opened.

**[Notes]:**
- Considering the fact that the "Tab strip" context menu options do not affect the "Multi-Account Containers" feature, in my opinion, the right click mouse events should be disabled in the "Long press" context menu.
- Attached a screen recording of the issue:
![rec of the issue](https://user-images.githubusercontent.com/31243259/32664774-f09fa15c-c63a-11e7-8d50-ab7928b5b934.gif)

**Comment by ShivangiKakkar** [comment] 2018-09-25 19:00
@jonathanKingston @groovecoder @bakul I would love to work on this issue. May I?

**Comment by groovecoder** [comment] 2018-09-25 19:34
This needs a platform-level change, so I'm not sure why it's marked as a good first bug - @jonathanKingston ?

**Comment by ShivangiKakkar** [comment] 2018-09-25 19:38
@groovecoder Oh okay, please let me know if it needs some changes on the container addon side. :)

**Comment by dannycolin** [comment] 2022-07-25 23:06
Closing since this is a bug in Firefox. 

Since I could still reproduce a slightly different variant of this issue, I filed a bug report upstream. You can subscribe to https://bugzilla.mozilla.org/show_bug.cgi?id=1781160 if you wish.

**Closed by dannycolin** 2022-07-25 23:06 UTC
Labels: bug, needs: Mozilla Central
