### ISSUE TITLE
[Feature request] Search-Engines: Create new temp container when jumping to resource

### ISSUE THREAD

**Issue by serious6** [mozilla/multi-account-containers#1372] opened 2019-04-17 09:34 UTC
This ticket is describing a feature request handling the situation when you have configured a container f.i. google.

### Actual behavior
- Defined a container for a given search engine f.i. google
- query for a random term in google
- click on a given result of the search
- Result: the page will be opened in the same google container

### Expected behavior
- Defined a container for a given search engine f.i. google
- query for a random term in google
- click on a given result of the search
- Result: the page will be opened in a temporary container being created once no container is already defined for this website (container can be withdrawn once current tab is closed)

### Optional enhancement
- The user can configure if a temporary container should be created once referring to other webpages from the current container

### Notes
The described current behavior implies that information from current session and history will be shared with the website visited once you found an entry from a search engine.

### Benefit if implemented
- More user-control
- Privacy improvements

**Comment by stoically** [comment] 2019-05-04 11:07
Duplicate of https://github.com/mozilla/multi-account-containers/issues/929 - please vote there, thanks!

**Closed by stoically** 2019-05-04 11:07 UTC
