### ISSUE TITLE
Extensions leak state

### ISSUE THREAD

**Issue by lvh** [mozilla/multi-account-containers#1316] opened 2018-12-09 20:17 UTC
Context: we have a consultancy with multiple clients that have to stay separate. I can use Chrome profiles for this easily, and while I generally prefer Firefox, it's always been worse at this because profiles are not as slick as they are in Chrome. I was excited about using Containers for this since it is a very clear example of a contextual identity problem. But I ran into issues because sharing extensions is a non-starter for essentially any extension that requires login. The simplest example I can think of is e.g. the Okta extension: you're only ever signed in to 1 account, so if you have multiple accounts (contextual identities -- they're both me, but they're me in different contexts) you can use Firefox profiles, Chrome profiles, but not Firefox containers.

I've previously solved this problem by running Qubes OS, where each Firefox contextual identity runs in a separate virtual machine. Obviously this "solves" my problem, but since it's an example of where someone wanting contextual identities and Firefox couldn't use containers to do it,  I figured it'd be useful to tell you :)

### Actual behavior

.. Containers share extensions.

### Expected behavior

. Containers contain extensions (or at least optionally can)

### Steps to reproduce

Elided since presumably pretty straight forward :)

### Notes

N/A

**Comment by stoically** [comment] 2019-05-04 12:51
Duplicate of https://github.com/mozilla/multi-account-containers/issues/309 - please vote there, thanks!

**Closed by stoically** 2019-05-04 12:51 UTC
