### ISSUE TITLE
feature request: History per container 

### ISSUE THREAD

**Issue by nklausen** [mozilla/multi-account-containers#2633] opened 2024-04-14 10:37 UTC
### Before submitting a bug report

- [X] I updated to the latest version of Multi-Account Container and tested if I can reproduce the issue
- [X] I searched for existing reports to see if it hasn't already been reported

### Step to reproduce

- Enter the url bar and start typing an address or,
- open the history menu or,
- open a new tab

### Actual behavior

History across all containers is listed, even sites which you have selected to always open in a specific container.

### Expected behavior

Expected behavior will have two different scenarios.

- When opening the history menu, the history of the default container is listed, as there are no context association of which container it is opened in.
- When entering the url bar, or opening a new tab, there are a context to select the container from, meaning the history from the url bar is searching though the history and the icons for the most and recent used sites is listed on the new tab page.

### Additional informations

In scenarios where you want to keep a history, but don't want that history to show in all situations, having a history pr container would help. It all would help in thinking about your online present in containers.

**Comment by dannycolin** [comment] 2024-04-15 13:21
Duplicate of #1233

**Closed by dannycolin** 2024-04-15 13:21 UTC
Labels: bug
