### ISSUE TITLE
Undo close tab after contained tab, "duplicates" the tab

### ISSUE THREAD

**Issue by yosubis** [mozilla/multi-account-containers#950] opened 2017-11-10 21:11 UTC
If I open a "sleeping" tab (from previous session) that is in a container and then undo close tab shortcut (ctrl+shift+T), a duplicate of this contained tab it opened. If I continue undo close tab, the same tab is duplicated again.

**Comment by SoftVision-EmilPasca** [comment] 2017-11-13 13:44
I have managed to reproduce the issue on Windows 10 x64 and Mac 10.12 with the latest Firefox release (56.0.2) and the latest Nightly (59.0a1-20171113100232) using the latest Multi-Account Containers (4.0.3).

Attached a screen recording of the issue:
![containers_duplicate_tab](https://user-images.githubusercontent.com/20083658/32728577-814c26e4-c889-11e7-94e6-f2cf41138238.gif)

**Comment by kris7453** [comment] 2017-11-15 20:30
Same problem. Now i have duplicated tabs in container and I can't show hidden duplicated tabs nor show visible tabs. When I have separated showed tabs by another container group, then when I click show, all duplicated tabs will open and when i close browser and open again then i have tripled tabs.
The problem appear  for newest firefox quantum 57.0(64bit)
![image](https://user-images.githubusercontent.com/20442936/32858268-4b024f6e-ca4b-11e7-8cd5-283a6df6a509.png)

**Comment by TanviHacks** [comment] 2018-01-23 18:37
Is wikipedia assigned to a container?

**Comment by oksmelnik** [comment] 2019-10-12 18:06
I'd like to work on this issue (outreachy applicant)

**Comment by oksmelnik** [comment] 2019-10-15 05:44
the problem is that opening recently closed container's tab triggers unhiding of all the other tabs of this container, including this particular tab again. Is containers tabs re-opening suppose to happen in this case, @groovecoder? If so, I'll try to find the way to not duplicate the tab.

**Comment by oksmelnik** [comment] 2019-10-19 13:25
please, check my PR here 
https://github.com/mozilla/multi-account-containers/pull/1540

**Comment by groovecoder** [comment] 2019-10-25 18:33
Fixed in #1540

**Closed by groovecoder** 2019-10-25 18:33 UTC
Labels: bug, help wanted, site assignment, vote for me
