### ISSUE TITLE
Back button on "manage site list" settings page is not working properly

### ISSUE THREAD

**Issue by philipreimer** [mozilla/multi-account-containers#1857] opened 2020-09-06 11:56 UTC
- Multi-Account Containers Version: 7.0.2
- Operating System + Version: Manjaro Linux Gnome Edition (current)
- Firefox Version: 79.0
- Other installed Add-ons + Version + Enabled/Disabled-Status:

Name 	Typ 	Version 	Aktiviert 	ID
Amazon.com	extension	1.1	true	amazondotcom@search.mozilla.org
Amazon.de	extension	1.1	true	amazon@search.mozilla.org
Bing	extension	1.1	true	bing@search.mozilla.org
Chambers (UK)	extension	1.0	true	chambers-en-GB@search.mozilla.org
ClearURLs	extension	1.19.0	true	{74145f27-f039-47ce-a470-a662b129930a}
Decentraleyes	extension	2.0.14	true	jid1-BoFifL9Vbdl2zQ@jetpack
DuckDuckGo	extension	1.0	true	ddg@search.mozilla.org
eBay	extension	1.1	true	ebay@search.mozilla.org
Ecosia	extension	1.0	true	ecosia@search.mozilla.org
Firefox Multi-Account Containers	extension	7.0.2	true	@testpilot-containers
Google	extension	1.0	true	google@search.mozilla.org
HTTPS Everywhere	extension	2020.8.13	true	https-everywhere@eff.org
KeePassXC-Browser	extension	1.7.0	true	keepassxc-browser@keepassxc.org
LEO Eng-Deu	extension	1.0	true	leo_ende_de@search.mozilla.org
Mailvelope	extension	4.3.2	true	jid1-AQqSMBYb0a8ADg@jetpack
Privacy Badger	extension	2020.8.25	true	jid1-MnnxcxisBPnSXQ@jetpack
RESTer	extension	4.3.0	true	rester@kuehle.me
uBlock Origin	extension	1.29.2	true	uBlock0@raymondhill.net
Wikipedia (de)	extension	1.0	true	wikipedia@search.mozilla.org
Deutsch (DE) Language Pack	locale	79.0buildid20200720193547	true	langpack-de@firefox.mozilla.org
English (GB) Language Pack	locale	79.0buildid20200720193547	true	langpack-en-GB@firefox.mozilla.org
English (US) Language Pack	locale	79.0buildid20200720193547	true	langpack-en-US@firefox.mozilla.org

### Actual behavior
Back button on "manage site list" settings page is not working properly.
I have to click the button 3 - 10 times before it reacts and returns back to the manage container settings page.

### Expected behavior
Back button should work on first click.

### Steps to reproduce
1. Open Multiaccount Containers menu by clicking menu bar icon
2. Click "Manage Containers"
3. Select a container, which has multiple sites in its site list
4. Click "Manage Site List..."
5. Click the "Back" button in the upper left corner
6. Click on "Back" button to get to the list of containers.
7. Select a different container, which has sites in its site list
8. Click "Manage Site List..."
9. Click the "Back" button

### Notes
For the first site list the button works on first click.

Every additional site list from a _different container_ that you enter without leaving the "Manage Containers" section will add **two** additional clicks to the number of clicks that are necessary to return from a container's Site List.

If you skip steps 6. and 7. above and just open the Site List of the _same_ container again, every time you open the Site List will add **one** additional click to the number of clicks that are necessary to return from a container's Site List.

UI flickers on each click but does not go back to previous settings page.

**Comment by kelbyers** [comment] 2020-10-03 21:07
I have seen this issue. I am able to reliably produce it on my browser, but doing the following:
- Manage containers
- Choose a container
- Manage Site List...
- Click on the back arrow. This works with a single click.
- Click on back arrow to get to the list of containers.
- Still in the Manage Containers function, choose a different container
- Manage Site List...
- Click on the back arrow. It now takes 3 clicks on the back arrow to get out of the site list
- Click on back arrow to get to the list of containers
- Choose a third container
- Manage Site List...
- Click on the back arrow. It now takes a total of 5 clicks on the back arrow.

On my testing, every additional container managed without exiting out of the Manage Containers feature will take an additional 2 clicks to back out of the site list. 1 click for the first site list, 3 clicks for the second site list, 5 clicks for the third site list. I only tried it to either 7 or 9 clicks.

**Comment by philipreimer** [comment] 2020-10-07 08:34
@kelbyers thanks for the improved steps to reproduce. It is the same for me. I hadn't noticed that pattern.

I updated the issue description accordingly.

**Comment by dannycolin** [comment] 2022-07-22 01:21
Do you still experiment this issue?

**Comment by dannycolin** [comment] 2022-12-27 21:04
Duplicate of #2437

**Closed by dannycolin** 2022-12-27 21:04 UTC
Labels: bug, Component: Panel, Status: Cannot Reproduce

**Comment by kelbyers** [comment] 2022-12-28 00:43
> Do you still experiment this issue?

Sorry, I didn't notice the notification for the question. The issue was resolved after the July 21 update. I do remember testing it out around that time, not sure why I didn't update this issue.
