### ISSUE TITLE
Manually re-opening tab in different container should override "Always Open This Site in..." settings

### ISSUE THREAD

**Issue by dadinn** [mozilla/multi-account-containers#2070] opened 2021-06-15 17:57 UTC
### Steps to reproduce
1. Create two containers: Work, and Personal
2. Open github.com
2. In the MAC plugin assign it to Work container with `Always Open This Site in...` option.
3. Open github.com again in a new tab
4. In the popup window when asked `Open this site in your assigned container?`, select the checkbox `Remember my decision for this site`, before clicking on the `Open in Work Container` button.
5. select the github.com tab (using Work container), rightclick on it, and choose Personal container under the `Reopen in Container` menu option.
### Actual behavior
A new tab is opened with github.com, but still automatically assigned to Work container.

### Expected behavior
Manually selecting a different container using `Reopen in Container` option should override automatic settings!

Alternatively, there should be an option to disable automatic assignments temporarily!

### Environment
OS: Debian Bullseye
Firefox version: 84.10.esr
MAC plugin version: 7.3.0

**Comment by grahamperrin** [comment] 2021-06-18 15:12
▶ #1222 and/or #1414 

@daddin please consider closing this duplicate, so that others can be more easily managed. Thank you.

**Comment by dadinn** [comment] 2021-06-18 17:06
Duplicate of #1222
Duplicate of #1410
Duplicate of #1414

**Comment by dadinn** [comment] 2021-06-18 17:11
DOES NOT COMPUTE!

**Comment by dadinn** [comment] 2021-06-18 17:24
@grahamperrin My assumption is that the valid state transition in an issue workflow to close an issue should be to mark it either: DONE, WONTFIX, or DUPLICATE.

Unfortunately, I can't mark it DONE until it's DONE, and I can't mark it DUPLICATE why!?

**Comment by grahamperrin** [comment] 2021-06-19 06:12
PS (after receiving e-mails for comments that are no longer here) whilst Bugzilla has the ability to e.g. choose _Duplicate_ from a pull-down menu, there's nothing comparable in GitHub. 

Your deleted mention of issue 1410 remains in 1410 (at the time of writing); my mentions of 1222 and 1414 will remain in those two issues. 

If you agree that this #2070 is a duplicate, you can simply close it (using the button below); cross references will remain.

**Comment by Vindickator** [comment] 2021-07-10 10:04
I too agree that this feature of temporary override be added to this add-on

#1222 has been left open since 2018; no solution
#1414 has been left open since 2019' no solution
In their subsequent thread mentions there is no solution to this whatsoever.

So, therefore, #2070 is actual and we request a fix for this add-on.

PS: The option of "Disabling always open site in" is not practical; if we are disabling "always open" we might as well just remove the add-on and use the inbuilt Firefox feature to switch containers.

Our request is simple,
Similar to @dadinn says, if I have two Youtube accounts,
and one has been primarily set (Container "Media") and always pops open when it encounters www.youtube.com
Sometimes, I have to switch to another account (Container "Ops"), 

Step-1: I type in www.youtube.com
Step-2: Gets taken to "Media" container
Step-3 Right click on the tab or the add-on and select "Reopen this site in", select "Ops" container
Step-4: A tab is created, (for a fraction we see different colour based on the container)
Step-5: The URL diverts back to "Media" container

There should really be an option to override _'site always set to container'_ if people deliberately choose to open it in a different container

**Comment by dannycolin** [comment] 2023-01-06 21:40
Duplicate of #1442

**Closed by dannycolin** 2023-01-06 21:40 UTC
Labels: Component: Site Assignment, :+1:  Feature Request
