### ISSUE TITLE
Containers not working correctly if permanent PrivateMode is turned on

### ISSUE THREAD

**Issue by igor2x** [mozilla/multi-account-containers#490] opened 2017-05-09 20:11 UTC
Hi,
it looks the same problem as in bug report #469. But I have opened a new report to not pollute existing bug, because I have different reproducing scenario. This reproduce scenario is ALWAYS reproducible.

I am using Firefox 53 on Ubuntu 16.04 LTS from default Ubuntu repository.

How to reproduce a problem:
1. Close down Firefox if running.
2. Create a new Firefox profile to make clean environment. From terminal execute: firefox -P
3. Click on "Create Profile" button.
4. Next Button.
5. In Enter Profile name I typed in: Container (but can be whatever name).
6. Click Finish button.
7. "Container" profile is selected. Click Start Firefox button to start Firefox with newly created profile.
8. In address bar type in: https://testpilot.firefox.com/
9. Click big green button: "Install the Test Pilot Add-on".
10. Big green "Installing..." button is displayed. When finished "Welcome to Test Pilot" dialog opens. Just press "X" at top-right of dialog.
11. On the same web page click on "Get Started" at Containers box.
12. At the top-right click on Enable Containers.
13. "Containers enabled" dialog appears. Click on "X" to close down dialog.
14. Now lets test it:
a) Move mouse to "+" right of tab (actually hover on it) and bellow four options are displayed: Personal, Work, Finance and Shopping. Clicking on Personal and container works fine.
b) Menu File | New Container Tab | Finance and new container is opened and working fine.
c) In toolbar (left of Open menu icon) click on Containers. Drop-down window is displayed with wizard: Get Started, Next, Done and containers list (Personal, Work, Finance and Shopping) are displayed. Click on e.g. Personal and new contain works fine.
15. Close down Firefox and now we are going to get into Permanent PrivateMode. In terminal type in:  cd ~/.mozilla/firefox
to get to Firefox settings.
16. Change directory to profile directory (the one with Container in directory name - it depends on the name selected on step 5) in my case it is:
cd 3786ei5s.Container
17. Create new file with command from terminal: gedit user.js
18. In text editor type in:
// Set browser to 'private browsing' mode
lockPref("browser.privatebrowsing.autostart", true);
19. Save the file and close the editor.
20. Start Firefox with profile from terminal: firefox -P
21. Select "Containers" profile and click on "Start Firefox".
22. Now test "Containers" extension with Permanent PrivateMode turned on.
a) Hover mouse on "+" on new tab icon. Nothing happens, no selection of containers like in step 14a). Actually it is displayed "Open a new tab (CTRL+T)" tip, but this is default Firefox/Ubuntu tip. PROBLEM.
b) Menu File | New Container Tab option is grayed out. PROBLEM.
c) Toolbar Container tab. Wizard: Get Started, Next, Done and list of containers are displayed (Personal, Work, Finance and Shopping). Clicking on Personal and container works fine. At first it looks like not working, because there is no blue line to indicate Personal container, but if clicked on another tab blue line is displayed at the top (not at the bottom!) of previous tab. Clicking on toolbar to create Work container and it also works (displaying orange color if moved to another tab). Signing in Gmail on Personal tab and another signing in into Work container tab and new login is required. So containers are working fine.
23. Close down Firefox and reopen it with: firefox -P (select Container profile and Start Firefox button).
24. a) Hover on "+" tab does NOT display container list. PROBLEM.
b) File | New Container is greyed out. PROBLEM.
c) Toolbar icon is working fine, except annoying wizard is dispalyed again! With Get Started, Next, Done wizard. But after clicking on Personal container works fine - login into Gmail. Tested with Work container again and another login is required for gmail. So containers works fine. WORKS WITH ANNOYING WIZARD EVERYTIME BROWSER IS RESTARTED.

Quick fix would be to remove "wizard" from toolbar to remove the need to go through wizard every time I restart browser in Permanent PrivateMode. It would be excellent all three problems fixed from step 24.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/MAC-552)

**Comment by grahamperrin** [comment] 2021-04-30 06:57
> Firefox 53

Is this issue reproducible with Firefox Quantum?

**Comment by dannycolin** [comment] 2023-01-10 00:04
It is still reproducible and expected since the addon doesn't support permanent private mode. Closing in favor of #469

**Closed by dannycolin** 2023-01-10 00:04 UTC
Labels: bug, Status: Expected
