### ISSUE TITLE
[Feature Request] Save and restore bookmarks to folder

### ISSUE THREAD

**Issue by rainbowdesign** [mozilla/multi-account-containers#1357] opened 2019-03-12 10:21 UTC
The idea is to have different "sessions" and save the "session" to bookmarks and restore it from there.

In this modus you get a button for every container. 
When you open a container with that button all other open containers are saved to their bookmark folder and all new tabs are open in that container.

The benefit is that you dont need to have many tabs open because you can simply store and manage them with a click.

Also sessions should have configureable "base sites" as example you can set if you enter facebook into the browser it will open the social networking session and all other session where facebook is a "base site" from from the bookmarks.

**Comment by rainbowdesign** [comment] 2019-03-12 10:47
I found an answer that looks similar but i would still suggest to merge the features into this plugin.
Also it seems a vers reoccuring feature request you should find a solution for whis question even its only to mention the other plugin in the description.

> The Conex extension  is built on containers, and might provide some of the user interface  you are seeking. I have found that its "Only show tabs of the current  container" setting works well as long as you confine most of your  browsing to one window. Perhaps this will be improved if the extension  is developed beyond its current "preview" state.
--

**Comment by stoically** [comment] 2019-05-04 11:20
This would need bookmarks to be aware of containers.

Duplicate of https://github.com/mozilla/multi-account-containers/issues/323 - please vote there.

**Closed by stoically** 2019-05-04 11:20 UTC
