### ISSUE TITLE
Previous button should not remain in the same container

### ISSUE THREAD

**Issue by biva** [mozilla/multi-account-containers#953] opened 2017-11-11 13:45 UTC
Steps to reproduce:
1.  Visit Site1 in ContainerA
2. Open Site2 in the same tab, by clicking on a bookmark
3. Site2 is configured to be automaticaly opened in ContainerB, so it opens in ContainerB in the same tab
4. Press the "Previous button"
5. Site1 is opened in ContainerB, while it shoud be opened in ContainerA

I don't know if this behavior happens in other situations. For example, on Site1, if I click on a link that is configured to be opened in ContainerB, it opens it in ContainerB in a new tab, and the previous button is not available.

**Comment by TanviHacks** [comment] 2018-01-09 19:02
What is the "Previous button"?

**Comment by groovecoder** [comment] 2018-01-09 19:02
I couldn't reproduce this with the back button. 👍 @TanviHacks - what do you mean by "Previous button" ?

**Comment by kendallcorner** [comment] 2019-12-05 17:14
Hi. We're currently triaging the Multi Account Container issues. These requests for more information were not answered, so I'm going to close it. If you don't feel the underlying issue has been resolved, feel free to reopen it with an updated steps to reproduce.

**Closed by kendallcorner** 2019-12-05 17:14 UTC
Labels: needs STR
