### ISSUE TITLE
Feature request: Allow sync using Firefox account

### ISSUE THREAD

**Issue by AssafTzurEl** [mozilla/multi-account-containers#1415] opened 2019-05-13 07:39 UTC
## Request

Allow synchronization of containers and related data using Firefox account.

### Actual behavior

Need to configure the containers on each machine I'm using. Then, I need to login to each account in each container on each machine. Tedious.

### Expected behavior

Create a container on one machine, see it on another. Login to a site in one container on one machine, be able to access that site on another machine.

### Notes

In case this feature already exists, please consider this as a bug report :)

**Comment by lhorace** [comment] 2019-05-13 10:45
Hello there,

Duplicate #339 

See also upstream bug report https://bugzilla.mozilla.org/show_bug.cgi?id=1288858.

Cheers

**Comment by tomrittervg** [comment] 2019-07-09 17:14
Is this as simple as using storage.sync instead of storage.local?  (Not counting the transition where you might need to check both, and propagate and whatnot...)

**Comment by groovecoder** [comment] 2019-07-09 17:26
Duplicate of https://github.com/mozilla/multi-account-containers/issues/339. Please upvote and comment there. I'm going to uplift the comment about `storage.sync` over there.

**Closed** 2019-07-09 17:27 UTC
Labels: duplicate
