### ISSUE TITLE
Manually add domain/subdomain to a Container

### ISSUE THREAD

**Issue by ghnp5** [mozilla/multi-account-containers#2680] opened 2024-10-16 18:44 UTC
### Before submitting a bug report

- [X] I updated to the latest version of Multi-Account Container and tested if I can reproduce the issue
- [X] I searched for existing reports to see if it hasn't already been reported

### Step to reproduce

1. Click the extension icon
2. Manage Containers
3. Click some container
4. Manage Site List

### Actual behavior

Can only delete sites from there.
Cannot add a new site, manually.

### Expected behavior

I'd like to be able to add domains/subdomains there, by typing it manually.

### Additional informations

Especially with authentication redirections, such as what happens when opening "onedrive.com" (as an example), it routes through a subdomain inside "live.com", which breaks authentication.

It's impossible to add the redirecting subdomain, because it redirects back to "onedrive.com" very quickly.

This could be fixed if I could simply add the subdomain to the list, manually.

**Comment by dannycolin** [comment] 2024-10-16 21:23
duplicate of #1670

**Closed by dannycolin** 2024-10-16 21:23 UTC
Labels: bug

**Comment by ghnp5** [comment] 2024-10-16 21:36
Oh, thanks! I really must improve my searching skills, as I didn't find that one! :) Apologies.
