### ISSUE TITLE
[Feature suggestion] Assign multiple sites to a container at once

### ISSUE THREAD

**Issue by ashwanianand** [mozilla/multi-account-containers#1897] opened 2020-11-01 07:47 UTC
It will be great to have the feature to copy paste a comma-separated sequence of websites somewhere to assign to a container. Right now, we have to add one by one.

**Comment by groovecoder** [comment] 2020-11-11 20:20
Duplicate of https://github.com/mozilla/multi-account-containers/issues/719

**Closed by groovecoder** 2020-11-11 20:20 UTC
Labels: duplicate
