### ISSUE TITLE
Possible to add current tab to a container

### ISSUE THREAD

**Issue by b-allard** [mozilla/multi-account-containers#997] opened 2017-11-22 12:32 UTC
Hi,

Is it possible to add the current opened tab to an existing container ? Have you planned to add this feature in the future ?

Thanks in advance,

Benjamin

**Comment by SoftVision-PaulOiegas** [comment] 2017-11-22 12:44
Hi @b-allard and thanks for your report. However this request was already discussed in #311 and it ended up as wontfix due to several downsides. You can check the comments on it to find the exact ones if you like.

However, there is an add-on that does what you ask and works together with Multi Account Containers. You can test it by installing [Context Plus](https://addons.mozilla.org/en-US/firefox/addon/context-plus/) add-on.

I will close this issue as a dupe of #311. If you have anything to add on this subject, you can do that there even if the issue is closed. 

Thanks and have a nice day! 😃

**Closed by SoftVision-PaulOiegas** 2017-11-22 12:44 UTC

**Comment by b-allard** [comment] 2017-11-22 12:56
Thanks !! :) and sorry for the dupe :/

**Comment by SoftVision-PaulOiegas** [comment] 2017-11-22 13:12
No problem, hope the suggestion was helpful. :)
