### ISSUE TITLE
Containers won't delete it comes back, I have sync turned on.

### ISSUE THREAD

**Issue by ShahariarSayem** [mozilla/multi-account-containers#1799] opened 2020-07-13 11:21 UTC
I'm new to this, would like some help.

**Comment by sdht0** [comment] 2020-08-05 19:35
I don't think this is an issue with sync. I turned off sync and tried to delete assigned websites from a container, but they still came back!

**Comment by Yowlen** [comment] 2020-08-07 19:56
Can confirm. This is a massive issue for those of us that use this in combination with the Temporary Containers addon for extra privacy, since it floods the sync with hundreds of `tmp` containers with no way to permanently delete them unless we give up the ability to use our permanent containers across different devices.

**Comment by jtagcat** [comment] 2021-03-04 09:11
Duplicate of #1696

**Closed** 2021-03-06 15:13 UTC
Labels: sync
