### ISSUE TITLE
[Enhancement] Have containers survive Firefox Refresh

### ISSUE THREAD

**Issue by JpTiger** [mozilla/multi-account-containers#1315] opened 2018-12-07 16:01 UTC
Hi there, Firefox Refresh is designed to keep your logins etc, but currently it only does that if they are in your default container (not in any container? not sure of the proper terminology). However, since MAC is an extension and refreshing Firefox wipes your extensions, it appears that you wind up losing the logins associated with individual containers and have to build those containers from scratch again. This might have to come from Firefox rather than this extension, but is there some way we can at least package the containers to be easily restored from the Old Firefox Data folder that refreshing Firefox generates? It'd be even better if this particular extension could survive the refresh process, but that seems far fetched given how refresh works.

**Comment by lestephane** [comment] 2018-12-08 10:32
Maybe another way to achieve what you need is to offer the capability to 'clear' or 'reset' the default container, and optionally to disable its use entirely. That's what i would want. I did not create a  new issue, and wrote a comment here instead, because the spirit of what you and I want is the same. The default container is the one you don't want to spend any more time inside of than you have to. So there should be a way to reset or clear it individually.

**Comment by dannycolin** [comment] 2022-12-08 05:23
> refreshing Firefox wipes your extensions [...] This might have to come from Firefox rather than this extension

Preventing a refresh from wiping the addon data can only be done in Firefox itself. This should be filed on bugzilla.mozilla.org.

> is there some way we can at least package the containers to be easily restored from the Old Firefox Data folder that refreshing Firefox generates?

This would be a duplicate of #1282 so I'll close this issue in favor of that one.

**Closed by dannycolin** 2022-12-08 05:23 UTC
Labels: :+1:  Feature Request
