### ISSUE TITLE
[Feature Request] Option to separate extension data per container

### ISSUE THREAD

**Issue by rkapur-gds** [mozilla/multi-account-containers#1351] opened 2019-03-04 17:49 UTC
It would be cool if we could separate extensions configuration per container. There are some containers that I'd like to enable a proxy extension for, but not for all containers.

**Comment by stoically** [comment] 2019-05-04 11:50
Duplicate of https://github.com/mozilla/multi-account-containers/issues/309 - please vote there.

**Closed by stoically** 2019-05-04 11:50 UTC
