### ISSUE TITLE
[Feature Request] Sync settings

### ISSUE THREAD

**Issue by syepes** [mozilla/multi-account-containers#1052] opened 2017-12-20 08:12 UTC
This addon is of great utility for working with a personal and work PC, but one killer feature that would make it even greater would be the possibility to Sync all its settings (State of Always open in XX, List of containers) in the Firefox Sync Account.

**Comment by groovecoder** [comment] 2017-12-20 14:25
Dupe of https://github.com/mozilla/multi-account-containers/issues/339 please upvote and comment there.

**Closed by groovecoder** 2017-12-20 14:25 UTC
Labels: duplicate
