### ISSUE TITLE
[Feature Request] Let users choose click-through behavior

### ISSUE THREAD

**Issue by dralley** [mozilla/multi-account-containers#1206] opened 2018-04-29 16:38 UTC
The Facebook Container extension has a nice behavior where, if you click on a link on Facebook, the tab will open in a normal, non-contained tab.  The behavior of this addon is to open links in the same container.  It would be fantastic if we could toggle to the Facebook Container click-through behavior on a per-container or global basis.

**Comment by nhck** [comment] 2018-05-02 16:13
You might like to read #847

**Comment by mcepl** [comment] 2018-05-11 10:44
I would say this is straight duplicate of #847 and it should be closed.

**Comment by groovecoder** [comment] 2018-05-11 16:27
Closing as duplicate of #847

**Closed by groovecoder** 2018-05-11 16:27 UTC
Labels: duplicate
