### ISSUE TITLE
Unable to install on Firefox 91.6.0esr from Debian repositories

### ISSUE THREAD

**Issue by MuadDibIII** [mozilla/multi-account-containers#2286] opened 2022-02-10 08:35 UTC
Hello, 

I'm trying to install this addon on my Firefox 91.6.0esr (64 bits)  sous Debian 11, but it says that I need a more recent version, even if the requirements says it need Firefox 91.1.0+.

Is it normal? When do you think I'll be able to install it?

Thanks in advance for your answer,

Best regards,
Marc

**Comment by edwardps** [comment] 2022-02-25 20:53
I see the same issue with installation.

**Comment by MuadDibIII** [comment] 2022-02-25 21:19
I actually managed to install it by downloading and manually installing it, the button to download is just behind the regular install button.

The question is why to block it knowing it works well and meet the minimum requirements?

**Comment by edwardps** [comment] 2022-02-25 21:30
> I actually managed to install it by downloading and manually installing it, the button to download is just behind the regular install button.

This works for me. Thanks :)

**Comment by castlefox** [comment] 2022-05-12 15:45
> Hello,
> 
> I'm trying to install this addon on my Firefox 91.6.0esr (64 bits) sous Debian 11, but it says that I need a more recent version, even if the requirements says it need Firefox 91.1.0+.
> 
> Is it normal? When do you think I'll be able to install it?
> 
> Thanks in advance for your answer,
> 
> Best regards, Marc

Are you still having this issue?

**Comment by dannycolin** [comment] 2022-06-10 00:25
Do you use the Firefox package from Debian repositories? I'm asking because the Debian package isn't maintained by Mozilla and it may be configured differently. This could be the issue here.

**Comment by MuadDibIII** [comment] 2022-06-10 06:00
As I said before, I managed to install manually the extention...

**Comment by dannycolin** [comment] 2022-06-10 13:50
> As I said before, I managed to install manually the extention...

I know that but I'm trying to confirm that the issue only happens with the Debian build of Firefox.

**Comment by dannycolin** [comment] 2022-06-13 17:24
After talking with the addons team, it seems like it's a known issue with the addons.mozilla.org server that should have been fixed. Obviously, it looks like the fix wasn't enough or there's something new that trigger the same issue.

Could you please file a bug report at https://github.com/mozilla/addons/issues/new so the addons team can investigate it further. And ofc, thanks for letting us know about this issue :).

**Comment by dannycolin** [comment] 2022-08-06 00:17
Duplicate of #2268

**Closed by dannycolin** 2022-08-06 00:17 UTC
Labels: bug, needs: Upstream
