### ISSUE TITLE
Add configuration to set default behavior when opening new tab to be "No Container"

### ISSUE THREAD

**Issue by gmagno** [mozilla/multi-account-containers#1651] opened 2020-02-19 20:08 UTC
Related to #1646.

I would like the default behavior of clicking in a link and opening a new tab to actually open the link in a "No Container" tab.
Can I change this somehow in the settings?

**Comment by kendallcorner** [comment] 2020-02-20 23:23
Hoping to merge #1474 soon, which would give you that ability. Also tagging as duplicate of #847. I'm going to close this, and you can comment further on #847 if needed. Thanks!

**Closed by kendallcorner** 2020-02-20 23:23 UTC
