### ISSUE TITLE
After sync the order of containers in the extension GUI is messed up

### ISSUE THREAD

**Issue by powerjungle** [mozilla/multi-account-containers#2406] opened 2022-08-13 12:47 UTC
### Before submitting a bug report

- [X] I updated to the latest version of Multi-Account Container and tested if I can reproduce the issue
- [X] I searched for existing reports to see if it hasn't already been reported

### Step to reproduce

Sync your containers to a fresh Firefox profile!

### Actual behavior

Random order of container list in the extension GUI.

### Expected behavior

Order in which the list was on the last sync.

### Additional informations

Firefox Containers version 8.0.7
Firefox version 103.0.2

**Comment by rednishat** [comment] 2022-09-03 22:42
I having the same issue.
Containers are not syncing in order they were in my MacBook air and windows firefox.

**Comment by dannycolin** [comment] 2022-12-08 05:29
Duplicate of #1625

**Closed by dannycolin** 2022-12-08 05:29 UTC
Labels: bug, Component: Sync
