### ISSUE TITLE
Feature Requests: Allow Assignment New Tab Page to a Container and treat "Default" Container Like any other Container

### ISSUE THREAD

**Issue by sahil48** [mozilla/multi-account-containers#906] opened 2017-10-12 15:44 UTC
These two features are somewhat related, so I put them in a single issue.

It is not possible to assign a new tab page to a container like personal or work. The new tab page is assigned to the "default container", which cannot be managed like tabs in other containers. For example, you cannot all default tabs in a new window or hide them.

It would be great to either allow the new tab page to be assigned to a container other than "default" and to treat "default" as a container that can be managed like "personal", "work", or any other container.

**Comment by Narvey** [comment] 2017-11-01 23:12
or better yet, to mark a named container as the default for new tabs, links opened from powershell, you name it, as long as it doesn't fit into another container's criteria.

In the mean time I'm using https://addons.mozilla.org/en-US/firefox/addon/cookie-autodelete/

**Comment by TanviHacks** [comment] 2018-01-30 18:38
This is a duplicate of https://github.com/mozilla/multi-account-containers/issues/356

**Closed by TanviHacks** 2018-01-30 18:38 UTC
Labels: duplicate
