### ISSUE TITLE
[Feature Request] Ability to change display order of built-in containers

### ISSUE THREAD

**Issue by Tichij** [mozilla/multi-account-containers#1077] opened 2018-01-10 08:31 UTC
Built-in containers now appear in the following order: Personal, Work, Banking, Shoping.
For example it would be more convenient in the work computer to have the Work container first. But now there is no such opportunity.
Thanks.

**Comment by groovecoder** [comment] 2018-01-10 17:05
Dupe of https://github.com/mozilla/multi-account-containers/issues/330

**Closed by groovecoder** 2018-01-10 17:05 UTC
Labels: duplicate
