### ISSUE TITLE
Add the ability to associate a container with a specific bookmark , or bookmark tag

### ISSUE THREAD

**Issue by bonespiked** [mozilla/multi-account-containers#2691] opened 2024-11-19 14:46 UTC
### Before submitting a bug report

- [X] I updated to the latest version of Multi-Account Container and tested if I can reproduce the issue
- [X] I searched for existing reports to see if it hasn't already been reported

### Step to reproduce

My primary use case for multi-account-containers is AWS - I use each for a separate account/environment.  However, all the URLs are the same - so the 'per domain' approach won't work.  I was thinking that you can add to a bookmark an indicator that it should be always opened in a specific container - or maybe you go the other way and associate a container with a specific bookmark tag - so it will always open in the specified container.

### Actual behavior

n/a

### Expected behavior

n/a

**Comment by dannycolin** [comment] 2024-11-19 20:07
Duplicate of #323

**Closed by dannycolin** 2024-11-19 20:07 UTC
Labels: bug
