### ISSUE TITLE
Container causes the whole browser to crash

### ISSUE THREAD

**Issue by RCMainak** [mozilla/multi-account-containers#705] opened 2017-08-02 16:36 UTC
Moving the discussion here from [Discourse](https://discourse.mozilla.org/t/container-causes-the-whole-browser-to-crash/17536)

**Steps to reproduce :**
1. Open up a website such as youtube in a new container tab (let’s assume in Personal container).
2. Right click on the page and select Always Open in This Container.
3. Now open up any webpage which contains a hyper links of youtube.
4. Right click on the link and try to open the link in some other container (let’s assume Work container).

**Expected Result :**
Do something without crashing the browser for the love of god :stuck_out_tongue_winking_eye:

**Actual Result :**
Crashes the whole browser which is super annoying.

I'm using Ubuntu MATE 16.04 and FIrefox 54.0 (64-bit)
**Build ID :** 20170612122310
**Containers Experiment :** 2.4.1
**Test Pilot :** 1.1.4-dev-ead6dcd

about:crashes gives this -> [bp-7a8eb161-09ad-4572-ad6f-ed88e1170802](https://crash-stats.mozilla.com/report/index/7a8eb161-09ad-4572-ad6f-ed88e1170802)

**Comment by jonathanKingston** [comment] 2017-08-03 13:10
This doesn't look like a containers crash at all from what I can see. I haven't tracked through that code to check if it is something that is caused by userContextId in the gecko code but it's likely more something that is a DOM issue.

Have you been able to consistently reproduce this?

**Comment by RCMainak** [comment] 2017-08-03 14:58
Yes, I can consistently reproduce this issue on my desktop. Haven't tried it yet on my laptop. Let me give a shot. Would it be better if I share a video with you? Maybe I'm not describing the steps to reproduce properly.

**Comment by jonathanKingston** [comment] 2017-09-28 10:26
Hey @RCMainak could you provide what websites you are looking at and the addons that you are using?

A lot has changed from when you raised this bug. Are you on version 4.x?

**Comment by RCMainak** [comment] 2017-09-28 12:41
@jonathanKingston I was so much annoyed by the crashes I started using FF57 nightly build. Can't reproduce the crashes after that. I am using 4.0.2

I'll try to reproduce the crashes if I can reproduce it I'll get back to you. Maybe something else was causing the crash.

**Comment by groovecoder** [comment] 2017-09-28 13:11
Closing unless/until we can reproduce the crashes. Please re-open with steps-to-reproduce if you find them.

**Closed by groovecoder** 2017-09-28 13:11 UTC
Labels: bug, question

**Comment by jonathanKingston** [comment] 2017-09-28 22:34
Thanks @RCMainak!
