### ISSUE TITLE
Confirm and Deny buttons on "Open this site in your assigned container" view is faulty

### ISSUE THREAD

**Issue by renderghost** [mozilla/multi-account-containers#1505] opened 2019-09-26 15:24 UTC
When a domain is assigned to a container, the next time a page from that domain is opened in a different container, the `open in {container name} container` button (see image below) is faulty.

![image](https://user-images.githubusercontent.com/21337875/65700969-d7a71d80-e080-11e9-9f25-e3ad4715b77e.png)

### Actual behavior
The `open in {container name}` button requires multiple clicks to respond. This number of clicks required is inconsistent, but it will work _eventually_.

### Expected behavior
Pressing this button once should suffice.

### Steps to reproduce
1. Open any webpage in a named container
2. Press the `MAC` icon in the top bar
3. Select `Always open in {container name}` from the add-on panel
4. Open any webpage from the **same domain** in a **different container**
5. When asked "open this site in your assigned container?" click `open in {container name} container`

### Notes
- I'm using Firefox 69.0.1 (64-bit) on OSX 10.14.6 (18G87)
- May duplicate #1331

**Comment by chk1** [comment] 2019-09-27 11:16
I can reproduce this on 70.0b9 (64-bit) (Firefox dev edition, mostly default settings) on Win10. I thought it was my container naming at first (something like "one/two three")

**Comment by renderghost** [comment] 2019-09-27 13:42
I have played with this a bit more and have an update. 
- Clicking on the button background works as expected
- Clicking on the button text works fine
- _But_ Clicking container name gives no response.

I had a look at the code and I noticed the container name is wrapped in <dfn>

```<dfn class="container-name">Reading</dfn>```

I tried again and noticed the exact same issue with both the primary and default buttons: the <dfn> tag that breaks the <button> behaviour.

@chk1 maybe you can confirm if you see the same?

**Comment by chk1** [comment] 2019-09-28 15:35
I can reproduce this exactly like you describe, clicking on the *container name* on either button does not trigger any actions

**Comment by ps-gssleap** [comment] 2019-10-02 16:29
The issue is in `confirm-page.js` and it is fixed in master in this commit: https://github.com/mozilla/multi-account-containers/commit/3ae1803420aeb3c0ea2ef8c642bad4172484c084

I assume that the next release will have this fixed.

**Comment by ps-gssleap** [comment] 2019-10-02 16:36
Duplicate of #1447

**Comment by chk1** [comment] 2019-10-09 15:03
This seems to be fixed now, it's working properly on my Firefox :)

The changelog for the most recent release (6 days ago as of now) mentions 
> 3ae1803 Bug 1539507 - Fix targeting of button click when button element isn't clicked.

[Bug 1539507 on Mozilla's Bugzilla](https://bugzilla.mozilla.org/show_bug.cgi?id=1539507)

**Comment by maxxcrawford** [comment] 2019-10-14 18:29
@chk1 Thanks!

**Closed by maxxcrawford** 2019-10-14 18:29 UTC
