### ISSUE TITLE
Reopening container-associated url in another container doesn't work

### ISSUE THREAD

**Issue by sohmstyle** [mozilla/multi-account-containers#1763] opened 2020-06-09 09:12 UTC
- Multi-Account Containers Version: 6.2.5
- Operating System + Version: Windows 7 x64
- Firefox Version: 78.0b1-78.0b4(current)
- Other installed Add-ons + Version + Enabled/Disabled-Status:

Name | Version | Enabled | ID
-- | -- | -- | --
Firefox Multi-Account Containers |	6.2.5 |	true |	@testpilot-containers
Temporary Containers |	1.8 | true |	{c607c8df-14a7-4f28-894f-29e8722976af}

### Actual behavior
Reopening url in another container doesn't work, if it already associated to specific container.

### Expected behavior
For example. I have two containers: Home and Work. I associate Gmail with Home container. But if i try to reopen it in Work container then it opens in Home container again.
This behavior worked in Firefox 77 correctly - i could reopen container-associated url in another containers.

### Steps to reproduce
1. Associate google.com with Home container.
2. Reopen this tab in Work or another container

**Comment by gkaklas** [comment] 2020-06-20 14:42
I believe this seems like a duplicate of #1442 :thinking:

**Comment by maxxcrawford** [comment] 2020-07-08 19:24
Seems related to #1764 too.

**Comment by maxxcrawford** [comment] 2020-07-08 19:24
Duplicate of #1442

**Closed by maxxcrawford** 2020-07-08 19:24 UTC
