### ISSUE TITLE
Add a way to focus on a particular container.

### ISSUE THREAD

**Issue by mymikal** [mozilla/multi-account-containers#1195] opened 2018-04-18 01:44 UTC
I propose a button (or some other device) that applies focus to a specified container and hides all tabs unrelated to that container such that the only visible tabs are the ones associated with the container in focus. If tabs of the specified container are visible, it simply hides the tabs not part of that container; else, it "swaps" containers by first revealing the tabs of the specified container and then hiding the rest. Note that all tabs stay within their original containers, maintaining security and privacy.

This is essentially a macro to keep the tab-space clean by unloading tabs that aren't part of focus (which keeps memory usage down), and it acts as a quick-swap mechanism for navigating between different container tabs.

**Comment by falolaf** [comment] 2018-04-18 08:14
Are you perhaps looking for something like what conex aims to do when it is ready for prime time:
https://addons.mozilla.org/en-US/firefox/addon/conex/

**Comment by maverick74** [comment] 2022-11-30 12:43
Conex, as good as it is, suffers from one terrible problem: when dealing with many tabs it gets slow and seems to lack performance!!! (if i remember correctly it's related to firefox not "hidding" the tabs and closing/suspending them instead...)

**Comment by dannycolin** [comment] 2022-11-30 13:56
@maverick74 if it's the case then Multi-Account Containers will be affected by the same problem and only a change on Firefox side could solve this.

**Comment by maverick74** [comment] 2022-11-30 15:30
> @maverick74 if it's the case then Multi-Account Containers will be affected by the same problem and only a change on Firefox side could solve this.

Yes, you're right! Probably it will also affect Multi-Account Containers... Still, even if this can't be solved in Multi-Account Containers, i believe it's still worth adding the option to show only tabs of the current container (even if it has the performance issue).

**Comment by dannycolin** [comment] 2022-12-14 14:06
Duplicate of #350

**Closed by dannycolin** 2022-12-14 14:06 UTC
Labels: Status: Good Extra Addon
