### ISSUE TITLE
"Always open in" leads to some tabs being opened twice

### ISSUE THREAD

**Issue by buckket** [mozilla/multi-account-containers#1080] opened 2018-01-11 11:04 UTC
After enabling the option to always open `youtube.com` in the Personal Container, it so happens that whenever I want to open a YouTube tab, via the address bar, Firefox opens two tabs of this site with the container enabled.

The same feature works fine with other sites I tried so far. Disabling and re-enabling it also had no effect.

Edit: The problem only occurs when I try to open `https://youtube.com/` but not when accessing `https://www.youtube.com/`. Maybe it has something to do with the redirect?

### Application  Basics
Attribute | Value
----------|------
Name |Firefox
Version |57.0.4
Build ID |20180105075100
User Agent |Mozilla/5.0 (X11; Linux x86_64; rv:57.0) Gecko/20100101 Firefox/57.0
OS |Linux 4.14.12-1-ARCH
Enabled Plugins |about:plugins
Build Configuration |about:buildconfig
Memory Use |about:memory
Performance |about:performance
Registered Service Workers |about:serviceworkers
Multiprocess Windows |1/1 (Enabled by user)
Web Content Processes |4/4
Stylo |true (enabled by default)
Google Key |Found
Mozilla Location Service Key |Found
Safe Mode |false
Profiles |about:profiles

### Extensions
Name | Version | Enabled | ID
-----|---------|---------|---
Firefox Multi-Account Containers|5.0.1|true|@testpilot-containers
FoxyTab|2.10.1|false|foxytab@eros.man
Tomato Clock|4.2.4|false|jid1-Kt2kYYgi32zPuw@jetpack
uBlock Origin|1.14.22|false|uBlock0@raymondhill.net

**Comment by jonathanKingston** [comment] 2018-01-23 18:22
So redirects can cause this sometimes in that the site ends up creating a new blank redirect tab.
Do you have the URLs that end up in the tabs or an example URL you clicked on?

**Comment by groovecoder** [comment] 2018-01-23 18:44
Marking as duplicate of https://github.com/mozilla/multi-account-containers/issues/940 - please add upvotes and comments there.

**Closed by groovecoder** 2018-01-23 18:44 UTC
Labels: bug, help wanted, needs STR, site assignment, vote for me
