### ISSUE TITLE
Two Factor Authentication with Containers, possible?

### ISSUE THREAD

**Issue by BEG65** [mozilla/multi-account-containers#1220] opened 2018-06-04 02:21 UTC
Is there any list or resource detailing what needs to be done in order to have for example a container that lets you log into a google account with 2FA?  I can see that it needs to have some set of other sites connected to that container so that the 2FA process is not blocked but after about an hour of dumping in every single google.com something I can think of, I still can't get it to complete the 2FA (not to mention that I'm afraid of putting it into some inaccessible mode with too many failures on the login process).

The Facebook-only specialized container also failed to allow me to use 2FA when logging into FB, so even that prepackaged setup isn't accounting for 2FA. Any pointers gratefully accepted.

Thanks,
--Cindy

**Comment by groovecoder** [comment] 2018-07-16 17:54
2FA should work the same with Containers. I have many 2FA accounts signed-in across a few different containers: Google, Facebook, Twitter, etc.

Can you be more specific with your steps-to-reproduce this issue?

**Comment by kendallcorner** [comment] 2019-12-06 04:59
Hi. We're currently triaging the Multi Account Container issues. Steps to reproduce were never provided, so I'm going to close this. If you don't feel the underlying issue has been resolved, feel free to comment with updated steps to reproduce, and I can reopen it.

**Closed by kendallcorner** 2019-12-06 04:59 UTC

**Comment by vraravam** [comment] 2021-06-15 10:37
This seems to have cropped up again. I have a google 2FA account with my company. This was working for the past few months/years that i had been using CwT, but since yesterday, this seems to open a new tab in FF for each redirect. Thus, the actual signin doesn't get completed ever. I am able to signin normally if I disable CwT. I'm running FF nightly - if that matters.

**Comment by Vjedi729** [comment] 2025-03-25 23:57
This is also happening to me, specifically when I've creating a container for all Google sites. It seems to happen specifically when the authentication page is opened as a pop-up rather than as a new tab. This consistently occurs if I try to make a mail filter in Gmail.
