### ISSUE TITLE
Firefox multi-account-containers forgets custom containers on being disabled/reenabled.

### ISSUE THREAD

**Issue by kensmosis** [mozilla/multi-account-containers#1988] opened 2021-03-09 17:53 UTC
### Describe the problem and steps to reproduce it:
(Please include as many details as possible.)

Disabling and re-enabling firefox multi-containers forgets any containers that were created, and forgets everything in those containers.   Since modern web usage requires constant disabling and reenabling of add-ons such as ghostery and ad-block, it is common to accidentally disable multi-containers by hitting the wrong button --- especially since the list of add-ons is rearranged when disabling one [nor is private mode a sensible alternative since it disables ALL add-ons].  This is a big problem, and makes multi-containers unusable.

I take the time to setup specialized containers, and log into accounts in those containers, and then one wrong tap and it's all lost and has to be rebuilt.   Nor is it obvious this will happen [no warning message, no ask-before-delete, no info to this effect].  It just silently forgets the configuration.  Permanently.

Other add-ons such as Leechblock, ghostery, and ad-block retain full configuration when disabled and reenabled.  This is what "disabling/enabling" means.  What happens now should be termed "reset to factory default settings", and available only as a special option under settings.  

This behavior by Multi-containers can only be deemed a bug. 

### What happened?

Custom containers disappeared permanently.  When multi-containers was reenabled, it reverted to the default 4 containers (shopping, blah blah).  

### What did you expect to happen?

A return to the exact state prior to disabling, or at least retention of the custom container settings.

### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)

**Comment by wagnerand** [comment] 2021-03-09 22:49
Duplicate of #1236.

**Comment by groovecoder** [comment] 2022-04-01 18:14
Closing as dupe of #1236. (and linking that bug to https://bugzilla.mozilla.org/show_bug.cgi?id=1549204 which I'm going to ping to try to get some help here.)

**Closed by groovecoder** 2022-04-01 18:14 UTC
Labels: duplicate
