### ISSUE TITLE
No icon when "Never remember history" is selected

### ISSUE THREAD

**Issue by Gorboram** [mozilla/multi-account-containers#1875] opened 2020-09-25 07:36 UTC
I installed the Multi-Account Containers add-on and no icon appeared. So, I came here to report this as a bug. However, when writing this post, I was presented with an issue template that says, in part:

> Also please make sure that:
>   - "Firefox will: Never remember history" in the Firefox Preferences/Options under "Privacy & Security > History" is NOT selected

I have "Never remember history" selected. I changed that setting to "Remember history" and the icon appeared. So, apparently, the Multi-Account Containers add-on doesn't work with the "Never remember history" setting. Kudos to someone for putting that note in the issue template, but maybe you should put this information in the add-on description and wiki as well. It is rather important.

So, why doesn't the add-on work with "Never remember history"? It makes no sense. Why should I have to choose between the privacy of containers vs. the privacy of a clean history? Why can't I have both?

**Comment by RhinocerosUnicornis** [comment] 2022-05-25 20:59
Seconding that it is frustrating that we can't log into multiple accounts when history is off.

**Comment by dannycolin** [comment] 2022-12-30 23:59
"Never remember history" sets Firefox to automatic private browsing mode and the addon currently doesn't support it. I'm closing as a duplicate of #1864

**Closed by dannycolin** 2022-12-30 23:59 UTC
