### ISSUE TITLE
rearrange the containers

### ISSUE THREAD

**Issue by guy1234-art** [mozilla/multi-account-containers#1720] opened 2020-04-24 02:29 UTC
please
how can i rearrange the containers ?
now the first container i did is in the top of the containers 
but i want to put in one the last of the containers

**Comment by Solid-Ice8** [comment] 2020-04-25 19:51
Please read my reference:  #1707

**Comment by alexanderadam** [comment] 2020-08-05 18:33
Duplicate of #330

**Comment by dannycolin** [comment] 2022-06-13 12:48
Duplicate of #330 indeed. See also #1608 for the Pull Request that introduced the ability to reorder containers.

**Closed by dannycolin** 2022-06-13 12:48 UTC
