### ISSUE TITLE
add setting: should links default to current or no container?

### ISSUE THREAD

**Issue by loldrup** [mozilla/multi-account-containers#999] opened 2017-11-23 00:35 UTC
I would love to have this behavior:
Links that points within the same (sub-)domain defaults to staying in the same container. Other links defaults to going to 'no' container.
While it might be too much to simply make this behavior the STANDARD behavior, perhaps we could have a UI settings button that enables this behavior?

**Comment by SoftVision-EmilPasca** [comment] 2017-11-23 09:49
Hi @loldrup, thanks for reporting this issue. However, this looks like a duplicate of https://github.com/mozilla/multi-account-containers/issues/473.

**Closed by SoftVision-EmilPasca** 2017-11-23 09:49 UTC
