### ISSUE TITLE
functionality/UX Suggestions 

### ISSUE THREAD

**Issue by brain8891** [mozilla/multi-account-containers#1234] opened 2018-07-07 12:21 UTC
suggestions:

1- having two check marks; ☑ Always open this website/URL (Facebook.com) with this container (My Facebook,) and  ☑ Except when I am in a different container.

Meaning if you made a container for a family member Gmail, Facebook, or their Other accounts; For example your mother, father, or technologically illiterate girlfriend accounts then you would be able to protect your privacy on ANY site not just Facebook, and manage other people or your other accounts. 

2-  Adding description to containers and viewing them when hovering over them

3- Have more custom control on colors and icons of containers, let the community make icons  and submit them.

4-  having the right click options not just within the page but also when you right click on a tab, it is more intuitive for users to click on the tab to set the option of "Always open in this container"

5- Organizing the containers in folders and sub-folders structure: I don't use Multi-account containers as much because I manage many accounts, and it would be nice to have the option to create folders and sub-folders . For example: you would have a folder called "Others accounts" and in it there is two others  folders "Managed businesses" and "family." Inside "Managed businesses" folder you would have business1, business2 containers; and in family you will have Father container Mother container etc.

Why? I have 4 main containers, I use them, if I made many containers then I will have a huge list, so I could add two folders at the bottom root list and fill them with containers that I don't use frequently. I think many people who manages there elderly/ illiterate girlfriends account would benefit from this. Also, those who manages many businesses.   Currently I use private browsing and I hate typing the passwords all the times.

Sorry for my broken English

**Comment by alexanderadam** [comment] 2020-08-05 18:44
Custom colors (3.) is a duplicate of #391

**Comment by brain8891** [comment] 2020-08-06 12:57
> Custom colors (3.) is a duplicate of #391

 @alexanderadam for customer colors, yes. also,  take a look at #984 
In hindsight I think number (3.) is a little complicated to maintain, However, being able to set custom colors, and let the user assign a 16x16 png for example, is not that hard. 
Additionally, as @Madis0 said at #984  having Unicode characters (AKA letters too) and  emojis as custom symbols, will be good for users who have more than 5 containers to spot them, and for users who want to have a symbol representing the container. 

I forgot about #1234, that is a cool number. Now that some years has past,  I use containers  more and more, but I stop myself from creating more containers, because it will clutter the interface, and I jump to Private window which means entering password more everytime, you see, if you are an IT, a freelancer who managers different businesses accounts, or the family IT where you have to make a container for each family member because it is impossible to teach them,. it helps to have  folders, custom icons and colors

**Comment by grahamperrin** [comment] 2021-04-23 17:18
Cross reference: 

* Mozilla bug [1454188 - Support character(s) as Containers icon](https://bugzilla.mozilla.org/show_bug.cgi?id=1454188)

**Comment by grahamperrin** [comment] 2021-04-23 17:20
> 5- … folders

▶ https://github.com/mozilla/multi-account-containers/issues/1849#issuecomment-689768544

**Comment by dannycolin** [comment] 2022-05-24 23:49
Closing since this contains more than one suggestions in one report. Some of the suggestions have already been asked as others have pointed out. For those that haven't feel free to file a new report for each of them.

**Closed by dannycolin** 2022-05-24 23:49 UTC
Labels: Feature request
