### ISSUE TITLE
Add option to set random user agent in a specific container

### ISSUE THREAD

**Issue by shahishasank** [mozilla/multi-account-containers#1981] opened 2021-03-02 09:43 UTC
I have been using this extension in firefox with [Random User agent](https://github.com/tarampampam/random-user-agent), but the problem is, I can't get the same user agent for every container. I have seen similar feature in ghost browser(ss attached), they call it identity manager and you can set random user agent in it. It would be really helpful feature if you embed the user agent feature. Thank you

![image](https://user-images.githubusercontent.com/32937688/109629160-90706680-7b69-11eb-8e7c-8dbade39d680.png)

**Comment by dannycolin** [comment] 2023-01-15 23:51
Duplicate of #2310

**Closed by dannycolin** 2023-01-15 23:51 UTC
Labels: Needs: Mozilla Central, :+1:  Feature Request
