### ISSUE TITLE
Exclusive containers

### ISSUE THREAD

**Issue by janlimpens** [mozilla/multi-account-containers#1260] opened 2018-09-19 12:44 UTC
I want to keep social media in one container, but all links leading outwards, to open in the default or another container, following normal rules.
For instance: I want everything under the domain facebook.com to be restricted to one container "fb".  When I click on a link within fb, that leads me to a domain not registered to the fb container, I want it to open in the default container, that is, if there is no other rule putting it into another container.
Can this be done somehow?

**Comment by groovecoder** [comment] 2018-09-19 17:56
For Facebook specifically, you can use https://addons.mozilla.org/firefox/addon/facebook-container/ instead of M-A-C.

This is otherwise a duplicate of the "whitelist" feature request in https://github.com/mozilla/multi-account-containers/issues/847

**Closed by groovecoder** 2018-09-19 17:56 UTC
