### ISSUE TITLE
Very often I'm unable to click the buttons to open a page either in the current container or its assigned container

### ISSUE THREAD

**Issue by echosa** [mozilla/multi-account-containers#1380] opened 2019-04-23 13:30 UTC
- Is "Firefox will: Never remember history" in the Firefox Preferences/Options under "Privacy & Security > History" selected? Yes/No: No
- Are you using Firefox in a Private Window? Yes/No: No
- Can you see a grayed out but ticked Checkbox with the description "Enable Container Tabs" in the Firefox Preferences/Options under "Tabs"? Yes/No: Yes
- Multi-Account Containers Version: 6.1.0
- Operating System + Version: Pop!_OS 19.04
- Firefox Version: 66.0.3
- Other installed Add-ons + Version + Enabled/Disabled-Status:
```
Cookie AutoDelete	3.0.1	true	CookieAutoDelete@kennydo.com
Don't touch my tabs! (rel=noopener)	2.1	true	{6b938c0c-fc53-4f27-805f-619778631082}
Firefox Multi-Account Containers	6.1.0	true	@testpilot-containers
GitHub Notifier	1.3.2	true	{0906178a-2043-4d0c-a099-bd6a4d00945e}
GNOME Shell integration	10.1	true	chrome-gnome-shell@gnome.org
HTTPS Everywhere	2019.1.31	true	https-everywhere@eff.org
JetBrains Toolbox Extension	1.9.3781	true	{bf9e77ee-c405-4dd7-9bed-2f55e448d19a}
LastPass: Free Password Manager	4.26.0.4	true	support@lastpass.com
Redirect AMP to HTML	2.0.0	true	{569456be-2850-4f7e-b669-71e55140ee0a}
Temporary Containers	0.95	true	{c607c8df-14a7-4f28-894f-29e8722976af}
uBlock Origin	1.18.16	true	uBlock0@raymondhill.net
Link Cleaner	1.5	false	{6d85dea2-0fb4-4de3-9f8c-264bce9a2296}
```

### Actual behavior
Sometimes, quite often in fact, when I click on a link that opens a tab asking if I want to open it in the current container or the container I've set as default (with a checkbox to not ask again), clicking the buttons to open in either container don't work. I can usually get it to work by toggling the checkbox a few times, then clicking the button to open in the desired container.

### Expected behavior
The buttons to open in a container should always work, first try.

### Steps to reproduce
1. Click a link for a site to which you have assigned a container but have not selected the checkbox to always open in that container by default.
2. On the page which asks you which container you'd like to open the page in (the current one or the assigned one), click the container choice buttons.

### Notes
This issue doesn't always happen, but it happens quite often. Many times per day. It also seems like once you get one to work, all future ones will work for a bit.

**Comment by stoically** [comment] 2019-04-23 13:35
A workaround is to not click the **bold** container name in the buttons. Open PR to fix this is #1350.

Duplicate of #1331.

**Closed by stoically** 2019-04-23 13:35 UTC
