### ISSUE TITLE
Custom container colors

### ISSUE THREAD

**Issue by sunknudsen** [mozilla/multi-account-containers#1712] opened 2020-04-14 11:49 UTC
This extension is absolutely amazing! Thanks so much for developing it!

I am desperately craving the possibility to assign custom colours to containers. A simple HEX text field would be sufficient to get started.

Imagine how cool it would be to assign `#4267B2` to Facebook and `#FF0000` to YouTube.

Feels like the natural thing to do as our minds are wired to link colours to brands.

I also create containers for each of my projects which all have branded colours.

Please, please, please, can someone create a PR for this?

**Comment by Solid-Ice8** [comment] 2020-04-16 01:26
I've requested this already > #1707.

**Comment by alexanderadam** [comment] 2020-08-05 18:41
Duplicate of #391

**Comment by grahamperrin** [comment] 2021-04-23 16:08
@sunknudsen please close this duplicate. Thank you.

**Closed** 2021-04-23 17:25 UTC

**Comment by grahamperrin** [comment] 2021-04-23 17:40
Thanks!
