### ISSUE TITLE
File -> Save Page As... from inside a container saves an out-of-container version

### ISSUE THREAD

**Issue by bialis** [mozilla/multi-account-containers#1225] opened 2018-06-14 08:01 UTC
| midgleyc (Reporter) (New to Bugzilla)

User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:61.0) Gecko/20100101 Firefox/61.0
Build ID: 20180517141400

Steps to reproduce:

1. Create a container
2. Inside the container, log in to a site
3. Navigate to a page that displays different content to logged-in users.
4. Save the page using File -> Save Page As or Ctrl-S.

Actual results:

The saved page is the one that would be displayed to logged-out users.

Expected results:

The saved page is the one seen in the browser.

This is what happens if you use Right-click -> Save Link As, but this is inaccessible when editing a URL directly, and trying to save the resulting page.

midgleyc (Reporter) (New to Bugzilla) | Tag Reply -
-- | --
Comment 3 • 16 days ago

The exact failure case originally was attempting to Save Page inside a container from the raw version of a GitLab-hosted .feature file. I have reproduced this. Saving the View Source page also fails. Both of these have type text/plain, which is the primary difference I can see between this and a standard webpage.

You can follow the rest of the discussion here: 
https://bugzilla.mozilla.org/show_bug.cgi?id=1463365

**Comment by kendallcorner** [comment] 2019-12-06 16:25
Hi this is a duplicate of #519, and it also looks like it's been fixed, so I'm going to close it.  If you don't feel the underlying issue has been resolved, feel free to comment with updated steps to reproduce, and I can reopen it.

**Closed by kendallcorner** 2019-12-06 16:25 UTC
