### ISSUE TITLE
Close tabs from hidden container all at once

### ISSUE THREAD

**Issue by lucasr** [mozilla/multi-account-containers#873] opened 2017-09-27 20:48 UTC
It's a bit clunky to see tabs being closed one by one when you hide a container.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/MAC-608)

**Comment by jonathanKingston** [comment] 2017-09-28 10:18
This is likely an issue with Firefox itself or the extensions you are using. What version Firefox are you using and what addons do you have?
Thanks

**Comment by dannycolin** [comment] 2022-05-21 00:41
I couldn't reproduce this in the latest Firefox version (currently 102/nightly). Closing. Please file a new bug report if this issue still happen.

**Closed by dannycolin** 2022-05-21 00:41 UTC
Labels: question, Feature request
