### ISSUE TITLE
Feature Request: UX support for per-site containers

### ISSUE THREAD

**Issue by DanielHeath** [mozilla/multi-account-containers#995] opened 2017-11-22 03:04 UTC
I'm using a different container (with 'always open in this container' set) for most sites I have a login to.

Currently this is quite time consuming as the flow is:

 * Add new container
 * Open new tab with container
 * Copy url over from previous tab
 * Right click -> mark 'always use'
 * Open another new tab, paste url
 * Click through "yes I meant it when I said 'always use'"

**Comment by jonathanKingston** [comment] 2017-11-28 12:06
Per site containers are basically First Party Isolation which is what the Tor browser uses. This breaks many sites however.

This is a duplicate of: https://github.com/mozilla/multi-account-containers/issues/719 or https://github.com/mozilla/multi-account-containers/issues/691

Please follow these instead, thanks for raising.

**Closed by jonathanKingston** 2017-11-28 12:06 UTC
Labels: assignment

**Comment by ArchangeGabriel** [comment] 2017-12-28 19:12
I’m not sure about the duplicates links. I think #655 looks more like it.
