### ISSUE TITLE
How to automatically have two of the same website open in different containers ?

### ISSUE THREAD

**Issue by ng4ever** [mozilla/multi-account-containers#1342] opened 2019-02-14 00:32 UTC
Basically I have two different login information for the same website.

**Comment by D219** [comment] 2019-04-05 12:47
One solution would have been #854, but it was closed

**Comment by nba2** [comment] 2019-04-18 19:08
+1, me and others in #854 would very much appreciate this feature. I just switched from firefox to chrome and it was very easy to have one personal profile and one profile for school that were totally separate. Multi-account containers is very much lacking in comparison.

**Comment by stoically** [comment] 2019-05-04 12:13
Duplicate of https://github.com/mozilla/multi-account-containers/issues/1171 - please vote there. Thanks!

**Closed by stoically** 2019-05-04 12:13 UTC
