### ISSUE TITLE
Ability to add a custom colour while creating or editing a container

### ISSUE THREAD

**Issue by yellowwoods12** [mozilla/multi-account-containers#1543] opened 2019-10-19 20:31 UTC
- Multi-Account Containers Version:
- Operating System + Version:
- Firefox Version:
- Other installed Add-ons + Version + Enabled/Disabled-Status:

### Actual behavior
There is a predefined set of limited colours that can be assigned to a container during its creation or editing.

### Expected behavior
A feature enhancement in which a user is able to add any custom colour to a container while creating a new one or editing a previous one.

**Comment by Aishat-Akinyemi** [comment] 2019-10-24 11:06
Hello @groovecoder and @maxxcrawford should I work on this as an #outreachy applicant

**Comment by kendallcorner** [comment] 2019-12-04 22:56
This is a duplicate of #391 please +1 or discuss on that issue. I'll close this, but feel free to reopen if you think it's a different issue.

**Closed by kendallcorner** 2019-12-04 22:56 UTC
