### ISSUE TITLE
proposal / enhancement: always-open-in-[set of containers]

### ISSUE THREAD

**Issue by escapewindow** [mozilla/multi-account-containers#1171] opened 2018-03-29 19:11 UTC
I have multiple accounts for certain sites: google, amazon, etc, and I want them to show up in container A or B.

I'm not sure if it would be more or less usable to constrain them to a set of containers, and have multi-account-containers ask us which container we'd like to open for a particular tab.

**Comment by JohnCalin** [comment] 2018-03-30 23:12
I'd like to second this.  Currently I can assign a site (say, amazon.com) to a container, and when I visit amazon.com it will ask me if I want to open it in the current container, or assigned container, and whether to remember that decision.  I would love to be able to either assign a site to multiple containers (e.g. amazon A or amazon B), or set a site to be excluded from a certain container (e.g. the Default container).  The confirmation screen could then offer me choices of the current container plus any of the assigned containers (or the current container plus any non-excluded containers, if going that way).  This would keep me from ever accidentally visiting and logging in in my default container, while also allowing multiple accounts to be used.

**Comment by JohnCalin** [comment] 2018-03-30 23:13
To be clear I'm not asking for both multiple assigned containers AND excluded containers - just exploring different ways to get the job done.

**Comment by escapewindow** [comment] 2018-03-30 23:33
I think an exclusion list could work. I'm using the Temporary Containers addon, so Google or Amazon link might appear in one of the tmp12345 containers, but I'm also using the Switch Container addon, so I could always switch it to the correct container.

**Comment by grahamperrin** [comment] 2021-04-23 22:45
> … constrain them to a set of containers, and have … ask us which container we'd like …

https://github.com/tiansh/always-in-container/issues/1

**Comment by dannycolin** [comment] 2023-01-02 01:47
Duplicate of #1749

**Closed by dannycolin** 2023-01-02 01:47 UTC
Labels: Component: Site Assignment, :+1:  Feature Request
