### ISSUE TITLE
"Always open in " allow multiple container assignments

### ISSUE THREAD

**Issue by t4777sd** [mozilla/multi-account-containers#1102] opened 2018-01-28 12:08 UTC
Currently, a particular domain can only be assigned ONE container. If you access that domain you are presented with a screen that asks you if you would like to open that domain in its particular assigned container.

I think a very useful feature is to allow a domain to be assigned MULTIPLE containers. If you access the domain when not in one of its assigned containers, then it asks you which container you want to open it in.

**Why is this feature very useful?**

One of primary aspects of containers is having multiple identities. For example, if a person has multiple gmail accounts and they only want to access their gmail account in its own container, then they need the ability to limit the gmail domain to multiple containers for the multiple identities.

This becomes even more important when containers (through an addon or default) allow different proxy settings.

**Comment by groovecoder** [comment] 2018-01-29 19:35
Duplicate of https://github.com/mozilla/multi-account-containers/issues/849. Please add upvote & comments there.

**Closed by groovecoder** 2018-01-29 19:35 UTC
