### ISSUE TITLE
Can't view Google Docs on containerized tab

### ISSUE THREAD

**Issue by ruipacheco** [mozilla/multi-account-containers#1023] opened 2017-12-04 12:33 UTC
I tried opening a Google Spreadsheet on a containerized tab and the cells appear as all black. First the page loads normally, then there's a pause and suddenly all cells are painted black.

If I try to open the spreadsheet on a tab that does not belong to any containers the spreadsheet loads correctly.

**Comment by SoftVision-EmilPasca** [comment] 2017-12-04 12:59
Hy @ruipacheco, thanks for reporting this issue. Can you please provide more information, as the Operating system, Firefox version and also the add-ons that you may have installed?

**Comment by ruipacheco** [comment] 2017-12-04 13:02
Hello,

I'm on the latest Firefox running on the latest macOS. I also have Ghostery, uBlock, HTTPSEverywhere, Imagus, Switch Container and Toby.

As an aside, I can't replicate this issue any more. I wrestled with it yesterday and today, opened this github issue and then used Switch Container to Decontain the page and now it works fine, even in the original container where I couldn't open it.

**Comment by SoftVision-EmilPasca** [comment] 2017-12-04 13:09
Thanks @ruipacheco  for the provided info. Since this is no longer reproducible for you, I'm going to close this issue.
Please feel free to re-open this if the issue comes back again and we're going to investigate this further.

**Closed by SoftVision-EmilPasca** 2017-12-04 13:09 UTC

**Comment by ruipacheco** [comment] 2017-12-04 14:52
I've hit the bug again. I had the spreadsheet open in a container where I was not logged in to Google. I used Switch Container to reload in a container where I was logged in to Google and the spreadsheet reloaded as all black.

**Comment by ruipacheco** [comment] 2017-12-04 14:53
Surprise surprise, I can't reproduce it again.

**Comment by SoftVision-EmilPasca** [comment] 2017-12-04 15:16
I am going to have a look upon this issue myself and see if I can also reproduce it.
