### ISSUE TITLE
The UI redesign makes it harder to open a new tab

### ISSUE THREAD

**Issue by abjbhat** [mozilla/multi-account-containers#1818] opened 2020-07-16 03:41 UTC
The previous design of the UI had a plus icon right next to the label. I have no idea why this option is now buried two levels deep into UI. Or maybe I'm missing something glaringly obvious. 

Either way, the UI redesign needs to be redesigned/reverted or give me an option to go back.

**Comment by mikeybanez** [comment] 2020-07-16 07:04
Yeah I had that first impression too. Though I recently realized that you could either long-press the + button or right-click it, and you still get the appropriate menu.

**Comment by abjbhat** [comment] 2020-07-16 07:10
Thanks for the tip! 

Yes, the right click on the new tab is a good option. Though I wish this was communicated somewhere. The new option is hard to figure out. 

Also, users installing this extension for the first time may not be able to discover this as fast as the previous way.

**Comment by robert-moore** [comment] 2020-07-16 12:32
The keyboard shortcuts are great though. I'm so hard wired to using cmd + t that I never got used to clicking the extension icon to open a new tab.

**Comment by sdht0** [comment] 2020-07-17 03:26
For me, in 7.0.1, clicking on the container name opens a new tab in that container, while clicking on the right area with the arrow opens the container settings.

**Comment by amicitas** [comment] 2020-07-17 14:44
I would like to see as an enhancement a second 'simplified' menu button as an option that only has tab opening (more similar to v6). The new menu is too complicated given that 99% of the time that I click on that button I just want to open a new tab.

**Comment by renedarioherrera** [comment] 2020-07-20 19:33
I concur. Version 7.0.2 UX redesign is a step back.

**Comment by dannycolin** [comment] 2023-01-01 00:09
Closing as a duplicate of #2089 that's about the same issue but more focused on the latest version.

**Closed by dannycolin** 2023-01-01 00:09 UTC
