### ISSUE TITLE
Feature: Reordering containers

### ISSUE THREAD

**Issue by tatifox** [mozilla/multi-account-containers#1843] opened 2020-08-03 19:45 UTC
Great extension,

I manage 20+ containers, could you please add a container reordering feature to customise containers position by dragging them to achieve desired order.

Thank you!

**Comment by fitzha** [comment] 2020-08-05 04:02
+1, would like this feature when the time allows 🙂

**Comment by alexanderadam** [comment] 2020-08-05 18:31
Duplicate of #330

**Comment by groovecoder** [comment] 2021-01-22 17:29
#330 was fixed in #1608 and 7.3.0 release is pushed to AMO waiting for review and publish.

**Closed by groovecoder** 2021-01-22 17:29 UTC
Labels: duplicate, enhancement
