### ISSUE TITLE
[Windows] A part of the current tab's title is wrongly displayed in the "Edit Containers" panel, after you move the window while the edit panel is open

### ISSUE THREAD

**Issue by Softvision-CristinaBadescu** [mozilla/multi-account-containers#1163] opened 2018-03-27 11:00 UTC
**[Affected versions]:**
- Multi-Account Containers 6.0.0
- Firefox 59.0.1 and above

**[Affected Platforms]:**
- All Windows

**[Prerequisites]:**
- Have a Firefox profile with the latest "Multi-Account Containers" add-on version (6.0.0) installed.

**[Steps to reproduce]:**
1. Open the browser with the profiles from prerequisites, navigate to https://brightside.me/ and click the "Multi-Account Containers" button from the browser toolbar.
2. Click the "Edit Containers" button and move the window.
3. Click again the add-on toolbar button and click the "Edit Containers" button.
4. Observe the edit panel.

**[Expected result]:**
- The edit panel is correctly displayed.

**[Actual result]:**
- A part of the current tab's title is wrongly displayed above the containers list.

**[Notes]:**
- You might need to repeat several times steps 2 & 3 to encounter this issue.
- Here is a screen recording of the issue:
![multi-account containers - title](https://user-images.githubusercontent.com/31244235/37963506-1fe72c62-31c7-11e8-8b9b-90ee2cc80838.gif)

**Comment by Paarmita** [comment] 2018-09-23 14:05
@Softvision-CristinaBadescu I tried this many times by changing the window location and trying clicking edit button several times, but I couldn't reproduce this error.

**Comment by groovecoder** [comment] 2018-09-24 19:54
Unable to reproduce; this seems to be fixed now.

**Closed by groovecoder** 2018-09-24 19:54 UTC
Labels: Container Panel, bug, help wanted
