### ISSUE TITLE
Syncronize container with every devices

### ISSUE THREAD

**Issue by drazde** [mozilla/multi-account-containers#1594] opened 2019-12-05 07:29 UTC
I would like have the same configurations of the containers (and the default containers for the site) share with all my device.

Could be possible add containers like options at Mozzilla Sync?

**Comment by kendallcorner** [comment] 2019-12-05 15:21
Hi. This looks like a duplicate of #339. Please vote (:+1:) or discuss on those issues so they are more likely to be completed. I'll close this, but feel free to reopen if you think it's a different issue.

**Closed by kendallcorner** 2019-12-05 15:21 UTC
