### ISSUE TITLE
Colour assignment for containers is unnecessarily restrictive

### ISSUE THREAD

**Issue by crankycoder** [mozilla/multi-account-containers#958] opened 2017-11-13 22:42 UTC
While I appreciate that someone spent the time to assign a nice colour palette for containers, it is a problem for people (namely me) who are severely colour blind.

I need to be able to make the colours wildly different for me to differentiate them - especially when the container colour only seems to draw a thin line at the bottom of the tab chrome.

Please do keep a default palette, but allow users to select arbitrary RGB colours to override the defaults.

**Comment by Madis0** [comment] 2017-11-19 19:31
Duplicate of #391

**Closed** 2017-11-20 09:21 UTC

**Comment by Softvision-CristinaBadescu** [comment] 2017-11-20 09:33
Indeed, the same idea seems to be discussed in #391. I'm gonna close this one, but please provide any additional feedback there if you think it's necessary.

**Comment by FabianoLothor** [comment] 2023-03-02 23:50
The other thread was closed, for how many years we'll still wait for that feature?
