### ISSUE TITLE
Pinned container tab lost pinned state next time opening Firefox

### ISSUE THREAD

**Issue by ameaninglessname** [mozilla/multi-account-containers#1921] opened 2020-12-18 07:49 UTC
- Multi-Account Containers Version:7.1.0
- Operating System + Version:Windows10 19042.685
- Firefox Version: 84.0
- Other installed Add-ons + Version + Enabled/Disabled-Status:Facebook container and many other extensions

### Actual behavior
When I open Firefox, 
pinned container tab ask me "Open this site in your assigned container?",
because **"Remember my decision for this site" is unchecked**.

After I choose one of the option, the tab is no longer pinned,
I need to pin them again.

### Expected behavior
Pinned container tab stays pinned after i choose one of the option of "Open this site in your assigned container?".

**Comment by rdcc** [comment] 2020-12-23 08:30
Same problem.
- Multi-Account Containers Version:7.1.0
- Operating System: Debian GNU/Linux (bullseye)
- Firefox Version: 84.0 (64 bits)

**Comment by rdcc** [comment] 2021-01-10 21:34
Similar problem here.
I created a Twitter container and works fine, but.. When I pin the Twitter tab like several other tabs, each one in their own container. When I close Firefox and then reopen it, all containerized tabs open in their usual places (pinned) except for the Twitter tab which opens unpinned but still containerized.
![Peek 10-01-2021 14-33](https://user-images.githubusercontent.com/10103315/104136018-cd319580-5350-11eb-8c65-53b38fcaee52.gif)

**Comment by judbd** [comment] 2021-02-11 21:48
Same problem here :
- If twitter is permanently assigned to a container and pinned = it's still in the container but unpinned when I close/reopen firefox
- If twitter is assigned to a container (not permanently) the container is lost when you close/reopen firefox (but the tab stays pinned)

It's like Twitter is loading in two steps with different URL or something like that.

**Comment by chihweitung** [comment] 2021-02-12 16:59
Hi,

I am Tom Tung from Mozilla. We are working on resolving this issue and it is tracked at https://bugzilla.mozilla.org/show_bug.cgi?id=1665942.

**Comment by sorinello** [comment] 2021-03-20 15:17
Hello. I see that this is marked as fixed in Bugzilla, but I am unable to find out if this was released in a version of Containers. I am still hitting this twitter issue with the latest Containers version (7.3.0)

**Comment by chihweitung** [comment] 2021-03-22 07:55
> Hello. I see that this is marked as fixed in Bugzilla, but I am unable to find out if this was released in a version of Containers. I am still hitting this twitter issue with the latest Containers version (7.3.0)

Hi @sorinello,

I couldn't reproduce the issue through the STR like:
1. Open a tab and load twtter.com
2. Right click that tab -> Reopen in container -> Chose any non-default container.
3. Close the non-default container tab and press Ctrl+Shift+T
on my laptop. The Firefox version I am using is Nightly 88 (The fix was landed on 88).

Maybe it's another issue or maybe it's because your Firefox version is not new enough?
If it's the former case, then could you provide the steps to reproduce your issue so that I can help you to fire another ticket on Bugzilla?

**Comment by sorinello** [comment] 2021-03-22 08:00
Hi @chihweitung 

I am running stable Firefox, currently at 86.0.1. When I'll get to Firefox 88 I will check again and come back to confirm if this is fixed for me.

**Comment by chihweitung** [comment] 2021-03-22 08:02
Ah, then we will see if that resolves your issue or not. Thanks for the information!

**Comment by dannycolin** [comment] 2022-12-29 03:25
Closing since it has been fixed upstream. If it still happen, you should file a bug on bugzilla.mozilla.org.

**Closed by dannycolin** 2022-12-29 03:25 UTC
Labels: bug
