### ISSUE TITLE
[Feature Request] Lost web sessions after a fast disable/enable multi-account-containers add-on

### ISSUE THREAD

**Issue by tvass** [mozilla/multi-account-containers#1212] opened 2018-05-16 19:44 UTC
### Actual behavior
I lost all my sessions when I disable and enable back the add-on a few seconds later. 

### Expected behavior
Make web sessions survives a fast disable/enable multi-account-containers add-on.

### Steps to reproduce
1. Login to https://[.....].com
2. Disable add-on
3. Enable add-on
4. Go back to https://[.....].com to see session if lost.

**Comment by dannycolin** [comment] 2022-07-19 18:59
Duplicate of #1236

**Closed by dannycolin** 2022-07-19 18:59 UTC
Labels: bug
