### ISSUE TITLE
Opening a URL using enter key modifiers does not open in same container tab

### ISSUE THREAD

**Issue by milescrabill** [mozilla/multi-account-containers#448] opened 2017-04-12 18:28 UTC
Steps to reproduce:

- Open a container tab
- In the URL bar of the container tab, enter a URL
- Press option+enter (open URL in new tab) or another URL open modifier

Expected Result:
URL opens in new container tab, the same container as the URL was opened from

Actual Result:
URL opens in new default tab, not in a container tab of the same container as opened from

**Comment by grahamperrin** [comment] 2021-04-30 08:32
Is this still an issue? 

I can't reproduce it. 

For me with Firefox `88`, neither <kbd>Alt</kbd>-<kbd>Return</kbd> nor <kbd>Alt</kbd>-<kbd>Enter</kbd> opens a new tab in the context of a URL entered at **about:newtab**

**Comment by dannycolin** [comment] 2023-01-10 00:26
Same here, Alt+Enter does nothing in 110. Closing since we didn't get an answer back from OP and 2 persons can't reproduce it.

**Closed by dannycolin** 2023-01-10 00:26 UTC
Labels: bug

**Comment by jwbth** [comment] 2024-03-20 08:21
I assume the OP just missed the step "Open any URL in the container tab", with which it's easily reproducable, while without it, Alt+Enter just proceeds to open the URL in the same tab (which is in itself a questionable behavior, but that would be offtopic). The issue is of the same class as #462, but  for opening a URL you have already typed in the address bar.
