### ISSUE TITLE
Custom container order isn't respected in other menus

### ISSUE THREAD

**Issue by denilsonsa** [mozilla/multi-account-containers#2648] opened 2024-07-16 13:47 UTC
### Before submitting a bug report

- [X] I updated to the latest version of Multi-Account Container and tested if I can reproduce the issue
- [X] I searched for existing reports to see if it hasn't already been reported

### Step to reproduce

1. Create a few custom containers.
2. Change their order.
3. Now try these locations:
    * Click on the extension icon at the toolbar. (AKA popup)
    * Click on the extension icon at the location bar. (AKA pageAction)
    * Click-and-hold or click-and-drag the New Tab button.
    * Right-click on a link, Open link in a new container tab.
    * Right click on a Bookmark. (untested by me, no screenshot provided)
    * (Anywhere else that I may have forgotten?)

### Actual behavior

* The list of containers is in the custom order at the main icon (AKA the extension popup), as expected.
* The list of containers is reset to their creation order in all other places. This is a bug.

Screenshots:

![Main extension popup](https://github.com/user-attachments/assets/66fb8eaf-bf36-4027-9d2a-aa06bd76983a)

![pageAction](https://github.com/user-attachments/assets/98c5238c-3acb-4305-ac38-e42e2786c38c)

![New tab menu](https://github.com/user-attachments/assets/ea34217f-263f-4fda-b511-f38476325b02)

![Context menu for links](https://github.com/user-attachments/assets/0a5d31d9-3b24-4905-b1e3-360d2109e25a)

### Expected behavior

The same custom order should be respected everywhere.

### Additional informations

This is the code to fetch the list of containers for the pageAction (i.e. from the icon at the location bar):

https://github.com/mozilla/multi-account-containers/blob/1537e9f6f2e66e772efed4f89305039c17eca829/src/js/pageAction.js#L3

Meanwhile, this seems to be the code for the list of containers in the main extension popup. It explicitly calls `.sort()`:

https://github.com/mozilla/multi-account-containers/blob/1537e9f6f2e66e772efed4f89305039c17eca829/src/js/popup.js#L234-L247

I don't know where is the rest of the code. I'd say this sorting logic should be moved inside `browser.contextualIdentities.query({})`, if possible. Otherwise, we should have some kind of helper function that queries the containers and returns them already sorted, and then rewrite all the code to use this wrapper instead of querying directly.

https://github.com/search?q=repo%3Amozilla%2Fmulti-account-containers+contextualIdentities.query&type=code

**Comment by dannycolin** [comment] 2024-07-16 15:04
Duplicate of #1958

**Closed by dannycolin** 2024-07-16 15:04 UTC
Labels: bug
