### ISSUE TITLE
Sort container list manually

### ISSUE THREAD

**Issue by Bergapalis** [mozilla/multi-account-containers#895] opened 2017-10-06 16:15 UTC
I would like to be able to sort the container list manually. Now when you add a container, it goes to the bottom of the list. Some containers like "bank" I use rarely, and it should go lower. I don't see that option in the edit menu.

**Comment by jonathanKingston** [comment] 2017-10-06 17:36
This is a duplicate of #330, please follow along there.
Thanks

**Closed by jonathanKingston** 2017-10-06 17:36 UTC
Labels: duplicate, enhancement
