### ISSUE TITLE
Multi-accounts works in private window blocking assigned sites

### ISSUE THREAD

**Issue by igorkurpis** [mozilla/multi-account-containers#1669] opened 2020-03-01 12:26 UTC
Multi-Account Containers Version: 6.2.1
Operating System + Version: Debian Buster 10.3
Firefox Version: 68.4.1 ESR

If site is assigned into container, then in private window multi-account-container block that site from opening.

Image that shows addon is working in private windows.
![Zrzut ekranu z 2020-03-01 13-05-16](https://user-images.githubusercontent.com/25401713/75625638-58ce8780-5bc0-11ea-9038-a19b51cd2302.png)

Multi-account-containers try to open pages in assigend containers in private windows, but containers are not available, so site don't open at all.

**Comment by jeremy21212121** [comment] 2020-06-22 02:08
I'm also experiencing this issue. Any site that is set to automatically open in a particular container is inaccessible in a Private Browsing window.

For example, I have a github container and github.com is set to always open in that container. If I try to follow a  github link in Private Browsing mode, nothing happens. If I try to open it in a new tab, the tab briefly appears then disappears.

What I suspect is happening is firefox is trying to open the site in a container, but containers are not available in Private Browsing mode, so the site does not open at all.

Perhaps a fix for this could involve checking for Private Browsing mode before checking if a site should be opened in a container.

Firefox: 68.9.0esr
Multi-Account Containers: 6.2.5
OS: Debian 10 Buster

**Comment by jeremy21212121** [comment] 2020-06-22 02:37
After some more investigation, I've found this is actually caused by this extension running in Private Browsing mode. It is not supposed to, yet when I open a Private Browsing window, the Multi-Account Containers icon is present.

This issue is also referenced in #1634 by [this comment](https://github.com/mozilla/multi-account-containers/issues/1634#issuecomment-586218609). The problem can be fixed by [refreshing your profile](https://support.mozilla.org/en-US/kb/refresh-firefox-reset-add-ons-and-settings).

**Comment by dannycolin** [comment] 2022-05-21 00:37
As mentioned, Multi-Account Containers doesn't work in Private Mode. Since this issue was filed for a very old version of both the addon and Firefox browser, I'm closing it. If you still experience this issue, please file a new bug.

**Closed by dannycolin** 2022-05-21 00:37 UTC
