### ISSUE TITLE
Tab search doesn't search across containers

### ISSUE THREAD

**Issue by nrktkt** [mozilla/multi-account-containers#2142] opened 2021-09-30 03:14 UTC
- Multi-Account Containers Version: 7.4.0
- Operating System + Version: Windows 10
- Firefox Version: 92.0.1

### Actual behavior
clicking "open new tab" and then typing the title of a page open in a different container results in no tabs showing up under "firefox suggest" in the autocomplete dropdown

### Expected behavior
pages from all containers would show up with a "switch to tab" option

### Steps to reproduce
1. open a page in a container
2. open a new tab in a different container
3. enter the title of the page in the search bar, see no "switch to tab" option
4. open a new tab in the first container
5. repeat 3, see that the "switch to tab" option is now available

### Notes

the same behavior can be seen in the "search tabs" function

**Comment by dannycolin** [comment] 2022-07-12 18:23
duplicate of #1705

**Closed** 2022-07-12 18:23 UTC
