### ISSUE TITLE
How to bookmark a page to always open in a set container?

### ISSUE THREAD

**Issue by UserNaem** [mozilla/multi-account-containers#854] opened 2017-09-24 01:58 UTC
Last time I checked, it was possible to bookmark a URL with the name of a container, making Firefox open that page in the specified container from this bookmark. I can't find anything referencing this functionality in any manuals, however. Was is removed? Or maybe I wasn't looking hard enough?

(Having to hold the new tab button for a whole second to get the containers menu feels terribly slow, by the way.)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/MAC-602)

**Comment by klint** [comment] 2017-09-24 13:49
You still get this feature by opening the page in its container and then clicking on the Containers icon  (last time I checked anyway ☺️)

**Comment by UserNaem** [comment] 2017-09-24 15:46
Doesn't seem to be working, either.

**Comment by tmottabr** [comment] 2017-09-25 03:05
You need to open the page in a specific container you want to bind and them click in the plugin icon and check the option "always open in container".

But this only work to bind and address to one single container, so everytime you open that address it will go to a tab from that specific container. If you want to use the same page on multiple containers with distinct accounts them you need to open a container tab and them open the bookmark for each container.

I would like to be able to have bookmark set to a specific container without binding the address to a container so i can have multiple bookmarks for the same address each opening in a distinct container.

**Comment by groovecoder** [comment] 2017-09-25 16:25
As @tmottabr said - there's a feature to always open a site in a container. This seems like a duplicate of https://github.com/mozilla/multi-account-containers/issues/323 ... please re-open if not.

**Comment by MurzNN** [comment] 2018-12-05 07:58
This is not a duplicate, containers are often needed for use two logins on one site. For example, I use 3 gmail accounts and we to have separate bookmarks for each of them, that will open bookmark in needed container.

**Comment by klint** [comment] 2018-12-05 09:20
I agree, this is not a duplicate of #323, as this one is about storing a container information at bookmark level to always open this bookmark in this context **by default** - without further action of the user when he opens the bookmark.
Whereas #323 is about giving the user a way to user to choose the context at the time when he opens the bookmark.

**Comment by internetionals** [comment] 2018-12-05 10:23
At work I have to be logged in with multiple identities in the same cloud platform. This means that simply assigning that site to a specific container doesn't work. And we also encounter a similar problem when using specific role accounts (separate users for normal and admin work) with web applications.

Allowing a bookmark to open the site in a specific container would allow me to create separate bookmarks for the different accounts.

**Comment by jugaltheshah** [comment] 2019-01-09 15:50
Wanted to chime in and reiterate what other folks have said. It would be super helpful to designate a container at the _bookmark_ level, so as to always open a _bookmark_ in an arbitrary container. This enables myriad use cases, like being able to create bookmarks to the same service (e.g. Gmail) for different uses, like Personal & Work.

Being able to assign a URL to always open in a container is **not** the same, and is actually counter-productive, as if you assign Gmail to Work, for example, the process to open Gmail in a Personal container is then circuitous.

**Comment by frankehlers** [comment] 2019-01-28 13:58
The same applies for me. I use multiple accounts for Microsoft tools (home, work, university) that need to be clearly separated. It would be really great if I could assign a container to a bookmark and that bookmark opens the page in the appropriate container.
It is important that the container is not assigned to a URL, but to the individual bookmark. It should be possible to have e.g. 3 bookmarks with the identical url.

**Comment by dafeder** [comment] 2019-02-04 14:31
Agreed - this would be a great feature, and is not a dupelicate

**Comment by mewwts** [comment] 2019-04-09 07:14
+1, not a duplicate.

**Comment by nba2** [comment] 2019-04-18 19:06
+1, would be a very helpful feature.

**Comment by mvdan** [comment] 2019-06-17 07:01
https://github.com/mozilla/multi-account-containers/issues/1050 is similar, but not the same issue.

@groovecoder any chance this issue can get a second look? Are you open to contributions?

**Comment by mewwts** [comment] 2019-06-17 07:33
Can we reopen or create a new issue for this?

**Comment by lhorace** [comment] 2019-06-17 08:53
> Or might be even more useful if user could associate a particular bookmark with a particular Container so that it automatically opens in the right Container. So when I left-click "Facebook" bookmark it opens in "Facebook" container, when I left-click my Online banking website it automatically launches into "Finances" container.

Source https://github.com/mozilla/multi-account-containers/issues/323#issue-211632110

>Last time I checked, it was possible to bookmark a URL with the name of a container, making Firefox open that page in the specified container from this bookmark. 

> It would be really great if I could assign a container to a bookmark and that bookmark opens the page in the appropriate container.



I'm a bit confused, isn't what #323 is trying to imply here?

**Comment by mewwts** [comment] 2019-06-17 14:49
To me #323 is about right-clicking on a bookmark and opening it in a specific container. The way I understand this issue is being able to create, say, 3 bookmarks that each open a specific link, e.g. gmail, in different containers.

**Comment by mvdan** [comment] 2019-06-20 07:00
It seems like comments here are being sent to the void, so I've opened https://github.com/mozilla/multi-account-containers/issues/1443 in case any active developers aren't aware of the situation.

**Comment by lhorace** [comment] 2019-06-22 03:02
> 3 bookmarks that each open a specific link, e.g. gmail, in different containers.

From my point of view, how is this different from the latter? I believe both issues are the same albeit slightly different in workflow. That as if I am following you response correctly.

> a particular Container so that it automatically opens in the right Container. So when I left-click "Facebook" bookmark it opens in "Facebook" container

> The way I understand this issue is being able to create, say, 3 bookmarks that each open a specific link, e.g. gmail, in different containers.

From my view, that's exactly what the other issue is trying to solve. _Isn't_ it to associate a container with a bookmark? If not, please clarify.

The intent here is to consolidate issues.

**Comment by lhorace** [comment] 2019-06-22 03:10
@mvdan 

It's not that it's going to a void, there is no one available to work on it. The one's who were active recently have went AWOL. Perhaps opening a issue to open existing issue my not be the way to go. And from what I understand @UserNaem should be able to reopen, however re-opening the issue doesn't necessarily mean any work will get done on it. Bear in mind, that issue has more votes, and more likely to see attention.

**Comment by mvdan** [comment] 2019-06-22 08:31
> The intent here is to consolidate issues.

We can agree there. But as others said, #323 is mainly about manually opening a bookmark in a specific container. It does mention that it would be nice to set a default too, but it's entirely possible that the issue will be closed/fixed without implementing both features.

Also, what I meant by "the void" is that it's easy for closed issues to go unnoticed. I also don't expect every open issue to be implemented. I'm simply suggesting that it would be good to keep this issue open, just to ensure this feature request doesn't fall through the cracks.

Ultimately, whether to have two open issues or one is up to upstream. I didn't open #1443 to tell them what to do; I opened it so that they can make a decision and act on it.

**Comment by MichaelTunnell** [comment] 2020-02-14 05:43
FINALLY! We can now start to advocate for this feature again after waiting for 3 years for it to be acknowledged that it is indeed a separate issue.

**Comment by E1k3** [comment] 2020-02-14 12:01
If this issue is going to be worked on, I suggest not making the solution exclusive to bookmarks. A container specific URL prefix similar to the search keywords (see about:preferences#search) could be used in bookmarks as well as manual input in the address bar.

An example of the behavior I suggest would be a container named `Banking` with the container keyword `cbank`. The URL `mybank.com` could then be opened in that contained by typing `cbank mybank.com` in the address bar and opening URLs like these from a bookmark would do the same thing.

**Comment by bgshacklett** [comment] 2020-02-14 16:09
One use case to keep in mind is having multiple bookmarks which open in separate containers, which a container-linked URL prefix would not solve for.

**Comment by E1k3** [comment] 2020-02-14 17:12
> One use case to keep in mind is having multiple bookmarks which open in separate containers, which a container-linked URL prefix would not solve for.

Would you mind elaborating on that?
Given two containers, one with the keyword `cone`, the other with the keyword `ctwo`, I would be able to save two bookmarks `cone example.com` and `ctwo example.com`, which open the same site in seperate containers.

**Comment by bgshacklett** [comment] 2020-02-14 17:16
My apologies; I misread.

**Comment by atimholt** [comment] 2020-04-28 02:36
I consider containers to be fundamentally broken without this. This functionality is the only way I would ever even begin to consider using containers. This is like being gifted a new car without tires, doors, seats, steering-wheel, or engine.

**Comment by MichaelTunnell** [comment] 2020-04-28 18:31
> I consider containers to be fundamentally broken without this. This functionality is the only way I would ever even begin to consider using containers. This is like being gifted a brand new car without tires, doors, seats, steering-wheel, or engine.

As i mentioned previously, you can do this already with a 3rd Party extension. This thread is about implementing it natively which would be better however saying that its fundamentally broken without it is a bit of an exaggeration in my opinion. Luckily for you in this case, there is [a solution](https://addons.mozilla.org/en-US/firefox/addon/open-url-in-container/) to fix the thing you find broken so enjoy. :D

**Comment by RobOo-Github** [comment] 2020-05-16 09:49
Hi, I agree a native solution would be preferable, but doesn't  https://addons.mozilla.org/en-US/firefox/addon/container-bookmarks/ do what you are after?

**Comment by Roy-Orbison** [comment] 2020-05-18 02:47
@RobOo-Github Reading the _About_ section of that addon makes it seem like a fragile stop-gap measure. It appears not to support containers with spaces in their name, and break bookmarks that have a fragment (because that's where the addon stores the desired container).

[The add-on](https://addons.mozilla.org/en-US/firefox/addon/open-url-in-container/) that @MichaelTunnell recommended is probably a better solution.

**Comment by piecevcake** [comment] 2020-07-13 04:10
> Hi, I agree a native solution would be preferable, but doesn't https://addons.mozilla.org/en-US/firefox/addon/container-bookmarks/ do what you are after?

No it's an unworkable shambles last time I looked. Set up a rule which opened all my bookmarks for a url in 1 container.  Which container tabs does already. which I did NOT want.

**Comment by piecevcake** [comment] 2020-07-13 04:14
3 years... still broken. This functionality is the only way I would ever even begin to consider using containers. This is like being gifted a brand new car without tires, doors, seats, steering-wheel, or engine.

**Comment by Roy-Orbison** [comment] 2020-07-13 05:04
@piecevcake
> still broken

Know the difference between bug and feature. You believe (as do I) that this functionality should be built in, but it's not. Therefore the feature needs to be added, because it's not 'present but broken' which would constitute a bug.

Try https://addons.mozilla.org/en-US/firefox/addon/open-url-in-container/ as suggested, which does **exactly** what you're after, I use it frequently. I even wrote a simple bookmarklet to create new contained bookmarks:

```
javascript:(function(c,u)%7Bc&&(c=c.replace(/%5E%5Cs+%7C%5Cs+$/g,''))&&(u=prompt('URL?'))&&(u=u.replace(/%5E%5Cs+%7C%5Cs+$/g,''))&&prompt('Contained%20URL:','ext+container:name='+encodeURIComponent(c)+'&url='+encodeURIComponent(u))%7D)(prompt('Container%20name?','Personal'))
```

Add that code as the URL of a new bookmark. Running it will provide three prompts: the container name (which defaults to `Personal` but you can change that in the bookmarklet), the URL you wish to bookmark, and the result. You copy the results and create bookmarks from them. It's not ideal, but it's not "broken".

**Comment by piecevcake** [comment] 2020-08-01 03:15
> 
> 
> @atimholt
> 
> > I consider containers to be fundamentally broken without this. This functionality is the only way I would ever even begin to consider using containers. This is like being gifted a brand new car without tires, doors, seats, steering-wheel, or engine.
> 
> As i mentioned previously, you can do this already with a 3rd Party extension. This thread is about implementing it natively which would be better however saying that its fundamentally broken without it is a bit of an exaggeration in my opinion. Luckily for you in this case, there is [a solution](https://addons.mozilla.org/en-US/firefox/addon/open-url-in-container/) to fix the thing you find broken so enjoy. :D



> 
> 
> @piecevcake
> 
> > still broken
> 
> Know the difference between bug and feature. You believe (as do I) that this functionality should be built in, but it's not. Therefore the feature needs to be added, because it's not 'present but broken' which would constitute a bug.
> 
> Try https://addons.mozilla.org/en-US/firefox/addon/open-url-in-container/ as suggested, which does **exactly** what you're after, I use it frequently. I even wrote a simple bookmarklet to create new contained bookmarks:
> 
> ```
> javascript:(function(c,u)%7Bc&&(c=c.replace(/%5E%5Cs+%7C%5Cs+$/g,''))&&(u=prompt('URL?'))&&(u=u.replace(/%5E%5Cs+%7C%5Cs+$/g,''))&&prompt('Contained%20URL:','ext+container:name='+encodeURIComponent(c)+'&url='+encodeURIComponent(u))%7D)(prompt('Container%20name?','Personal'))
> ```
> 
> Add that code as the URL of a new bookmark. Running it will provide three prompts: the container name (which defaults to `Personal` but you can change that in the bookmarklet), the URL you wish to bookmark, and the result. You copy the results and create bookmarks from them. It's not ideal, but it's not "broken".

@Roy-Orbison 
1. what do you call a brand new car which the manufacturer forgot to put an engine in?  I would call it broken.
2. I tried the bookmarklet, thank you, but could not find any bookmark created by it. So perhaps you can clarify whether if I assign Bookmark1 of URLx to "Personal" container, then Bookmark2 of the same URL to "Work" container, when I click on each, it will open that URL in the specified container?
3. Like everyone else has been saying, I do not want to open _URLs_ in a container.  Have you missed the entire discussion above? Or does your add-on actually open different bookmarks of the same URL in different containers, as has been requested?

**Comment by Roy-Orbison** [comment] 2020-08-02 13:10
@atimholt & @piecevcake

I believe the term is "choosing beggar". No one is giving you a car, and you haven't bought one. No one is saying correlating a specific bookmark with a container is bad, indeed, that's why this issue is still open, because it would be good. I, too would like this to be native, but understand that someone has to put time and effort into doing this, and that someone is probably not you.

@piecevcake the bookmarklet (not an add-on) does not create *bookmarks*, it container-ises a URL, and you can save that container-ised URL to a bookmark, yourself, or a desktop shortcut, or anywhere else you put usable URLs. The resulting URLs only open in the named container, e.g. of you created two separate bookmarks from these container-ised URLs:
```text
ext+container:name=Foo&url=https://mozilla.org
ext+container:name=Bar&url=https://mozilla.org
```
then each bookmark will always open the same original URL but do so in different containers, the exact behaviour requested in this issue. You can create bookmarks manually by right-clicking a folder (I just use "Other bookmarks") and selecting "New". It requires a bit of extra effort, but it works.

> Have you missed the entire discussion above?
No, it is you who has not read others words thoroughly, nor apparently bothered to read any of the add-on description/documentation.

**Comment by extremegf** [comment] 2020-10-16 12:40
@Roy-Orbison This is genuinely a good solution. Let me summarize the steps needed for this to work:

1. Install [this extension](https://addons.mozilla.org/en-US/firefox/addon/open-url-in-container/) it **requires no permissions**.
2. Open bookmark manager Library -> Bookmarks > All Bookmarks
3. Create a bookmarklet by clicking Organize -> New Bookmark,
Name: Containerize a Bookmark
Location: `javascript:(function(c,u){c&&(c=c.trim())&&(u=prompt('URL?',location))&&(u=u.trim())&&prompt('Contained URL to copy and bookmark:','ext+container:name='+encodeURIComponent(c)+'&url='+encodeURIComponent(u))})(prompt('Container name?','Personal'))`
4. Put it somewhere accessible - for example at the top of the list in Ctrl+B Bookmarks Bar - you can't launch a bookmarklet by searching for it in the address bar.
5. Go to the site you want to run in a specific container.
6. Click the "Containerize a Bookmark", pick the container name and copy the link.
7. Create or edit some existing bookmark to set it to this link.

Now when you call the bookmark it will open in the specified container. It seems like a log of work but in my case I have maybe 4-5 often used bookmarks which i really want to be auto-containerized. The frustration this saves me is worth it.

**Comment by grahamperrin** [comment] 2020-12-27 00:25
### [Container Bookmarks](https://addons.mozilla.org/addon/container-bookmarks/)

https://github.com/mozilla/multi-account-containers/issues/854#issuecomment-629916434

> appears not to support containers with spaces

Works for me. Supports _doo dad_. 

> break bookmarks that have a fragment 

Works for me. My doo dad container bookmark for https://github.com/mozilla/multi-account-containers/issues/854#issuecomment-629916434 is not broken. 

https://github.com/mozilla/multi-account-containers/issues/854#issuecomment-657348112

> Set up a rule which opened all my bookmarks, linls and external links for a url in 1 container. 

No such problem here.

**Comment by lcorsini** [comment] 2021-02-03 13:00
the bookmarklet above is the simplest solution, but this basic function should be really merged into the containers extension
It is immensely useful to work with containers (especially if you have multiple identities) and using the domain only to assign a site to a container has many limits (for example, I work on gcp console with multiple identities, still the url is always console.cloud.google.com)

**Comment by extremegf** [comment] 2021-02-04 11:53
This requires extensive permissions...

> ### [Container Bookmarks](https://addons.mozilla.org/addon/container-bookmarks/)

> This add-on needs to:
> 
> Read and modify bookmarks
> **Access your data for all websites**

**Comment by E1k3** [comment] 2021-02-04 11:55
> This requires extensive permissions...

That is exactly why this should be implemented / maintained by a trusted source, i.e. Mozilla.

**Comment by E1k3** [comment] 2021-02-04 12:05
>     1. Install [this extension](https://addons.mozilla.org/en-US/firefox/addon/open-url-in-container/) it **requires no permissions**.

While the execution is a little clunky, in principle it is pretty much exactly what I proposed in #1302. If this was natively implemented, it would fix most of the issues I've seen regarding URL and bookmark tagging.

**Comment by grahamperrin** [comment] 2021-02-04 18:12
> https://github.com/mozilla/multi-account-containers/issues/854#issuecomment-773251638

> … extensive permissions …

https://github.com/rafaelgomesxyz/container-bookmarks/issues/11

**Comment by Roy-Orbison** [comment] 2021-02-05 01:03
As a stop-gap measure, could an *Open in Container Tab* submenu be added to the context menu of bookmarks? Between the *Open in a New Tab* and *Open in a New Window* items would be congruent with the main menu's *File > New Container Tab*.

**Comment by E1k3** [comment] 2021-02-05 02:03
As far as I know, you can already enable this in the container-addon preferences.

**Comment by Roy-Orbison** [comment] 2021-02-05 02:12
Thanks @E1k3, I had looked in `about:preferences#containers` but not `about:addons` > *Firefox Multi-Account Containers* > *Preferences*

**Comment by grahamperrin** [comment] 2021-02-05 07:42
https://github.com/mozilla/multi-account-containers/issues/854#issuecomment-773729610

> As far as I know, you can already enable this in the container-addon preferences.

There is no bookmark-related preference.

**Comment by Roy-Orbison** [comment] 2021-02-05 09:31
Yes, @grahamperrin, it does not resolve this issue. It just makes life a little easier for average users to open a bookmark in a specific container.

It's so unintrusive, I don't know why the add-on doesn't enable it by default.

**Comment by extremegf** [comment] 2021-02-05 09:53
> > [#854 (comment)](https://github.com/mozilla/multi-account-containers/issues/854#issuecomment-773251638)
> 
> > … extensive permissions …
> 
> [rafaelgomesxyz/container-bookmarks#11](https://github.com/rafaelgomesxyz/container-bookmarks/issues/11)

I see that this commit clarifies the use of permissions. But that's not the issue - I trust the developer doesn't do anything wrong with the data. The real issue is that if an extension is hacked and attacker pushes a malicious update, then he'll be able to leverage the permission I've granted when I installed the extension. Therefore, I as a security concous user, try to minimize any privlages granted to any extension. I very often forgo installing extensions on my main profile for this reason.

**Comment by oscar230** [comment] 2021-12-29 11:44
> You still get this feature by opening the page in its container and then clicking on the Containers button (last time I checked anyway ☺️)

I don't think that is what he was looking for.

> You need to open the page in a specific container you want to bind and them click in the plugin icon and check the option "always open in container".
> 
> But this only work to bind and address to one single container, so everytime you open that address it will go to a tab from that specific container. If you want to use the same page on multiple containers with distinct accounts them you need to open a container tab and them open the bookmark for each container.
> 
> I would like to be able to have bookmark set to a specific container without binding the address to a container so i can have multiple bookmarks for the same address each opening in a distinct container.

You described it perfectly, that is what I am looking for as well.

Anyone know if this feature is considered? :)

**Comment by extremegf** [comment] 2021-12-29 12:10
@oscar230 I you this semi-manual method. It works 100% and is completely secure.

https://github.com/mozilla/multi-account-containers/issues/854#issuecomment-710020845

**Comment by josharrington** [comment] 2022-02-10 16:35
I'm attempting to use the solution in https://github.com/mozilla/multi-account-containers/issues/854#issuecomment-710020845 and I'm not having any success. It provides me with a link like below:

```
ext+container:name=TestContainer&url=https%3A%2F%2Fwww.google.com%2F
```

However, clicking a bookmark with this set as the url results in a page saying 

```
The address wasn’t understood

Firefox doesn’t know how to open this address, because one of the following protocols (ext container) isn’t associated with any program or is not allowed in this context.
```

I definitely have the extension installed and am able to use it manually. This specific container also exists. Is this a new regression or has someone encountered this before?

**Comment by extremegf** [comment] 2022-02-10 21:48
Just verified

FF 97.0
Open external links in a container: 1.0.3
Firefox Multi-Account Containers: 8.0.5

Bookmarked your link, clicked it from the bookmarksidebar and it opened in TestContainer. Is your setup different in any way?

**Comment by josharrington** [comment] 2022-02-10 21:52
Ah, ignore me. I somehow completely missed installing the extension. Thank you for checking and sorry for the bother!

**Comment by extremegf** [comment] 2022-02-10 21:54
Glad to help :)

**Comment by Karljord** [comment] 2022-04-21 06:21
+ 1

**Comment by dannycolin** [comment] 2022-06-14 13:05
#323 asked for two things and this issue is clearly a duplicate of the second thing asking to "associate a particular bookmark with a particular Container so that it automatically opens in the right Container".

This definitely covers the use case of having multiple bookmarks with the same URL that each open in a different containers. I'm now closing this issue as a duplicate and will update #323 accordingly.

**Closed by dannycolin** 2022-06-14 13:05 UTC
Labels: Feature request

**Comment by MichaelTunnell** [comment] 2022-06-14 17:57
Are you kidding me? How on earth is my comment off-topic?

**Comment by vHanda** [comment] 2022-06-14 18:01
@dannycolin : I can understand not wanting to address the issue. In that case, please just close this bug as a "WONT FIX", but closing it as completed and then marking genuine complaints as offtopic is quite disingenuous.

I'm sure you're better than this. I believe in you.

**Comment by dannycolin** [comment] 2022-06-14 18:31
I'm following the same etiquette as on Bugzilla where offtopic/me too/advocate tags are synonymous. See https://wiki.mozilla.org/BMO/comment_tagging

GitHub isn't as granular so I will unhide the comment to avoid confusion.

**Comment by Roy-Orbison** [comment] 2022-06-15 02:32
@dannycolin Did you also hide the comments that contain the instructions for the only currently viable workaround? If so, why? I can see comments discussing the workaround remain, but not the ones that are actually useful to people who come across this issue: https://github.com/mozilla/multi-account-containers/issues/854#issuecomment-657360111 https://github.com/mozilla/multi-account-containers/issues/854#issuecomment-710020845

**Comment by dannycolin** [comment] 2022-06-15 11:58
@Roy-Orbison It is now on the [wiki](https://github.com/mozilla/multi-account-containers/wiki).

**Comment by MichaelTunnell** [comment] 2023-01-02 19:17
For anyone interested in this feature . . . it has now been migrated to a new Mozilla Connect platform with the url of https://connect.mozilla.org/t5/ideas/container-preference-in-bookmarks/idi-p/3857 

We are apparently losing all of the comments and effort for support of this idea by moving this to a new platform for some reason so please go comment there to continue to show the userbase interest is still high.

The previous frustrating thread has been locked so no one can comment about the migration, I just wanted to take this opportunity of this thread still being open to comment on a statement in the migration message which says the reason for migration is "so it gets more visibility" . . . I would like to point out that this thread would have had plenty of visibility without the excessively nonsensical closing of this thread repeatedly for 6 years.

Yes, I do expect my comment to be hidden, deleted or whatever and this thread be locked as a result of my comment but honestly this is so frustrating that you and the other moderators dont seem to understand what the word duplicate means and now we are FINALLY getting the fact it is NOT a duplicate recognized but it took moving to a totally new platform 6 years later to do it.

**Comment by dannycolin** [comment] 2023-01-02 19:37
@MichaelTunnell I do appreciate that you are like me and a lot of others very passionate about this project and Firefox in general. 

However, I'd like you to take the time to [read our Community Participation Guideline](https://www.mozilla.org/en-US/about/governance/policies/participation/) because your multiple comments are definitely trying to build hostility against the folks working on this project instead of being a constructive criticism. Unfortunately, I will have to lock this thread because of this and I will have prefer not to have to.

To clarify @MichaelTunnell mentioning that:

> We are apparently losing all of the comments and effort for support of this idea by moving this to a new platform for some reason so please go comment there to continue to show the userbase interest is still high.

This is absolutely false because if the Mozilla team decides to review this feature they will definitely look at #323 and its duplicates to get as much data points as possible to implement it the right way.
