### ISSUE TITLE
Sub-Options of 'Firefox Multi-Account Containers' option on right clicking any of the containers is not working

### ISSUE THREAD

**Issue by ShivangiKakkar** [mozilla/multi-account-containers#1266] opened 2018-09-21 12:06 UTC
### Prerequisites:
- Is "Firefox will: Never remember history" in the Firefox Preferences/Options under "Privacy & Security > History" selected? No
- Are you using Firefox in a Private Window? No
- Can you see a grayed out but ticked Checkbox with the description "Enable Container Tabs" in the Firefox Preferences/Options under "Tabs"? Yes
- Multi-Account Containers Version: 6.0.0
- Operating System + Version: Mac OS (10.13.6)
- Firefox Version: 62.0
- Other installed Add-ons + Version + Enabled/Disabled-Status: No

### Steps to reproduce
1. Go to Firebox than click on `Multi-Account Containers` extension. You will see the list of containers there.
2. Right-click any of the containers, a menu will be opened.
3. Go to `Firefox Multi-Account Containers` option, Hover on it; It will further open a sub-menu. 
4. Click on any of the sub-options of the sub-menu. It doesn't respond. No action happens even after clicking. 

### Actual behaviour:
- Does not perform any action when clicked on any of the sub-options.

![webp net-gifmaker](https://user-images.githubusercontent.com/35342019/45880210-d3d52100-bdc4-11e8-9f51-0070b51a15e2.gif)

### Expected behavior:
- Should perform the actions listed in the sub-menu while being clicked on.

### NOTE:
- Right click isn't enabled for `New Tab`.

**Comment by ShivangiKakkar** [comment] 2018-09-21 12:19
@groovecoder @bakulf I am trying to find the problem reason for this issue. Can you please direct me to the files I need to check regarding this issue? Thanks :)

**Comment by jonathanKingston** [comment] 2018-09-27 23:35
@ShivangiKakkar I think the issue will be with the 'https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/menus/ContextType' we enable the [contextmenu](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/menus/create).
The code should be doing something like `browser.contextMenu.create({contexts: ["..."]})` (I think we use contextMenu which is an alias for menus). Whatever we are using it likely can be narrowed to not include this context.

**Comment by ShivangiKakkar** [comment] 2018-09-27 23:41
@jonathanKingston Okay, will look into it and land a PR soon. Thanks! 😄

**Comment by ShivangiKakkar** [comment] 2018-10-03 15:44
@jonathanKingston 
> Whatever we are using it likely can be narrowed to not include this context.

By this do you mean, we don't need this sub-menu here? If yes, currently the contexts is set to type  "all" . Something like this for hiding the container menu -
```
browser.contextMenus.create({
      id: this.MENU_HIDE_ID,
      title: "Hide This Container",
      contexts: ["all"],
    }); 
```
Can you give an idea how do I not select/remove a particular context(like the one we have now) and include all other contexts?

**Comment by jonathanKingston** [comment] 2018-10-15 10:06
> By this do you mean, we don't need this sub-menu here?

Yeah that is correct. I think anything in the "Firefox Multi-account Containers" menu can go.

You can use an array instead of the `"all"` and pass each context we want to keep. It probably makes more sense to drop anything that doesn't make sense to "Hide this container" like password.

**Comment by kendallcorner** [comment] 2019-12-06 21:16
Hi. This looks like a duplicate of #887. Please vote (:+1:) or discuss on that issue to show your interest. I'll close this, but feel free to request a reopen if you think it's a different issue.

**Closed by kendallcorner** 2019-12-06 21:16 UTC
