### ISSUE TITLE
Disabling addon erases containers

### ISSUE THREAD

**Issue by djmitche** [mozilla/multi-account-containers#1733] opened 2020-05-06 17:00 UTC
- Multi-Account Containers Version: 6.2.5
- Operating System + Version: Fedora 31
- Firefox Version: 75
- Other installed Add-ons + Version + Enabled/Disabled-Status:

### Actual behavior

After disabling and re-enabling containers, I'm back to the default set of containers.

### Expected behavior

Disabling and re-enabling should retain my existing settings.

### Steps to reproduce
1. Disable multi-account containers
2. (guessing: wait long enough for a sync to occur?)
3. Re-enable multi-account containers
4. See personal / work / banking / shopping, all "always open in this container" is gone

### Notes

I disabled the addon to test some non-webcompat website, and forgot I had disabled it.  So it was off for a few days..

**Comment by Hard-Wired** [comment] 2020-09-30 05:21
Same problem. Nothing comes back from synced storage after turning off the extension and then turning it back on after a few minutes. Everything is reset to default. Getting really frustrated having to recreate everything when I need to temporarily turn it off.

**Comment by julikaiba** [comment] 2020-10-24 16:46
same here; when resyncing the ff account the containers are back but without assigned pages

**Comment by Pegart** [comment] 2020-10-25 16:30
Same here. Installed Firefox on another computer, enabled Firefox Sync, it installed all my addons on the new computer. I disabled some, including multi-account containers which disabled it on my old computer. After enabling it back on my old computer ALL the custom created containers were gone. Very annoying.

**Comment by dveditz** [comment] 2020-11-10 00:51
Is this the same as issue #1236?

**Comment by Pegart** [comment] 2020-11-10 09:35
It's probably related/the same because of the steps to reproduce:

> Steps to reproduce:
> 1. Add a new container
> 2. Disable the add-on
> 3. Enable the add-on
> 
> The new container has disappeared.

It seems like disabling and re-enabling the add-on deletes every custom/manually created container and websites connected to these containers.

**Comment by dannycolin** [comment] 2022-05-24 23:39
It's indeed a duplicate of #1236

**Closed by dannycolin** 2022-05-24 23:39 UTC
