### ISSUE TITLE
Can no longer use MAC for Gmail.

### ISSUE THREAD

**Issue by doobersn** [mozilla/multi-account-containers#1969] opened 2021-02-20 04:58 UTC
I installed MAC on FF on Windows 10 a few days ago and gmail worked perfectly fine with mail.google.com as the site in MAC. I bought a new laptop and when i try to do the same thing I get a 400 error from gmail about a malformed request. Any ideas what is going on? Thanks!

**Comment by blackjackshellac** [comment] 2021-02-20 13:58
Have you tried clearing your cookies for google?  Preferences/Security/Cookies & Site Data/Manage Data

**Comment by doobersn** [comment] 2021-02-21 05:15
> 
> 
> Have you tried clearing your cookies for google? Preferences/Security/Cookies & Site Data/Manage Data

Hi, yes, I have cleared all cookies, then made sure none were being blocked (also tried to block them just in case in another attempt) and nothing. Same 400 error. Thanks a lot for your help!

**Comment by dannycolin** [comment] 2022-12-02 00:02
Duplicate of #1882

**Closed by dannycolin** 2022-12-02 00:02 UTC
