### ISSUE TITLE
TypeError: aEvent.currentTarget.firstChild is null browser.js:299:5

### ISSUE THREAD

**Issue by kjozwiak** [mozilla/multi-account-containers#407] opened 2017-03-29 22:36 UTC
Whenever creating a new tab via the "+" button while the Containers experiment is installed, you'll get the following error under the browser console:

```
TypeError: aEvent.currentTarget.firstChild is null browser.js:299:5
	_mousedownHandler chrome://browser/content/browser.js:299:5
	handleEvent chrome://browser/content/browser.js:356:9
```

STR:

* install the latest fx `[fx52.0.2, buildid: 20170323105023, chageset: e81854d6ce91]`
* install the test pilot via https://testpilot.firefox.com/
* install the latest container experiment `[Extensions: Containers Experiment	2.0.0 @testpilot-containers]`
* open the browser console and open a new tab via the "+" button

**Comment by jonathanKingston** [comment] 2017-04-04 13:49
This is in the browser itself... I'm not sure if we can fix due to us removing that item in the menu.

Can look into (I had noticed myself), however it's not actually causing an issue from what I can see.

**Comment by kjozwiak** [comment] 2017-04-04 17:06
> Can look into (I had noticed myself), however it's not actually causing an issue from what I can see.

Agreed, I didn't notice any issues/side affects because of this error appearing in the browser console, but figured it might be an easy fix. If it's an issue within the browser itself, we can just move this into stretch.

**Comment by jonathanKingston** [comment] 2017-04-05 11:00
Yeah it looks like it happens because we remove the element, we could probably clean up the event handlers but it might be that XBL is adding them back in too.

**Comment by kendallcorner** [comment] 2019-12-03 20:48
Hi. We're currently triaging the Multi Account Container issues. This appears to have been fixed, so I'm going to close it. If you don't feel the underlying issue has been resolved, feel free to reopen it with updated steps to reproduce.

**Closed by kendallcorner** 2019-12-03 20:48 UTC
Labels: bug
