### ISSUE TITLE
In Proton UI tabs are not highlighted by a color of container

### ISSUE THREAD

**Issue by achernyakevich-sc** [mozilla/multi-account-containers#2102] opened 2021-08-13 15:16 UTC
- Multi-Account Containers Version: 7.4.0
- Operating System + Version: Windows 10, 21H1
- Firefox Version: 91.0
- Other installed Add-ons + Version + Enabled/Disabled-Status:
Russian spellchecking dictionary	dictionary	0.4.5.1webext	true	ru@dictionaries.addons.mozilla.org
Amazon.com	extension	1.3	true	amazondotcom@search.mozilla.org
Bing	extension	1.3	true	bing@search.mozilla.org
DuckDuckGo	extension	1.1	true	ddg@search.mozilla.org
Feedbro	extension	4.9.10	true	{a9c2ad37-e940-4892-8dce-cd73c6cbbc0c}
Firefox Multi-Account Containers	extension	7.4.0	true	@testpilot-containers
FoxyProxy Standard	extension	7.5.1	true	foxyproxy@eric.h.jung
Google	extension	1.1	true	google@search.mozilla.org
KeePassXC-Browser	extension	1.7.9.1	true	keepassxc-browser@keepassxc.org
Open in Sidebar	extension	2019.7.8	true	open-link-in-sidebar@afnankhan
Simple Tab Groups	extension	4.7	true	simple-tab-groups@drive4ik
Simple Translate	extension	2.5.3	true	simple-translate@sienori
Tampermonkey	extension	4.13.6136	true	firefox@tampermonkey.net
User-Agent Switcher	extension	1.4.1	true	user-agent-switcher@ninetailed.ninja
Wikipedia (en)	extension	1.1	true	wikipedia@search.mozilla.org
Yandex	extension	1.2	true	yandex@search.mozilla.org

### Actual behavior

In Proton UI tabs are not highlighted by a color of container:
![image](https://user-images.githubusercontent.com/24388336/129379184-72dcf610-04d0-4d40-88b9-b08d77d8eec3.png)

### Expected behavior

As container "Scand" has blue color then tab should have some blue color highlighting the tab. In earlier version it was blue tab border.

### Steps to reproduce
1. Install Firefox 91.0.
2. Open tab of the container.
3. No visual highlighting.

### Notes

Earlier highlighting was implemented as one colored border. Maybe there is a reason to highlight all boarders of the tab because in Proton UI tab selector looks like a independent button.

**Comment by achernyakevich** [comment] 2021-08-13 16:06
As we could see that there was at least two other issues related to the same problem cause by forcing Proton UI to be turned on for everybody. It is really pity that to find which container tab belongs to you need to open this tab and look to URL field. :(

**Comment by shadowmage45** [comment] 2021-08-13 17:57
I found that if I open about:config, and search for 'Proton', I was able to restore the above-tab color bar for containers by enabling the 'browser.proton.enabled' setting (previously was set to disabled, likely by me trying to fix some other Proton UI issues...).

Hope this helps...

![image](https://user-images.githubusercontent.com/1503399/129400099-85177135-7634-4db1-b6f7-de66608cf694.png)

**Comment by achernyakevich** [comment] 2021-08-14 09:40
> I found that if I open about:config, and search for 'Proton', I was able to restore the above-tab color bar for containers by enabling the 'browser.proton.enabled' setting (previously was set to disabled, likely by me trying to fix some other Proton UI issues...).
> 
> Hope this helps...

Thanks for your screenshot. I have rechecked my settings about Proton and have found that I have kept `browser.proton.enabled` set to `false` after my attempts to disable Proton UI. I did it because new tabs decoupled from page itself look really bad. But after update to Firefox 91 I have found that this setting do not disable Proton. :(

So our joint research results are:

* if `browser.proton.enabled=true` (Proton is enabled) then tabs are colored.
* if `browser.proton.enabled=false` (Proton expected to be disabled but in reality is not) then tabs coloring does not work.

I'm not sure will developers of this add-on treat as a bug. But if possible I would like have tabs colored even if `browser.proton.enabled` set to `false`.

**Comment by spocko** [comment] 2021-08-14 21:24
Thank you @shadowmage45 and @achernyakevich. I have also confirmed these results. Setting browser.proton.enabled=true allows the tab colors to be displayed.

**Comment by arnofly** [comment] 2021-11-22 14:30
Thank you too @shadowmage45. That's fix the "bug". Photon was definitively a better UI than Proton. That's why I set this variable to FALSE, as many people I think so... Mozilla loose users year after year, but don't care about opinion of historic users.

For me, the color line at the bottom of the tab was more readable (i am web developer).

**Comment by achernyakevich-sc** [comment] 2021-11-22 15:19
@arnofly BTW: the following issue and its comments could be useful for you - https://github.com/mozilla/multi-account-containers/issues/2121

It provides info how to customize Firefox UI and color stripes for tabs of container (see, https://github.com/mozilla/multi-account-containers/issues/2121#issuecomment-974807710 comment).

**Comment by dannycolin** [comment] 2022-05-20 00:37
Closing since this was a Firefox issue.

**Closed by dannycolin** 2022-05-20 00:37 UTC
