### ISSUE TITLE
Allow full URLs to be opened in specific containers 

### ISSUE THREAD

**Issue by djhworld** [mozilla/multi-account-containers#1064] opened 2018-01-04 16:08 UTC
At work I login to my cloud provider accounts through a federated login, e.g.

For my development environment: https://federated-login-service.foo/cloud/account/development
For my production environment: https://federated-login-service.foo/cloud/account/production

If I create two profiles in Multi Account Containers (e.g. "Dev", "Prod") I can't see a way of assigning the above URLs to each container profile, so they open in the correct one. 

e.g. 

if I visit the development URL, it should always open in my "Dev" container profile
if I visit the production URL, it should always open in my "Prod" container profile

When I tick the 'Always open in....' checkbox, it doesn't seem to work this way, it looks like it works at the domain level (i.e. `federated-login-service.foo`) rather than the above case where the URL implies different semantics.

**Comment by groovecoder** [comment] 2018-01-09 18:23
Duplicate of https://github.com/mozilla/multi-account-containers/issues/691

**Closed by groovecoder** 2018-01-09 18:23 UTC
