### ISSUE TITLE
[Feature Request] Specify Container for Bookmarks to open Urls with specific Containers

### ISSUE THREAD

**Issue by lordgringo** [mozilla/multi-account-containers#1059] opened 2017-12-28 17:03 UTC
I would like to specify the container for Bookmarks.

As Idea we should be able to specify the to be used container for bookmarks. Simple solution would be add this in the url oder to add a field to the Properties.

Thus you can open Amazon with different Accounts direct with two different bookmarks.
Container1: www.amazon.com
Container2: www.amazon.com

Kind Regards

**Comment by precz** [comment] 2018-01-04 10:39
This is a needed feature!

**Comment by rsironneau** [comment] 2018-01-04 13:20
+1 Should be great :)

**Comment by groovecoder** [comment] 2018-01-09 18:26
Mostly dupe of https://github.com/mozilla/multi-account-containers/issues/323 ... please add upvotes and comments there.

**Closed by groovecoder** 2018-01-09 18:26 UTC

**Comment by thelaith** [comment] 2019-02-07 12:42
Any news?
