### ISSUE TITLE
One click to show/hide containers

### ISSUE THREAD

**Issue by lucasr** [mozilla/multi-account-containers#872] opened 2017-09-27 20:47 UTC
It would be great if hiding/showing containers could be done from the top-level list of containers instead of having to click on the arrow and then clicking on "Hide/Show this container".

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/MAC-607)

**Comment by psychoslave** [comment] 2017-11-17 11:04
Actually I was desperately looking for a similar feature, so thank you @lucasr to highlight it's there although hidden in a hardly discoverable part of the interface. 

What I'm looking for is a way to replace features that tabgroup used to provide. Especially, only show tabs of a single context at a time. So, this feature should do the trick, but with a less convenient UX so far.

**Comment by dannycolin** [comment] 2022-12-14 14:05
Duplicate of #755

**Closed by dannycolin** 2022-12-14 14:05 UTC
Labels: :+1:  Feature Request
