### ISSUE TITLE
Allow moving a tab to a container tab via context menu

### ISSUE THREAD

**Issue by danemacmillan** [mozilla/multi-account-containers#877] opened 2017-09-29 15:30 UTC
Frequently I'll open a site in a tab, and then realize I wanted it opened in a specific container tab. I don't want to permanently assign it, because I have multiple accounts for the same site. I'd like to be able to just right-click on the tab, and select an option like "Re-open tab in container > [container list]." 

To resolve this currently, I need to copy the URL, go the container tabs icon, select the container I want, which opens an empty tab for that container, paste the URL, hit enter; I now have the site loaded in the container I want. It would be much easier if I could just summon a context menu on the tab and select a container from the menu, similar to how the "Duplicate Tab" functionality works. It's ultimately in the same realm of convenience, with the main difference being that it is duplicating the current tab in a container and closing the original tab.

**Comment by groovecoder** [comment] 2017-09-29 15:38
Dupe of https://github.com/mozilla/multi-account-containers/issues/311. Consensus there is to use https://addons.mozilla.org/nn-no/firefox/addon/context-plus/?src=search

**Closed by groovecoder** 2017-09-29 15:38 UTC
Labels: duplicate
