### ISSUE TITLE
Do not use "open website in" logic when "Reopen in container" menu is chosen

### ISSUE THREAD

**Issue by mathstuf** [mozilla/multi-account-containers#1916] opened 2020-12-13 00:32 UTC
I have some sites assigned to certain containers. It is a little annoying that "ask every time" intercepts explicit "open site in container" menu selections. It'd be nice if it could be used to override even forced site assignments too.

**Comment by securingmom** [comment] 2021-01-01 21:03
Is there not a check box in the prompt page above and to the left of the blue button?

**Comment by lonix1** [comment] 2021-03-11 07:04
#1442

**Comment by mathstuf** [comment] 2021-05-25 15:38
> Is there not a check box in the prompt page above and to the left of the blue button?

Yes, but this only works if I have a single container that I always want to use. If I have a site where I use multiple accounts, I cannot use this because "always use" overrules the "reopen in X" option.

**Comment by dannycolin** [comment] 2022-12-29 03:32
Duplicate of #1442

**Closed by dannycolin** 2022-12-29 03:32 UTC
