### ISSUE TITLE
Auto-focus to location bar when opening a new container tab

### ISSUE THREAD

**Issue by lordserch** [mozilla/multi-account-containers#554] opened 2017-05-30 13:54 UTC
As a user, I want Firefox to automatically set the focus on the location bar so I can start typing or pasting a URL immediately after opening a container tab

Steps to reproduce: 
1. Open a tab from a container
2. Start typing a URL

Expected:
3. URL typed on the location bar

Actual:
3. Nothing happens, you need to manually click on the location bar to set the focus

**Comment by jonathanKingston** [comment] 2017-05-30 13:59
This was broken by a change I worked on however it should be fixed in the next Firefox release which is currently in beta.

I will double check this is the case. It certainly isn't a problem in Nightly.

This was fixed by the Web Extensions team and cause by removing custom SDK code we had.

**Comment by DorianVasco** [comment] 2017-06-10 15:53
Maybe a related problem: when hovering over the [+] button in the tab bar, the container menu opens and cursor focus gets lost (on form fields or in awesome bar). Regards, Dorian

**Comment by subinvarghesein** [comment] 2017-06-27 09:09
I use multiple monitors. When another application is currently in focus and then I open a container tab by clicking on the [+] button in tab bar and selecting a container, the focus would go back to the application rather than focussing on Firefox's location bar.

I am using 56.0a1 (2017-06-26) (64-bit)

**Comment by jonathanKingston** [comment] 2017-06-27 09:12
Sounds related but I don't think it is. Firefox 56 should have the
mentioned fix in it.

**Comment by Softvision-MariusComan** [comment] 2017-09-26 12:24
I could not reproduce this issue on the latest "Multi-Account Containers" build (4.0.2). 
I have verified it on on Windows 10 x64, Ubuntu 14.04 and Mac 10.12, with the latest Firefox release (55.0.3) and the latest Nightly (58.0a1).
@lordserch, can you please verify if this is still reproducible on your end?

**Comment by groovecoder** [comment] 2017-12-05 16:37
Closing since it hasn't been reproduced since Sep 26.

**Closed by groovecoder** 2017-12-05 16:37 UTC
Labels: bug, needs: Testing
