### ISSUE TITLE
Hide/Show tabs in this container actually closes and reopens tabs instead of hiding/showing, meaning it cannot reopen (show) privileged tabs (file, chrome, about, etc.)

### ISSUE THREAD

**Issue by gijsk** [mozilla/multi-account-containers#1717] opened 2020-04-17 21:40 UTC
Original report is https://bugzilla.mozilla.org/show_bug.cgi?id=1620757 .

Quoting Tomislav:

> It looks like instead of showing/hiding tabs, it actually closes and opens them:
https://github.com/mozilla/multi-account-containers/blob/d654810d/src/js/background/backgroundLogic.js#L315
> 
> Unfortunately, we prevent extensions from opening file:// urls for security reasons, we only support limited interactions with local files that users explicitly open themselves.

This was previously covered in #46, but it doesn't look like it was obvious then that this means the functionality actually doesn't work correctly.

If we're concerned about resource usage, we should be able to use the tab discarding API to effectively remove the relevant docshells without closing the tab, before hiding the tabs. I'm hoping/assuming (but haven't tested) that discarding file:/chrome:/about: tabs is allowed.

**Comment by schra** [comment] 2020-12-20 16:50
This issue is a duplicate of #918, see https://github.com/mozilla/multi-account-containers/issues/918#issuecomment-360537785

> [Steps to reproduce]:
> 3. Open a "Work" container tab and drag a local file into it.

However I like like the wording of this issue better because it actually describes the root of the problem.

**Comment by dannycolin** [comment] 2022-12-20 02:01
Duplicate of #802

**Closed by dannycolin** 2022-12-20 02:01 UTC
