### ISSUE TITLE
Custom containers missing after disable -> re-enable

### ISSUE THREAD

**Issue by RARgames** [mozilla/multi-account-containers#2016] opened 2021-04-17 00:13 UTC
- Multi-Account Containers Version: 7.3.0
- Operating System + Version: Win 10 Edu 20H2
- Firefox Version: 87.0 (64-bit)
- Other installed Add-ons + Version + Enabled/Disabled-Status: 
Name 	Type 	Version 	Enabled 	ID
Amazon.co.uk	extension	1.4	true	amazon@search.mozilla.org
Bing	extension	1.3	true	bing@search.mozilla.org
Chambers (UK)	extension	1.0	true	chambers-en-GB@search.mozilla.org
DuckDuckGo	extension	1.1	true	ddg@search.mozilla.org
eBay	extension	1.3	true	ebay@search.mozilla.org
Firefox Multi-Account Containers	extension	7.3.0	true	@testpilot-containers
Google	extension	1.1	true	google@search.mozilla.org
Privacy Badger	extension	2021.2.2	true	jid1-MnnxcxisBPnSXQ@jetpack
uBlock Origin	extension	1.34.0	true	uBlock0@raymondhill.net
Wikipedia (en)	extension	1.1	true	wikipedia@search.mozilla.org
Adblock Plus - free ad blocker	extension	3.10.2	false	{d10d0bf8-f5b5-c8b4-a8b2-2b9879e08c5d}
Grammarly for Firefox	extension	8.872.0	false	87677a2c52b84ad3a151a4a72f5bd3c4@jetpack
Popupblocker	extension	2.1	false	{05ce2135-ced2-4272-97b0-c00c00a93355}
Video DownloadHelper	extension	7.4.0	false	{b9db16a4-6edc-47ec-a1f4-b86292ed211d}

### Actual behavior

When I disable the multi account containers and re-enable it later all my custom containers are gone.

### Expected behavior

Containers should save.

### Steps to reproduce
1. Add a custom container.
2. Disable the add-on.
3. Enable the add-on.
4. All custom containers are missing :(

**Comment by veritablyclean** [comment] 2021-04-20 21:13
Same issue, occurred when entering troubleshooting mode for unrelated issues.

**Comment by dannycolin** [comment] 2022-10-11 22:49
Duplicate of #1236

**Closed by dannycolin** 2022-10-11 22:49 UTC
