### ISSUE TITLE
Data loss: All containers deleted after uninstalling tree-style tabs

### ISSUE THREAD

**Issue by DanielHeath** [mozilla/multi-account-containers#996] opened 2017-11-22 08:59 UTC
I was using multi-account containers and tree-style tabs, but decided tree-style tabs didn't suit how I use firefox, so I disabled the tree-style tabs extension.

Afterwards, clicking the multi-account containers button opened an empty panel (instead of the usual one) which was only ~10-15px high.

I restarted firefox (58.0b5) and clicking the MAC button opened the panel correctly but with none of my custom containers.

It was working correctly immediately prior to disabling tree-style tabs.

**Comment by Softvision-MariusComan** [comment] 2017-11-22 12:25
I have not managed to reproduce the issue on Windows 10 x64, Ubuntu 14.04 x64 and Mac 10.12 with the latest Firefox release (57.0), Firefox Beta (58.0b5) and latest Nightly (59.0a1) installed. I have installed the latest "Multi-Account Containers" (4.1.0) and the "Tree Style Tab" (2.2.11) add-ons, created a couple of custom containers, uninstalled the "Tree Style Tab" and when I've clicked on the "Multi-Account Containers" the panel has opened and all the elements were displayed.

Could you please navigate to the "about:config" page, search for "userContext" and list all the pref values?

Also can you please retest this issue on a new clean Firefox profile, to eliminate custom settings as a possible cause (https://goo.gl/AR5o9d)? If the issue is still reproducible on a new profile, can you please post a copy of the "about:support" page?

**Comment by DanielHeath** [comment] 2017-11-26 09:44
about:config
<img width="810" alt="screen shot 2017-11-26 at 8 35 25 pm" src="https://user-images.githubusercontent.com/47430/33238858-2e8771be-d2ea-11e7-8a5d-6ac710877942.png">

Will try to get time to retest soon. 
about:support
```
{
  "application": {
    "name": "Firefox",
    "osVersion": "Darwin 17.2.0",
    "version": "58.0b6",
    "buildID": "20171123161455",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:58.0) Gecko/20100101 Firefox/58.0",
    "safeMode": false,
    "updateChannel": "beta",
    "supportURL": "https://support.mozilla.org/1/firefox/58.0/Darwin/en-US/",
    "numTotalWindows": 1,
    "numRemoteWindows": 1,
    "remoteAutoStart": true,
    "currentContentProcesses": 4,
    "maxContentProcesses": 4,
    "autoStartStatus": 0,
    "styloBuild": true,
    "styloDefault": true,
    "styloResult": true,
    "styloChromeDefault": false,
    "styloChromeResult": false,
    "keyGoogleFound": true,
    "keyMozillaFound": true
  },
  "modifiedPreferences": {
    "accessibility.typeaheadfind.flashBar": 0,
    "accessibility.lastLoadDate": 1498975431,
    "browser.cache.disk.filesystem_reported": 1,
    "browser.cache.disk.hashstats_reported": 1,
    "browser.cache.frecency_experiment": 3,
    "browser.cache.disk.smart_size.first_run": false,
    "browser.cache.disk.smart_size.use_old_max": false,
    "browser.cache.disk.capacity": 358400,
    "browser.cache.disk.smart_size_cached_value": 358400,
    "browser.download.manager.alertOnEXEOpen": true,
    "browser.fixup.domainwhitelist.hrkiosk": true,
    "browser.places.smartBookmarksVersion": 8,
    "browser.places.importBookmarksHTML": false,
    "browser.search.suggest.enabled": false,
    "browser.search.useDBForOrder": true,
    "browser.sessionstore.upgradeBackup.latestBuildID": "20171123161455",
    "browser.sessionstore.restore_on_demand": false,
    "browser.startup.homepage_override.mstone": "58.0",
    "browser.startup.homepage": "about:startpage",
    "browser.startup.homepage_override.buildID": "20171123161455",
    "browser.tabs.closeButtons": 1,
    "browser.tabs.warnOnClose": false,
    "browser.tabs.remote.force-enable": true,
    "browser.tabs.warnOnOpen": false,
    "browser.urlbar.maxRichResults": 12,
    "dom.apps.lastUpdate.buildID": "20161019084923",
    "dom.fetch.enabled": true,
    "dom.push.userAgentID": "9c30a2639f384dc7bc47de33704645ce",
    "dom.ipc.processCount.extension": 2,
    "dom.apps.reset-permissions": true,
    "dom.apps.lastUpdate.mstone": "49.0.2",
    "dom.mozApps.used": true,
    "extensions.lastAppVersion": "58.0",
    "font.internaluseonly.changed": true,
    "gfx.crash-guard.glcontext.deviceID": "0x162b",
    "gfx.crash-guard.glcontext.appVersion": "45.0.2",
    "gfx.blacklist.direct2d.failureid": "FEATURE_FAILURE_DL_BLACKLIST_g984",
    "gfx.crash-guard.status.glcontext": 2,
    "media.webrtc.debug.log_file": "/Users/daniel.heath/Library/Caches/TemporaryItems/WebRTC.log",
    "media.benchmark.vp9.versioncheck": 2,
    "media.gmp-gmpopenh264.lastUpdate": 1510278428,
    "media.eme.enabled": false,
    "media.webrtc.debug.aec_log_dir": "/Users/daniel.heath/Library/Caches/TemporaryItems",
    "media.gmp-gmpopenh264.abi": "x86_64-gcc3",
    "media.gmp-manager.lastCheck": 1511588624,
    "media.youtube-ua.override.to": "43",
    "media.gmp.storage.version.observed": 1,
    "media.benchmark.vp9.fps": 115,
    "media.gmp-gmpopenh264.version": "1.7.1",
    "media.gmp-manager.buildID": "20171123161455",
    "network.prefetch-next": false,
    "network.dns.disablePrefetch": true,
    "network.http.speculative-parallel-limit": 0,
    "network.predictor.enabled": false,
    "network.auth.allow-subresource-auth": 2,
    "network.predictor.cleaned-up": true,
    "network.cookie.prefsMigrated": true,
    "places.history.expiration.transient_current_max_pages": 164575,
    "places.database.lastMaintenance": 1511327580,
    "plugin.state.directorshockwave": 0,
    "plugin.state.default browser": 0,
    "plugin.state.quicktime plugin": 0,
    "plugin.importedState": true,
    "plugin.state.quakeliveplugin": 0,
    "plugin.state.sharepointbrowserplugin": 0,
    "plugin.state.adobepdfviewernpapi": 0,
    "plugin.state.nplastpass": 1,
    "plugin.state.java": 0,
    "plugin.state.unity web player": 0,
    "plugin.disable_full_page_plugin_for_types": "application/pdf",
    "plugin.state.flash": 0,
    "plugin.state.uhd-installdetector": 0,
    "plugins.ctprollout.cohort": "early-adopter-disabled",
    "plugins.notifyMissingFlash": false,
    "print.printerXXXXXXXXXXXXELIDEDXXXXXXXX": 0,
    "privacy.userContext.ui.enabled": true,
    "privacy.donottrackheader.enabled": true,
    "privacy.sanitize.migrateClearSavedPwdsOnExit": true,
    "privacy.cpd.sessions": false,
    "privacy.cpd.cookies": false,
    "privacy.cpd.offlineApps": true,
    "privacy.firstparty.isolate": true,
    "privacy.sanitize.migrateFx3Prefs": true,
    "security.sandbox.content.tempDirSuffix": "{920d51e2-849b-c04c-9146-e908eacc2756}",
    "security.disable_button.openCertManager": false,
    "security.use_mozillapkix_verification": false,
    "services.sync.declinedEngines": "passwords",
    "services.sync.lastPing": 1511669267,
    "services.sync.lastSync": "Sun Nov 26 2017 20:33:19 GMT+1100 (AEDT)",
    "services.sync.numClients": 1,
    "services.sync.engine.greasemonkey": false,
    "services.sync.engine.bookmarks.validation.lastTime": 1511669272,
    "services.sync.engine.addons": false,
    "services.sync.engine.prefs.modified": false,
    "services.sync.engine.passwords": false,
    "storage.vacuum.last.places.sqlite": 1511327573,
    "storage.vacuum.last.index": 1
  },
  "lockedPreferences": {},
  "media": {
    "currentAudioBackend": "audiounit",
    "currentMaxAudioChannels": 2,
    "currentPreferredChannelLayout": "stereo",
    "currentPreferredSampleRate": 44100,
    "audioOutputDevices": [
      {
        "name": "Internal Speakers",
        "groupId": "AppleHDAEngineOutput:1B,0,1,1:0",
        "vendor": "Apple Inc.",
        "type": 2,
        "state": 2,
        "preferred": 15,
        "supportedFormat": 12336,
        "defaultFormat": 4096,
        "maxChannels": 2,
        "defaultRate": 44100,
        "maxRate": 96000,
        "minRate": 44100,
        "maxLatency": 4861,
        "minLatency": 779
      },
      {
        "name": "ZoomAudioDevice",
        "groupId": "ZoomAudioEngine:0",
        "vendor": "zoom.us",
        "type": 2,
        "state": 2,
        "preferred": 0,
        "supportedFormat": 12336,
        "defaultFormat": 4096,
        "maxChannels": 2,
        "defaultRate": 44100,
        "maxRate": 192000,
        "minRate": 44100,
        "maxLatency": 4096,
        "minLatency": 14
      }
    ],
    "audioInputDevices": [
      {
        "name": "Internal Microphone",
        "groupId": "AppleHDAEngineInput:1B,0,1,0:1",
        "vendor": "Apple Inc.",
        "type": 1,
        "state": 2,
        "preferred": 15,
        "supportedFormat": 12336,
        "defaultFormat": 4096,
        "maxChannels": 2,
        "defaultRate": 44100,
        "maxRate": 96000,
        "minRate": 44100,
        "maxLatency": 4162,
        "minLatency": 80
      },
      {
        "name": "ZoomAudioDevice",
        "groupId": "ZoomAudioEngine:0",
        "vendor": "zoom.us",
        "type": 1,
        "state": 2,
        "preferred": 0,
        "supportedFormat": 12336,
        "defaultFormat": 4096,
        "maxChannels": 2,
        "defaultRate": 44100,
        "maxRate": 192000,
        "minRate": 44100,
        "maxLatency": 4096,
        "minLatency": 14
      }
    ]
  },
  "javaScript": {
    "incrementalGCEnabled": true
  },
  "accessibility": {
    "isActive": false,
    "forceDisabled": 0,
    "handlerUsed": false,
    "instantiator": ""
  },
  "libraryVersions": {
    "NSPR": {
      "minVersion": "4.17",
      "version": "4.17"
    },
    "NSS": {
      "minVersion": "3.34",
      "version": "3.34"
    },
    "NSSUTIL": {
      "minVersion": "3.34",
      "version": "3.34"
    },
    "NSSSSL": {
      "minVersion": "3.34",
      "version": "3.34"
    },
    "NSSSMIME": {
      "minVersion": "3.34",
      "version": "3.34"
    }
  },
  "userJS": {
    "exists": false
  },
  "intl": {
    "localeService": {
      "requested": [
        "en-US"
      ],
      "available": [
        "en-US"
      ],
      "supported": [
        "en-US"
      ],
      "regionalPrefs": [
        "en-US"
      ],
      "defaultLocale": "en-US"
    },
    "osPrefs": {
      "systemLocales": [
        "en-US"
      ],
      "regionalPrefsLocales": [
        "en-US"
      ]
    }
  },
  "crashes": {
    "submitted": [],
    "pending": 0
  },
  "sandbox": {
    "contentSandboxLevel": 3,
    "effectiveContentSandboxLevel": 3
  },
  "graphics": {
    "numTotalWindows": 1,
    "numAcceleratedWindows": 1,
    "windowLayerManagerType": "OpenGL",
    "windowLayerManagerRemote": true,
    "windowUsingAdvancedLayers": false,
    "adapterDescription": "",
    "adapterVendorID": "0x8086",
    "adapterDeviceID": "0x162b",
    "adapterRAM": "",
    "adapterDrivers": "",
    "driverVersion": "",
    "driverDate": "",
    "offMainThreadPaintEnabled": false,
    "webgl1Renderer": "Intel Inc. -- Intel(R) Iris(TM) Graphics 6100",
    "webgl1Version": "4.1 INTEL-10.28.29",
    "webgl1DriverExtensions": "GL_ARB_blend_func_extended GL_ARB_draw_buffers_blend GL_ARB_draw_indirect GL_ARB_ES2_compatibility GL_ARB_explicit_attrib_location GL_ARB_gpu_shader_fp64 GL_ARB_gpu_shader5 GL_ARB_instanced_arrays GL_ARB_internalformat_query GL_ARB_occlusion_query2 GL_ARB_sample_shading GL_ARB_sampler_objects GL_ARB_separate_shader_objects GL_ARB_shader_bit_encoding GL_ARB_shader_subroutine GL_ARB_shading_language_include GL_ARB_tessellation_shader GL_ARB_texture_buffer_object_rgb32 GL_ARB_texture_cube_map_array GL_ARB_texture_gather GL_ARB_texture_query_lod GL_ARB_texture_rgb10_a2ui GL_ARB_texture_storage GL_ARB_texture_swizzle GL_ARB_timer_query GL_ARB_transform_feedback2 GL_ARB_transform_feedback3 GL_ARB_vertex_attrib_64bit GL_ARB_vertex_type_2_10_10_10_rev GL_ARB_viewport_array GL_EXT_debug_label GL_EXT_debug_marker GL_EXT_framebuffer_multisample_blit_scaled GL_EXT_texture_compression_s3tc GL_EXT_texture_filter_anisotropic GL_EXT_texture_sRGB_decode GL_APPLE_client_storage GL_APPLE_container_object_shareable GL_APPLE_flush_render GL_APPLE_object_purgeable GL_APPLE_rgb_422 GL_APPLE_row_bytes GL_APPLE_texture_range GL_ATI_texture_mirror_once GL_NV_texture_barrier",
    "webgl1Extensions": "ANGLE_instanced_arrays EXT_blend_minmax EXT_color_buffer_half_float EXT_frag_depth EXT_sRGB EXT_shader_texture_lod EXT_texture_filter_anisotropic EXT_disjoint_timer_query OES_element_index_uint OES_standard_derivatives OES_texture_float OES_texture_float_linear OES_texture_half_float OES_texture_half_float_linear OES_vertex_array_object WEBGL_color_buffer_float WEBGL_compressed_texture_s3tc WEBGL_compressed_texture_s3tc_srgb WEBGL_debug_renderer_info WEBGL_debug_shaders WEBGL_depth_texture WEBGL_draw_buffers WEBGL_lose_context",
    "webgl1WSIInfo": "CGL",
    "webgl2Renderer": "Intel Inc. -- Intel(R) Iris(TM) Graphics 6100",
    "webgl2Version": "4.1 INTEL-10.28.29",
    "webgl2DriverExtensions": "GL_ARB_blend_func_extended GL_ARB_draw_buffers_blend GL_ARB_draw_indirect GL_ARB_ES2_compatibility GL_ARB_explicit_attrib_location GL_ARB_gpu_shader_fp64 GL_ARB_gpu_shader5 GL_ARB_instanced_arrays GL_ARB_internalformat_query GL_ARB_occlusion_query2 GL_ARB_sample_shading GL_ARB_sampler_objects GL_ARB_separate_shader_objects GL_ARB_shader_bit_encoding GL_ARB_shader_subroutine GL_ARB_shading_language_include GL_ARB_tessellation_shader GL_ARB_texture_buffer_object_rgb32 GL_ARB_texture_cube_map_array GL_ARB_texture_gather GL_ARB_texture_query_lod GL_ARB_texture_rgb10_a2ui GL_ARB_texture_storage GL_ARB_texture_swizzle GL_ARB_timer_query GL_ARB_transform_feedback2 GL_ARB_transform_feedback3 GL_ARB_vertex_attrib_64bit GL_ARB_vertex_type_2_10_10_10_rev GL_ARB_viewport_array GL_EXT_debug_label GL_EXT_debug_marker GL_EXT_framebuffer_multisample_blit_scaled GL_EXT_texture_compression_s3tc GL_EXT_texture_filter_anisotropic GL_EXT_texture_sRGB_decode GL_APPLE_client_storage GL_APPLE_container_object_shareable GL_APPLE_flush_render GL_APPLE_object_purgeable GL_APPLE_rgb_422 GL_APPLE_row_bytes GL_APPLE_texture_range GL_ATI_texture_mirror_once GL_NV_texture_barrier",
    "webgl2Extensions": "EXT_color_buffer_float EXT_texture_filter_anisotropic EXT_disjoint_timer_query OES_texture_float_linear WEBGL_compressed_texture_s3tc WEBGL_compressed_texture_s3tc_srgb WEBGL_debug_renderer_info WEBGL_debug_shaders WEBGL_lose_context",
    "webgl2WSIInfo": "CGL",
    "info": {
      "AzureCanvasBackend": "skia",
      "AzureFallbackCanvasBackend": "none",
      "AzureContentBackend": "skia",
      "AzureCanvasAccelerated": 1,
      "ApzWheelInput": 1,
      "ApzDragInput": 1,
      "ApzKeyboardInput": 1,
      "ApzAutoscrollInput": 1,
      "TileHeight": 1024,
      "TileWidth": 1024
    },
    "featureLog": {
      "features": [
        {
          "name": "HW_COMPOSITING",
          "description": "Compositing",
          "status": "available",
          "log": [
            {
              "type": "default",
              "status": "available"
            }
          ]
        },
        {
          "name": "OPENGL_COMPOSITING",
          "description": "OpenGL Compositing",
          "status": "available",
          "log": [
            {
              "type": "default",
              "status": "available"
            }
          ]
        },
        {
          "name": "WEBRENDER",
          "description": "WebRender",
          "status": "unavailable",
          "log": [
            {
              "type": "default",
              "status": "opt-in",
              "message": "WebRender is an opt-in feature"
            },
            {
              "type": "runtime",
              "status": "unavailable",
              "message": "Build doesn't include WebRender"
            }
          ]
        },
        {
          "name": "OMTP",
          "description": "Off Main Thread Painting",
          "status": "blocked",
          "log": [
            {
              "type": "default",
              "status": "disabled",
              "message": "Disabled by default"
            },
            {
              "type": "runtime",
              "status": "blocked",
              "message": "OMTP does not yet support tiling"
            }
          ]
        }
      ],
      "fallbacks": []
    },
    "crashGuards": []
  },
  "experiments": [],
  "extensions": [
    {
      "name": "DuckDuckGo Plus",
      "version": "2017.11.21",
      "isActive": true,
      "id": "jid1-ZAdIEUB7XOzOJw@jetpack"
    },
    {
      "name": "uBlock Origin",
      "version": "1.14.18",
      "isActive": true,
      "id": "uBlock0@raymondhill.net"
    },
    {
      "name": "Fangs",
      "version": "1.0.8.1-signed.1-signed",
      "isActive": false,
      "id": "{21D01944-2878-4eb3-A72A-83E8D1E6D4A6}"
    },
    {
      "name": "LastPass: Free Password Manager",
      "version": "4.2.1.21",
      "isActive": false,
      "id": "support@lastpass.com"
    },
    {
      "name": "NoScript",
      "version": "10.1.2",
      "isActive": false,
      "id": "{73a6fe31-595d-460b-a920-fcc0f8843232}"
    }
  ],
  "features": [
    {
      "name": "Activity Stream",
      "version": "2017.11.03.1438-bf427ddd",
      "id": "activity-stream@mozilla.org"
    },
    {
      "name": "Application Update Service Helper",
      "version": "2.0",
      "id": "aushelper@mozilla.org"
    },
    {
      "name": "Firefox Screenshots",
      "version": "19.2.0",
      "id": "screenshots@mozilla.org"
    },
    {
      "name": "Follow-on Search Telemetry",
      "version": "0.9.6",
      "id": "followonsearch@mozilla.com"
    },
    {
      "name": "Form Autofill",
      "version": "1.0",
      "id": "formautofill@mozilla.org"
    },
    {
      "name": "Photon onboarding",
      "version": "1.0",
      "id": "onboarding@mozilla.org"
    },
    {
      "name": "Pocket",
      "version": "1.0.5",
      "id": "firefox@getpocket.com"
    },
    {
      "name": "Shield Recipe Client",
      "version": "76.1",
      "id": "shield-recipe-client@mozilla.org"
    },
    {
      "name": "Web Compat",
      "version": "1.1",
      "id": "webcompat@mozilla.org"
    }
  ]
}
```

**Comment by Softvision-CristinaBadescu** [comment] 2017-11-27 10:49
I have tested this issue but could not reproduce it on Mac 10.13, using latest Firefox Release (57.0) and latest Firefox Beta (58.0b6). I have installed the latest "Multi-Account Containers" (4.1.0), the "Tree Style Tab" (2.2.11), the "DuckDuckGo Plus" (2017.11.21) and the "uBlock Origin" (1.14.18) add-ons, created a couple of custom containers, uninstalled the "Tree Style Tab", and when I've clicked on the "Multi-Account Containers" the panel opened and all the elements were displayed, including the custom containers. I have also managed to correctly open the "Multi-Account Containers" panel after restarting the browser.

Daniel, from your "about:config" page I noticed you have "userContext" prefs set to false. Can you please set all the "userContext" prefs to "true" to see if it correctly brings back the add-on panel?
 
Can you please retest this on a new clean Firefox profile(https://goo.gl/THLbW2) as @Softvision-MariusComan suggested?

**Comment by DanielHeath** [comment] 2017-11-29 00:14
The panel came back after a restart without changing any settings, but all the containers were gone.

**Comment by DanielHeath** [comment] 2017-11-29 00:19
Retested in a clean profile - worked perfectly. No idea what might've caused it, sorry.

**Comment by Softvision-CristinaBadescu** [comment] 2017-11-29 08:56
Thanks Daniel for reporting back. Because I wasn't able to reproduce the issue and based on your last comment, I'm going to close this issue.

**Closed by Softvision-CristinaBadescu** 2017-11-29 08:56 UTC
