### ISSUE TITLE
Ability to manually designate sites to a container

### ISSUE THREAD

**Issue by FOSS-Love** [mozilla/multi-account-containers#2117] opened 2021-09-04 14:45 UTC
Scenario : I always want to open my work-account of mail in container-1 and i dont want to open any other sites in container-1, inorder to limit container to designated sites i need to set my mail to always open in container-1, but i have my personal mail in container-2. 

Request : Ability to add a site to be opened in a locked container without enabling always open trigger.

- Created 2 containers (work & personal)
- work account of https://website.com is in work container, personal account of https://website.com is in personal container.
-  I want to lock my work container to just open https://website.com and https://github.com. 
- But to lock my work container i need to make https://website.com and https://github.com to always open in work container.
- But the problem is i also need to open https://website.com in personal container.
- If there is a option to manually add site addresses to designate to a container, then i can designate https://website.com to work container and lock it.

**Comment by dannycolin** [comment] 2023-01-09 00:11
Duplicate of #1749

**Closed by dannycolin** 2023-01-09 00:11 UTC
