### ISSUE TITLE
Multi-Account Containers wierd behaviour with Google

### ISSUE THREAD

**Issue by pdehaan** [mozilla/multi-account-containers#2021] opened 2021-04-21 05:43 UTC
Reported via Foxfooding for Firefox 89/MR1.

---

**Firefox Version:** Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:89.0) Gecko/20100101 Firefox/89.0
**Window Size (inner width and height):** 1536x739

## Steps to Reproduce
1) put Google domains to be always opened in certain custom (e.g. "Google") container.
2) write address of google product (Gmail, Drive, Play) URL in address bar. 
3) Hit Enter

## Expected Behavior
Open address webpage in custom container.

## Actual Behavior
Gmail: Error 400.

Drive: constant loading Loop with URL: 

https://accounts.google.com/ServiceLogin?service=wise&passive=1209600&continue=https://drive.google.com/?pli%3D1%26authuser%3D0&followup=https://drive.google.com/?pli%3D1%26authuser%3D0&emr=1

**Comment by grahamperrin** [comment] 2021-04-23 19:03
Reproducible with a clean profile? 

`about:profiles`

**Comment by GraemeF** [comment] 2022-02-23 07:59
I'm also seeing this - containers would be great for managing multiple Gmail accounts but I can't sign in to one of them now, 400 every time with version 8.0.6.

**Comment by dannycolin** [comment] 2022-12-02 00:02
Duplicate of #1882

**Closed by dannycolin** 2022-12-02 00:02 UTC
