### ISSUE TITLE
Browser is crashing when "open in new tab" on startpage for urls assigned to containers

### ISSUE THREAD

**Issue by trevan** [mozilla/multi-account-containers#454] opened 2017-04-14 03:47 UTC
I have github assigned to its own container.  In startpage.com, if I right click and say "open in new tab", the browser crashes.  If I command-click, the browser crashes.

If I just click on the link normally, it opens a new tab (which is what startpage always does) in the correct container.

If the link is not assigned to a container, there is no crash.

If I'm already in the correct container and I command-click a link, there is no crash.

So there is some weird interaction between the open in new tab, assigned containers, and startpage's mechanism to open links.

Here's one of the crash reports: https://crash-stats.mozilla.com/report/index/57abea8a-05e9-4d7f-9c36-056aa1170414

**Comment by jonathanKingston** [comment] 2017-04-16 21:14
Wasn't able to reproduce, the crash also doesn't look related to the mentioned issue either.

Do you have any other crash reports or an example link you used to trigger the crash?

**Comment by trevan** [comment] 2017-04-17 04:08
Here's two more crashes:

https://crash-stats.mozilla.com/report/index/bp-b79f0737-6fa4-408e-8d29-704fc2170417
https://crash-stats.mozilla.com/report/index/bp-c81a158c-d114-4253-abaa-3e9cb2170417

It happens every single time for me.

**Comment by trevan** [comment] 2017-04-17 04:13
Here's two more crashes:

https://crash-stats.mozilla.com/report/index/bp-b79f0737-6fa4-408e-8d29-704fc2170417
https://crash-stats.mozilla.com/report/index/bp-c81a158c-d114-4253-abaa-3e9cb2170417

It happens every single time for me.

**Comment by trevan** [comment] 2017-04-17 04:14
Here's a animated gif of the crash:

![container_crash](https://cloud.githubusercontent.com/assets/2044248/25078597/e76dca6a-22f1-11e7-9817-db6381e0e92f.gif)

The first time I click on the link and it opens fine.  You can see that it set the container automatically.  The second time, I right click and select open in new tab.  The crash happens right after that.  The crash report for that is https://crash-stats.mozilla.com/report/index/bp-a32b703f-0b8b-4036-b9b9-b50c12170417

**Comment by kjozwiak** [comment] 2017-04-17 05:43
I'm pretty sure that Adblock Plus is causing this crash. I couldn't reproduce the crash with a clean profile using fx52.0.2 so I looked through the extensions portion of the crash reports that @trevan added and noticed the following non-default extensions that were installed:

* DownThemAll!
* savedpasswordeditor@daniel.dawson
* morningCoffee@shaneliesegang
* adblock plus

After a process of elimination, I managed to reproduce the same crash [here](https://crash-stats.mozilla.com/report/index/ad033359-d8bb-46c1-bbc7-7b02b2170417) and [here](https://crash-stats.mozilla.com/report/index/34fe1ae8-7c2b-48b5-8a0d-9bcfa2170417) using just AdBlock Plus.

The strange part is that once I disabled/re-enabled AdBlock Plus via about:addons, I couldn't reproduce the crash anymore. However, re-installing it once it's removed will cause the same issue to occur.

@jonathanKingston, @groovecoder, @bakulf do we know anyone from AdBlock that we can contact? Maybe we can reach out to someone in the add-on team and see if they have any contacts if this can't be fixed on our side. I looked for a way to report this but it seems like AdBlock Plus likes it's issues reported via a forum which I don't really want to make an account for...

STR:

* install fx52.0.2
* once installed, install the test pilot via https://testpilot.firefox.com/ and enable "Containers"
* install "Adblock Plus" via about:addons
* open the "Personal" container, visit and login into github
* once logged in, right click and assign github to the "Personal" container via "Aways Open in This Container"
* open a regular non-container tab and visit https://www.startpage.com
* search for "github", right click on the first result and select "Open Link in New Tab"

**Comment by groovecoder** [comment] 2017-04-17 14:55
Thanks for the thorough investigation, @kjozwiak.

@palant may be able to help if he has time.

**Comment by palant** [comment] 2017-04-17 16:39
Judging by the stack trace, this crash is likely related to the user stylesheet added by Adblock Plus. The crash isn't "caused" by Adblock Plus however - the bug is still somewhere in Gecko. You can see the user stylesheets active on startpage.com under `about:abp-elemhide?css` and `about:abp-elemhide?css=www.startpage.com`. One would test whether the same stylesheets applied by other means (Stylish?) will cause issues as well - and if they do, reduce the contents to see which parts Gecko cannot handle.

**Comment by bakulf** [comment] 2017-04-24 10:03
@kjozwiak, are you able to reproduce this crash in nightly?

**Comment by kjozwiak** [comment] 2017-04-24 21:30
@bakulf, I couldn't reproduce the issue with the latest version of nightly, however I did manage to reproduce the issue with all the other channels:

* fx53.0, buildid: 20170413192749, changeset: d345b657d381 - **Reproduced**
* fx54.0b1, buildid: 20170420011827, changeset: cf76e00dcd6f - **Reproduced**
* fx54.0a2, buildid: 20170424004007, changeset: 94b7e538af7d - **Reproduced**
* fx55.0a1, buildid: 20170424030211, changeset: 73752931e273 - **Couldn't reproduce**

I ran through the test case on a debug version of fx54.0b1 and received the following assertion once I hit the issue:

Full Stack:  https://pastebin.mozilla.org/9019848

```
Assertion failure: mPresContext->mLayoutPhaseCount[eLayoutPhase_FrameC] == 0 (recurring into frame construction), at /Users/kjozwiak/projects/mozilla-beta/layout/base/nsAutoLayoutPhase.cpp:55

Process 38993 stopped
* thread #1, queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=1, address=0x0)
    frame #0: 0x000000010625625c XUL`nsAutoLayoutPhase::Enter(this=0x00007fff5fbc80d0) at nsAutoLayoutPhase.cpp:54
   51  	                 "constructing frames in the middle of a paint");
   52  	      MOZ_ASSERT(mPresContext->mLayoutPhaseCount[eLayoutPhase_Reflow] == 0,
   53  	                 "constructing frames in the middle of reflow");
-> 54  	      MOZ_ASSERT(mPresContext->mLayoutPhaseCount[eLayoutPhase_FrameC] == 0,
   55  	                 "recurring into frame construction");
   56  	      MOZ_ASSERT(!nsContentUtils::IsSafeToRunScript(),
   57  	                 "constructing frames and scripts are not blocked");
```

@bakulf, it looks like the crash is occurring on the platform. I created [bug#1359232](https://bugzilla.mozilla.org/show_bug.cgi?id=1359232) and needinfo'd you.

**Comment by groovecoder** [comment] 2017-12-05 16:57
Clsoing; hasn't been reproduced in recent builds.

**Closed by groovecoder** 2017-12-05 16:57 UTC
Labels: bug, needs: M-C Platform
