### ISSUE TITLE
extension icon is missing in firefox 73.0.1

### ISSUE THREAD

**Issue by activebiz1** [mozilla/multi-account-containers#1665] opened 2020-02-27 10:51 UTC
Since the last browser update, I no longer have the icon either on the top bar or in the sidebar.
I always had the multi-account-container icon handy on the toolbar.
No other problem - This is the first time that I experienced this puzzling no show of an extension icon.

There was little in my folders, so I copied and saved the URLs, then uninstalled the extension and rebooted my computer. Then installed the extension new. I created my folders, they all show up  - except no icon to see so I am unable to use the extension.

I have a dark background on my toolbar. So I checked by switching to the white default theme, to be able to see all icons clearly - all my icons are there except the multi-account-containers icon.

I am at a loss at this point. It would be very much appreciated if someone knows something more than what I have already tested.

Thank you  -:)

**Comment by kendallcorner** [comment] 2020-02-27 14:33
Does it show up on the toolbar or down below where you could drag it up to the toolbar when you try to customize? https://support.mozilla.org/en-US/kb/customize-firefox-controls-buttons-and-toolbars

**Comment by DemiGuru** [comment] 2020-03-03 13:23
I can concur - I have the same issue - it appears as though select extensions become unavailable through the toolbar. The only way to "Recover" is to restart the browser with all addons disabled and restart again with them enabled.

**Comment by gitvalds** [comment] 2020-05-09 15:01
I have this problem too, since Firefox 75.(...something).
In this moment I am using Firefox 76.0, which is the latest from Fedora 32.
All addons don't work.
The icons are not shown.
I can solve it for a day or so, by either:

1)
disabling all addons, then restarting firefox, then enabling all addons.

2)
deleting all <profile>/extension*, then deleting <profile>/compatibility.ini, then restarting firefox.

3)
downgrading to firefox 75. This also solved it for a day or so.

This profile is shared by two Fedora 32 installations, only one of which has selinux enforcing, and the problem appears on both installations.

**Comment by Gustowiththeflow** [comment] 2020-06-21 16:03
I'm having the same problem. CHas anyone come across a colution?

**Comment by grahamperrin** [comment] 2021-04-23 16:25
Reproducible with Firefox `88`? If so, please also look for symptoms in Bugzilla for Mozilla.

**Comment by dannycolin** [comment] 2022-12-06 23:06
Closing since 73 is end-of-life for a while now. If you still experience this issue with the latest version, please reply and I'll reopen it.

**Closed by dannycolin** 2022-12-06 23:06 UTC
