### ISSUE TITLE
In the "Manage Site List..." panel the back button requires an increasing number of clicks.

### ISSUE THREAD

**Issue by mozjag** [mozilla/multi-account-containers#1805] opened 2020-07-14 07:59 UTC
MAC 7.0.0
Win 10
Firefox 78.0.2

### Actual behavior

If you go to "Manage Site List..." for any container more than once (without closing the add-on's panel), you'll need to click the add-on's back button (looks like a less-than sign) an increasing number of times for it to work.

### Expected behavior

The back button should require just the one click, regardless of how many times you want to manage the site list ;-)

### Steps to reproduce

1. Click the add-on button and pick "Manage Containers"
2. Pick a container, then click on "Manage Site List..."
3. Click the back button, then click on "Manage Site List..." again.
4. Click the back button, nothing happens, click it again, should take you back (if not, keep clicking!)
5. Click "Manage Site List..." again, and now it should take 3 clicks.

If you go to another container and pick "Manage Site List..." from there it seems to add 2 clicks to the required count.

### Notes

Closing the add-on panel seems to reset the counter.

**Comment by mozjag** [comment] 2020-07-14 08:02
Could this be related to (or have the same root cause as) issue #1781?

**Comment by jimaldon** [comment] 2020-07-16 22:49
The back button also reverts the "Limit to Designated Sites" check box to off once you check it for more than one container

**Comment by mozjag** [comment] 2020-07-19 17:03
Tried again in 7.0.2, still an issue, so unfortunately the fix for #1781 didn't fix this.

**Comment by dannycolin** [comment] 2023-01-01 00:19
Duplicate of #2437

**Closed by dannycolin** 2023-01-01 00:19 UTC
