### ISSUE TITLE
can't rename a container

### ISSUE THREAD

**Issue by ak1dd** [mozilla/multi-account-containers#1643] opened 2020-02-17 17:43 UTC
If I try to rename a container - Edit Container, select the pencil icon - edit the name, it appears to work but when I hit Enter or the back button it is not renamed. Restart firefox and it is still not renamed. This is version 6.2.1 of the extension

**Comment by andrewcrook** [comment] 2020-02-19 19:40
@ak1dd 
 
Are  there any name(s) in particular? 
I can rename with 6.2.1, however, I found certain characters do not work and rather than throw an error it just ignores the new name.

**Comment by nvhaver** [comment] 2020-02-26 14:43
Can confirm this issue on my setup. Version 6.2.1, Firefox 73.0.1 (64-bit) on a Windows machine. As indicated by OP, it seems the editing container names function does not work.

**Comment by andrewcrook** [comment] 2020-02-26 19:58
I have found the issue here

I have tested on Version 6.2.1, Firefox 73.0.1 (64-bit) on up to date Windows 10 x64 and MacOS 10.15.3

The issue is if you press enter to update the edit the changes fail to save.
However, if you click the arrow on the left to go back it passes and up dates the name.

Please find animated Gifs of the Pass and Fail testing results

Passing
![pass](https://user-images.githubusercontent.com/803618/75382131-d0a36600-58d1-11ea-9444-294d4c9a4ec6.gif)

Failing 
![fail](https://user-images.githubusercontent.com/803618/75382173-e022af00-58d1-11ea-953e-b985f9fa7363.gif)

**Comment by kendallcorner** [comment] 2020-02-26 21:14
Thank you for tracking that down! I'll see if I can take a look!

**Comment by kendallcorner** [comment] 2020-02-26 22:55
I suspect the fix for #1656 will also fix this.

**Comment by kendallcorner** [comment] 2020-02-27 20:53
This fix is merged and sent to the addon's team. You should see an update in 1-2 business days.

**Closed by kendallcorner** 2020-02-27 20:53 UTC
Labels: bug
