### ISSUE TITLE
Feature request: Ability to clean cache and other stuff per container

### ISSUE THREAD

**Issue by rahmanshaber** [mozilla/multi-account-containers#1955] opened 2021-01-28 06:43 UTC
If there is ability to clean the cache and other stuff by per container will be great help.

I use goggle search in a container and if there is a way to clear the cache just only within that container will be very helpful as i don't wanna do clean up the whole browser as if i do it i need the re-login.
just want clean the cookies, cache and other on the container i use goggle search.

**Comment by ameaninglessname** [comment] 2021-02-04 16:43
[Try this add-on : **Cookie AutoDelete**](https://addons.mozilla.org/firefox/addon/cookie-autodelete/)
[GitHub repo](https://github.com/Cookie-AutoDelete/Cookie-AutoDelete/)

**Comment by jay0x** [comment] 2021-02-13 11:17
@ameaninglessname It will not work in all cases. For example, some sites make 3rd party cookies or super cookies. There are no way to find out that to delete without a research. It would be great to have a feature to purge a container from time to time.

**Comment by rahmanshaber** [comment] 2021-02-22 04:14
Yes, i keep those google search in a container and ability to clean that container will be great from the same add-on.

**Comment by GemKosan** [comment] 2021-02-22 23:37
I found an extension that might be a good workaround:
https://addons.mozilla.org/en-US/firefox/addon/clear-private-data-now/?utm_source=addons.mozilla.org&utm_medium=referral&utm_content=search

**Comment by josegfv** [comment] 2021-03-02 15:36
This is definitely a needed feature to add,  it will be great to select the container and do a clear cache only for the cookies and data related to the specific container.

**Comment by winks** [comment] 2021-05-17 15:19
+1, but for a specific reason, and that's why I think the proposed addons don't work, at least in my case. (cookie autodelete would make me not stay logged in, and for "clear private data now" I suppose the website would have to load first, but read on...)

I've now had it repeatedly (3 times for Slack, but at least once for another website) where something went completely haywire and I couldn't access the page anymore, but all other pages (except the one I was confining to the container, ironically) still worked. I think it has something to do with ssl certs, or maybe cookies or webworkers the cache (NS_ERROR_DOM_ABORT_ERR), but if it happens I have to nuke the container right now (because there's nothing wrong with my connection, it works in another container, or the raw profile or another browser). Not the end of the world and certainly not as bad as having to nuke the profile (if cleaning wouldn't help), but a little annoying.

**Comment by FOSS-Love** [comment] 2022-05-12 17:08
#303 duplicate

**Comment by dannycolin** [comment] 2022-12-29 02:33
Closing as duplicate of #303. For the "other stuff", there's already a couple of other reports filed for history, cookies, etc. It's better to keep one feature request per report.

**Closed by dannycolin** 2022-12-29 02:33 UTC
