### ISSUE TITLE
Small aesthetic suggestion: first container is always highlighted

### ISSUE THREAD

**Issue by rnkn** [mozilla/multi-account-containers#1479] opened 2019-08-15 07:23 UTC
Just a small aesthetic suggestion here. When clicking the MAC menu button to display the popup, the first saved container button is always highlighted/selected, with the blue plus button on the side:

<img width="382" alt="Screen Shot 2019-08-15 at 5 17 05 pm" src="https://user-images.githubusercontent.com/1256849/63079476-c3500b00-bf81-11e9-908b-445b48937333.png">

It feels like this shouldn't be highlighted, because the user is yet to select anything, and also this obscures the user-saved icon/colour (e.g my orange shopping cart for Amazon) making is just that tiny bit harder to quickly see which container to select.

**Comment by rnkn** [comment] 2019-08-15 07:25
p.s. For context, how I think the popup ought to look when first clicked:

<img width="339" alt="Screen Shot 2019-08-15 at 5 23 45 pm" src="https://user-images.githubusercontent.com/1256849/63079391-900d7c00-bf81-11e9-8dab-f9953cb3109d.png">

**Comment by kendallcorner** [comment] 2019-12-05 20:45
Hi. This looks like a duplicate of #1173. Please vote (:+1:) or discuss on that issue to show your interest. I'll close this, but feel free to reopen if you think it's a different issue.

**Closed by kendallcorner** 2019-12-05 20:45 UTC
Labels: enhancement
