### ISSUE TITLE
Configuration lost after disabeling and re-enabeling add-on

### ISSUE THREAD

**Issue by dima0git** [mozilla/multi-account-containers#2043] opened 2021-05-06 05:54 UTC
Had a strange issue with firefox redirect and had to find out with add-on is responsible for that. Disabled all add-ons one by one to find out the source for the issue. Multi-account-containers lost the whole configuration during this process.

### Actual behavior

Add-On looses all settings, after disabling it.

### Expected behavior
All other addons, keep their settings if I disable and then re-enable it. This add-one completely looses the entire configuration. This is really bad. I spend so much time configuring it and now all is gone.

### Steps to reproduce
1. Go to Add-on page in your settings.
2. Disable multi-account-containers
3. Enable multi-account-containers
4. Configuration gone!

**Comment by DrewNull** [comment] 2021-06-09 01:42
This just happened to me today -- for what feels like the 10th time. 

![Chris-Farley-Angry](https://user-images.githubusercontent.com/1610135/121279289-92954000-c891-11eb-83fb-1bff944e4135.gif)

**Comment by chylex** [comment] 2022-02-15 07:14
Could this please be addressed? Thankfully I have hourly backups of my system (which turned out to be a great decision because this is far from the first time I've had to restore my Firefox profile from a backup), but if I didn't this would go from a mild nuisance to an uninstall.

**Comment by dannycolin** [comment] 2022-12-28 01:11
Duplicate of #1236

**Closed by dannycolin** 2022-12-28 01:11 UTC
