### ISSUE TITLE
All custom containers lost. 

### ISSUE THREAD

**Issue by klint** [mozilla/multi-account-containers#978] opened 2017-11-17 12:52 UTC
I just have noticed that all my non-default containers had disappeared. 
What could be the cause for that?

The only actions I can remember recently are upgrading from 57 to 58beta, and also I deactivated/activated all my addons to chase a compatibility issus between 2 addons (not related to containers).
Thanks

**Comment by groovecoder** [comment] 2017-11-17 14:53
Think this is a dupe of https://github.com/mozilla/multi-account-containers/issues/949

**Closed by groovecoder** 2017-11-17 14:53 UTC
Labels: duplicate
