### ISSUE TITLE
Feature Request: Set Homepage per Container 

### ISSUE THREAD

**Issue by cutiekeek** [mozilla/multi-account-containers#2055] opened 2021-05-19 20:24 UTC
It would be nice to be able to set a specific homepage per container. Right now using bookmarks can somewhat have similar workflows but it's still pretty manual vs clicking on a container and having a default page open.

**Comment by dannycolin** [comment] 2022-12-28 01:13
Duplicate of #1289

**Closed by dannycolin** 2022-12-28 01:13 UTC
