### ISSUE TITLE
Panel paths are incorrectly populated

### ISSUE THREAD

**Issue by ahzaz** [mozilla/multi-account-containers#1941] opened 2021-01-06 20:33 UTC
- Multi-Account Containers Version:  7.1.0
- Operating System + Version: Windows 10
- Firefox Version: 84.0.1

### Actual behavior
After going back between "Container Info" and "Container Edit" Panel, The back arrow needs to be clicks a lot of times to transition from Edit to Info panel.

### Expected behavior
Panel transition should be done in one click.

### Steps to reproduce
1. Click container icon and click arrow right on any container
2. Click Manage This Container
3. Click Back arrow at top left
4. Repeat 2 and 3 for few times
5. Each time clicks required to go back increases by 1

### Notes
The issue is probably [here in popup.js](https://github.com/mozilla/multi-account-containers/blob/f0afc0da36d8bd217ef5db89c39f04cb0e27379d/src/js/popup.js#L814) where handlers are never removed and are executed multiple times.

**Comment by dannycolin** [comment] 2022-07-22 01:25
This looks like a duplicate of #1857 so closing. If you still experience this issue, please upvote or comment on the other bug report.

**Closed by dannycolin** 2022-07-22 01:25 UTC
Labels: bug, Container Panel
