### ISSUE TITLE
Feature Request: Assign open tab to a different container

### ISSUE THREAD

**Issue by sahil48** [mozilla/multi-account-containers#907] opened 2017-10-12 15:51 UTC
It would be great to be able to assign a opened tab or multiple opened tabs to a different container.

**Comment by SoftVision-EmilPasca** [comment] 2017-10-12 16:52
Hi @sahil48, thanks for reporting this, however, this issue is a dupe of https://github.com/mozilla/multi-account-containers/issues/311, please go there if you like to read more about this.

**Closed by SoftVision-EmilPasca** 2017-10-12 16:52 UTC
