### ISSUE TITLE
Cannot add a specific domain to a specific container

### ISSUE THREAD

**Issue by echoleaf** [mozilla/multi-account-containers#1619] opened 2020-01-21 18:39 UTC
For whatever reason, app.later.com can be opened in a Facebook container but when I got to assign it to the container, the checkbox only says 'Always open in Default.'

Why isn't there a way to manually add a domain to a container, instead of requiring a bunch of clicks?

**Comment by B00ze64** [comment] 2020-07-01 02:57
Lowest Common Denominator I guess? I also require this feature, doing this manually and trying to sync settings between profiles is such a chore! Where's my Listview in about:preferences?! More resources need to be added to this, there's 422 bugs opened!

**Comment by dannycolin** [comment] 2022-10-11 01:00
duplicate of #1670

**Closed by dannycolin** 2022-10-11 01:00 UTC
Labels: Feature Request
