### ISSUE TITLE
Screen to confirm opening website cannot get website icon and does not load properly

### ISSUE THREAD

**Issue by rgamici** [mozilla/multi-account-containers#1158] opened 2018-03-21 20:50 UTC
The confirmation page to assign a website to a permanent container sometimes cannot get the site icon.
In that case, it never finish loading and consume half of my CPU time, while it is open, even if I stop loading the page. 
The source code shows that it assigned "moz-icon://goat?size=16" as the icon, ~~and that might have been the problem~~. 
Update: It is loading the icon, it is just looks like it is cropped.
I noticed it for gmail and facebook.

It does not have behave like that when the website icon is loaded.
The original website icon is correctly shown on the bookmark toolbar and on the tab, but is not shown on the menu to edit the containers.
"moz-icon://goat?size=16" loads normally on a new tab.

I'm currently using FF 61.0a1 (2018-03-20) (64-bit) on linux.
I'm not sure when it started, because I was forcing it to skip the confirmation page.
But I remember having the same problems a few weeks ago.

**Comment by stoically** [comment] 2018-03-22 12:45
I can't reproduce with either gmail or facebook in a default profile, in both cases the favicons are loaded instantly and correctly with the latest Nightly (61.0a1).

However, I'm able to reproduce with `privacy.trackingprotection.enabled` set to `true`. Do you maybe have this configuration active? In that case it would be a duplicate of #1143

**Comment by rgamici** [comment] 2018-03-22 16:23
Yes, it is enabled.
Changing privacy.trackingprotection.enabled to false solves the problem.

**Comment by stoically** [comment] 2018-03-22 16:26
In this case the solution would be https://bugzilla.mozilla.org/show_bug.cgi?id=1315616 as mentioned in #1143

**Closed by stoically** 2018-03-22 16:26 UTC
Labels: needs STR
