### ISSUE TITLE
Open an entire window in a container

### ISSUE THREAD

**Issue by Dr-Ari-Gami** [mozilla/multi-account-containers#1878] opened 2020-09-29 17:09 UTC
I think the ability to open an entire window in a container would be nice. Have another option listed in [this menu](https://i.imgur.com/ZhCHhMQ.png) or something. 

Not much to explain about this, just the ability to assign or create a new window with a container, along with the container tabs.

**Comment by dylanmorroll** [comment] 2021-02-04 12:00
I would also love to see this! With the purpose of this extension to be a replacement to using different browsers, it would be great if I could have a whole window with it's tabs all in a specific container, then when I finish work I can just close that containered window and open it again the next day. Rather than at the end of the day having to reopen any tabs that aren't in a container into the right one and then close it all. Would be a nice feature!

**Comment by grahamperrin** [comment] 2021-04-27 20:39
@Dr-Ari-Gami this might be a duplicate of #943

If so, please close. Thank you.

**Closed** 2021-04-27 20:42 UTC

**Comment by grahamperrin** [comment] 2021-04-28 00:04
Thanks!
