### ISSUE TITLE
Enhancement - Containers sites detail.

### ISSUE THREAD

**Issue by NessunoIM** [mozilla/multi-account-containers#1408] opened 2019-05-08 15:26 UTC
Is possible to have a page or a window in this extension where I can view, for every container, what sites I added ed eventually modify directly it (adding or removing sites).

**Comment by stoically** [comment] 2019-05-08 15:40
Duplicate of https://github.com/mozilla/multi-account-containers/issues/1363 - please vote there, thanks!

**Closed by stoically** 2019-05-08 15:40 UTC
