### ISSUE TITLE
Feature Request: Be able to assign urls to containers without visiting that specific url

### ISSUE THREAD

**Issue by adamjc** [mozilla/multi-account-containers#1602] opened 2019-12-10 19:51 UTC
I would love to be able to assign a url to a container without having visited that url. 

I have a very specific use case that containers would be amazing for: I work as an software engineer that has to sign into multiple accounts that are redirected to one individual url

these logins are session based, so the only way to use multiple accounts is to have containers or private windows for each one. 

i.e.
`https://cloud-provider/account/12345` 302s to: `https://cloud-provider/dashboard` (logged into account 12345)
`https://cloud-provider/account/56789` 302s to: `https://cloud-provider/dashboard` (logged into account 56789)
`https://cloud-provider/account/abcde` 302s to: `https://cloud-provider/dashboard` (logged into abcde)

this redirect happens on the server, there is no way for me to assign `https://cloud-provider/account/12345` to a container

Is there appetite for this feature? I will happily make a PR if there is 🙃

**Comment by kendallcorner** [comment] 2019-12-11 15:53
Hi. This looks like a duplicate of #1227. Please vote (:+1:) or discuss on that issue to show your interest. I'll close this, but feel free to request a reopen if you think it's a different issue

**Comment by kendallcorner** [comment] 2019-12-11 15:54
Also, I think #1227 proves there is appetite, and PRs are always welcome. Thanks!

**Closed by kendallcorner** 2019-12-11 15:53 UTC

**Comment by adamjc** [comment] 2019-12-11 16:37
Thanks for the speedy response!
