### ISSUE TITLE
Different containers should have seperated browsing history

### ISSUE THREAD

**Issue by garywill** [mozilla/multi-account-containers#1544] opened 2019-10-20 12:29 UTC
- Multi-Account Containers Version: 6.1.1
- Operating System + Version: linux 
- Firefox Version: 68
- Other installed Add-ons + Version + Enabled/Disabled-Status:

### Actual behavior
On homepage's "Top Sites" section and toolbar's "history", shows our browsing history. You browse a URL in one container and it's showed in all containers.

### Expected behavior
In one container won't see others' history.

### Notes
"History" section shows other container's URL will mislead users to click, then the URL is opened in a container that we don't mean to use.

**Comment by silvererudite** [comment] 2019-10-21 07:23
Would be a nice feature for **truly isolating** everything.  @maxxcrawford and @groovecoder would like to work on it.
Any idea how to approach it?

**Comment by alittlebitofit** [comment] 2019-10-28 05:33
Yes, I second this too. Is this being implemented?

**Comment by silvererudite** [comment] 2019-10-28 08:34
Oooh @alittlebitofit. Yes I'm trying to implement this trying things here and there. Looks like I need more research and trials. love your idea as well.

**Comment by alittlebitofit** [comment] 2019-10-28 15:12
Oh wow thanks for the encouragement! I'm looking forward to it :D

**Comment by kendallcorner** [comment] 2019-12-04 20:37
This is a duplicate of #1233. Please vote or discuss on that issue. Also see this comment: https://github.com/mozilla/multi-account-containers/issues/1386#issuecomment-489316595

**Closed by kendallcorner** 2019-12-04 20:37 UTC

**Comment by kendallcorner** [comment] 2019-12-05 20:56
Original is actually #537
