### ISSUE TITLE
Feature request for moving container position in list

### ISSUE THREAD

**Issue by xRiot** [mozilla/multi-account-containers#1438] opened 2019-06-12 09:27 UTC
- Multi-Account Containers Version: 6.1.0
- Operating System + Version: Debian 10 Buster (64bit)
- Firefox Version: 68.0b9 (64-bit)
- Other installed Add-ons + Version + Enabled/Disabled-Status: Dark Reader / Firefox DevTools ADB Extension / Floating Player / Hide Tabs / React Developer Tools / uBlock Origin / User-Agent Switcher / Simple Tab Groups (disabled)

### Actual behavior
There is no option to move around container group order when you go to Navigation bar > click on Addon's icon > `Edit Containers`

### Expected behavior
It would be useful if there could be a way of moving each container groups' position in the list with mouse.

### Steps to reproduce
1. Click on addon's icon in the navigation bar.
2. Select `Edit Containers`
3. Try to move the containers with mouse, nothing happens.

### Notes
This is a feature request, in the meantime, is there a different way to rearrange the container groups order, for instance though a config file or similar?

Thanks.

**Comment by falolaf** [comment] 2019-06-13 07:14
Have a look here:
https://github.com/mozilla/multi-account-containers/issues/1208

**Comment by kendallcorner** [comment] 2019-12-09 15:49
Hi. This looks like a duplicate of #330. Please vote (:+1:) or discuss on that issue to show your interest. I'll close this, but feel free to request a reopen if you think it's a different issue.

**Closed by kendallcorner** 2019-12-09 15:49 UTC
