### ISSUE TITLE
Feature request: Ability to manually add sites to a container through Manage Site List

### ISSUE THREAD

**Issue by tomaspapi** [mozilla/multi-account-containers#1830] opened 2020-07-23 18:14 UTC
Creating this issue as discussed with @maxxcrawford on #1784. 

**Feature request:**

Add ability to manually add sites to a container through Manage Site List

**Context:**

Right now, if you go to `Manage Containers > [Select Container] > Manage Site List`, you can only delete sites but not add new ones by just typing them there.

**Benefit:**

- If we could add sites this way, we could whitelist domains that are only accessed momentarily as part of a redirection flow which cannot be included in any container otherwise. (i.e. URL shorteners such as bitly, googl, etc)
- It'd also be helpful in case we want to add a domain just in case we are redirected to it —so it doesn't get mixed with other sites— but that we don't necessarily want to have to visit first in order to isolate it in a container.

**Upgrade idea:**

On top of being able to write down a domain in order to isolate it to a container, include the ability to write `*.domain.com` to include all possible subdomains so they default to the same container.

Thank you!

**Comment by dehghani-mehdi** [comment] 2020-07-24 04:24
Where this data is stored? I mean is there any way to do this manually?

**Comment by EnronEvolved** [comment] 2020-07-26 18:54
Further to this: the ability to export and import site lists would be a useful feature, as an alternative to synchronisation through a Firefox account. It would also make setting up containers for specific websites and domains (Google, Twitter, etc.) that much easier.

**Comment by EnronEvolved** [comment] 2020-07-27 04:26
There is an issue (#1670) which is practically identical to this issue, with an associated pull request (#1688) to implement it. I found a pull request, #1500, that implements the wildcard subdomain idea.

It shouldn't come as a surprise that this has been thought of before, but it seems like the PRs are stuck behind reviews and merge conflicts.

**Comment by AdamJel** [comment] 2020-08-07 10:40
Further to this:
The settings of 'limit to designated sites' in NOT currently synced. The site list is, but it is needed to tick the box again on new instance of Firefox. It would be very useful to synchronize this as well.
And I support the idea of having option to import/export/ settings = managing it by file, which may then be on a repo and thus having the ability to declaratively set the state. I already have quite a number of containers, so having the option to manage it by script (json) and having it back on gitxxx would be nice.

**Comment by groovecoder** [comment] 2020-08-12 19:17
Marking as dupe of #1670.

**Comment by groovecoder** [comment] 2020-08-12 19:18
Please upvote and comment on #1670

**Closed by groovecoder** 2020-08-12 19:18 UTC
Labels: duplicate
