### ISSUE TITLE
Sites deleted from container assignments are restored by Synch

### ISSUE THREAD

**Issue by CakeOD36** [mozilla/multi-account-containers#2527] opened 2023-04-15 00:43 UTC
### Before submitting a bug report

- [X] I updated to the latest version of Multi-Account Container and tested if I can reproduce the issue
- [X] I searched for existing reports to see if it hasn't already been reported

### Step to reproduce

1.  Assign a site to always open in a certain container.
2.  Remove the site from the container assignment

### Actual behavior

Site is restored after synch

### Expected behavior

Removal of site container entry

**Comment by TheNightRider12** [comment] 2023-04-17 06:17
I have had this very same issue for a long time. I have just resorted to not syncing my containers. I have opened an issue similar to this one awhile back. Didn't get any response or anything.

**Comment by ilyak83** [comment] 2023-04-18 06:17
I have exactly the same issue. And this bug was exist an about one year ago, I just ignored it.

**Comment by dannycolin** [comment] 2023-04-22 20:50
duplicate of #2110

**Closed by dannycolin** 2023-04-22 20:50 UTC
Labels: bug
