### ISSUE TITLE
Shifting container context causes new background tab to steal focus

### ISSUE THREAD

**Issue by Alamei** [mozilla/multi-account-containers#897] opened 2017-10-06 21:53 UTC
While you're browsing in any container (including the default), if you open link for a domain that is set to always open in a different container in a new background tab, that tab immediately moves to the foreground. If this behavior is intended, it would be nice to have an option to disable it and let new tabs open in the background even when they're changing container contexts.

In case this issue is platform-specific, I'm experiencing it running 57.0b6 (both dev and non-dev editions) on a variety of Windows machines running 8/8.1/10.

**Comment by jonathanKingston** [comment] 2017-10-09 13:28
Duplicate of #442.

**Closed by jonathanKingston** 2017-10-09 13:28 UTC
Labels: bug, duplicate
