### ISSUE TITLE
"Always open in <container>" should respect URL path

### ISSUE THREAD

**Issue by mkurz** [mozilla/multi-account-containers#976] opened 2017-11-17 10:59 UTC
I want to sign in to Google Maps with a different account than to google.com:
https://www.google.at/maps/
https://www.google.at/

However as soon as I run "Always open in \<container>" for the `/maps/` path also the whole domain gets locked into that container. I also tried the lock google.at into a different container afterwards, however that also changes the `/maps/` container as well again...

**Comment by erjiang** [comment] 2017-11-30 01:19
How do you propose users choose between whether they want to create a rule for the entire domain or just for a subdirectory?

**Comment by brunoais** [comment] 2017-11-30 08:40
Allow the creation of rules using pattern matching while providing some
defaults.
Allow specifying patterns in the "office way" (using "*", "?" and "!") and
regex for the more advanced people.

Put that option available in an options page (accessible in the extension's
popup page) by a button/link on the element that contains the container's
name and color.
Pressing the button or link will open a popin that will allow the user to
insert the rules he wants to insert.
I suggest having a whitelist and a blacklist.
Blacklist has priority towards whitelist.

By default, both are empty, which means it matches no urls.
Adding url patterns to the whitelist will make them match (and select that
container as the one).
Adding url patterns to the blacklist will make them match and make that tab
not be placed in that container (by this system), regardless if they
matched in the whitelist.

Make it so the user can specify multiple rules that add to each other using
an OR (for example, one per line).

Any opinions?

**Comment by groovecoder** [comment] 2017-12-05 19:06
See also https://github.com/mozilla/multi-account-containers/issues/473

**Comment by mkurz** [comment] 2017-12-05 19:14
@groovecoder What does the assignment label mean?

**Comment by groovecoder** [comment] 2017-12-05 19:59
Just that this issue is related to the site assignment feature.

**Comment by jakecoppinger** [comment] 2017-12-21 21:01
Functioning work around I found after struggling with this:
- Disable WiFi/network
- Open tab of the container of your choosing
- Open maps.google.com, it will error and keep the domain
- Go Containers menu -> `Always Open in <Your Container>` (don't worry about the Error page title)
- Re-enable network

Now https://www.google.com/search?q=test will stay in default container, and maps.google.com will _change container, and then redirect_ to https://www.google.com/maps!

**Comment by mkurz** [comment] 2017-12-21 21:21
@jakecoppinger Unbelievable, it's working! Thank you very much for sharing this workaround! I am curious, how did you find out?

**Comment by jakecoppinger** [comment] 2017-12-21 21:38
Oh wow, first time I've got a thumbs up to a comment! Glad to have helped!

@mkurz I started playing around with containers this evening and I could see that the `Always Open In...` mapping of URLs to containers was storing the redirected domain. I tried hitting maps.google.com and stopping the page load as fast as I could so that I could store the different base URL but I couldn't stop it in time. I tried disabling my WiFi to stop the redirect as I couldn't find network throttling in the devtools and the error page title doesn't matter, so it seems that the base URL is the key rather than the page title.

I don't think it would work for differentiating http://example.com/test1 and http://example.com/test2 as these have the same base URL, but it should differentiate http://example.com/test1, http://test1.example.com and http://test2.example.com

**Comment by mkurz** [comment] 2017-12-21 21:47
@jakecoppinger Thanks!

I just found out we could probably also simply edit the file `~/.mozilla/firefox/<profile-id>/browser-extension-data/@testpilot-containers/storage.js` by hand to achieve a desired behaviour. Seems that is the file which stores all the container data.

**Comment by groovecoder** [comment] 2018-01-09 18:44
This is a duplicate of https://github.com/mozilla/multi-account-containers/issues/691

**Closed by groovecoder** 2018-01-09 18:44 UTC
Labels: duplicate, site assignment

**Comment by GJRobert** [comment] 2018-12-11 09:56
> @jakecoppinger Thanks!
> 
> I just found out we could probably also simply edit the file `~/.mozilla/firefox/<profile-id>/browser-extension-data/@testpilot-containers/storage.js` by hand to achieve a desired behaviour. Seems that is the file which stores all the container data.

Editing this file directly works (must quit the browser first), thanks. For example, find the following string in that file like:
```siteContainerMap@@_github.com```
and append subdirectories or other part of the URL to be like
```siteContainerMap@@_github.com/mozilla/multi-account-containers/issues/473```
so to always open this issue in a certain container, while keeping other github.com URLs unset.

**Comment by StefanSchoof** [comment] 2019-11-13 11:55
For things like http://example.com/test1 and http://example.com/test2 you can use the [Containerise](https://addons.mozilla.org/en-US/firefox/addon/containerise/) addon to configure this. (found in https://github.com/mozilla/multi-account-containers/issues/473#issuecomment-524319820)

**Comment by GJRobert** [comment] 2019-11-15 06:22
> For things like http://example.com/test1 and http://example.com/test2 you can use the [Containerise](https://addons.mozilla.org/en-US/firefox/addon/containerise/) addon to configure this. (found in [#473 (comment)](https://github.com/mozilla/multi-account-containers/issues/473#issuecomment-524319820))

Hi,
I haven't been able to make the mentioned behavior work in my Firefox 68 with Containerise installed. Could you?

**Comment by carlos-delamo** [comment] 2021-02-22 13:13
> 
> 
> > For things like http://example.com/test1 and http://example.com/test2 you can use the [Containerise](https://addons.mozilla.org/en-US/firefox/addon/containerise/) addon to configure this. (found in [#473 (comment)](https://github.com/mozilla/multi-account-containers/issues/473#issuecomment-524319820))
> 
> Hi,
> I haven't been able to make the mentioned behavior work in my Firefox 68 with Containerise installed. Could you?

Same issue here. I tried with containerise extension with no luck. Any updates?

**Comment by GJRobert** [comment] 2021-02-22 13:53
> > > For things like http://example.com/test1 and http://example.com/test2 you can use the [Containerise](https://addons.mozilla.org/en-US/firefox/addon/containerise/) addon to configure this. (found in [#473 (comment)](https://github.com/mozilla/multi-account-containers/issues/473#issuecomment-524319820))
> > 
> > 
> > Hi,
> > I haven't been able to make the mentioned behavior work in my Firefox 68 with Containerise installed. Could you?
> 
> Same issue here. I tried with containerise extension with no luck. Any updates?

I use https://addons.mozilla.org/en-US/firefox/addon/container-bookmarks/ instead. Bit tricky but works.

**Comment by mtalexan** [comment] 2021-12-28 02:51
> > > For things like http://example.com/test1 and http://example.com/test2 you can use the [Containerise](https://addons.mozilla.org/en-US/firefox/addon/containerise/) addon to configure this. (found in [#473 (comment)](https://github.com/mozilla/multi-account-containers/issues/473#issuecomment-524319820))
> > 
> > 
> > Hi,
> > I haven't been able to make the mentioned behavior work in my Firefox 68 with Containerise installed. Could you?
> 
> Same issue here. I tried with containerise extension with no luck. Any updates?

Old response, but the Containerise add-on is working fine for me in the latest version of Firefox (95.0.2).

The big thing to note is that you have to preface glob patters with `!` and no whitespace before the pattern, and regex patterns have to be prefaced with `@` and you have to carfully backslash escape any literal dots in the (sub)domains.

The GUI isn't the best with Containerise, but I tested it and the glob and literal patterns work for me with domains like `play.hbomax.com` (matched by pattern `!*.hbomax.com`) and `disneyplus.com` (matched by pattern `disneyplus.com`).
