### ISSUE TITLE
Support wildcards (*)

### ISSUE THREAD

**Issue by BPower0036** [mozilla/multi-account-containers#2279] opened 2022-02-01 07:53 UTC
- Multi-Account Containers Version: 8.0.4
- Operating System + Version: Windows 10
- Firefox Version: 96.0.3
- Other installed Add-ons + Version + Enabled/Disabled-Status:
![afbeelding](https://user-images.githubusercontent.com/80090789/151930204-cde3592d-1bd9-46a4-a257-6c0a55cc7db0.png)

### Actual behavior
When you want `Google` to open always in a container, you have now to set every subdomain.
![afbeelding](https://user-images.githubusercontent.com/80090789/151930477-7ec394d7-262b-4ded-a5c7-f1b72e57e1fe.png)
![afbeelding](https://user-images.githubusercontent.com/80090789/151930562-6fc3d37e-4ea7-41a2-bca3-b181cc4cc1d5.png)

### Expected behavior
It would be much more conveniant to have the possibility to use wildcards.
So you can do his all with one rule `*.google.com`

### Steps to reproduce
1. Open `google.com` when you have no internet (to prevent redirects)
2. See in the address bar `https://google.com/`
3. Select `Always Open This Site in...` in extension popup.
4. When you have internet, open `mail.google.com` or `earth.google.com`
5. the extension does not open the set container for `google.com`

**Comment by BPower0036** [comment] 2022-02-04 10:44
@lesleyjanenorton @mozilla Can you look at this proposal

**Comment by achernyakevich-sc** [comment] 2022-02-05 10:37
@BPower0036 I'm not developer of this add-on but I have seen many similar request... I got impression that the development team is concentrated on core functionality only. The request you did will require a lot of efforts to implement and much more in the future to maintain. So I expect it will be never implemented of this add-on. MAC is designed so that it could be utilized by other add-ons.

Probably https://addons.mozilla.org/en-US/firefox/addon/containerise/ could help you as one of the features they have could match to what you need. :)

**Comment by BPower0036** [comment] 2022-02-07 10:39
@achernyakevich-sc The only problem with this extension (https://addons.mozilla.org/en-US/firefox/addon/containerise/) is that you cannot restrict curtain websites to curtain containers, like `google.com` must open in the container `google` but when entering `twitter.com` he must exist that container in stead of staying in it.

**Comment by achernyakevich-sc** [comment] 2022-02-07 13:00
@BPower0036 As far as I see this case is a part of MAC itself. I have defined URLA that it should be **always** open in the Container A and URLB - **always* in the container B. When page behind URLA is open in the container A and that has link that should open URLB then in my browser it cause opening URLB in the the container B in new browser's tab.

**Comment by BPower0036** [comment] 2022-02-07 15:56
@achernyakevich-sc but what if you haven't defined URL C and you want it not to open in Container A?

**Comment by achernyakevich-sc** [comment] 2022-02-07 17:14
@BPower0036 If there is no any rule that will force to **always** open some URL in some particular container then it reasonably will stay in the same container as source page/tab was open in. It is reasonable behavior. Because you can't define rule for every possible URL that exists in the Internet.

We just need to use MAC taking into account this kind functionality provided by the Add-On. If you have other use case then probably you need to use MAC different way or use something other than MAC. For example, functionality for tabs grouping or sticking container to group of tabs is well supported in the Simple Tab Groups add-on.

Probably if you will describe you use case in more details (including what goals you try to achieve) I will be able to propose a solution for you. :)

**Comment by BPower0036** [comment] 2022-02-08 06:43
@achernyakevich-sc I want `mail.google.com` to open in Container `Google`, but when I open URLs from emails I want to open them in **_any_** container I have except the `Google` container; I want the `Google` container **only** for Google and thus want to prohibited _**whatever**_ website to open in the `Google` container.

**Comment by groovecoder** [comment] 2022-02-09 20:19
I think this is a dupe of https://github.com/mozilla/multi-account-containers/issues/473. Please upvote there.

**Closed by groovecoder** 2022-02-09 20:19 UTC

**Comment by achernyakevich-sc** [comment] 2022-02-10 07:13
> @achernyakevich-sc I want `mail.google.com` to open in Container `Google`, but when I open URLs from emails I want to open them in **_any_** container I have except the `Google` container; I want the `Google` container **only** for Google and thus want to prohibited _**whatever**_ website to open in the `Google` container.

@BPower0036 I have thought about your use case. It looks that it is completely different than MAC was designed for. And even Containerise will not help. Because both of them **select a container** to open URL by positive matching. What you ask - **preventing opening in the container**.

Sorry, but it looks like that MAC developers will never implement it - too complicate and expensive for so rare case. Though you could try to find somebody who could implement for you as a separate add-on for money.
