### ISSUE TITLE
"Open this site in your assigned container" dialogue fails to action on clicking "Open in xxx container"

### ISSUE THREAD

**Issue by geotheory** [mozilla/multi-account-containers#1365] opened 2019-04-03 10:12 UTC
- Is "Firefox will: Never remember history" in the Firefox Preferences/Options under "Privacy & Security > History" selected? Yes/No:  NO
- Are you using Firefox in a Private Window? Yes/No:  NO
- Can you see a grayed out but ticked Checkbox with the description "Enable Container Tabs" in the Firefox Preferences/Options under "Tabs"? Yes/No:  YES
- Multi-Account Containers Version: 6.1.0
- Operating System + Version:  macOS 10.14.3
- Firefox Version: 67.0b7
- Other installed Add-ons + Version + Enabled/Disabled-Status:

Cookie AutoDelete	3.0.1	true	CookieAutoDelete@kennydo.com
Firefox Multi-Account Containers	6.1.0	true	@testpilot-containers
LastPass: Free Password Manager	4.26.0.4	true	support@lastpass.com
Neat URL	4.1.5	true	neaturl@hugsmile.eu
Search by Image	1.19.0	true	{2e5ff8c8-32fe-46d0-9fc8-6b8986621f3c}
Simple Translate	2.0.4	true	simple-translate@sienori
uBlock Origin	1.18.6	true	uBlock0@raymondhill.net
Wayback Machine	1.8.6	true	wayback_machine@mozilla.org
uMatrix	1.3.16	false	uMatrix@raymondhill.net

### Actual behavior

In the `Open this site in your assigned container` dialogue, clicking `Open in xxx container` has no effect.

### Expected behavior

- should open page in specified container

### Steps to reproduce
1. tick the box to always open site in this container. 
2. open site from another container and reach the `Open this site in your assigned container` dialogue
3. click `Open in xxx container`
- Nothing happens

### Notes
..

**Comment by stoically** [comment] 2019-04-03 10:51
A workaround is to not click on the bold text on the button, until #1350 gets released.

Duplicate of #1331

**Closed by stoically** 2019-04-03 10:51 UTC
