### ISSUE TITLE
Microsoft Outlook Does Not Work in a Container

### ISSUE THREAD

**Issue by Tater-K7S5A** [mozilla/multi-account-containers#1925] opened 2020-12-20 14:47 UTC
- Multi-Account Containers Version:  7.1.0
- Operating System + Version:  Linux Mint 20 Cinnamon
- Firefox Version:  84.0
- Other installed Add-ons + Version + Enabled/Disabled-Status: 
Bitwarden - Free Password Manager	extension	1.47.1	true
Decentraleyes	extension	2.0.15	true
DuckDuckGo	extension	1.0	true	
Facebook Container	extension	2.1.2	true	
Firefox Multi-Account Containers	extension	7.1.0	true	
Startpage	extension	1.0	true	
uBlock Origin	extension	1.31.0	true	
Wikipedia (en)	extension	1.1	true	
Yahoo!	extension	1.0	true	

### Actual behavior

I am trying to log into Outlook.com in a container.  Seven new tabs open one after the other with the final tab containing the Microsoft message "Something went wrong and we can't sign you in right now. Please try again later.
The Microsoft account login server has detected too many repeated authentication attempts. Please wait a moment and try again."

It's like Outlook doesn't want to be contained.

### Expected behavior
Outlook login and use works inside the container.

### Steps to reproduce
1.  Set up outlook.live.com to open in its own container.
2. Go to outlook.live.com
3. Click "Sign in"
4. Watch a new tab labeled "Continue" appear.  Then another, and another.  The final tab has the error message.

### Notes
Without the container the site works as it is supposed to.

**Comment by securingmom** [comment] 2021-01-01 20:59
Cannot replicate.

**Comment by Tater-K7S5A** [comment] 2021-01-02 17:48
I still have the problem on the Mint 20 system as reported.  After I saw your message I confirmed it was still not working. 

I then booted into Solus Budgie and attempted to replicate the issue with Firefox 84.0 that I have on that system.  I cannot replicate the problem there.  I am baffled as to what the issue is with Firefox on Mint 20.  I will see about reinstalling Firefox on that system and see if that "fixes" the issue.

**Comment by filcode** [comment] 2021-04-30 13:53
> * Multi-Account Containers Version:  7.1.0
> * Operating System + Version:  Linux Mint 20 Cinnamon
> * Firefox Version:  84.0
> * Other installed Add-ons + Version + Enabled/Disabled-Status:
>   Bitwarden - Free Password Manager	extension	1.47.1	true
>   Decentraleyes	extension	2.0.15	true
>   DuckDuckGo	extension	1.0	true
>   Facebook Container	extension	2.1.2	true
>   Firefox Multi-Account Containers	extension	7.1.0	true
>   Startpage	extension	1.0	true
>   uBlock Origin	extension	1.31.0	true
>   Wikipedia (en)	extension	1.1	true
>   Yahoo!	extension	1.0	true
> 
> ### Actual behavior
> I am trying to log into Outlook.com in a container. Seven new tabs open one after the other with the final tab containing the Microsoft message "Something went wrong and we can't sign you in right now. Please try again later.
> The Microsoft account login server has detected too many repeated authentication attempts. Please wait a moment and try again."
> 
> It's like Outlook doesn't want to be contained.
> 
> ### Expected behavior
> Outlook login and use works inside the container.
> 
> ### Steps to reproduce
> 1. Set up outlook.live.com to open in its own container.
> 2. Go to outlook.live.com
> 3. Click "Sign in"
> 4. Watch a new tab labeled "Continue" appear.  Then another, and another.  The final tab has the error message.
> 
> ### Notes
> Without the container the site works as it is supposed to.

I can confirm that Outlook still do not work with firefox containers and with temporary container. Everything updated and in latests versions in this date!

**Comment by Tater-K7S5A** [comment] 2021-06-27 13:54
I have been playing around with the containers and have figured out that Outlook will open in the "Personal" container but not the container I created for it.  I tried some other included containers and found that Outlook would open in them.  

I then deleted the container I had made for Outlook and created a new one.  Outlook opens in the new container without incident.  There must have been something wrong with the original container.  

filcode - Try deleting and recreating the container.

**Comment by gtnbssn** [comment] 2021-07-05 09:30
I am having a similar issue, posting here in case it helps.

Firefox 89.0.2 (64-bit) on Ubuntu 20.04.2

I have a work container with my personal work email and a team container with the team's shared email. It was working last week and i could use both mailboxes in parallel.

Today, when i open the team container, outlook loads indefinitely, and ends up opening another work container with my personal email and never displaying the shared email.

**Comment by filcode** [comment] 2021-07-17 15:50
@Tater-K7S5A I always create my own containers. Default containers are immediately deleted after install Firefox Multi-Account Containers. For Outlook I have no specific container because I rarely use Outlook. However, because I also use temporary containers, Outlook do not open with temporary containers. I have to try assigning Outlook to a specific container and see if I can open it.

**Comment by filcode** [comment] 2021-07-17 16:02
@gtnbssn Correct, Outlook loads indefinitely. I have a specific container for Google and when I open Youtube on that container sometimes is necessary several Tabs to open it.

**Comment by unhammer** [comment] 2021-11-07 21:59
For me it says `emsg: UserHasNoMailboxAndNoLicenseAssignedError` if I try to assign it a container. Strangely I can log in with a Temporary Container from that addon.

**Comment by vtronko** [comment] 2022-09-19 07:36
Can confirm.

**Comment by dannycolin** [comment] 2022-12-29 02:58
Did you enable "Limit to Designated Sites" on your Outlook container?

**Comment by Tater-K7S5A** [comment] 2022-12-29 09:51
@dannycolin I had not.  I also haven't had the problem come back since I initiated this issue.

**Comment by dannycolin** [comment] 2022-12-30 05:33
Thanks. I'm going to close this issue then. 

If anyone else has an issue with Outlook, it's better to file a new report since it could be caused by something different than the original report.

**Closed by dannycolin** 2022-12-30 05:33 UTC
Labels: bug, Needs: Testing
