### ISSUE TITLE
Searching from the address bar doesn't work if websites is assigned to a container

### ISSUE THREAD

**Issue by Booteille** [mozilla/multi-account-containers#1886] opened 2020-10-06 15:08 UTC
_This is a copy of the issue I opened on [Searx repository](https://github.com/searx/searx/issues/2249)._

Hi.

As said in the title, with Firefox Multi-Account Containers extension enabled, searx does not work properly.

**What's happening**
If I am not focusing my Searx instance tab and if I try to make a search through Firefox address bar or Firefox search bar, the Searx instance opens but the search is not made. I just arrive on the Searx instance homepage.
However, once I am focusing the Searx instance tab, and if I try to make a search through the address bar or search bar of Firefox, the search is being made correctly.
If the tab is open but I am not focusing it, it does not work neither.

**How to reproduce**

1. Create a fresh Firefox instances (about:profiles) and launch Firefox with this profile
2. Go on a searx instance (I tried different instances but my reference instance will be searx.fmac.xyz/)
3. Add it as search engine (click on the three-dot menu, in address bar, then click on "add search engine")
4. (Optional) Enable it as default search engine in Firefox menus
5. Type `about:addons` in address bar and search for "multi".
6. Download Firefox Multi-Account Container extension
7. Manage containers to add a new one : Searx
8. Set up the searx instance (searx.fmac.xyz/) to always open through this container.
9. Make a search through Firefox search bar or address bar.

**Versions**
I used last Firefox Nightly build and Firefox 81.0. Both on Pop_OS 20.04.
As I said, I tried with fresh profiles with only multi-account containers open.

**More informations**
It's maybe not bound to Searx but Multi-Account containers seems to work properly with **every**
 other websites I am using since months. So that's why I opened this issue here.
I'll open another one on Multi-Account Containers.

**Comment by xpufx** [comment] 2022-08-07 09:48
I have this same issue. I think what's going on is the following. You'll be on a container tab that is not the one assigned to searx so when you enter a search term into the boxes it has to replace that tab with the one for searx. However it's going to the base url of searx instead of using the search logic that adds `search?q=searchquery`. (Or the POST equivalent)

This might be a security thing because otherwise it should have been a pretty common use case and be handled properly. Any comments?

**Comment by dannycolin** [comment] 2023-01-07 01:25
Following the Step-to-reproduce does open searchx in the right container for me. However, the search terms inserted in the address bar are lost during the process. 

This is most likely due to the fact that Multi-Account Container has to first close the none containerized New Tab and reopen Searchx in the assigned container. Since both environment are isolated from each others we're losing data in the transit.

I'm not 100% sure but I think this would need a change in Firefox itself (and how tab creation is handle by the WebExtension API). 

In the meantime, the only workaround I could see is to:
1. Open a new tab in the desired container
2. Visit Searchx
3. Search from the website form instead of the tabbar.

**Comment by dannycolin** [comment] 2023-01-07 01:36
Ah just found #1736. Closing as a duplicate of it.

**Closed by dannycolin** 2023-01-07 01:36 UTC
Labels: bug, Needs: Mozilla Central, Component: Site Compatibility
