### ISSUE TITLE
"Open this site in your assigned Container" page is missing its CSS

### ISSUE THREAD

**Issue by yllekz** [mozilla/multi-account-containers#2455] opened 2022-11-26 13:56 UTC
### Before submitting a bug report

- [X] I updated to the latest version of Multi-Account Container and tested if I can reproduce the issue
- [X] I searched for existing reports to see if it hasn't already been reported

### Step to reproduce

1. Open a site that is assigned to a specific container that triggers the "open this site in your assigned container?" prompt
2. Observe the design is malformed and it seems as if the CSS is missing

This is happening across multiple computers and OSes (Linux, Mac, Windows) on the latest version of Firefox with the latest version of this extension.

### Actual behavior

The page is functional but the CSS is missing
<img width="529" alt="image" src="https://user-images.githubusercontent.com/28446638/204092369-5f8fa842-4b04-4151-9b3e-c141a5c38ef5.png">

### Expected behavior

The prompt should be styled with the rest of Firefox as it has in previous versions.

**Comment by achernyakevich-sc** [comment] 2022-11-26 14:07
@yllekz Issue you created looks like a duplicate of already existing and discussed #2441. Especially [this comment](https://github.com/mozilla/multi-account-containers/issues/2441#issuecomment-1321151420) will be helpful.

Please, would you close this issue and follow discussion in the #2441.

**Comment by dannycolin** [comment] 2022-11-26 16:14
duplicate of #2441

**Closed by dannycolin** 2022-11-26 16:14 UTC
Labels: bug
