### ISSUE TITLE
Video tutorial is private on YouTube

### ISSUE THREAD

**Issue by Haltarys** [mozilla/multi-account-containers#2482] opened 2023-01-03 15:07 UTC
### Before submitting a bug report

- [X] I updated to the latest version of Multi-Account Container and tested if I can reproduce the issue
- [X] I searched for existing reports to see if it hasn't already been reported

### Step to reproduce

1. I went to the [addon page](https://addons.mozilla.org/en-US/firefox/addon/multi-account-containers/) and clicked on the link to the [video tutorial](https://www.youtube.com/watch?v=Gy7lyvAfOSw) but YouTube says it's private.

### Actual behavior

I can't watch the video tutorial on YouTube because it's private.

### Expected behavior

I should be able to watch the video tutorial on YouTube.

**Comment by dannycolin** [comment] 2023-01-03 15:37
Duplicate of #2443

**Closed by dannycolin** 2023-01-03 15:37 UTC
Labels: bug
