### ISSUE TITLE
"Error: Invalid tab ID" & "Id already exists" errors when moving tabs

### ISSUE THREAD

**Issue by kjozwiak** [mozilla/multi-account-containers#523] opened 2017-05-19 21:50 UTC
I'm not 100% sure if this is an issue, but we're getting the following errors in the browser console when moving tabs back into the main window once they've been detached:

```
Error: Invalid tab ID: 21  (unknown)
Id already exists ext-contextMenus.js:389
	set id chrome://browser/content/ext-contextMenus.js:389:13
	setProps chrome://browser/content/ext-contextMenus.js:356:7
	MenuItem chrome://browser/content/ext-contextMenus.js:337:3
	createInternal chrome://browser/content/ext-contextMenus.js:614:24
	bound createInternal self-hosted:913:17
	call resource://gre/modules/ExtensionParent.jsm:593:64
	receiveMessage resource://gre/modules/ExtensionParent.jsm:506:11
```

This is reproducible under 2.2.0 as well so it shouldn't be a blocker for the 2.3.0 release.

STR (example: [https://youtu.be/iBGcqpNAuEI](https://youtu.be/iBGcqpNAuEI))

* install fx and the containers experiment (2.2.0 or 2.3.0)
* once installed, open the browser console via `Hamburger Menu -> Developer -> Browser Console`
* open a new `about:newtab` and detach it from the main window
* attach the same window back into the main window and notice the error in the browser console
* open a new personal container and load facebook.com
* detach the personal container into it's own window and than move it back into the main window

**Comment by jonathanKingston** [comment] 2017-05-23 09:33
I have seen this loads, I think it might be one for @andymckay's squad. I might see what we are doing different, perhaps over calling the API.

**Comment by jonathanKingston** [comment] 2017-05-23 09:35
Related to: https://bugzilla.mozilla.org/show_bug.cgi?id=1365718

**Comment by jonathanKingston** [comment] 2017-05-26 10:01
Adding m-c Platform tag as likely only can be fixed there as a extension issue.

**Comment by kendallcorner** [comment] 2019-12-03 22:09
Hi. We're currently triaging the Multi Account Container issues. I can't reproduce this, so I'm going to close it. If you don't feel the underlying issue has been resolved, feel free to reopen it with updated steps to reproduce.

**Closed by kendallcorner** 2019-12-03 22:09 UTC
Labels: bug, needs: M-C Platform
