### ISSUE TITLE
[Feature Request] Allow "Delete cookies and site data when Firefox  is closed" to be container specific

### ISSUE THREAD

**Issue by ALink2ThePast** [mozilla/multi-account-containers#1382] opened 2019-04-24 16:07 UTC
Some of my containers are set for productive things I'd like to stay logged into, others I'd like to see automatically delete cookies and site data whenever I close FF.

The "Delete cookies and site data when Firefox  is closed" setting is great but it would be even better if I could have it only apply to site data associated with containers that I specify.

**Comment by falolaf** [comment] 2019-04-25 05:12
I belive that you can do that with:
https://addons.mozilla.org/sv-SE/firefox/addon/cookie-autodelete/
You can set it to be container aware and then add domains to the "greylist", per container. Hope that will work for you.

**Comment by kendallcorner** [comment] 2019-12-06 21:59
Hi. This looks like a duplicate of #48. Please vote (:+1:) or discuss on that issue to show your interest. I'll close this, but feel free to request a reopen if you think it's a different issue.

**Closed by kendallcorner** 2019-12-06 21:59 UTC
Labels: needs: M-C Platform
