### ISSUE TITLE
Containers in Right click menu are not sorted just like containers in "Manage Containers" list.

### ISSUE THREAD

**Issue by KrzysztofLesniczak** [mozilla/multi-account-containers#2106] opened 2021-08-16 10:20 UTC
Hi
I sorted Containers in right upper corner in addin "Manage containers" but still when I right click on some link, the list of containers visible for me to choose is not sorted like I did in "Manage Containers". It is just like it was on the beginiong, so most recent containers added, are on the botom. Is it possible to have same sort of contaziners in right click menu, just like in Managed Containers ?
I found CONTAINERS.json in FF profile, where We can see that each container has "userContextId" and most recent has highest ID and probably right click menu is sorted by this ID.

**Comment by carljdp** [comment] 2022-03-16 07:02
Possible duplicate of [#1958](https://github.com/mozilla/multi-account-containers/issues/1958)

**Comment by dannycolin** [comment] 2022-07-22 17:02
Duplicate of #1958

**Closed by dannycolin** 2022-07-22 17:02 UTC
