### ISSUE TITLE
[Question] Possible to make bookmark link to a contrainer?

### ISSUE THREAD

**Issue by neetch1** [mozilla/multi-account-containers#1868] opened 2020-09-18 15:18 UTC
Hey was wondering if you can somehow edit a bookmark to link to a certain container?

For example i dont wanna use the "always open in" feature on a youtube link but would use a second link for another youtube account without having to open another container first.

**Comment by mrshubhagarwal** [comment] 2020-09-18 15:44
You can make a Separate Container for the Second Youtube Account Login and enable the 'Enable Bookmark Menus' in the Add-On settings to directly open the bookmarked linked in the second container using right-click to select the container on the bookmark. 
![image](https://user-images.githubusercontent.com/64166355/93617639-dbe7eb80-f9f3-11ea-9677-1723733825ba.png)

**Comment by neetch1** [comment] 2020-09-19 13:19
Sweet didnt know thanks @mrshubhagarwal

**Comment by wAuner** [comment] 2020-11-24 13:28
I'm looking for the same feature, that would be really great.

**Comment by mrshubhagarwal** [comment] 2020-11-24 13:49
Try This. 👉 https://github.com/mozilla/multi-account-containers/issues/1868#issuecomment-694942687

**Comment by wAuner** [comment] 2020-11-24 13:55
@mrshubhagarwal I‘ve already tried that, but it‘s not really what OP is asking for. It‘s a workaround and helps, but I‘d like to have the feature to link a bookmark to a specific container.

**Comment by mrshubhagarwal** [comment] 2020-11-24 15:11
Oh Yeah. I get it now.

**Comment by siran** [comment] 2020-12-03 14:31
If always opening a site in a container is possible so should be opening a specific bookmark in a specfic container. There has to be a way to work around any possibly Firefox shortcomings, if any.

I'd like to link a bookmark to a container so I only have to click the bookmark and it open in the specified container.

The right-click on the bookmark is not enough for frequently used bookmarks (and dozens of containers).

**Comment by neetch1** [comment] 2021-01-20 15:57
> 
> 
> If always opening a site in a container is possible so should be opening a specific bookmark in a specfic container. There has to be a way to work around any possibly Firefox shortcomings, if any.
> 
> I'd like to link a bookmark to a container so I only have to click the bookmark and it open in the specified container.
> 
> The right-click on the bookmark is not enough for frequently used bookmarks (and dozens of containers).

Yes this is what i originally meant. Would be great to see this as a feature in the future or maybe theres already a workaround that anyone know about?

I have multible accounts on single specific sites that i use daily. Would be much easier to just have a bookmark for each account instead of having to create the container first.

**Comment by Sayrus** [comment] 2021-02-02 09:49
Indeed, it would be awesome to be able to set `Always open this bookmark (or bookmark folder) in X container`.

**Comment by grahamperrin** [comment] 2021-04-23 22:26
▶ 2017 issue #854, where there's a workaround. 

@neetch1 please close this triplicate issue; there will remain cross-references in #854. Thank you.

**Comment by dannycolin** [comment] 2022-12-06 05:10
Duplicate of #854

**Closed by dannycolin** 2022-12-06 05:10 UTC
