### ISSUE TITLE
After opening an empty container tab, context menu entry doesn't appear

### ISSUE THREAD

**Issue by n1trux** [mozilla/multi-account-containers#1067] opened 2018-01-06 10:11 UTC
When you click on the Add-On menu and select a container out of the list, a new container tab opens.

If you then input an URL and right-click on the newly visited site, the context menu entries for Multi-Account Containers is missing.

If you reload the page, the context menu entry will appear. If you re-visit the site in the same container, the menu entry will appear. It's only on first visit in a new container that the context menu entry doesn't appear.

**Comment by akkuraten** [comment] 2018-01-06 18:05
same story

**Comment by SoftVision-EmilPasca** [comment] 2018-01-08 07:50
Hy @n1trux, thanks for reporting this issue. Can you please give us more details regarding your environment, such as your operating system, FF version and other addons that you may have installed on your profile?

**Comment by n1trux** [comment] 2018-01-08 08:49
FF 59.0a1 (2018-01-04) (64-bit) nightly on Fedora Linux 27

Add-Ons:

Name | Version
--|--
Cookie AutoDelete | 2.0.1
Greasemonkey | 4.1
HTTPS Everywhere | 2017.12.6
Mailvelope | 02.01.01
Multi-Account Containers | 04.01.00
Open With | 7.0b12
Reddit Enhancement Suite | 05.08.06
snoozetabs | 1.0.20
Stylish - Custom themes for any website | 3.0.1
Test Pilot | 2.0.6-dev-d957066
uBlock Origin | 1.14.22

**Comment by SoftVision-EmilPasca** [comment] 2018-01-08 10:25
Seems that this issue is a duplicate of https://github.com/mozilla/multi-account-containers/issues/855.

**Closed by SoftVision-EmilPasca** 2018-01-08 10:25 UTC

**Comment by n1trux** [comment] 2018-01-08 12:51
No, it's not. I can open the context menu on the sites mentioned just fine.

Maybe it's the same root bug which is the cause of it, but the issue is certainly not.
