### ISSUE TITLE
changelog.md or GitHub releases

### ISSUE THREAD

**Issue by deepsweet** [mozilla/multi-account-containers#453] opened 2017-04-13 19:29 UTC
Hi.

It'd be really nice to see what's new in one structured place :+1: It's not so easy to wade through commits history.

**Comment by jonathanKingston** [comment] 2017-05-23 09:47
@groovecoder lets start this for the next release. Even if we just have a neatened version of:

```
git log --oneline HEAD...970a7ea4
```

**Comment by kendallcorner** [comment] 2019-12-03 21:35
Hi. We're currently triaging the Multi Account Container issues. It looks like we've added changelogs, so I'm going to close it. If you don't feel the underlying issue has been resolved, feel free to reopen it with updated steps to reproduce.

**Closed by kendallcorner** 2019-12-03 21:35 UTC
Labels: enhancement
