### ISSUE TITLE
Preferences regarding websites do not sync

### ISSUE THREAD

**Issue by ExoCode17** [mozilla/multi-account-containers#1506] opened 2019-09-27 06:54 UTC
It would be nice if containers and bookmarks preferences could sync between different PCs. 

I installed this extension and used it for a week or so on my new Firefox installation. It was almost mandatory as I was used to multi-persons Chrome. I spent a week customizing my bookmarks so they could open by default in a container instead of another. When I went to my laptop and installed FF to benefit from sync tho, it was a bit of a disappointment to see that the preferences were gone :/ There's no way I will spend time mirroring the preferences between a PC and another, it would be too much work.

Any workaround for this? A file which I can sync via some third party tool?

**Comment by silvererudite** [comment] 2019-10-09 15:45
Did you log in to the newly installed Ff with your previously used account? As far as I know,  the same FF account syncs preferences in different devices.

**Comment by cowreth** [comment] 2019-11-18 11:05
Hi, same issue here. Two laptops. Both sync'ed. Spent a full day customizing on Laptop 1, and now I've just launched laptop 2. The extension has been locally downloaded, but not the preferences (container names, assignations, …).

Am I missing something ?

**Comment by sciencetaco** [comment] 2019-11-27 17:01
I'm seeing the exact same behavior as @cowreth. I'm running firefox 70.0.1 on os x 10.15.1 on two machines. Configured containers on one, found no configuration on the other after the addon was added via sync. 

Is there a way to manually sync this data until there is a fix?

**Comment by macks2008** [comment] 2019-11-28 02:04
can also confirm this. Glad I haven't spent too much time customizing things yet, as it's much easier to incrementally mirror things than it is to mirror things in bulk.
Both devices are logged into the same account and I even tried clicking the button to "sync now" on both of them, but to no effect

**Comment by houstdav000** [comment] 2019-12-03 11:50
As far as I know, while the list of installed add-ons from the Mozilla Add-On site automatically sync and reinstall, settings don't for _all_ add-ons, this one included. It would be nice to enable synchronization of add-on preferences, but I do see the potential for it being abused by a malicious add-on creator,

**Comment by sciencetaco** [comment] 2019-12-03 13:14
@houstdav000 agreed. I'm cool with syncing it manually if someone could tell me where the data lives. Short of that, a 'cloud' mechanism like what ublock origin uses would be extremely helpful, especially if you're the kind of person who gets all bent out of shape about consistent configs.

**Comment by kendallcorner** [comment] 2019-12-04 23:18
Hi. This looks like a duplicate of #339 . Please +1 or discuss on that issue. I'll close this, but feel free to reopen if you think it's a different issue.

**Closed by kendallcorner** 2019-12-04 23:18 UTC
