### ISSUE TITLE
Extend the Function of "Always open in..."

### ISSUE THREAD

**Issue by kurobeats** [mozilla/multi-account-containers#1249] opened 2018-08-16 08:23 UTC
I would like to see tighter restrictions on the container whitelisting. For example: 
- You have created a Facebook container and set https://www.facebook.com to always open in that container
- You open https://www.google.com from within the same container and suddenly Google is being used and mixed with facebook.com

I understand you can "simply" create a Google container to stop this from happening but it's not feasible for all websites. I would expect that if you tried to open any website OTHER than facebook.com from within the Facebook container that it switches to the Default container.

**Comment by kurobeats** [comment] 2018-08-16 08:25
Might I add, this addon/functionality seems to be a victim of it's own success (judging by the "Issues"). It's a great idea, keep up the good work team!

**Comment by blackjackshellac** [comment] 2019-05-30 13:37
This should be the "default" behaviour.

**Comment by lhorace** [comment] 2019-06-01 00:00
Hi @kurobeats and @blackjackshellac Might want to move discussion over to #847.

Cheers

**Comment by kendallcorner** [comment] 2019-12-06 20:22
Yes, this looks like a duplicate of #847. Please vote (:+1:) or discuss on that issue to show your interest. I'll close this, but feel free to request a reopen if you think it's a different issue.

**Closed by kendallcorner** 2019-12-06 20:22 UTC
