### ISSUE TITLE
My "confirmation" page seems unstyled, or incorrectly styled, causing visual discomfort in low-light settings

### ISSUE THREAD

**Issue by colemickens** [mozilla/multi-account-containers#2434] opened 2022-10-27 22:13 UTC
### Before submitting a bug report

- [X] I updated to the latest version of Multi-Account Container and tested if I can reproduce the issue
- [X] I searched for existing reports to see if it hasn't already been reported

### Step to reproduce

1. Install MAC
2. Use a colorways theme
3. Set a page to "always open in X container"
4. Open a naive blank tab.
5. Go to that page.
6. Watch as your eyes are blinded by the unstyled, white confirmation page

I actually started using this because of someone else using it at NixCon, and both the colors and general styling of this page looked way better. I'm not sure what if anything I would have done or have installed that would affect this...

![screenshot-1666908666](https://user-images.githubusercontent.com/327028/198407806-d60375f3-9be2-4c30-ab2f-44ec3466fb5d.png)

compare to:

![screenshot-1666908733](https://user-images.githubusercontent.com/327028/198407893-4b2a3848-77e5-4e13-9423-1baedd107ccb.png)

### Actual behavior

I'm exposed to a very, very bright white screen, hihgly in contrast with every other element on my screen.

### Expected behavior

The page is styled and follows the Firefox Home styling.

### Additional informations

I tried to not be too obnoxious in the title, but this is very jarring. Firefox has done a good job of internalizing dark themes elsewhere.

**Comment by dannycolin** [comment] 2022-10-28 02:22
duplicate of #2423

**Closed by dannycolin** 2022-10-28 02:22 UTC
Labels: bug
