### ISSUE TITLE
Always open in specific container leaves deprecated tab

### ISSUE THREAD

**Issue by a-wigand** [mozilla/multi-account-containers#1704] opened 2020-04-10 12:16 UTC
- Multi-Account Containers Version: 6.2.3
- Operating System + Version: Windows 10 (1909)
- Firefox Version: 75.0 (64-bit)
- Other installed Add-ons + Version: LeechBlock NG (1.0.5)

### Actual behavior
When opening a site that is set to always open in a specific container, that site will be opened in a new tab. The deprecated tab has to be closed manually. So far so good and not a big problem.
With LeechBlock enabled and set to forward to a specific site, however, this can create an issue.
I set LeechBlock to open a site as a blocking site, which is set to open in a specific container. When triggered, this opens 'infinite' tabs of the same site as the original tab, that triggers the LeechBlock intervention never closes.

### Expected behavior
If opening a site that belongs to a different container, the current tab should be exchanged for the new tab (closing the current tab and opening the site in a new tab or switching the tab's container in one step)

### Steps to reproduce
1. Set LeechBlock to show a site that belongs to a specific container as a blocking site
2. Open a new tab
2. Enter a site that would be blocked by LeechBlock
3. The blocking site would usually be opened in the tab of the blocked site but as the container site opens in a new tab and the triggering tab never closes, this will create 'infinite' new tabs.

### Notes
This might be an issue with LeechBlock itself but even without LeechBlock I would prefer the container to open in the same tab or for the old tab to be closed automatically.

**Comment by xdhmoore** [comment] 2020-06-13 21:45
Related to #1765 and #1590

**Comment by dannycolin** [comment] 2023-01-02 01:16
Can you still reproduce this issue since #1835 has been merged?

**Closed** 2023-01-04 09:50 UTC
Labels: bug
