### ISSUE TITLE
Running extensions in containers

### ISSUE THREAD

**Issue by jefferai** [mozilla/multi-account-containers#1013] opened 2017-11-29 21:26 UTC
I have a number of extensions (Pushbullet, Zoom.us, Bookmark OS) that use Google to authenticate. When these are installed and you try to log in, because they cannot be locked to a container, I end up having to log into Google with my default account, when I would otherwise have all Google-related activity in my Personal account. This can allow the kind of targeted tracking (tying browsing in the default account to a Google account) that this extension is supposed to disallow.

**Comment by jonathanKingston** [comment] 2017-12-05 21:01
This is a duplicate of a platform bug that we have already: https://bugzilla.mozilla.org/show_bug.cgi?id=1365019

Thanks

**Closed by jonathanKingston** 2017-12-05 21:01 UTC
