### ISSUE TITLE
CLI interface to open link in specific container

### ISSUE THREAD

**Issue by christophgysin** [mozilla/multi-account-containers#1366] opened 2019-04-04 10:51 UTC
I would like to have a way to be able to open a link from the commandline in a specifc container. E.g.:

```bash
$ firefox --new-tab --container=work <url>
```
Is there a way something like this could be implemented?

I'm happy to contribute if someone can point me in the right direction what is needed to achieve this.

**Comment by stoically** [comment] 2019-05-04 12:25
Duplicate of https://github.com/mozilla/multi-account-containers/issues/365 - please vote there. Thanks!

**Closed by stoically** 2019-05-04 12:25 UTC
Labels: duplicate

**Comment by QuantumGrizzly** [comment] 2023-01-24 23:26
In the meantime, you can use the extension honsiorovskyi/open-url-in-container
