### ISSUE TITLE
Add hook for ignoring "always open in" setting

### ISSUE THREAD

**Issue by lonix1** [mozilla/multi-account-containers#1414] opened 2019-05-11 06:29 UTC
If "always open in container" is selected, then that behavior is impossible to  circumvent.

Other addons (e.g. [Context Plus](https://github.com/totallymike/contextPlus/issues/33)) which allow to reopen or move a tab to a different identity (/tab) won't work because the move is intercepted by this addon, and the "always open in" policy is enforced.

It would be nice if there were some sort of hook that allowed this addon to work well with other addons, so that this feature would be ignored if allowed by the user.

**Comment by vinzent** [comment] 2019-05-15 14:38
I think this relates to my issue/request: https://github.com/mozilla/multi-account-containers/issues/1410

**Comment by lonix1** [comment] 2019-05-15 15:27
Related but not the same thing. Your issue is part of firefox itself, whereas this is about interoperability with other addons.

We need the ability to 1) move container tabs around, and 2) move them between "identities" as made possible by other addons.

**Comment by grahamperrin** [comment] 2021-04-27 21:03
Is this a duplicate of #1222?

**Comment by dannycolin** [comment] 2023-01-06 22:06
> 2) move them between "identities" as made possible by other addons.

The main concept is to isolate each container from the others. This would go against that principle. So if by moving identities, you also mean moving the data for this site (cookies, local storage) this won't happen.

I do thing allowing a way to open only an assigned website with "re-open" is a valid use case without copying the data to the second container.

With that in mind, I'll go ahead and close this as a duplicate of #1442 that should solve this part of the issue.

**Closed by dannycolin** 2023-01-06 22:06 UTC
Labels: Component: Site Assignment, :+1:  Feature Request
