### ISSUE TITLE
All Containers Lost after FF Crash - HELP

### ISSUE THREAD

**Issue by akasaka99** [mozilla/multi-account-containers#1968] opened 2021-02-19 11:22 UTC
Hi-
I'm using FF 85.0.2 on MacOS 13.6.
1. After a sudden FF crash which I do not know the reason, all my containers disappeared even though I had FF sync on.
2. However, it looks like the add-on has started from fresh without taking into account the sync feature??
3. I recall to usually be prompted to re-sync my Multi-Container add-on in such cases but for some reason this time I was not prompted to sign in the add-on for it to re-sync so I am not sure if it has re-sync or not as it appear totally fresh.

So I would like to know how I could recover my containers by either :
1) "forcing" the add-on to re-sync which it does not seem to have done this time 
2) where are those containers data located on my Mac as I do a regular disk back-up so I could restore them from a previous backup but I do not know what/where they are.

Many thanks for your help.

**Comment by rpl** [comment] 2021-02-19 13:34
> Hi-
> I'm using FF 85.0.2 on MacOS 13.6.
> 
>     1. After a sudden FF crash which I do not know the reason, all my containers disappeared even though I had FF sync on.
> 
>     2. However, it looks like the add-on has started from fresh without taking into account the sync feature??
> 
>     3. I recall to usually be prompted to re-sync my Multi-Container add-on in such cases but for some reason this time I was not prompted to sign in the add-on for it to re-sync so I am not sure if it has re-sync or not as it appear totally fresh.
> 
> 
> So I would like to know how I could recover my containers by either :
> 
>     1. "forcing" the add-on to re-sync which it does not seem to have done this time
> 
>     2. where are those containers data located on my Mac as I do a regular disk back-up so I could restore them from a previous backup but I do not know what/where they are.

The list of containers (the one that Firefox itself stores, the extension itself may have some additional metadata on its own, but the containers definitions still need to be part of this file) is in a file named `containers.json` stored in the Firefox profile directory.

**Comment by akasaka99** [comment] 2021-02-19 14:58
Great found it. So I would just have to replace the current "blank" JSON file with the backed-up JSON file and hotepguly that's it? Thnks !

**Comment by dannycolin** [comment] 2023-01-06 22:14
Duplicate of #1236

**Closed by dannycolin** 2023-01-06 22:14 UTC
