### ISSUE TITLE
When firefox crashes / restarts, logins do not persist 

### ISSUE THREAD

**Issue by timeassistant** [mozilla/multi-account-containers#881] opened 2017-09-29 17:14 UTC
was advised by @groovecoder to post a potential bug here...

If firefox crashes or reboots all of my sessions are signed out while using containers (whether I have assigned profiles or not) everything is signed out once all tabs and windows are restored. It is hinted that this is a bug rather than annoying behaviour. 

I disabled the containers extension and crashed firefox via task manager and it restored the sessions logins.

going by this it would seem containers atleast for me, has issues keeping sites logged in. 

by request of Tanvi here are a couple screenshots from the settings

![image](https://user-images.githubusercontent.com/18701905/31027222-6167c894-a541-11e7-8138-460eec397108.png)
![image](https://user-images.githubusercontent.com/18701905/31027243-73aadc8a-a541-11e7-9192-1d86fb8dab0b.png)

Build identifier: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:55.0) Gecko/20100101 Firefox/55.0
Windows 10 Pro 64bit
Acer TC-705
Core i7 4790
12GB DDR3

**Comment by groovecoder** [comment] 2017-09-29 17:43
I think your "Accept cookies from sites: Keep until: I close Firefox" is what's killing your sessions when you close Firefox.

I don't think we do anything to change that setting. Maybe multifox was changing it and we are not?

Can you try running Containers with "Keep until: they expire" and see if your login sessions persist between browser sessions?

**Comment by timeassistant** [comment] 2017-10-02 10:16
Hello, 

Sorry for the delay, that setting was actually me just testing, forgot to revert it for the screenshot. I have set it to keep until they expire and killed the process and re-opened, its still making me sign in to things like gmail even if a tab is not set to any container.

**Comment by groovecoder** [comment] 2017-10-02 14:01
@SoftVision-EmilPasca - can you reproduce this one?

**Comment by timeassistant** [comment] 2017-10-02 15:39
Hey @groovecoder 

I noticed that I was still running Firefox 55 even though I should have had an option to update to 56 (even went to the about: page that triggers update prompt) For some reason it wasn't wanting to update, so I have reinstalled the browser as it was beginning to crash very often (still using same list of addons) and it now seems to be saving sessions across reboots - the issue at least for now seems to have been resolved  😕 

The reason I was prompted to check my firefox version is because I also use Firefox Developer edition and it auto updated to v57 killing off all the extensions loaded on it (most still don't have replacements!) so I had to reinstall the previous version (56), at which point I decided to check my normal firefox install to ensure nothing had happened to it. 

I'm wondering if having firefox developer edition  along side regular firefox was an issue?  standard firefox was running v55 and developer firefox had auto upgraded to v57. Maybe its nothing and I'm just clutching at straws looking for answers ! 

I will certainly try and reproduce this issue and see if it happens again though just incase its an issue other users have

**Comment by SoftVision-EmilPasca** [comment] 2017-10-03 13:34
I have tested this issue using the latest Multi Account Containers(4.0.3) and also Multi Account Containers(4.0.2) on Windows 10 x64 with Firefox release(55.0.3), latest Firefox release (56.0) and the latest Nightly (58.0a1-20171002220204) and haven't managed to reproduce it.

After being logged in various websites like Twitter and Facebook in different containers, if the preferences set in "about:preferences" are set as in the images displayed in https://github.com/mozilla/multi-account-containers/issues/881#issue-261707101 , when restarting the browser or closing and reopening it, the previous opened tabs are re-open in the corresponding containers, without reseting the cookies, same if the browser has been previously crashed.

@timeassistant, can you please list the list of the addons you have installed or the information in "about:support" maybe the information there will help us investigate this further.
Thank you!

**Comment by timeassistant** [comment] 2017-10-03 14:05
@SoftVision-EmilPasca Thank you for the very detailed response, I appreciate the level of analysis here. 

My current addon list is as per screenshot below: 

![image](https://user-images.githubusercontent.com/18701905/31128990-41242fde-a84b-11e7-8ab6-af6fe928875f.png)

I'm still unable to reproduce this issue since I installed v56. Also Multifox seems to be completely removed now, I don't see any traces of it left perhaps that was the issue? is it possible some part of multifox was still previously loaded when it was v55?

**Comment by groovecoder** [comment] 2017-10-03 14:06
Thanks @SoftVision-EmilPasca. Since we can't reproduce, I'm closing this. If we see/notice it come back, please re-open.

**Closed by groovecoder** 2017-10-03 14:06 UTC
