### ISSUE TITLE
"Open link in new contatiner Tab" right click menu option does not appear when right click on links from bookmarks toolbar

### ISSUE THREAD

**Issue by MohamedAbdultawab** [mozilla/multi-account-containers#1336] opened 2019-02-02 15:38 UTC
- Multi-Account Containers Version: 6.1.0
- Operating System + Version: ubuntu 16.04
- Firefox Version: 65.0

### Actual behavior
"Open link in new contatiner Tab" right click menu option does not appear when right click on links from bookmarks toolbar

### Expected behavior
"Open link in new contatiner Tab" right click menu option appears when right click on links from bookmarks toolbar
### Steps to reproduce
1. from bookmarks toolbar right click on any link
2. the option does not appear

**Comment by larssb** [comment] 2019-04-05 20:34
This would be great to get in. Going the long route of:

1. Right click on 'x' bookmark
2. Clicking properties
3. `Tab` to the `Location` field
4. Ctrl+C
5. OS centric key (MacOS == `cmd`) + T, to open a new tab
6. Ctrl+V to insert the copied bookmark URI
7. Hit *Enter* to finally go to the site in a *multi-account-container* you want....

that is cumbersome :-)

Thanks

**Comment by stoically** [comment] 2019-05-04 12:31
Duplicate of https://github.com/mozilla/multi-account-containers/issues/323 - please vote there. Thanks!

**Closed by stoically** 2019-05-04 12:31 UTC
