### ISSUE TITLE
Links opened with middle mouse button open in two new tabs

### ISSUE THREAD

**Issue by tmarplatt** [mozilla/multi-account-containers#1003] opened 2017-11-27 12:44 UTC
When using container tabs, opening links in new container tabs using middle mouse button may open two tabs instead of just one.

This behavior is not entirely consistent and a MMB link click often works as intended. If I can narrow down the specific circumstances that reproduce this issue then I will post a follow up.

My about:support dump (excerpt): https://gist.github.com/tmarplatt/9d6fa6d878ac9a978c76dff49d2f2b68

Edit: to clarify, I've not had this happen in default tabs, which is why I believe is a container tabs-specific issue.

**Comment by TheSweetLily** [comment] 2017-11-28 13:12
I have had the same happen to me, but it seems really random.. Sometimes I experience it often-ish, and sometimes I get it once every few days, if not less.

I'll report in if I can reproduce it myself, too.

**Comment by Alarm-Siren** [comment] 2017-11-28 19:48
I wasn't able to reproduce this bug, but in trying to do so I noticed that if the new container is different to the old one, it gives focus to the new tab even though it doesn't normally do this within the same, or no, container. I suspect what's happening is the new tab is in the "wrong" container, immediately gets deleted and a new tab in the correct container opened to replace it, which then receives focus. Perhaps your bug is related to the old tab not being correctly cleaned up?

**Comment by terrizgit** [comment] 2017-12-02 00:04
Related: Opening a new tab by clicking a link in an email (from outside Firefox) opens two tabs with the same link.

**Comment by gaborluk** [comment] 2017-12-05 00:21
I believe this is a duplicate of #940, where @magkopian has provided a nice recording of the issue.

**Comment by groovecoder** [comment] 2017-12-05 13:38
Closing as dupe of #940. Please 👍 and comment there.

**Closed by groovecoder** 2017-12-05 13:38 UTC
Labels: duplicate
