### ISSUE TITLE
Add ability to reorganize Containers

### ISSUE THREAD

**Issue by gwynnarth** [mozilla/multi-account-containers#330] opened 2017-03-03 13:21 UTC
It would be useful if users could change the order of Containers after they are created.

**Comment by jonathanKingston** [comment] 2017-04-05 14:28
I actually think this could be solved with drag and drop when in edit mode using the browser action.

We would need some form of index adding to the storage to remember what to display them into though.

**Comment by erickt** [comment] 2017-06-17 18:30
It would also be nice to alphabetically sort the containers. I use a lot of containers to manage a bunch of Amazon environments, so it's always a bit of a pain to find the right one.

**Comment by billturk** [comment] 2017-07-26 16:42
Yes being able to alphabetically sort the containers would help a lot!!!

**Comment by smichel17** [comment] 2017-10-03 16:20
Perhaps it would make more sense to add this functionality to about:preferences#containers ?

**Comment by Narvey** [comment] 2017-11-01 19:31
Yes @smichel17 , we should be able to manually order our containers, and have that affect the Sort Containers button (which seems to be useless at the moment, somebody correct me if I'm wrong).

**Comment by t4777sd** [comment] 2017-11-13 02:41
Definitely agree. Not being able to sort the containers makes them a lot more difficult to work with.

**Comment by psychoslave** [comment] 2017-11-17 17:05
I use containers as tabgroups replacement, I already defined more the 30 containers and I only use them since yersterday. Grouping alphabeticaly would be fine for me as I use a "theme/subtheme" nomemclature, however being able to drag&drop to move them around would be a big plus.

Note really the issue topic, but being able to switch context and only display included tabs with one click would be great. The current behaviour seems to be "open a new tab in this container" which is really odd for my use. To achieve what I want to do, I have to go in the target container submenu, select one tab, then go back to the container menu, find the container I no longer want to display, go in the submenu and finally hide it.  What I'm accustomed to with the grouptabs was "drop down list of group, select, tada" for the same result.

Having better isolation is fine, but in my priority list it's really far, far, far behind being able to easily switch context, that is having a group of tabs.

**Comment by RadonX** [comment] 2017-11-22 04:07
@psychoslave You will like this addon https://addons.mozilla.org/en-US/firefox/addon/conex/

**Comment by psychoslave** [comment] 2017-11-22 13:02
Thank you @RadonX for the suggestion. I already tested it, but it seems that currently it brings only more clutter in the toobar with 0 additional feature until some bug is fixed.

**Comment by br3n065** [comment] 2017-12-06 19:08
I've deleted/repurposed far to many containers, an option to rearrange them manually or alphabetically would be awesome.

**Comment by o-l-a-v** [comment] 2017-12-11 13:20
Please implement this. Either alphabetically or custom/ manually, or both. 
To only sort by creation time, is pretty useless.

**Comment by v00p** [comment] 2018-04-10 02:00
Any update on this sorting capability ? is this being worked on or stalled ?

**Comment by jonathanKingston** [comment] 2018-10-01 22:49
@Paarmita the only problem is some of the menus come from Firefox itself so you would have to add an index to the internal storage and sort those menus the same.

**Comment by franzjschneider** [comment] 2019-03-08 09:32
Hard to believe it's 2019 and we're still asking for something so simple and such a no-brainer. I keep getting tempted to switch to Brave completely.

**Comment by JohnLGalt** [comment] 2019-04-17 15:52
#1347 adds code for sorting alphabetically only, and while this is a step in the right direction, I think we need more.

Since editing the containers.json manually works perfectly, I've done it that way - but would be great to see it in the UI itself.

**Comment by franzjschneider** [comment] 2019-04-17 21:56
After way too long a wait and a struggle to find a replacement, I ditched this extension for Simple Tab Groups. Worth the switch. It's a great extension with a good level of customization, organization, and sorting for groups. Great in combination with SortTabs for also sorting tabs by different criteria.

Simple Tab Groups by Drive4ik:
https://addons.mozilla.org/en-US/firefox/addon/simple-tab-groups/

**Comment by JohnLGalt** [comment] 2019-04-27 14:49
Simple Tab Groups looks great - if you simply want different tabs.  This bullet item under current functionality seems especially interesting:

Added support of "Firefox Multi-Account Containers"

I wonder if that means that the full functionality of MAC is there, including isolated credentials, history, etc.

I'll definitely take a look at it.  Thanks!

> 
> 
> After way too long a wait and a struggle to find a replacement, I ditched this extension for Simple Tab Groups. Worth the switch. It's a great extension with a good level of customization, organization, and sorting for groups. Great in combination with SortTabs for also sorting tabs by different criteria.
> 
> Simple Tab Groups by Drive4ik:
> https://addons.mozilla.org/en-US/firefox/addon/simple-tab-groups/

**Comment by franzjschneider** [comment] 2019-04-28 04:06
> Simple Tab Groups looks great - if you simply want different tabs. This bullet item under current functionality seems especially interesting:
> 
> Added support of "Firefox Multi-Account Containers"
> 
> I wonder if that means that the full functionality of MAC is there, including isolated credentials, history, etc.
> 
> I'll definitely take a look at it. Thanks!
> 
> > After way too long a wait and a struggle to find a replacement, I ditched this extension for Simple Tab Groups. Worth the switch. It's a great extension with a good level of customization, organization, and sorting for groups. Great in combination with SortTabs for also sorting tabs by different criteria.
> > Simple Tab Groups by Drive4ik:
> > https://addons.mozilla.org/en-US/firefox/addon/simple-tab-groups/

No problem. And while I haven't personally used the isolated credentials, it looks like you can use this extension with containers under Preferences > General > Tabs > and then check "Enable Container Tabs." You can then add containers by clicking Settings... next to that check box.

For managing memory, here's another extension that works well with Simple Tab Groups for suspending idle tabs. It uses minimal permissions and the developer has been responsive so far. Works beautifully.

Total Suspender:
https://addons.mozilla.org/en-US/firefox/addon/total-suspender/

**Comment by Ryonez** [comment] 2019-08-18 09:26
I would also like to be able to sort the list please.

**Comment by franzjschneider** [comment] 2019-08-21 04:05
> I would also like to be able to sort the list please.

Check out Simple Tab Groups. I ditch Multi-Account containers several months ago after getting fed up waiting for such a simple feature. Simple Tab Groups runs smooth and is great for organizing a large amount of tabs into different groups.

**Comment by Ryonez** [comment] 2019-08-21 06:20
@franzjschneider I'd really want to see that in action before installing that. I use Multi-Containers and temporary containers for the moment and am not sure that'd be a good replacement for my setup.

**Comment by JohnLGalt** [comment] 2019-08-21 14:59
I found a replacement for Tab Groups (Panorama) that works well on Nightly builds - https://github.com/projectdelphai/panorama-tab-groups (also available on AMO).
With this one I've been able to relegate my tabs that I only need grouped back to different groups, and relegate tans that I need to use multiple accounts with into MACs.  It's a win win.

**Comment by yellowwoods12** [comment] 2019-10-19 20:40
@jonathanKingston @maxxcrawford @groovecoder  It would be great if we can provide a custom sorting functionality for the created containers through the popup itself. It will add a lot of power to the present functionality and will be much more useful. Would love to work on this feature and know your views about it.

**Comment by sryze** [comment] 2019-12-29 05:41
I've created a PR that allows you to re-order containers via drag&drop - https://github.com/mozilla/multi-account-containers/pull/1608, can someone do a code review?

**Comment by Laurensdc** [comment] 2020-02-14 09:25
Please implement this, we need it!

**Comment by o-l-a-v** [comment] 2020-03-29 15:26
One more reason to make this possible: #1697

**Comment by Tyler-2** [comment] 2020-04-20 19:30
+1. I use containers for multiple AWS consoles and it's a real bear scrolling up and down the long unsorted list looking for the one I want. I've considered deleting all of my containers and recreating them in the right order. :1st_place_medal:

**Comment by andrew-jacob** [comment] 2020-06-07 17:00
Failure to address this issue is also is making CookieAutoDelete unable to be synced between computers. The expressions are syncing up with the wrong container because the list order is not synced. Frustrating oversight by containers to sync in a seemingly random order... not even alphabetical or identical to my other computer.

Here is the referenced issues: 
Cookie-AutoDelete/Cookie-AutoDelete#579
https://github.com/mozilla/multi-account-containers/issues/1697

**Comment by spaelling** [comment] 2020-06-15 06:46
need this badly!

**Comment by alsoeric** [comment] 2020-06-17 15:00
please add this feature. also grouping containers would be a big help

**Comment by nicolasbadia** [comment] 2020-06-17 17:14
#1608 just need one more approval... since 6 months...

**Comment by pethron** [comment] 2020-08-13 09:35
Consider adding sorting and grouping

**Comment by lindhe** [comment] 2020-08-13 13:05
I like your suggestion, @pethron , but I suggest that goes as a separate PR as to not delay this even more.

**Comment by perlancar** [comment] 2020-09-10 23:20
For those that find a PowerShell script in #1208 (a duplicate of this issue) useful: you might also want to consider an equivalent (but slightly enhanced) CLI script I've written in Perl: https://metacpan.org/pod/firefox-mua-sort-containers . It lets you sort the containers quite flexibly. I've also [blogged](https://perlancar.wordpress.com/) about it.

**Comment by MurzNN** [comment] 2020-10-15 07:29
Additionally Multi-Account Containers popup, other place for implement reordering feature can be about:preferences#containers - in this place I already can mass remove containers via single clicks, instead of "long click quest" at Multi-Account Containers popup.

**Comment by zanona** [comment] 2020-10-15 10:54
By having a look on @perlancar suggestion and analysing the source, I was able to manually edit `~/.mozilla/firefox/profile.default/containers.json` file _(you may need to adjust the path for this file depending on your platform)_.

I'm not completely sure yet if changing this had any negative effect besides the ones mentioned below, so please, beware.

```json
{
  "version": 4,
  "lastUserContextId": 4,
  "identities": [
    { "name": "userContextIdInternal.webextStorageLocal", "userContextId": 4294967295, "public": false, "icon": "", "color": "", "accessKey": "" },
    { "name": "userContextIdInternal.thumbnail", "userContextId": 4294967296, "public": false, "icon": "", "color": "", "accessKey": "" },
    { "name": "Personal", "userContextId": 1, "public": true, "icon": "fingerprint", "color": "blue" },
    { "name": "Shopping", "userContextId": 2, "public": true, "icon": "cart", "color": "orange" },
    { "name": "Crypto", "userContextId": 3, "public": true, "icon": "dollar", "color": "orange" },
    { "name": "Other", "userContextId": 4, "public": true, "icon": "chill", "color": "blue" }
  ]
}
```

So, by manually sorting the array and restarting Firefox, the container order has been adjusted accordingly.
I've noticed that it's not needed to change the `userContextId` in order to make it work.
And a big **disclaimer**: after doing this, the cookies I had saved for each tab no longer were present, so I had to sign in to the sites I was logged in previously. Not sure what caused this, but it's important to let you know.

Also, you'd need to reassign your shortcuts in case you had it configured under the extension preferences. However, for an improved behaviour and not opening a new tab every time you switch context, I would recommend [easy container shortcuts extension](https://github.com/gsomoza/firefox-easy-container-shortcuts) instead.

And finally, as @MurzNN suggested, this is also reflected under `about:preferences#containers`

**Comment by Tyler-2** [comment] 2020-10-16 11:55
>  And a big **disclaimer**: after doing this, the cookies I had saved for each tab no longer were present, so I had to sign in to the sites I was logged in previously. Not sure what caused this, but it's important to let you know.

Would that be because the cookies are store for like... Identities[0], Identities[1], etc? Seems like a bigger impact of this would be that the new site at [0] would have access to the old [0] site's cookies! But... I'm just guessing.

**Comment by zanona** [comment] 2020-10-16 12:24
> Would that be because the cookies are store for like... Identities[0], Identities[1], etc? Seems like a bigger impact of this would be that the new site at [0] would have access to the old [0] site's cookies! But... I'm just guessing.

I found out that tweaking the `userContextId`, specially for `userContextIdInternal.thumbnail` and `userContextIdInternal.webextStorageLocal` wasn't a good idea at all. Moving them around by adjusting the position you want in the array is really not a problem, though.

I have tried in many ways after that, and keeping `userContextId` as is, didn't introduce any problems. At least this is how it stands for me so far. So I guess you are right, cookies are possibly being linked to the `userContextId`.

One example of linking a new tab to a container through an extension is given below, so it would make sense those are connected in a way, I guess? 

[source](
https://github.com/gsomoza/firefox-easy-container-shortcuts/blob/1bf389a6fbbc3aa17cb702aff53e0e30876a9d1e/background.js#L80-L85)
```js
    browser.tabs.create({
      cookieStoreId: context.cookieStoreId, //cookieStoreId belongs to context (container)
      index: currentTab.index + 1,
      url: currentTab.url
    });
```

**Comment by naamancampbell** [comment] 2020-12-13 12:28
Yet another community solution (_I am the author_): [ff-containers-sort](https://pypi.org/project/ff-containers-sort/) - requires Python 3.6+
```bash
pip install ff-containers-sort
```

**Features:**
* alphabetical sorting of containers
* manual sorting mode
* safely updates containers.json after manual changes
* preserves Firefox private container objects
* creates backups of Firefox Container config prior to making changes
    * deletes backups older than 7 days
* tested on Linux, Windows & Mac

**Comment by maxxcrawford** [comment] 2021-01-22 15:18
We merged in a feature to drag and drop the order of the containers! 

Fixed by PR #1608

**Closed by maxxcrawford** 2021-01-22 15:18 UTC
Labels: enhancement, vote for me

**Comment by hub2git** [comment] 2021-01-30 19:29
After updating to Firefox 85.0 on Linux, I now can sort the containers -- **as they appear in the toolbar** -- by drag and drop.

But the changes are not reflected when right-clicking a link on a webpage and hovering over "Open Link in New Container Tab".

**Comment by grahamperrin** [comment] 2021-01-31 01:34
Thanks @hub2git please raise an issue for this, if one is not already open.

**Comment by jonathanKingston** [comment] 2021-01-31 11:15
The other bug should be closed. The work needs to happen in Firefox, for which there is a bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1333395

**Comment by minhnhattonthat** [comment] 2022-04-30 16:43
Is there a way to sort the No Container at the end instead of before all Containers?

**Comment by o-l-a-v** [comment] 2022-05-22 10:01
Quick PowerShell script to sort containers alphabetically

```powershell
#Requires -Version 5.1
<#
    .SYNOPSIS
        Sort Mozilla Firefox containers alphabetically.

    .NOTES
        # Script info
        Author:   Olav Rønnestad Birkeland | github.com/o-l-a-v
        Created:  220522
        Modified: 220522

        # Resources
        * https://bugzilla.mozilla.org/show_bug.cgi?id=1333395
        * https://github.com/mozilla/multi-account-containers/issues/330
#>


# Automatically
## Get file path
$ContainersFilePath = [string](
    Get-ChildItem -Path ('{0}\Mozilla\Firefox\Profiles' -f $env:APPDATA) -Filter 'containers.json' -File -Recurse | `
        Sort-Object -Property 'LastWriteTime' -Descending | `
        Select-Object -ExpandProperty 'FullName' -First 1
)

## Get file content
$Containers = [PSCustomObject](
    Get-Content -Raw -Path $ContainersFilePath -Encoding 'UTF8' | ConvertFrom-Json
)

## Sort
$Containers.'identities' = [PSCustomObject[]]($Containers.'identities' | Sort-Object -Property 'public', 'name')

## Set
$null = Set-Content -Path $ContainersFilePath -Value ($Containers | ConvertTo-Json -Depth 2 -Compress) -Force -Encoding 'UTF8' -NoNewline
```

**Comment by JohnLGalt** [comment] 2023-11-29 13:23
Even on a new profile that you log in and sync with?

**Comment by FlominatorTM** [comment] 2023-12-30 09:32
It would be cool if one would build a website, where you can paste the JSON and sort it, either manually or by attributes.

**Comment by blachawk** [comment] 2024-04-15 04:01
whats the latest thoughts from the engineers behind this project?
