### ISSUE TITLE
[Feature Request] Separating new websites which isn't in any container

### ISSUE THREAD

**Issue by mertcelen** [mozilla/multi-account-containers#1036] opened 2017-12-06 22:40 UTC
Hi there

I'd love to have feature that move any 3rd party websites to let's say Junk container and keep them isolated in there. In that way, may be we can help reducing some tracking.

What you do you guys think about it?

**Comment by TriMoon** [comment] 2018-01-09 08:56
The "Default" container is the "Junk" container already 😉

**Comment by groovecoder** [comment] 2018-01-23 18:35
This seems like a dupe of https://github.com/mozilla/multi-account-containers/issues/847. Please move comments and upvotes there.

You may be able to get a similar kind of protection by enabling first-party isolation. https://wiki.mozilla.org/Security/FirstPartyIsolation

**Closed by groovecoder** 2018-01-23 18:35 UTC
