### ISSUE TITLE
All tabs refreshing when loading container - lazy loading

### ISSUE THREAD

**Issue by vlldk** [mozilla/multi-account-containers#970] opened 2017-11-16 07:58 UTC
All tabs are loaded when opening a hidden container - only tabs selected should be loaded until others are selected

**Comment by groovecoder** [comment] 2018-01-09 18:47
I think this is a dupe of https://github.com/mozilla/multi-account-containers/issues/348.

**Closed by groovecoder** 2018-01-09 18:47 UTC
Labels: duplicate, enhancement
