### ISSUE TITLE
Missing functionality? One user's suggestions..

### ISSUE THREAD

**Issue by DougBrunelle** [mozilla/multi-account-containers#1766] opened 2020-06-15 00:52 UTC
OS, partition 1 - Kubuntu 20.04. 
OS, partition 2 - Ubuntu Studio 20.04.
Multi-Account Containers version: 6.2.5
Firefox version: 77.0.1 (64-bit)
I have two other extensions running concurrently:
* Gesturefy, Version: 3.0.2 
* Video DownloadHelper, Version: 7.3.9

Multi-Account Containers is a cool extension for Firefox.. But, there seems to be some things missing, or not working quite how I expected. 

1. One disappointment is that containers and their tabs are apparently not saved to a server for re-use in Firefox on another partition/OS. When I had my tabs and containers set up how I wanted them, I switched to an OS on another partition where I had Firefox installed. When I logged into my Firefox account on the second partition, I was expecting my tabs and containers to sync with what I had set up in the other instance of Firefox and show up in this instance. They did not. 

2. Also, it's great that we can show and hide containers and their tabs, but this should include the option to "Show only 'x' container, so we don't have to hide one or more containers, then show another container to work with its tabs. 

And this option is not easy to get to - there should be an easy way, like a key combo, to quickly switch, hide, and show containers. Or maybe have a way to collapse all the tabs in a given container into a "SuperTab" or tab stack (as in Vivaldi browser). You could have several "SuperTabs," each representing a different container, visible in the tab bar. Clicking on a SuperTab would open that container's tabs and collapse the tabs of all other containers. This, to paraphrase Steve Jobs, would be "insanely great!"

3. To get around the problem described above, I have been using separate Firefox windows and loading up the different container tabs in each separate window. But this is not an elegant solution. 

4. Also, when using separate Firefox windows, I've run across the problem of opening up new container tabs in a window and losing them when I close the window. Seems to me that when closing the window, it should give you the option of keeping the new container tabs as part of that container. (maybe an option in the Settings?) 

Regards,
Doug Brunelle, Oceanside, CA

**Comment by Solid-Ice8** [comment] 2020-06-20 15:15
>1.  One disappointment is that containers and their tabs are apparently not saved to a server for re-use in Firefox on another partition/OS. When I had my tabs and containers set up how I wanted them, I switched to an OS on another partition where I had Firefox installed. When I logged into my Firefox account on the second partition, I was expecting my tabs and containers to sync with what I had set up in the other instance of Firefox and show up in this instance. They did not

This is intended and MAC's not at fault; FireFox browser is. It sounds like you've essentially only migrated the `Containers.json` which strictly saves **only** your containers and not the websites and this is also intended. Since you're essentially using 2 different operating systems, this means there's 2 separate profiles.

During my time off in quarantine vacation, I loved experimenting & testing. I played around with migrating FireFox Profile(s) between PC to Laptop & vice versa and learned that the websites saved from one profile does not migrate to another unless you move the whole profile.  Something on the lines of a portable FireFox profile.

These websites are stored in their own _LocalStorage_ - This is what FireFox website and Cookie AutoDelete calls it. It's literally impossible to find in the actual profile, hence I mentioned moving the whole profile.

You can easily find the portable version with the FireFox's official installation file or you can find it from [PortableApps.com](https://portableapps.com) which provides portable versions of tons of other programs. I use a variety of the apps here on my USB drive that I carry around with me majority of the time.

**Comment by SLRover** [comment] 2021-11-07 12:39
Hello!

I absolutely agree with 1st, 2nd and 4th points. For my case I use MAC for separate work and personal tabs on different PC and Macs. And these features are must have for connection work/private/banking use cases in one browser window.

It would be great if these features were added.

**Comment by dannycolin** [comment] 2023-01-01 23:54
> One disappointment is that containers and their tabs are apparently not saved to a server for re-use in Firefox on another partition/OS.

Enabling Sync in the addon options should propagate your container data across your devices in the latest version.

>  "Show only 'x' container

Duplicate of #1662 

>  there should be an easy way, like a key combo, to quickly switch, hide, and show containers

Duplicate of #338 

Other suggestions (e.g. Super Tab/Tab Group) also have a bug report filed. Closing this one for now.

**Closed by dannycolin** 2023-01-01 23:54 UTC
Labels: :+1:  Feature Request
