### ISSUE TITLE
No way to configure "always open this site in" default container

### ISSUE THREAD

**Issue by gentoo-root** [mozilla/multi-account-containers#2520] opened 2023-03-28 13:16 UTC
### Before submitting a bug report

- [X] I updated to the latest version of Multi-Account Container and tested if I can reproduce the issue
- [X] I searched for existing reports to see if it hasn't already been reported

### Step to reproduce

1. Click the extension icon.
2. Click "Always Open This Site in...".

### Actual behavior

The list of containers is shown, but the default container (no container) is not in the list.

### Expected behavior

I would expect "no container" to show up in the list to be able to force some sites to open in the default, non-containerized way, when I navigate there by a link from a containerized tab.

Use case: I use most of the sites outside of containers, log into accounts, etc., and when some link in a containerized tab leads me to some site where I have an account, I would like it to open in the "default" container (i.e. no container). However, right now it's only possible to make it open in another container.

**Comment by ColonelGerdauf** [comment] 2023-04-04 13:42
I previously achieved this via IIRC a hack via about:config, but I have forgotten, and the Firefox setup got lost to time and data corruption.

**Comment by dannycolin** [comment] 2023-04-08 23:42
Duplicate of #503

**Closed by dannycolin** 2023-04-08 23:42 UTC
Labels: bug
