### ISSUE TITLE
Add option to allow to open new tabs only in the same container when the domain name fits

### ISSUE THREAD

**Issue by RedirectCleaner** [mozilla/multi-account-containers#1310] opened 2018-11-24 16:44 UTC
### Actual behavior

Opening a new tab with "ctrl+link click" or with just a click on the link (which opens a new tab), opens a new tab in the same container

### Expected behavior
Add settings option that allows by default to only open the tab it in the same container when the domain name fits

### Steps to reproduce
1. Create a twitter container
2. add twitter.com to the container
3. login into twitter
4. click a link inside twitter, that leads to an external website
5. a new tab gets opened but it's still inside the twitter container

**Comment by nhnt11** [comment] 2018-12-04 19:20
+1 on this. Here are two more ways to articulate this issue:
- Add an option to open links in a "no container" tab by default, i.e. make "no container" the default for new tabs, even if coming from a container tab
- Don't "carry over" the container of the current tab, to new tabs opened from links.

**Comment by RedirectCleaner** [comment] 2018-12-05 19:09
Don't "carry over" the container of the current tab, to new tabs opened from links, when the link leads to another domain. Opening links with the same domain should stay inside the same container

**Comment by BlackDex** [comment] 2018-12-06 07:32
This would be a great feature which i'm also missing.
This would be very useful with gmail or hotmail for instance where you want to have the webmail in the container but not opening the links in the same container, this kind defeats the purpose of containers for me to hide my Google/Microsoft account cookies from other websites.

**Comment by cypressious** [comment] 2019-01-03 00:34
Is this open for contribution? I'd like to take at it.

**Comment by cypressious** [comment] 2019-03-06 20:41
I created a standalone extension (https://addons.mozilla.org/de/firefox/addon/container-outgoing-links/) if anyone is interested. It only triggers if the link is opened in a new tab. 

I prototyped the behavior in this code base but found the overall code structure very confusing. If anyone is interested, the code is here: https://github.com/cypressious/ff-container-outgoing-links

**Comment by lhorace** [comment] 2019-03-06 20:52
Not bad, though, I wonder the problem with that. If Firefox or MAC make changes, would it break that extension and would you bee keen to maintaining?

Ideally, having this in a PR, would be great. Seems like issues are pilling and not receiving much attention these days.

**Comment by cypressious** [comment] 2019-03-06 21:05
@lhorace The only thing that I can see breaking is the default container not being named 'firefox-default'. As you can see, there's not a lot of code in https://github.com/cypressious/ff-container-outgoing-links/blob/master/background.js.

I would have liked to make a PR but like I said, the code is not very welcoming to outsiders.

**Comment by stoically** [comment] 2019-05-04 12:58
Duplicate of https://github.com/mozilla/multi-account-containers/issues/847 - please vote there, thanks!

**Closed by stoically** 2019-05-04 12:58 UTC
