### ISSUE TITLE
buttons

### ISSUE THREAD

**Issue by Antony197878** [mozilla/multi-account-containers#966] opened 2017-11-14 19:36 UTC
im not sure but arent you must make "add to container" button for already opened tabs? i dont wanna copypaste all my 20+ tabs( and how can i remove something from container? and also i wanna see coloured dots (for example) that fastly sawitch my opened tabs for not holding them all opened (it must open only tabs from one of containers and reopen others if i wanna switch between containers) - only then it ll be useful.... for now i have to do it manually and cant even close tabs for check how it works( Summary: add to container button and fast switcher using any (like coloured dots) trigger from panel (like near adress panel)
sorry if im repeating someone

**Comment by Antony197878** [comment] 2017-11-14 19:40
also i just discovered that my saved tabs disappeared and i see only Create container though i already created couple. that meams i have to look into browser history and remember which ones i need to restore((( thx for extra work for me

**Comment by Antony197878** [comment] 2017-11-14 19:57
also i just discovered that my saved tabs disappeared and i see only Create container though i already created couple. that meams i have to look into browser history and remember which ones i need to restore((( thx for extra work for me

**Comment by Antony197878** [comment] 2017-11-14 21:13
wht files) kidding me?

**Comment by groovecoder** [comment] 2018-01-09 18:55
This sounds like a dupe of https://github.com/mozilla/multi-account-containers/issues/311 ... please check there for some work-arounds and explanations why we don't implement an "Add|Switch to Container" button.

**Closed by groovecoder** 2018-01-09 18:55 UTC
