### ISSUE TITLE
Allow per-container cookie settings

### ISSUE THREAD

**Issue by apastuszak** [mozilla/multi-account-containers#1235] opened 2018-07-08 17:58 UTC
I disable third party cookies in Firefox.  This tends to break quite a few sites that I use on a regular basis, the biggest culprit for me being dndbeyond.com, because it requires a login to twitch.tv.  I'd love it if there could be per-container cookie settings.  That way I can block third party cookies in my main container, and make another container that allows them.

**Comment by NicolaiSoeborg** [comment] 2018-07-13 11:30
This will be archived if https://github.com/mozilla/multi-account-containers/issues/318 is implemented.

**Comment by kendallcorner** [comment] 2019-12-06 16:33
Hi. This looks like a duplicate of #318. Please vote (:+1:) or discuss on that issue to show your interest. I'll close this, but feel free to request a reopen if you think it's a different issue.

**Closed by kendallcorner** 2019-12-06 16:33 UTC
