### ISSUE TITLE
Arrange containers by drag-and-drop

### ISSUE THREAD

**Issue by Paarmita** [mozilla/multi-account-containers#1267] opened 2018-09-22 15:46 UTC
### Actual behavior
We cannot arrange containers in the sequence we want.

### Expected behavior
I think we should drag the container to the place we want and get the most used container on the top.
So drag and drop feature to manage containers in the list.

**Comment by Paarmita** [comment] 2018-09-22 15:49
@groovecoder @jonathanKingston Can I work on adding this feature or discussing it?

**Comment by groovecoder** [comment] 2018-09-22 16:17
This seems to be a duplicate of https://github.com/mozilla/multi-account-containers/issues/330 ? Please read thru that one and provide a summary comment and plan for the UI/UX of how it could be done.

**Closed by groovecoder** 2018-09-22 16:17 UTC
