### ISSUE TITLE
Containers extension "forgets" my customer containers configuration, and closes container tabs

### ISSUE THREAD

**Issue by terrycloth** [mozilla/multi-account-containers#894] opened 2017-10-05 00:26 UTC
This has happened to me twice in the past week or so: Soon after opening Firefox, Containers closed all my container tabs, *and* also lost/deleted my container configurations, resetting everything to the default. I'm not sure what's causing this, except maybe extension updates? Have there been a couple recent updates?

My system setup:

* Fedora 26 Workstation x86_64 (Linux)
* KDE Plasma Workspaces 5.10.5
* Firefox Developer Edition 57.0b5 (auto-updating static binary downloaded from official web page, rather than a distro package)
* all enabled extensions:
    * Multi-account Containers
    * Context Plus
    * Test Pilot
    * Snooze Tabs
    * uBlock Origin
    * Wayback Machine

Possibly related to #431.

**Comment by emmyemi** [comment] 2017-10-05 02:11
I've had this issue a couple of times as well. My setup, for reference:

* Windows 10 64-bit
* Firefox Dev Edition 57.0b5
* Extensions:
  * bitwarden
  * Context Plus
  * Decentraleyes
  * Firefox Pioneer
  * Multi-Account Containers
  * Smart HTTPS
  * uBlock Origin

Sometimes when this issue occurs, the extension is removed entirely and must be re-downloaded. Others, my configuration just disappears and I have to redo it all from scratch.

Notably, the extension remembers when I've set a site to always open in a specific container, and will automatically do so even if I don't tell it to. However, if the order of the re-configured containers is different from before, it will automatically open the site in whichever container happens to be in the slot that previously held the correct container. Example:

**Containers:**

1. Container A
2. Container B
3. Container C

* Site X is configured to automatically open in Container B.
* Settings are wiped, forcing me to redo.
* As I'm setting up my containers, I place a different one after Container A, changing the order of those after it. The order is now as follows:

1. Container A
2. Container D (new)
3. Container B
4. Container C

Although Site X is configured to open in **Container B**, upon re-configuring my containers, it will now auto-open in **Container D**, since that container now takes up slot 2. I'm unsure of whether this will be of any help, but hopefully it will, because I'm growing tired of having to redo my settings every few days.

**Comment by hoosteeno** [comment] 2017-10-05 15:46
I saw something similar to this yesterday, too. Prior commenters: Do you have any containers that you've assigned sites to open in? My container configuration -- the names, colors and icons I had set for my containers -- reset to default, but when I visit one of the sites I have configured to "always open in this container", it still opens in a container. Specifically, I modified the Personal container, calling it "Twitter" and changing its icon. I set it up so twitter.com _always_ opens in the Twitter container. After the reset described in this issue, the container is now again called "Personal" and has the default (fingerprint) icon, but if I visit twitter.com it still opens in the Personal container.

**Comment by jonathanKingston** [comment] 2017-10-05 17:05
@hoosteeno do you have any other extensions installed?

Your symptom sounds like the containers preference got flipped, which would cause:
- Container tabs to close
- Purges all container data
- Containers to be reset to default
This happens here: http://searchfox.org/mozilla-central/source/toolkit/components/contextualidentity/ContextualIdentityService.jsm#126

However this pref shouldn't be randomly flicking from one setting to another. @bakulf could you look at that observer, is there any chance that `getBoolPref` could return false there because the pref table is locked or some edge case of writing the pref again?

**Comment by hoosteeno** [comment] 2017-10-05 17:11
I have Multi-Account Containers, TestPilot, and uBlock Origin. I can confirm that, when the issue was triggered...
* Container tabs all closed
* All my signed-in sessions in containers disappeared (I had to login again)
* My container config was set to default

**Comment by groovecoder** [comment] 2017-10-09 13:53
@jonathanKingston I wonder if this can happen when about:addons installs an updated add-on?

**Comment by jonathanKingston** [comment] 2017-10-09 15:09
@groovecoder possible see: https://github.com/mozilla/multi-account-containers/issues/900

**Comment by jonathanKingston** [comment] 2017-10-10 14:43
https://bugzilla.mozilla.org/show_bug.cgi?id=1407209 << platform bug here

**Comment by SoftVision-EmilPasca** [comment] 2017-10-11 16:32
I have managed to reproduce this issue on Windows 10x64 the latest Firefox Developer Edition(57.0b7-20171009192146) as follows:

[Prerequisites]:
- Have the preference "xpinstall.signatures.required;" set to "false" in "about:config".
- Have the Firefox Multi Account Containers add-on versions 4.0.2 and 4.0.3 xpis (downloaded from [here](https://github.com/mozilla/multi-account-containers/releases)).


[Steps to reproduce]:
1. Open the browser with the profile from prerequisites.
2. Drag 4.0.2-xpi into about:addons.
3. Assign the "Always open in Personal" option to any website.
4. Create a customs container ("Container # 01").
5. Assign the "Always open in Container # 01" to any website.
6. Drag 4.0.3-xpi into about:addons.
7. Observe the available containers in the "Containers" panel.
8. Create a new custom container with a different name and color from the previously created one.
9. Open the websites that have been previously set to be opened in different containers and observe the container tabs.


[Expected result]:
7. All the default and custom created containers appear in the "Containers" panel.
9. The website for which containers were assigned in steps 2 and 4 are correclty opened in the corresponding container tab.

[Actual Results]:
7. Only the default containers appear in the "Containers" panel.
9. The website for which custom containers was assigned in step 4 is wrongly opened in a different container tab.

[Notes]:
- Attached the browser console log: 
[browser_console_containers.txt](https://github.com/mozilla/multi-account-containers/files/1376382/browser_console_containers.txt)

- Attached a screen recording of the issue: 
![containers_updating_issue](https://user-images.githubusercontent.com/20083658/31453368-a08861d2-aeba-11e7-9139-5de89cbf5804.gif)

**Comment by jonathanKingston** [comment] 2017-10-13 15:22
I'm not sure if this is only because of the upgrade code of the add-on or actually the browser @SoftVision-EmilPasca

**Comment by SoftVision-EmilPasca** [comment] 2017-10-13 15:30
@jonathanKingston I've manage to reproduce this also by overwriting with the same .xpi.

**Comment by jonathanKingston** [comment] 2017-10-13 16:15
@SoftVision-EmilPasca did this include the patch https://github.com/mozilla/multi-account-containers/pull/901 or just the web extension version? I am a little worried that this is happening in the Firefox code rather than the code I fixed in the patch.

The problem with upgrades is it will run the uninstall code first of the current running extension which I think where we have the issue in #901

**Comment by SoftVision-EmilPasca** [comment] 2017-10-13 16:24
The issue is reproducible with the latest Multi-Account Containers(4.0.3 - 10/13/2017), just re-tested on Windows 10 x64 with Firefox Beta(57.0b8-20171013042429).

**Comment by jonathanKingston** [comment] 2017-10-15 17:06
That patch isn't in master yet, you can checkout that branch and then create a version increase manually.

If you can replicate with just the web extension version as explained in the README then this is likely a bigger issue in central.

**Comment by jonathanKingston** [comment] 2017-10-20 18:00
@SoftVision-EmilPasca I assume this is now fixed in the latest beta/nightly also? I fixed this in platform, the bug that is open should just prevent further messing with these prefs.

**Comment by jonathanKingston** [comment] 2017-10-20 18:02
Sorry just seen your confirmation on: https://bugzilla.mozilla.org/show_bug.cgi?id=1407209 Thanks!
I think we should land that PR anyway @groovecoder whenever we want to cut a patch as it solves the add-on running code it doesn't need which is a good thing anyway.

**Comment by SoftVision-EmilPasca** [comment] 2017-10-23 07:49
I have verified this issue on Mac OS 10.13, Windows 10 x64 and Ubuntu 14.04 x64 with the latest Beta (57.0b10-20171019140425) and also with the latest Nightly(58.0a1-20171022220103) it is no longer reproducible.

**Comment by terrycloth** [comment] 2017-11-09 19:22
So, wait, sorry, does that mean mean the update which fixes this bug has been pushed to the AMO site? Or was @SoftVision-EmilPasca testing a git build of the extension?

**Comment by SoftVision-EmilPasca** [comment] 2017-11-13 10:22
@terrycloth The update which fixes this issue has landed in latest Beta and Nightly channels. 
The issue is no longer reproducible with the same Containers version from AMO if you are using the latest Beta or Nightly versions.

**Comment by groovecoder** [comment] 2017-12-05 16:34
This particular bug is fixed, but https://github.com/mozilla/multi-account-containers/issues/949 is tracking new use reports of the same thing happening on the latest versions.

**Closed by groovecoder** 2017-12-05 16:34 UTC
Labels: bug, needs: Testing, P1 bug
