### ISSUE TITLE
Containers plugin causes high CPU usage

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla/multi-account-containers#1044] opened 2017-12-13 09:29 UTC
**This issue is cloned form Bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1424224**
Probably is related to #572 

User Agent: Mozilla/5.0 (X11; Linux x86_64; rv:59.0) Gecko/20100101 Firefox/59.0
Build ID: 20171206221407

Steps to reproduce:
1. Set a website to always open in a certain container tab
2. Open the website in any other container tab
The confirmation page to switch containers opens up..

Actual results:
- The page causes a very high CPU load.

However, I am having a hard time reproducing this issue. It happens every single time when I try to open facebook.com and the container confirmation page opens up, but with other websites, I don't see the issue. 

Expected results:
- The page should load but then not require any additional CPU resources.

[Notes]:
- Here is a screenshot with "about:performance" page:
![ff](https://user-images.githubusercontent.com/19226534/33931434-a32a3702-dff8-11e7-8986-8a9dcde85f8f.jpg)

**Comment by groovecoder** [comment] 2017-12-19 18:32
Closing as dupe of https://github.com/mozilla/multi-account-containers/issues/572. Thanks for the extra info though!

**Closed by groovecoder** 2017-12-19 18:32 UTC
Labels: duplicate
