### ISSUE TITLE
Feature Request: Specific firefox settings for a container (delete cookies, delete history, delete passwords, etc)

### ISSUE THREAD

**Issue by RenatoLopes771** [mozilla/multi-account-containers#2111] opened 2021-08-27 17:42 UTC
Firefox containers is pretty good, however I would like to be able to interact with the firefox settings for a specific container.

In a perfect world, I could open settings while on a container and only see the settings for that container. But I can see how that would mess with things like saved passwords (where someone can use the same password for multiple containers). But then there could be a global container that I could acess settings on which could resolve that.

But being able to just tweak a few settings would be enough. For instance, I think being able to use themes within certain containers would be overkill. Just dealing with stuff like history, cache, cookies and so on would be fine.

**Comment by Paul-Sagnola-RR** [comment] 2022-04-28 15:22
I would like to see this too. I want to clear all the cookies from a single container, not from everything. Cannot figure out how to do this currently.

**Comment by cheesington** [comment] 2022-11-29 18:23
I would like to configure a container to delete its cookies on browser close.

**Comment by dannycolin** [comment] 2022-12-28 00:45
* History isn't isolated per containers. See [bug 1283320](https://bugzilla.mozilla.org/show_bug.cgi?id=1283320).
* Passwords are separated on purpose. See the [container implementation details](https://wiki.mozilla.org/Security/Contextual_Identity_Project/Containers#Implementation_Details)
* Cookies is a duplicate of https://github.com/mozilla/multi-account-containers/issues/303

**Closed by dannycolin** 2022-12-28 00:45 UTC
