### ISSUE TITLE
Multi-Accounts Addon DELETED by "Moziila/Firefox upgrade 98+"

### ISSUE THREAD

**Issue by crosstowntraffic** [mozilla/multi-account-containers#2313] opened 2022-03-19 15:21 UTC
- Multi-Account Containers Version:
- Operating System + Version: M1 Mac Monterey
- Firefox Version: 97

I used Multi-Accounts as a Mozilla/Firefox addon for years. Every day with 7 or 8 containers for LOGINS to Banking, Hosting Providers, Social Media, Paypal, Amazon etc. Indispensable Addon that made logging in to these sites less problematic as I traveled or just worked with these sites daily, hourly.

A few weeks ago I accepted another Firefox Upgrade notification.
I've done these hundreds of times over the years on my different computers with different operating systems.
When I restarted Firefox after this 98 Upgrade I discovered Multi-Accounts, the whole installation, had been ERASED.
In its place CONTAINERS. Which looked like it was THE replacement Mozilla demanded to replace Multi-Accounts.

### Expected behavior
Firefox would restart and I would find my usual toolbar with the Addons icons waiting for me.

### What Happened instead
All of my carefully configured Multi-Accounts containers were DELETED, ERASED as if this addon never existed.
Mozilla did not import my Multi-Accounts settings into CONTAINERS.
Since Multi-Accounts had been a Mozilla APPROVED ADDON for years I would assume that Mozilla understood they had a responsibility to automatically Support the change-over to CONTAINERS

I looked all over the Mozilla site looking for feedback. Maybe info on how to IMPORT Multi-Containers Addon files into CONTAINERS.  But nothing.  Looking at the file structure of Mozilla 98 or 98.0.1 Multi-Containers Addon was simpled DELETED from my upgrade Firefox...And the Synch feature across browsers similarly will wipe out Multi-Containers on my other computers.

This is outrageous.

For this reason I routinely dismiss the Firefox Upgrade nags and have now for weeks.

**Comment by dannycolin** [comment] 2023-01-05 01:23
The update for an unknown reason must have disabled/enabled the addon (even for a fraction of second) and by default this trigger the removal of the container data. It's a bug in Firefox itself.

I'm really sorry for this and feel your pain since it also happened to me in the past. I'm going to close this issue as a duplicate of #1236 since that's where we track any progress from the Firefox bug. You can also subscribe to the bug report upstream directly at https://bugzilla.mozilla.org/show_bug.cgi?id=1549204.

**Closed by dannycolin** 2023-01-05 01:23 UTC
