### ISSUE TITLE
Allow us to apply certain add-ons per container

### ISSUE THREAD

**Issue by n8zwn** [mozilla/multi-account-containers#1486] opened 2019-08-27 19:07 UTC
- Multi-Account Containers Version:
- Operating System + Version:
- Firefox Version:
- Other installed Add-ons + Version + Enabled/Disabled-Status:

### Actual behavior

You cannot choose the specific add-ons that apply to a container, such as foxy proxy or other tools I use for work. 

### Expected behavior

I would love the ability to have certain add-ons available based on the container. Is this even possible?

**Comment by HURSSGH** [comment] 2019-09-07 01:16
Agree completely.

In fact, I would like to see containers have all preferences configurable on a per-container basis.

**Comment by alexanderadam** [comment] 2020-08-05 18:39
Duplicate of #1370

**Comment by dannycolin** [comment] 2022-05-17 23:11
Duplicates of #1167

**Closed by dannycolin** 2022-05-17 23:11 UTC
Labels: enhancement
