### ISSUE TITLE
Gmail 404s with Multi-Account Containers enabled

### ISSUE THREAD

**Issue by pdehaan** [mozilla/multi-account-containers#2020] opened 2021-04-21 05:42 UTC
Reported via Foxfooding for Firefox 89/MR1.

---

**Firefox Version:** Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:89.0) Gecko/20100101 Firefox/89.0
**Window Size (inner width and height):** 1536x739
## Steps to Reproduce
1) Multi-Account Containers enabled.
2) Enter www.gmail.com in address bar. Enter.
3) Extension asks "Open this site in your assigned container?"
3.1) Two options appear: "Open Current Contaiener"; "Open in "Custom" container".
4) Select "Open in "Custom" Container"

## Expected Behavior
Open Gmail.com 

## Actual Behavior
Google 400 page. 

> 400. That’s an error.
> "The server cannot process the request because it is malformed. It should not be retried. That’s all we know."

**Comment by dannycolin** [comment] 2022-12-02 00:02
Duplicate of #1882

**Closed by dannycolin** 2022-12-02 00:02 UTC
