### ISSUE TITLE
⁨"Containers⁩ requires Firefox ⁨53⁩ or later." On verstion 56

### ISSUE THREAD

**Issue by M-G-ARC** [mozilla/multi-account-containers#724] opened 2017-08-11 17:49 UTC
Would like to try the extension but it will not install via the test pilot website. My version of firefox is compatible, Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:56.0) Gecko/20100101 Firefox/56.0 

It seems this is a bug.

**Comment by bunnybooboo** [comment] 2017-08-12 13:28
Tested in new profile in both 56.0b1 and 56.0b2. Could not reproduce bug.
Mozilla/5.0 (X11; Linux x86_64; rv:56.0) Gecko/20100101 Firefox/56.0

**Comment by jonathanKingston** [comment] 2017-08-22 09:54
I have seen this myself on stale profiles without any debugging.

@clouserw have you seen this at all?

**Comment by jonathanKingston** [comment] 2017-09-28 10:25
@M-G-ARC lots has changed since this bug was raised could you try installing the extension from:
https://addons.mozilla.org/en-GB/firefox/addon/multi-account-containers/

**Comment by kendallcorner** [comment] 2019-12-03 21:10
Hi. We're currently triaging the Multi Account Container issues. This issue does not appear to be relevant any more, so I'm going to close it. If you don't feel the underlying issue has been resolved, feel free to reopen it with an updated description of the issue.

**Closed by kendallcorner** 2019-12-03 21:10 UTC
Labels: needs: Testing, question
