### ISSUE TITLE
Feature Request: "Always open in" configurable domain level

### ISSUE THREAD

**Issue by pauschuu** [mozilla/multi-account-containers#1017] opened 2017-12-01 09:34 UTC
Right now it seems that the full domain is considered for matching "Always open in". I want to be able to set it to TLD only, for example.

Because sites like google.com, they have tons of subdomains, and I want my whole google world in its own container but I don't want to click "always open in" for every single google subdomain I use again and again.

**Comment by stoically** [comment] 2017-12-04 21:14
The [Containerise Add-on](https://addons.mozilla.org/en-US/firefox/addon/containerise/) lets you specify Domain and automatically includes Subdomains.

**Comment by groovecoder** [comment] 2017-12-05 19:06
Duplicate of https://github.com/mozilla/multi-account-containers/issues/473.

**Closed by groovecoder** 2017-12-05 19:06 UTC
Labels: assignment, duplicate
