### ISSUE TITLE
Request - can we get more colours please

### ISSUE THREAD

**Issue by gomopa** [mozilla/multi-account-containers#1101] opened 2018-01-28 11:21 UTC
Request - can we get more colours please

Thanks Go

**Comment by grahamperrin** [comment] 2018-02-18 16:10
Duplicate of [Let users set custom colors · Issue #391 · mozilla/multi-account-containers](https://github.com/mozilla/multi-account-containers/issues/391)

**Comment by groovecoder** [comment] 2018-02-20 16:25
Closing as dupe of #391. Please upvote and comment there.

**Closed by groovecoder** 2018-02-20 16:25 UTC
Labels: enhancement, needs: UX
