### ISSUE TITLE
Deleted container comes back to life

### ISSUE THREAD

**Issue by aplatypus** [mozilla/multi-account-containers#1723] opened 2020-04-29 09:31 UTC
- Multi-Account Containers Version:
- Operating System + Version:
- Firefox Version:
- Other installed Add-ons + Version + Enabled/Disabled-Status:

### Actual behavior

  * I deleted a container on from my Multi-containers, call it "CAN"
  * This was effective in correcting another problem 
     * New tabs were opening in "CAN" despite the "only open using CAN" option being clear.
     * After deletion, tabs open in container they are directed to, using the "Reopen in container" menu item.
  * The remoded container is NO Longer in the list. (/)
  *  After some time, the removed container has returned
  * Using the "Reopen in container" option again opens the desired web page in the "CAN" container(grrr)
  
It is like a bad zombie movie -- You just cant KILL a container.

### Expected behavior

  * Want a deleted container GONE
  * No resurrection
  * GONE

Second and may be more useful

  * _If_ I make a new container with the name "CAN", that should be a NEW container without baggage or settings from any previous container with that name.
  * It does seem when "CAN" reappears that it has the settings or preferences of the deleted instance.

I would suggest ...

  1. Use some kind of UUID for identifying containers so that the name is irrelevant.
  2. Purge settings of options related to a removed name
  3. Provide a method to Export/Import container settings to a JSON file
      * An import shall completely replace any OLD values
      * Or import can have the option to "merge" or "replace"

### Steps to reproduce

I am not sure how it happens.  I suspect the Firefox sync.  

1. Make sure you have at least two firefox instances running and logged in to sync.
2. Make a container called "CAN"
3. Pick a target web page and set: "Always open in CAN" ON
4. Select that web URL a few times form other containers ensure it always opens in "CAN"
5. Clear the "Always open in CAN" OFF option.
6. Select that web URL a few times form other containers ensure it Does Not open them with CAN unless explicitly directed.
7. Delete the "CAN" container
8. Wait / Browse some more
9. Inspect the container list: "CAN" may yet be returned
10. Click on the test url - it starts opening in "CAN" containers again.
11. Again delete the container "CAN"
12. Repeat steps 5 through 11

I have run throught points 5 through 11 at least 10 times today.  On another occasion I had to keep doing this on my daughter's PC.  She has no privileges on the Windows PC so I thought I was because of that.

I have access on both Windows and Linux -- Same problem. 

### Notes

It is very frustrating.  It can also have significant consequences.  My dauthter was unable to open her on-line schooling becaue the URS-s were being direected to the "CAN" container.  Google or someone refused to even "see her id" in that container.  It becomes an endless circle.

What if ... the wrong container opened in the wrong container  and you didn't notice.  You compose a insensitive message or post and publish that message.

Only to learn that you have just trashed all your boss in a public forum, not your nice quiet personal chat page.

### software

  * firefox: Developer 76.0b8 (64-bit)
  * Linux 19.10 and Windows 10
  * Multi-containers: Version 6.2.5 / Last Updated 15 April 2020

**Comment by Solid-Ice8** [comment] 2020-04-30 00:33
Keep in mind you can manually remove containers within the containers.json file. Many people have suggested sorting containers and this how too. Look at my reference here: #1707

**Comment by Solid-Ice8** [comment] 2020-04-30 00:40
This is also repeat of #1696

**Comment by dannycolin** [comment] 2022-12-28 00:50
Duplicate of #1696

**Closed by dannycolin** 2022-12-28 00:50 UTC
Labels: bug, Component: Sync
