### ISSUE TITLE
"Search container name" cant search for numbers

### ISSUE THREAD

**Issue by user18081972** [mozilla/multi-account-containers#2655] opened 2024-08-06 13:23 UTC
### Before submitting a bug report

- [X] I updated to the latest version of Multi-Account Container and tested if I can reproduce the issue
- [X] I searched for existing reports to see if it hasn't already been reported

### Step to reproduce

1. open the multi account container dropout in the Toolbar.
2. Click on the search bar
3. type a number

### Actual behavior

Whenever the multi account container toolbar dropout is open, typing any number opens a container.

### Expected behavior

When the search bar in the multi account container toolbar dropout is active, typing a number into the searchbar should not open a container and close out the toolbar dropout. It should just let you search for the container you are looking for.

**Comment by dannycolin** [comment] 2024-08-06 14:11
Duplicate of #2650

**Closed by dannycolin** 2024-08-06 14:11 UTC
Labels: bug
