### ISSUE TITLE
Disabling extension closes all container tabs without warning

### ISSUE THREAD

**Issue by wanderview** [mozilla/multi-account-containers#864] opened 2017-09-26 16:48 UTC
I disabled the extension in about:addons.  This closed all my container tabs without warning.  Re-enabling the extension did not restore the tabs.  This was a bit unexpected and inconvenient.

**Comment by jonathanKingston** [comment] 2017-09-26 18:18
This would require changing platform itself when the last contextualIdentities extension is removed. Currently I think we warn when we remove containers in about:preferences but hitting remove doesn't doe that here or disable etc. (this might actually be a dupe with a platform bug, will check).

**Comment by grahamperrin** [comment] 2017-10-03 20:32
> … disabled the extension in about:addons. This closed all my container tabs … 

Not reproducible here with Multi-Account Containers 4.0.3 added to a clean profile of Firefox 56.0 (64-bit) on FreeBSD-CURRENT. Neither disabling nor removing the extension caused disappearance of the one page that I had contained. 

After removing the extension I quit then relaunched Firefox, restored the previous session then non-extended Firefox presented the page, contained. All good.

**Comment by wanderview** [comment] 2017-10-03 20:34
My tabs were pinned container tabs on FF57.  Not sure if that difference matters.

**Comment by wanderview** [comment] 2017-10-04 01:43
Also, I had deleted all the default containers and created these containers from scratch.  Perhaps if you have the default containers they are not reset?

**Comment by grahamperrin** [comment] 2017-10-04 19:02
> … pinned container tabs on FF57. Not sure if that difference matters.

I can't comment on 57 but for what it's worth, with _removal_: 

> … [created a test profile, installed and removed the addon, no browser restart required and all pinned tabs are still there.](https://github.com/mozilla/multi-account-containers/issues/505#issuecomment-333965728)

**Comment by grahamperrin** [comment] 2017-10-05 03:41
https://blog.mozilla.org/tanvi/2017/10/03/update-firefox-containers/#comment-36315 (2017-10-04) mentions a bug fix relating to loss of hidden containers. Did that fix occur after the 2017-09-26 opening of this issue? I wonder. 

Also @wanderview please: what's your platform? And can you recall the exact version or build of 57 that was in use when this issue was reported? 

I might have read, somewhere, that PPA provision of builds of e.g. `firefox-trunk` for Linux sometimes lags a little behind what's built in other areas.

**Comment by jonathanKingston** [comment] 2017-10-09 21:03
> Also, I had deleted all the default containers and created these containers from scratch. Perhaps if you have the default containers they are not reset?

57+ uses native central behaviour on deleting containers and resetting them.

The current algo for this is here:
http://searchfox.org/mozilla-central/source/toolkit/components/contextualidentity/ContextualIdentityService.jsm#124

Given the two main places for this experience are:
- Disabling an addon in about:addons
- Disabling an addon in about:preferences

We could probably just put warnings there for now, however I will speak with the web extension folk to see if there is a better way. about:addons is likely more of a priority as the intent in about:preferences is to disable containers anyway.

**Comment by grahamperrin** [comment] 2018-02-21 19:10
Drive-by thought: if Firefox Sync will cause uninstallation of all containers-related extensions from a second or nth computer, then should the user be warned at each computer?

**Comment by stoically** [comment] 2018-03-12 03:58
Not sure if that's feasible/wanted, but might it be an alternative to reset containers only if the last container Add-on is removed instead of just disabled?

**Comment by ramast** [comment] 2019-05-04 16:19
So this problem has affected virtually every user of firefox containers today. With no warning of any kind.
I understand this is open source and is provided as is but is there really no solution whatsoever to this? Have I really lost all my containers and all saves sessions of all websites ?

**Comment by 3j9fkyahunqoxwqu** [comment] 2019-05-04 16:24
Hi
i don't know about addon developing but may be a way to backup/restore containers also be a great workaround for this issue if it is hard to fix or impossible due to APIs or ...
Thanks

**Comment by codingchristoff** [comment] 2019-05-09 11:59
Recently I started FireFox on both my Laptop and Desktop and both started in what seemed like a fresh install. All add-ons had been disabled. When I investigated it stated they were out of date and unsupported. When I closed FF and re-opened my add ons came back however it seemed they had all reset to default. 

The containers is by far the most annoying as all my custom containers have now been lost. 

Expected Result:

Disabled add-ons should not delete config files by default. Allowing users to restore their custom settings.

**Comment by grahamperrin** [comment] 2019-05-12 17:43
**Enable Built-in Containers Feature**
<https://addons.mozilla.org/addon/enable-builtin-containers/>

> … can be useful to keep the built-in containers on and avoid container data loss.

**Comment by dannycolin** [comment] 2019-05-12 18:07
@grahamperrin it wouldn't have help with the certificate problem since all addons were disabled automatically. 

It'd be better to open an issue on bugzilla.mozilla.org asking the devs to make sure that `privacy.userContext.enabled` can't be reset by Firefox if it has been set to `true` manually or by an extension that is still installed even if it's disabled.

@jonathanKingston did you have any luck contacting the devs?

**Comment by grahamperrin** [comment] 2019-05-26 15:27
> wouldn't have help with the certificate problem 

True, but it's an extension that might help to minimise the future possibility of a user shooting himself or herself in the foot. 

> … asking the devs to make sure that `privacy.userContext.enabled` can't be reset …

I should encourage a more fundamental re-think. Essentially: 

- disabling the containers feature of Firefox must not delete container-related data.

**Comment by dannycolin** [comment] 2019-05-26 16:34
> I should encourage a more fundamental re-think. Essentially:
> 
>     * disabling the containers feature of Firefox must not delete container-related data.

@grahamperrin FYI, https://bugzilla.mozilla.org/show_bug.cgi?id=1549204

**Comment by grahamperrin** [comment] 2019-05-26 16:43
Thanks, I began following that bug a couple of weeks ago but hadn't digested it. I'm with https://bugzilla.mozilla.org/show_bug.cgi?id=1549204#c3

**Comment by kendallcorner** [comment] 2019-12-05 16:40
Since the original issue has been solved and there's a bugzilla bug open for the remainder of concerns, I'm going to close this, but feel free to reopen if you would prefer it stay open.

**Closed by kendallcorner** 2019-12-05 16:40 UTC
Labels: needs: M-C Platform
