### ISSUE TITLE
Allow other extensions to ask for assignments

### ISSUE THREAD

**Issue by totallymike** [mozilla/multi-account-containers#1105] opened 2018-01-29 20:14 UTC
I'd love to teach contextPlus to ask if a given hostname is assigned to a context, so that I may warn users that my extension probably won't behave the way they expect if they try to open a URL in a different context.

Would it be possible to make some messages, such as `getAssignment` available to external messages?

Or is there a different flow available for such facilities?

Thanks

**Comment by stoically** [comment] 2018-01-30 07:00
I've actually opened a [PullRequest](https://github.com/mozilla/multi-account-containers/pull/1095) regarding that just a few days ago. :)

**Comment by TanviHacks** [comment] 2018-01-30 18:19
Duplicate of https://github.com/mozilla/multi-account-containers/pull/1095

**Closed by TanviHacks** 2018-01-30 18:19 UTC
