### ISSUE TITLE
Keyboard shortcut for new private window no longer working in firefox, works when extension is disabled

### ISSUE THREAD

**Issue by kavanaram** [mozilla/multi-account-containers#1790] opened 2020-07-12 08:02 UTC
- Multi-Account Containers Version: 7.0.0
- Operating System + Version: MacOS Catalina 10.15.5 (19F101) (additionally, I use Dvorak Right-handed keyboard layout). 
- Firefox Version: 78.0.2 (64-bit)
- Other installed Add-ons + Version + Enabled/Disabled-Status: 

Adblock Plus - free ad blocker	3.9	true	{d10d0bf8-f5b5-c8b4-a8b2-2b9879e08c5d}
Amazon.co.uk	1.1	true	amazon@search.mozilla.org
Bing	1.1	true	bing@search.mozilla.org
DuckDuckGo	1.0	true	ddg@search.mozilla.org
eBay	1.0	true	ebay@search.mozilla.org
Firefox Multi-Account Containers	7.0.0	true	@testpilot-containers
Google	1.0	true	google@search.mozilla.org
Grammarly for Firefox	8.864.0	true	87677a2c52b84ad3a151a4a72f5bd3c4@jetpack
Juris-M Connector	5.0.89.2	true	jurism@juris-m.github.io
Save Tiddlers	0.8	true	random201709301147@buggyjef.uk
Wikipedia (en)	1.0	true	wikipedia@search.mozilla.org

### Actual behavior

When I type the shortcut Cmd + Shift + P to open a new private window, this does not work (it highlights 'File' for a second but does not do anything else). 
The shortcut works when I disable Multi-account containers and stops working when I re-enable it. The shortcut was working yesterday with Multi-account containers enabled (it's possible the latest update has done something to it). Using File>New Private Window works fine and opens a new private window. 

### Expected behavior

Firefox should open a new private window. 

### Steps to reproduce
1. Set keyboard layout to dvorak right-handed keyboard 
2. Enable multi-account containers 
3. Use keyboard shortcuts (Cmd + Shift + P) to open new private window

**Comment by maxxcrawford** [comment] 2020-07-13 03:07
Can you confirm this is issue exists when ONLY this extension is installed/active? I'm unable to reproduce it as described.

**Comment by dannycolin** [comment] 2022-11-01 01:36
I also can't reproduce in the latest version (8.0.7). I'm closing this issue since there's been no answer back by the reporter.

**Closed by dannycolin** 2022-11-01 01:36 UTC
Labels: cannot reproduce, Component: Shortcuts
