### ISSUE TITLE
Add additional ruleset for Site List restrictions

### ISSUE THREAD

**Issue by maxxcrawford** [mozilla/multi-account-containers#2057] opened 2021-05-24 14:50 UTC
_Issue copied via a submission to `containers@mozilla.com` email:_ 

I support a number of customers using different environments within the same data center share the same domain, but the subfolders really differentiate different customers or different environments.

For example:
- https://example.com/customer1
- https://example.com/customer2
 
My problem is I need to be logged into both at the same time and I manually open different containers to do so.  

Unfortunately I cannot use the Site List restrictions to do this automatically since they only check the domain in the path and both links would default to the same container.  Any way you could enhance multi-account containers to allow for specific paths defaulting to a container?

**Comment by maxxcrawford** [comment] 2021-05-24 14:50
Could be solved by #1984

**Comment by rektide** [comment] 2021-06-23 18:01
As someone with a couple different github accounts that are dedicated to specific projects, I can not begin to state how radically this would improve my life. Having a way to make certain projects open to certain containers would make Multi-Account-Containers soo much more useable.

For example, if I come here (https://github.com/mozilla/multi-account-containers/) it'd be great for it to open in my Personal container. If I go to my work (https://github.com/yoyodyne-enterprises/) it'd be great to open in the Work container.

**Comment by rektide** [comment] 2021-06-23 18:02
Possible dupe of #691

**Comment by MadManMoon** [comment] 2022-05-09 11:58
I really, really want same/similar functionality to this, and I'm pretty sure that it's been asked for perhaps alongside similar request like wildcard and/or regex entries.

I went long, so I'll hide the rest below.
<details><summary>My Ridiculousness</summary>

I **think** (_if I understand, and support, the original request rightly_) that this would need stronger, sandboxed, cookie management. In addition to that, some more configurable options to make this a 'true' multi-account container infrastructure, no?

For example, if I have an 'always open this page in' for (example) a Google login, then no amount of URL inquisition will enable me to log in to separate Google Accounts. Moreso then shift those logins to different account containers, as the Google Login will always go to the container that I've set for that URL. ¹

Although, that said ... I wonder if just adding a '**_This time only_**' option (_to ignore auto-container_) would be a good work around here? I'm assuming that the FFMAC cookie infrastructure is resilient enough for that.

---

Looking at @rektide's request, you wouldn't just be able to get away with temporarily removing the "open github links in the git container" to log in to 3 different accounts in different containers. Because that would begin to get tiresome after doing it so many times when the logins inevitably expire, or you have cookie protections on a laptop/mobile device.

Equally, with things like YouTube accounts (_or 'channels' - of which you can have MANY_), I'd *really* enjoy being able to open comedy links in the channel I have for gaming the algorithm to comedy, coding to my code account, gaming to the gaming, and KPop to ... you get the point. However each time it would need a possible login, and/or potentially a different Google Account. Perhaps 'sub-containers' would be a good option? I dunno. 😏

All the same it's a definitively useful request, which I 100% support.

---

¹ Google accounts may be a bad example, as I may or may not have just realised that because the g-Login is on a subdomain that by removing accounts dot google dot com from a specific container that I might have solved that. 😩😅 Anyway, please pretend that this subdomain login doesn't exist for the purposes of the example!

</details>

**Comment by achernyakevich-sc** [comment] 2022-05-09 12:52
Source issue could be handled by using Containerise add-on together with MAC add-on. You could check [this comment](https://github.com/mozilla/multi-account-containers/issues/1741#issuecomment-1067240605) and probably the whole comments thread.

@maxxcrawford If it really helps then it could be great to close this issue to show others where the solutions could be searched. :)

**Comment by dannycolin** [comment] 2022-06-15 00:04
> Possible dupe of #691

Yep. Closing as duplicate of #691 since pattern matchin (regex) would be the solution for this.

**Closed by dannycolin** 2022-06-15 00:04 UTC
Labels: Feature request
