### ISSUE TITLE
[Feature Request] Ability to assign domains to a container, without visiting the site

### ISSUE THREAD

**Issue by zi0r** [mozilla/multi-account-containers#1317] opened 2018-12-10 15:12 UTC
### Actual behavior
Today, you have to open a container, visit a site, assign it to the container.

### Expected behavior
Ability to goto the container edit page, manually add domains to the list.

### Notes
This would allow you to proactively assign sites to a container.  For example, if you know you want to group all of your shopping sites in a shopping container and know that you commonly shop at 5 different sites, it would be useful to be able to simply enter in all 5 sites at once into the shopping container.

**Comment by gcollura** [comment] 2018-12-17 12:04
I use [containerise](https://github.com/kintesh/containerise), but it would be nice this was included in Containers.

**Comment by musenbaron** [comment] 2019-02-06 09:23
maybe it should be integrated into your favorites

**Comment by stoically** [comment] 2019-05-04 12:49
Duplicate of https://github.com/mozilla/multi-account-containers/issues/719 - please vote there. Thanks!

**Closed by stoically** 2019-05-04 12:49 UTC
