### ISSUE TITLE
Hiding container tabs that use file on the system is not functioning properly

### ISSUE THREAD

**Issue by Alvenix** [mozilla/multi-account-containers#898] opened 2017-10-07 13:10 UTC
Step to produce:
-Drag any file from your computer to a container tab (I have tried pdf and jpg)
-Hide the container tabs
-showing container tabs does not restart the tab of the file.

about:support:
{
  "application": {
    "name": "Firefox",
    "osVersion": "Darwin 16.7.0",
    "version": "56.0",
    "buildID": "20170926190823",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:56.0) Gecko/20100101 Firefox/56.0",
    "safeMode": false,
    "updateChannel": "release",
    "supportURL": "https://support.mozilla.org/1/firefox/56.0/Darwin/en-US/",
    "numTotalWindows": 1,
    "numRemoteWindows": 0,
    "remoteAutoStart": false,
    "currentContentProcesses": 0,
    "maxContentProcesses": 1,
    "autoStartStatus": 7,
    "styloBuild": true,
    "styloDefault": false,
    "styloResult": false,
    "keyGoogleFound": true,
    "keyMozillaFound": true
  },
  "modifiedPreferences": {
    "accessibility.typeaheadfind.flashBar": 0,
    "browser.cache.disk.filesystem_reported": 1,
    "browser.cache.disk.hashstats_reported": 1,
    "browser.cache.disk.smart_size.first_run": false,
    "browser.cache.frecency_experiment": 3,
    "browser.cache.disk.smart_size.use_old_max": false,
    "browser.cache.disk.capacity": 358400,
    "browser.download.manager.alertOnEXEOpen": true,
    "browser.places.smartBookmarksVersion": 8,
    "browser.sessionstore.upgradeBackup.latestBuildID": "20170926190823",
    "browser.startup.homepage_override.mstone": "56.0",
    "browser.startup.homepage": "about:home",
    "browser.startup.homepage_override.buildID": "20170926190823",
    "browser.tabs.warnOnClose": false,
    "browser.tabs.remote.autostart.2": true,
    "browser.urlbar.lastSuggestionsPromptDate": 20170827,
    "browser.urlbar.timesBeforeHidingSuggestionsHint": 0,
    "browser.urlbar.daysBeforeHidingSuggestionsPrompt": 0,
    "dom.apps.lastUpdate.buildID": "20161019084923",
    "dom.push.userAgentID": "1fb5845c780247f88d847727d03d8e3d",
    "dom.apps.reset-permissions": true,
    "dom.apps.lastUpdate.mstone": "49.0.2",
    "extensions.lastAppVersion": "56.0",
    "font.internaluseonly.changed": true,
    "media.webrtc.debug.log_file": "/private/var/folders/3m/3gq7_k6s0xz3vmc21cwc8pph0000gn/T/TemporaryItems/WebRTC.log",
    "media.benchmark.vp9.versioncheck": 2,
    "media.gmp-widevinecdm.lastUpdate": 1507329571,
    "media.gmp-gmpopenh264.lastUpdate": 1493129052,
    "media.gmp-gmpopenh264.abi": "x86_64-gcc3",
    "media.gmp-manager.lastCheck": 1507329965,
    "media.gmp-widevinecdm.abi": "x86_64-gcc3",
    "media.gmp-widevinecdm.version": "1.4.8.1008",
    "media.gmp.storage.version.observed": 1,
    "media.benchmark.vp9.fps": 122,
    "media.gmp-gmpopenh264.version": "1.6",
    "media.gmp-manager.buildID": "20170926190823",
    "network.prefetch-next": false,
    "network.dns.disablePrefetch": true,
    "network.http.speculative-parallel-limit": 0,
    "network.predictor.enabled": false,
    "network.predictor.cleaned-up": true,
    "network.cookie.prefsMigrated": true,
    "places.history.expiration.transient_current_max_pages": 108849,
    "places.database.lastMaintenance": 1506782823,
    "plugin.importedState": true,
    "plugin.disable_full_page_plugin_for_types": "application/pdf",
    "plugins.ctprollout.cohortSample": "0.882355",
    "plugins.ctprollout.cohort": "test",
    "print.printer_HP_LaserJet_P2035.print_orientation": 0,
    "print.printer_HP_LaserJet_P2035.print_margin_right": "0.5",
    "print.printer_HP_LaserJet_P2035.print_edge_top": 0,
    "print.print_paper_width": "  8.50",
    "print.print_to_file": false,
    "print.printer_HP_LaserJet_P2035.print_footerright": "&D",
    "print.print_margin_top": "0.5",
    "print.printer_HP_LaserJet_P2035.print_unwriteable_margin_right": 25,
    "print.printer_HP_LaserJet_P2035.print_resolution": 53746976,
    "print.printer_HP_LaserJet_P2035.print_headerright": "&U",
    "print.print_reversed": false,
    "print.print_orientation": 0,
    "print.printer_HP_LaserJet_P2035.print_edge_right": 0,
    "print.printer_HP_LaserJet_P2035.print_margin_top": "0.5",
    "print.printer_HP_LaserJet_P2035.print_paper_size_unit": 0,
    "print.print_paper_height": " 11.00",
    "print.print_scaling": "  1.00",
    "print.printer_HP_LaserJet_P2035.print_margin_bottom": "0.5",
    "print.printer_HP_LaserJet_P2035.print_paper_width": "  8.50",
    "print.printer_HP_LaserJet_P2035.print_footerleft": "&PT",
    "print.print_unwriteable_margin_right": 25,
    "print.printer_HP_LaserJet_P2035.print_oddpages": true,
    "print.printer_HP_LaserJet_P2035.print_headercenter": "",
    "print.print_unwriteable_margin_left": 25,
    "print.printer_HP_LaserJet_P2035.print_evenpages": true,
    "print.printer_HP_LaserJet_P2035.print_to_file": false,
    "print.printer_HP_LaserJet_P2035.print_unwriteable_margin_bottom": 57,
    "print.printer_HP_LaserJet_P2035.print_margin_left": "0.5",
    "print.printer_HP_LaserJet_P2035.print_shrink_to_fit": true,
    "print.printer_HP_LaserJet_P2035.print_duplex": 0,
    "print.print_paper_size_unit": 0,
    "print.print_unwriteable_margin_bottom": 20,
    "print.print_paper_name": "",
    "print.print_margin_right": "0.5",
    "print.printer_HP_LaserJet_P2035.print_headerleft": "&T",
    "print.printer_HP_LaserJet_P2035.print_paper_height": " 11.00",
    "print.print_paper_data": 0,
    "print.print_oddpages": true,
    "print.printer_HP_LaserJet_P2035.print_scaling": "  1.00",
    "print.print_bgcolor": false,
    "print.printer_HP_LaserJet_P2035.print_page_delay": 50,
    "print.print_bgimages": false,
    "print.print_margin_left": "0.5",
    "print.print_duplex": 71303424,
    "print.printer_HP_LaserJet_P2035.print_footercenter": "",
    "print.printer_HP_LaserJet_P2035.print_paper_name": "",
    "print.print_evenpages": true,
    "print.print_margin_bottom": "0.5",
    "print.printer_HP_LaserJet_P2035.print_paper_data": 0,
    "print.printer_HP_LaserJet_P2035.print_in_color": true,
    "print.printer_HP_LaserJet_P2035.print_reversed": false,
    "print.printer_HP_LaserJet_P2035.print_unwriteable_margin_top": 25,
    "print.print_shrink_to_fit": true,
    "print.print_unwriteable_margin_top": 20,
    "print.printer_HP_LaserJet_P2035.print_edge_bottom": 0,
    "print.printer_HP_LaserJet_P2035.print_unwriteable_margin_left": 25,
    "print.print_in_color": true,
    "print.print_page_delay": 50,
    "print.printer_HP_LaserJet_P2035.print_bgcolor": false,
    "print.printer_HP_LaserJet_P2035.print_edge_left": 0,
    "print.printer_HP_LaserJet_P2035.print_bgimages": false,
    "print.print_resolution": 0,
    "privacy.cpd.siteSettings": true,
    "privacy.userContext.ui.enabled": true,
    "privacy.sanitize.timeSpan": 2,
    "privacy.usercontext.about_newtab_segregation.enabled": true,
    "privacy.userContext.enabled": true,
    "privacy.userContext.longPressBehavior": 2,
    "privacy.cpd.offlineApps": true,
    "security.sandbox.content.tempDirSuffix": "{0e4085df-f111-a340-b84c-7161eb71b8b4}",
    "services.sync.declinedEngines": "",
    "storage.vacuum.last.index": 1,
    "storage.vacuum.last.places.sqlite": 1506176488
  },
  "lockedPreferences": {},
  "media": {
    "currentAudioBackend": "audiounit",
    "currentMaxAudioChannels": 2,
    "currentPreferredChannelLayout": "stereo",
    "currentPreferredSampleRate": 44100,
    "audioOutputDevices": [
      {
        "name": "Internal Speakers",
        "groupId": "AppleHDAEngineOutput:1B,0,1,1:0",
        "vendor": "Apple Inc.",
        "type": 2,
        "state": 2,
        "preferred": 15,
        "supportedFormat": 12336,
        "defaultFormat": 4096,
        "maxChannels": 2,
        "defaultRate": 44100,
        "maxRate": 96000,
        "minRate": 44100,
        "maxLatency": 4861,
        "minLatency": 779
      }
    ],
    "audioInputDevices": [
      {
        "name": "Internal Microphone",
        "groupId": "AppleHDAEngineInput:1B,0,1,0:1",
        "vendor": "Apple Inc.",
        "type": 1,
        "state": 2,
        "preferred": 15,
        "supportedFormat": 12336,
        "defaultFormat": 4096,
        "maxChannels": 2,
        "defaultRate": 44100,
        "maxRate": 96000,
        "minRate": 44100,
        "maxLatency": 4162,
        "minLatency": 80
      }
    ]
  },
  "javaScript": {
    "incrementalGCEnabled": true
  },
  "accessibility": {
    "isActive": false,
    "forceDisabled": 0,
    "handlerUsed": false
  },
  "libraryVersions": {
    "NSPR": {
      "minVersion": "4.16",
      "version": "4.16"
    },
    "NSS": {
      "minVersion": "3.32.1",
      "version": "3.32.1"
    },
    "NSSUTIL": {
      "minVersion": "3.32.1",
      "version": "3.32.1"
    },
    "NSSSSL": {
      "minVersion": "3.32.1",
      "version": "3.32.1"
    },
    "NSSSMIME": {
      "minVersion": "3.32.1",
      "version": "3.32.1"
    }
  },
  "userJS": {
    "exists": false
  },
  "crashes": {
    "submitted": [],
    "pending": 0
  },
  "sandbox": {
    "contentSandboxLevel": 3,
    "effectiveContentSandboxLevel": 3
  },
  "graphics": {
    "numTotalWindows": 1,
    "numAcceleratedWindows": 1,
    "windowLayerManagerType": "OpenGL",
    "windowLayerManagerRemote": true,
    "windowUsingAdvancedLayers": false,
    "adapterDescription": "",
    "adapterVendorID": "0x8086",
    "adapterDeviceID": "0x162b",
    "adapterRAM": "",
    "adapterDrivers": "",
    "driverVersion": "",
    "driverDate": "",
    "webgl1Renderer": "Intel Inc. -- Intel(R) Iris(TM) Graphics 6100",
    "webgl1Version": "2.1 INTEL-10.25.17",
    "webgl1DriverExtensions": "GL_ARB_color_buffer_float GL_ARB_depth_buffer_float GL_ARB_depth_clamp GL_ARB_depth_texture GL_ARB_draw_buffers GL_ARB_draw_elements_base_vertex GL_ARB_draw_instanced GL_ARB_fragment_program GL_ARB_fragment_program_shadow GL_ARB_fragment_shader GL_ARB_framebuffer_object GL_ARB_framebuffer_sRGB GL_ARB_half_float_pixel GL_ARB_half_float_vertex GL_ARB_instanced_arrays GL_ARB_multisample GL_ARB_multitexture GL_ARB_occlusion_query GL_ARB_pixel_buffer_object GL_ARB_point_parameters GL_ARB_point_sprite GL_ARB_provoking_vertex GL_ARB_seamless_cube_map GL_ARB_shader_objects GL_ARB_shader_texture_lod GL_ARB_shading_language_100 GL_ARB_shadow GL_ARB_sync GL_ARB_texture_border_clamp GL_ARB_texture_compression GL_ARB_texture_compression_rgtc GL_ARB_texture_cube_map GL_ARB_texture_env_add GL_ARB_texture_env_combine GL_ARB_texture_env_crossbar GL_ARB_texture_env_dot3 GL_ARB_texture_float GL_ARB_texture_mirrored_repeat GL_ARB_texture_non_power_of_two GL_ARB_texture_rectangle GL_ARB_texture_rg GL_ARB_transpose_matrix GL_ARB_vertex_array_bgra GL_ARB_vertex_blend GL_ARB_vertex_buffer_object GL_ARB_vertex_program GL_ARB_vertex_shader GL_ARB_window_pos GL_EXT_abgr GL_EXT_bgra GL_EXT_blend_color GL_EXT_blend_equation_separate GL_EXT_blend_func_separate GL_EXT_blend_minmax GL_EXT_blend_subtract GL_EXT_clip_volume_hint GL_EXT_debug_label GL_EXT_debug_marker GL_EXT_draw_buffers2 GL_EXT_draw_range_elements GL_EXT_fog_coord GL_EXT_framebuffer_blit GL_EXT_framebuffer_multisample GL_EXT_framebuffer_multisample_blit_scaled GL_EXT_framebuffer_object GL_EXT_framebuffer_sRGB GL_EXT_geometry_shader4 GL_EXT_gpu_program_parameters GL_EXT_gpu_shader4 GL_EXT_multi_draw_arrays GL_EXT_packed_depth_stencil GL_EXT_packed_float GL_EXT_provoking_vertex GL_EXT_rescale_normal GL_EXT_secondary_color GL_EXT_separate_specular_color GL_EXT_shadow_funcs GL_EXT_stencil_two_side GL_EXT_stencil_wrap GL_EXT_texture_array GL_EXT_texture_compression_dxt1 GL_EXT_texture_compression_s3tc GL_EXT_texture_env_add GL_EXT_texture_filter_anisotropic GL_EXT_texture_integer GL_EXT_texture_lod_bias GL_EXT_texture_rectangle GL_EXT_texture_shared_exponent GL_EXT_texture_sRGB GL_EXT_texture_sRGB_decode GL_EXT_timer_query GL_EXT_transform_feedback GL_EXT_vertex_array_bgra GL_APPLE_aux_depth_stencil GL_APPLE_client_storage GL_APPLE_element_array GL_APPLE_fence GL_APPLE_float_pixels GL_APPLE_flush_buffer_range GL_APPLE_flush_render GL_APPLE_object_purgeable GL_APPLE_packed_pixels GL_APPLE_pixel_buffer GL_APPLE_rgb_422 GL_APPLE_row_bytes GL_APPLE_specular_vector GL_APPLE_texture_range GL_APPLE_transform_hint GL_APPLE_vertex_array_object GL_APPLE_vertex_array_range GL_APPLE_vertex_point_size GL_APPLE_vertex_program_evaluators GL_APPLE_ycbcr_422 GL_ATI_separate_stencil GL_ATI_texture_env_combine3 GL_ATI_texture_float GL_ATI_texture_mirror_once GL_IBM_rasterpos_clip GL_NV_blend_square GL_NV_conditional_render GL_NV_depth_clamp GL_NV_fog_distance GL_NV_light_max_exponent GL_NV_texgen_reflection GL_NV_texture_barrier GL_SGIS_generate_mipmap GL_SGIS_texture_edge_clamp GL_SGIS_texture_lod ",
    "webgl1Extensions": "ANGLE_instanced_arrays EXT_blend_minmax EXT_color_buffer_half_float EXT_frag_depth EXT_sRGB EXT_shader_texture_lod EXT_texture_filter_anisotropic MOZ_debug OES_element_index_uint OES_standard_derivatives OES_texture_float OES_texture_float_linear OES_texture_half_float OES_texture_half_float_linear OES_vertex_array_object WEBGL_color_buffer_float WEBGL_compressed_texture_s3tc WEBGL_compressed_texture_s3tc_srgb WEBGL_debug_renderer_info WEBGL_debug_shaders WEBGL_depth_texture WEBGL_draw_buffers WEBGL_lose_context MOZ_WEBGL_lose_context MOZ_WEBGL_compressed_texture_s3tc MOZ_WEBGL_depth_texture",
    "webgl1WSIInfo": "CGL",
    "webgl2Renderer": "Intel Inc. -- Intel(R) Iris(TM) Graphics 6100",
    "webgl2Version": "4.1 INTEL-10.25.17",
    "webgl2DriverExtensions": "GL_ARB_blend_func_extended GL_ARB_draw_buffers_blend GL_ARB_draw_indirect GL_ARB_ES2_compatibility GL_ARB_explicit_attrib_location GL_ARB_gpu_shader_fp64 GL_ARB_gpu_shader5 GL_ARB_instanced_arrays GL_ARB_internalformat_query GL_ARB_occlusion_query2 GL_ARB_sample_shading GL_ARB_sampler_objects GL_ARB_separate_shader_objects GL_ARB_shader_bit_encoding GL_ARB_shader_subroutine GL_ARB_shading_language_include GL_ARB_tessellation_shader GL_ARB_texture_buffer_object_rgb32 GL_ARB_texture_cube_map_array GL_ARB_texture_gather GL_ARB_texture_query_lod GL_ARB_texture_rgb10_a2ui GL_ARB_texture_storage GL_ARB_texture_swizzle GL_ARB_timer_query GL_ARB_transform_feedback2 GL_ARB_transform_feedback3 GL_ARB_vertex_attrib_64bit GL_ARB_vertex_type_2_10_10_10_rev GL_ARB_viewport_array GL_EXT_debug_label GL_EXT_debug_marker GL_EXT_framebuffer_multisample_blit_scaled GL_EXT_texture_compression_s3tc GL_EXT_texture_filter_anisotropic GL_EXT_texture_sRGB_decode GL_APPLE_client_storage GL_APPLE_container_object_shareable GL_APPLE_flush_render GL_APPLE_object_purgeable GL_APPLE_rgb_422 GL_APPLE_row_bytes GL_APPLE_texture_range GL_ATI_texture_mirror_once GL_NV_texture_barrier",
    "webgl2Extensions": "EXT_color_buffer_float EXT_texture_filter_anisotropic EXT_disjoint_timer_query MOZ_debug OES_texture_float_linear WEBGL_compressed_texture_s3tc WEBGL_debug_renderer_info WEBGL_debug_shaders WEBGL_lose_context MOZ_WEBGL_lose_context MOZ_WEBGL_compressed_texture_s3tc",
    "webgl2WSIInfo": "CGL",
    "info": {
      "AzureCanvasBackend": "skia",
      "AzureFallbackCanvasBackend": "none",
      "AzureContentBackend": "skia",
      "AzureCanvasAccelerated": 1,
      "TileHeight": 1024,
      "TileWidth": 1024
    },
    "featureLog": {
      "features": [
        {
          "name": "HW_COMPOSITING",
          "description": "Compositing",
          "status": "available",
          "log": [
            {
              "type": "default",
              "status": "available"
            }
          ]
        },
        {
          "name": "OPENGL_COMPOSITING",
          "description": "OpenGL Compositing",
          "status": "available",
          "log": [
            {
              "type": "default",
              "status": "available"
            }
          ]
        },
        {
          "name": "WEBRENDER",
          "description": "WebRender",
          "status": "unavailable",
          "log": [
            {
              "type": "default",
              "status": "opt-in",
              "message": "WebRender is an opt-in feature"
            },
            {
              "type": "runtime",
              "status": "unavailable",
              "message": "Build doesn't include WebRender"
            }
          ]
        }
      ],
      "fallbacks": []
    },
    "crashGuards": []
  },
  "experiments": [],
  "extensions": [
    {
      "name": "Multi-Account Containers",
      "version": "4.0.3",
      "isActive": true,
      "id": "@testpilot-containers"
    },
    {
      "name": "To Google Translate",
      "version": "2.2",
      "isActive": true,
      "id": "jid1-93WyvpgvxzGATw@jetpack"
    },
    {
      "name": "uBlock Origin",
      "version": "1.14.10",
      "isActive": true,
      "id": "uBlock0@raymondhill.net"
    },
    {
      "name": "Web Paint",
      "version": "1.2.6",
      "isActive": true,
      "id": "jid1-0dhOSYKGj326og@jetpack"
    }
  ],
  "features": [
    {
      "name": "Activity Stream",
      "version": "0.0.0",
      "id": "activity-stream@mozilla.org"
    },
    {
      "name": "Application Update Service Helper",
      "version": "2.0",
      "id": "aushelper@mozilla.org"
    },
    {
      "name": "Click-to-Play staged rollout",
      "version": "1.4",
      "id": "clicktoplay-rollout@mozilla.org"
    },
    {
      "name": "Firefox Screenshots",
      "version": "10.12.0",
      "id": "screenshots@mozilla.org"
    },
    {
      "name": "Follow-on Search Telemetry",
      "version": "0.9.3",
      "id": "followonsearch@mozilla.com"
    },
    {
      "name": "Form Autofill",
      "version": "1.0",
      "id": "formautofill@mozilla.org"
    },
    {
      "name": "Multi-process staged rollout",
      "version": "3.00",
      "id": "e10srollout@mozilla.org"
    },
    {
      "name": "Photon onboarding",
      "version": "0.1",
      "id": "onboarding@mozilla.org"
    },
    {
      "name": "Pocket",
      "version": "1.0.5",
      "id": "firefox@getpocket.com"
    },
    {
      "name": "Shield Recipe Client",
      "version": "65",
      "id": "shield-recipe-client@mozilla.org"
    },
    {
      "name": "Web Compat",
      "version": "1.1",
      "id": "webcompat@mozilla.org"
    }
  ]
}

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/MAC-613)

**Comment by SoftVision-EmilPasca** [comment] 2017-10-09 09:26
I have also managed to reproduce the issue on Mac 10.12, Windows 10 x64 and Ubuntu 14.04, using the latest Firefox Release (56.0) and latest Nightly (58.0a1-20171008220130).

**[Notes]:**
- Added a screen recording of the issue:
![containers_localfile_issue](https://user-images.githubusercontent.com/20083658/31331920-fe132c44-acec-11e7-8b40-4c97c82bf2fb.gif)

**Comment by grahamperrin** [comment] 2021-04-28 05:54
## `file:///⋯`

There's almost certainly something hide- and `file:///⋯`-related in Bugzilla, or Mozilla wiki, or Mozilla documentation for developers, but I can't find what's required. 

For now, the closest that I can find are: 

* [WebExtensions/Filesystem - MozillaWiki](https://wiki.mozilla.org/WebExtensions/Filesystem)
* [File and Directory Entries API - Web APIs | MDN](https://developer.mozilla.org/en-US/docs/Web/API/File_and_Directory_Entries_API)

**Comment by dannycolin** [comment] 2023-01-12 00:38
Duplicate of #1407

**Closed by dannycolin** 2023-01-12 00:38 UTC
Labels: bug, Component: Tab
