### ISSUE TITLE
Information leaks among google (mail, calendar) tabs

### ISSUE THREAD

**Issue by lars-t-hansen** [mozilla/multi-account-containers#549] opened 2017-05-29 07:04 UTC
I have a gmail tab open with my work account; I have later opened a Personal container tab with my private email.  But now, when I try to, say, open a new calendar tab from my work account tab, the default credential that is being presented in Google's login window is my personal email.  This suggests information is leaking from the personal tab somehow.

**Comment by jonathanKingston** [comment] 2017-05-29 14:31
@lars-t-hansen are you using non container tabs for work? Could it be that the previous cookies before containers still exist?

**Comment by lars-t-hansen** [comment] 2017-05-29 16:03
> @lars-t-hansen are you using non container tabs for work?

I am.

> Could it be that the previous cookies before containers still exist?

Anything's possible... It's a very new computer and I thought I had been very careful, and I installed Containers pretty much the moment I got it so that I could have a tab for private email, but of course I might not have been careful enough.

I can try to set up Nightly with a clean profile and containers, and see if I can repro.  Might not be today.

**Comment by jonathanKingston** [comment] 2017-05-29 18:30
> I can try to set up Nightly with a clean profile and containers, and see if I can repro. Might not be today.

I would appreciate that, personally I only authenticate with containers themselves. We take containment bugs pretty seriously. If you could make a clean reproduction that would be great.

**Comment by SoftVision-EmilPasca** [comment] 2017-10-12 14:43
I have tested this on Windows 10 x64 with the latest Firefox Release(56.0), latest Beta(57.0b7-20171009192146) and also with the latest Nightly(58.0a1-20171011220113) and haven't managed to reproduce the issue.

After assigning the Personal/Work container to gmail, google calendar, when accessing gmail, there are no credentials suggested, also all gmail or calendar links are correctly opened in the corresponding container.

@lars-t-hansen Is this issue still reproducible on your end? Have you managed to test this with a clean profile on Nightly?

**Comment by lars-t-hansen** [comment] 2017-10-15 10:30
OK, thanks.  Regrettably I've not had time to try to repro the issue locally, and for various reasons I stopped using containers for my separate accounts anyway, so it's not come up naturally.

**Comment by TravisLittlechilds** [comment] 2018-01-29 14:52
I noticed this same behavior and thought it was undesirable a week ago when I installed this. Upon further testing/reinstall of Firefox, it seems to actually be the autofill that is populating across. (Up to the point I save a password, it doesn't do this.)

**Comment by groovecoder** [comment] 2018-01-29 19:43
Ah, this is because we don't separate saved passwords or form auto-fill data by containers. This is [by design](https://wiki.mozilla.org/Security/Contextual_Identity_Project/Containers#What_is_.28and_isn.27t.29_separated_between_Containers) so I'm closing this issue.

**Closed by groovecoder** 2018-01-29 19:43 UTC
Labels: needs: Testing
