### ISSUE TITLE
Assignment of sites

### ISSUE THREAD

**Issue by LeSeigneur00** [mozilla/multi-account-containers#1876] opened 2020-09-26 16:55 UTC
the way to remove a to some container assinged site is a bit too hitten.

can it be possible to assign not only the domain but something after the "/"

for instance... I use different google accounts, one for just googeling and stuff and one which is also the one I use on my phone, so there is the calendar the docs the drive; I've assigned all of them to one container, what works because it's calender.google.com, docs.google.de, drive.google.com; but with some google services it's like google.com/SERVICE

or make a feature/workaroung that if you've got something in front of the "http://" like "[c10]http://" it opens the site in container #10...

**Comment by dannycolin** [comment] 2022-12-30 22:59
Duplicate of #691

**Closed by dannycolin** 2022-12-30 22:59 UTC
