### ISSUE TITLE
Open a new container tab to a specified page/address

### ISSUE THREAD

**Issue by joe-synapps** [mozilla/multi-account-containers#1700] opened 2020-03-31 19:10 UTC
When I open a defined container tab, I always want to go to a certain web page. Using the "always open in" option doesn't work for me because I have multiple containers that I want to use for the same website. Please allow us to specify a default page (home page or new tab page, whatever will work when opening a new container) for each container, allowing duplicates across containers. This would provide some expected default functionality (ease of use and speed) and save some clicking and typing.

**Comment by Canuteson** [comment] 2020-04-06 19:21
Agree this has use cases not covered by "always open in", a simple example would be having multilple Gmail tabs open to different accounts simulataneously, and having a "personal gmail" and "work gmail" tabs, which both always open to Gmail.

**Comment by linkp** [comment] 2020-07-22 19:04
This is a duplicate of: #375

**Closed** 2022-06-13 13:02 UTC
