### ISSUE TITLE
Add option in settings to allow newly created tabs to be in same container

### ISSUE THREAD

**Issue by robotichead** [mozilla/multi-account-containers#1257] opened 2018-09-07 10:45 UTC
Sometimes when working in a "Work" container, I press CTRL + T (or the mac equivalent) and it will open up a regular tab. It would be nice to have the option to turn on the ability for when this happens the tab will open up in the exact same container.

Another option would be able to add shortcuts to the containers - for example CTRL + T + 1

**Comment by groovecoder** [comment] 2018-09-07 15:28
Duplicate of https://github.com/mozilla/multi-account-containers/issues/462. Please upvote there.

**Closed by groovecoder** 2018-09-07 15:28 UTC
Labels: duplicate
