### ISSUE TITLE
Add ability to hide the page action icon

### ISSUE THREAD

**Issue by iliadaili** [mozilla/multi-account-containers#2101] opened 2021-08-12 21:50 UTC
Hi! My suggestion is for the addition of more options to customize how multi account container looks on your browser. For example, something that bothers me, but is inevitable if you use multi acc containers is the colored strip above container tabs, it really stands out for me. Maybe, there could be an option to remove it, and something else that I thought about was an option to fade the name of the container on the address bar, also to make it stand out less. I'm sure many people are into the colorful visuals added by the extension, as it can help you keep track of what container why are using, but I'm sure many people want to have a more clean interface, and it would be nice if the extension was more customizable to please different preferences. An option to remove the new ''always open in this container'' icon on the address bar, instead of making it an obligatory addition could also be interesting. It's nice to be able to customize extensions, since one of Firefox's strongest selling points it's how it is very customizable. The suggestion here is for the addition of an option to remove the colored stripe on the container tabs, with a few other ideas given after I presented it, but it's really about suggesting Multi Account Containers was more customizable in general.

**Comment by achernyakevich-sc** [comment] 2021-08-13 15:41
You problems with "the colored strip above container tabs" caused by upgrade to Firefox 90-91. These versions have enable Proton UI and it looks that with this UI multi-container add-on just don't have implemented this kind highlighting.

So I would propose you to treat your issue as duplicate of more detailed #2102 and vote for  that one. :)

P.S. Proton UI looks as completely unexpected for Add-Ons developers and looking very strange from the point of UI/UX for desktop. I know many people who decide to stay with Firefox 90< version because of Proton UI.

**Comment by iliadaili** [comment] 2021-08-14 18:28
> 
> 
> You problems with "the colored strip above container tabs" caused by upgrade to Firefox 90-91. These versions have enable Proton UI and it looks that with this UI multi-container add-on just don't have implemented this kind highlighting.
> 
> So I would propose you to treat your issue as duplicate of more detailed #2102 and vote for that one. :)
> 
> P.S. Proton UI looks as completely unexpected for Add-Ons developers and looking very strange from the point of UI/UX for desktop. I know many people who decide to stay with Firefox 90< version because of Proton UI.

I see. Should I close the issue then?

**Comment by iliadaili** [comment] 2021-08-14 18:30
> 
> 
> You problems with "the colored strip above container tabs" caused by upgrade to Firefox 90-91. These versions have enable Proton UI and it looks that with this UI multi-container add-on just don't have implemented this kind highlighting.
> 
> So I would propose you to treat your issue as duplicate of more detailed #2102 and vote for that one. :)
> 
> P.S. Proton UI looks as completely unexpected for Add-Ons developers and looking very strange from the point of UI/UX for desktop. I know many people who decide to stay with Firefox 90< version because of Proton UI.

Wait, no, I'm suggesting the exact opposite, the addition of an option to remove the colored strip. Right?

**Comment by achernyakevich-sc** [comment] 2021-08-15 16:15
Sorry, you are right. I just reread your initial comment and found that you really ask about introducing settings to enable/disable any kind visualization to identify which container a tab belongs to.

So your issue can't be treated as duplicate of mine. :)

**Comment by iliadaili** [comment] 2021-08-16 15:59
Alright! Np

**Comment by dannycolin** [comment] 2022-07-18 23:54
Both container indicator (tab line, name in address bar) are rendered by Firefox itself and Multi-Account Container can't change or remove them.

> An option to remove the new ''always open in this container'' icon on the address bar, instead of making it an obligatory addition could also be interesting

This is the only actionable item that we can work on. I'll rename the issue to reflect that and would invite you to look (and open a new bug report if it doesn't exist) on bugzilla.mozilla.org for your two other suggestions.

**Comment by dannycolin** [comment] 2022-11-26 01:25
Closing as WONTFIX because pageAction (left one) will be removed in the newest version of WebExtension API called Manifest V3 

See for more informations on Manifest V3: https://extensionworkshop.com/documentation/develop/manifest-v3-migration-guide/

**Closed by dannycolin** 2022-11-26 01:25 UTC
Labels: :+1:  Feature Request
