### ISSUE TITLE
New tab links are opened in foreground (tab is focused), even when Firefox set to open in background

### ISSUE THREAD

**Issue by nekromoff** [mozilla/multi-account-containers#954] opened 2017-11-11 17:24 UTC
Opening a link from a default no-content container in a new tab (e.g. ctrl+click) opens them in new tab in foreground and focusing the tab, which is under different context (e.g. website forced to open in certain context).

This is hardly an expected or even requested behavior. Specifically, this happens even when Firefox has global setting to keep newly opened tabs in background and not to focus them.

**Comment by ArchangeGabriel** [comment] 2017-11-11 17:27
I can confirm that, it annoys me when I opening multiple links and some of them happen to be actually on website that are “containerized”.

**Comment by Svinto** [comment] 2017-11-22 08:40
I also have this problem. I usually open multiple links with ctrl+click from DuckDuckGo and Google search results. Suddenly having one of the new tabs steal focus because they changed container is quite annoying.

**Comment by Softvision-MariusComan** [comment] 2017-11-22 09:31
@Nekromoff, thanks for the report. However this issue is a duplicate of https://github.com/mozilla/multi-account-containers/issues/923. Please follow up that issue and add all your information there.

**Closed by Softvision-MariusComan** 2017-11-22 09:31 UTC
