### ISSUE TITLE
Containers no longer work with microsoft work account

### ISSUE THREAD

**Issue by XCD2018** [mozilla/multi-account-containers#2542] opened 2023-06-18 10:22 UTC
### Before submitting a bug report

- [X] I updated to the latest version of Multi-Account Container and tested if I can reproduce the issue
- [X] I searched for existing reports to see if it hasn't already been reported

### Step to reproduce

1) open a new container  and open a web page related to work software
2) try login to using microsoft account 

### Actual behavior

keep asking for credentials

### Expected behavior

login successfully

### Additional informations

it happens with firefox 113 and the last version of multi container.
wondering if it's not the a variant of the issue with the one related to microsoft teams and school

**Comment by dannycolin** [comment] 2023-06-18 14:58
Duplicate of #2534

**Closed by dannycolin** 2023-06-18 14:58 UTC
Labels: bug
