### ISSUE TITLE
Synchronization duplicating containers

### ISSUE THREAD

**Issue by andresgarcia0313** [mozilla/multi-account-containers#2161] opened 2021-10-24 18:14 UTC
Synchronization duplicating containers
How can I erase the data?

**Comment by iverik-no** [comment] 2021-11-24 08:51
I'm having the same issue. The containers just keeps duplicating, and no amount of deleting them, deleting profiles, signing out of sync on all devices helps. They just keep reappering and duplicating. Deleting the containers from the interface will have them pop up in a short while, with a few extra copies of the containers just to be safe.

I've even done it step-by-step to try to ensure erasure of all containers.
- I've deleted the containers. 
- On all devices.
- Signed out on all but one.
- Made sure they've been deleted on the last one.
- Let it sit to be sure to sync the DELETE to the server(?)
- Deleted browser profile folders on all devices.
- Signed in on one device.
- BOOM, a bazillion duplicate containers.

How can they reapper when they've been deleted?

**Comment by flanger001** [comment] 2023-02-03 15:07
This went away for a while, then reappeared ☹️

**Comment by dannycolin** [comment] 2023-02-03 16:47
Duplicate of #1839

**Closed by dannycolin** 2023-02-03 16:47 UTC
Labels: bug, Component: Sync
