### ISSUE TITLE
Extension automatically grouping tabs based on category

### ISSUE THREAD

**Issue by GeckoEidechse** [mozilla/multi-account-containers#1637] opened 2020-02-14 12:54 UTC
- Multi-Account Containers Version: 6.2.0
- Operating System + Version: Windows 8.1, Ubuntu 19.10
- Firefox Version: 73
- Other installed Add-ons + Version + Enabled/Disabled-Status:

| Name                             | Version   | Activated |
|----------------------------------|-----------|-----------|
| Bitwarden                        | 1.42.2    | true      |
| Cookie AutoDelete                | 3.0.3     | true      |
| Dark Reader                      | 4.8.9     | true      |
| HTTPS Everywhere                 | 2019.11.7 | true      |
| Old Reddit Redirect              | 1.1.2     | true      |
| Privacy Badger                   | 2020.1.13 | true      |
| Snowflake                        | 0.2.1     | true      |
| Stylus                           | 1.5.6     | true      |
| Tree Style Tab                   | 3.3.5     | true      |
| uBlock Origin                    | 1.24.4    | true      |
| Firefox Multi-Account Containers | 6.2.0     | true      |
| Reddit Enhancement Suite         | 5.18.10   | false     |

### Actual behavior

The extension causes tabs from different containers to be reshuffled so that containers from the same category are next to each other.

[Screencap](https://i.imgur.com/Gwu0S14.png)

### Expected behavior

The Multi-Account-Containers extension should not shuffle around the order of tabs.  (Or at least give an option to disable such behaviour)

### Steps to reproduce
1. Make sure *Restore previous session* is enabled in settings and Multi-Account Containers is installed.
2. Create a few tabs in different containers.
3. Disable the extension and restart Firefox
4. Reorder the tabs, preferably such that different categories intersect.

```
[Work]
[Personal]
[Work]
[None]
```

5. Re-enable Multi-Account-Containers and restart Firefox
6. By now all tabs should be reordered based on your list of containers. Going by the default it should now look like:
```
[None]
[Personal]
[Work]
[Work]
```

### Notes

Started happening shortly after the update that allows container syncing dropped.

I do not use the container syncing feature however.

I suspected [Tree Style Tab](https://addons.mozilla.org/de/firefox/addon/tree-style-tab/) to be the culprit initially but disabling the extension and restarting Firefox did not fix the issue.

Removing Multi-Account-Containers no longer causes the tabs to be grouped by category i.e. it seems that Multi-Account-Containers is the culprit.

Additionally Tree Style Tabs and Multi-Account-Containers seem to fight over the tab ordering causing a partial reshuffle of tabs and completely messing up the tab ordering.

**Comment by jjdelc** [comment] 2020-02-14 22:26
I dot not have TST and suffered the same bug. I do have Simple Tab Groups extension installed.

**Comment by camiloaa** [comment] 2020-02-15 08:03
It's not just about addon incompatibility. Even if only using Multi-account containers, tabs seem to reshuffle randomly from time to time. The only work-around is downgrading the addon to 6.1.1.

**Comment by GeckoEidechse** [comment] 2020-02-18 18:08
@jjdelc @camiloaa you two are also experiencing the issue, right? Are you logged in into Firefox Sync?
I'm trying to narrow down what causes this and one notable change from 6.1.1 to 6.2.0 is the possibility to sync containers.
As @camiloaa pointed out, the automatic grouping by container does not happen in 6.1.1

**Comment by jjdelc** [comment] 2020-02-18 18:24
Yes I enabled Sync, it started to happen with Valentine's day update.
It is still consistent every time I open a new container tab all get reorganized (on 6.2.1)

**Comment by escapewindow** [comment] 2020-02-18 18:42
+1. I also am seeing 3 copies of some containers on one of my computers.

**Comment by camiloaa** [comment] 2020-02-25 12:37
@GeckoEidechse: I enabled sync, but the problem persisted even after disabling it. I'm not sure how to revert to a pre-sync state, if possible, because I guess sync data doesn't disappear from the local or remote databases after removing the add-on. If there is a way, let me know, and I'll try a more systematic debugging.

**Comment by GeckoEidechse** [comment] 2020-02-25 14:11
You can [create a new profile](https://support.mozilla.org/en-US/kb/profile-manager-create-and-remove-firefox-profiles) (think of it like a second instance) by starting Firefox from the terminal via `firefox -P`. This should give you a clean Firefox instance to test on.

To switch back to your old profile run `firefox -P` again and select your old one.

**Comment by nikoladev** [comment] 2020-02-26 15:27
I noticed that the re-ordering of tabs only happens if I use my keyboard to select a container and then press `Return` to open a new tab with a new container. If I instead do it by clicking on a container my tabs don't get re-ordered. I also noticed that the re-ordering was predictable, in that the groups always line up in the same way.

While playing around with this I noticed that there is a `Sort tab` button (see below) which causes the exact same behaviour which has been bothering me. So I feel that **the bug is that the `Sort tab` behavior is somehow triggered while using the keyboard to open a new container tab**.

I hope this helps with finding the bug!

I'm using:
* Multi-Account Containers: **6.2.1**
* Firefox: **73.0**
* macOS: **10.14.6**

<hr>

<img width="298" alt="image" src="https://user-images.githubusercontent.com/15011519/75358910-e5710100-58b3-11ea-9766-a9c8464c9e9e.png">

**Comment by nikoladev** [comment] 2020-02-26 15:32
Also, I think that the label `addon incompatibility` is not the right one because this also happens when I disable all addons except for this one. A `bug` label seems to be the right one.

**Comment by rr0ss0rr** [comment] 2020-02-26 15:52
Also, it shouldn’t touch pinned tabs

**Comment by kendallcorner** [comment] 2020-02-26 18:42
Linking #1656

**Comment by kendallcorner** [comment] 2020-02-26 18:43
Are you all using keyboard shortcuts? Could #1656 be the cause of this or do you think it's something else?

**Comment by kendallcorner** [comment] 2020-02-26 18:44
I didn't mean to close

**Comment by nikoladev** [comment] 2020-02-26 19:04
> Are you all using keyboard shortcuts? Could #1656 be the cause of this or do you think it's something else?

I feel like both these issues are about the same thing. The sorting behavior described by @GeckoEidechse in this issue is the exactly same as what I'm experiencing:
* No container
* Personal
* Work
* etc...

And the cause as described by @anbenson in #1656 is also the same as what I've found.

**Comment by anbenson** [comment] 2020-02-26 19:10
Yep, I'm quite certain that my explanation of the bug's cause in #1656 is correct. If I had seen this issue when I initially filed my issue, I would have just commented here.

IMO, all we need at this point is an alternative way to make onboarding a11y-friendly so we can remove the code causing this bug. Or since this is a regression, maybe removing the code anyway could be justified?

**Comment by jjdelc** [comment] 2020-02-26 22:57
> Are you all using keyboard shortcuts? Could #1656 be the cause of this or do you think it's something else?

Yes, I am using keyboard shortcuts to open new containers. Never occurred to me to try clicking through and it doesn't reorder my tabs.

**Comment by GeckoEidechse** [comment] 2020-02-27 12:34
Just here to confirm as well that the reshuffling is only caused when opening a new container tab by pressing enter on the pop-over menu from the addon.

**Comment by kendallcorner** [comment] 2020-02-27 20:54
This fix is merged and sent to the addon's team. You should see an update in 1-2 business days.

**Closed by kendallcorner** 2020-02-27 20:54 UTC
Labels: bug

**Comment by nikoladev** [comment] 2020-02-28 11:38
I can confirm that `v6.2.2` is live and fixes the problem. Thanks for the quick response :)

**Comment by GeckoEidechse** [comment] 2020-02-28 12:35
Same here. Thanks a lot @kendallcorner <3

**Comment by mlncn** [comment] 2022-11-16 03:46
Is it doing it again?  I don't have any other tab management extensions installed and this automatic sorting is happening and driving me crazy.
