### ISSUE TITLE
Advanced Proxy Settings PROBLEM!

### ISSUE THREAD

**Issue by elwason29** [mozilla/multi-account-containers#2278] opened 2022-02-01 05:50 UTC
The "Advanced Proxy Settings" option does not change my proxy on any of my containers. Yesterday it worked. I need help please.

**Comment by Movva** [comment] 2022-02-01 11:48
+1

proxy is not applying on container level, suddenly stopped working in middle of work.

**Comment by srinidhibs** [comment] 2022-02-01 15:16
I received the update for version 8.0.5 today and the proxy settings stopped working. The 8.0.5 version contains the fix for #2258 which could be causing this. Also, the addons page now says that I need a newer version of Firefox to run 8.0.5.

Hence, I downgraded back to 8.0.4 and disabled auto-update for this extension. Everything is back to normal.

**Comment by elwason29** [comment] 2022-02-01 18:40
How did you get down to 8.0.4 again?

**Comment by elwason29** [comment] 2022-02-01 18:47
For those who have the problem you can download the previous version 8.0.4 of the plugin here: https://addons.mozilla.org/en-US/firefox/addon/multi-account-containers/versions/

**Comment by wishbone1138** [comment] 2022-02-02 20:32
Also experienced this, disappointed that this failed open, which impacts what we expect to happen with containers.

**Comment by wishbone1138** [comment] 2022-02-02 21:39
I successfully confirmed the bug.  Containers use the per container proxy setting in 8.0.4, but upgrading to 8.0.5 they seem to completely ignore it.

**Comment by lesleyjanenorton** [comment] 2022-02-09 20:20
Hi folks, if you could include your platform information (mac, linux, Windows) it would be incredible helpful. Thank you!

**Comment by lesleyjanenorton** [comment] 2022-02-09 20:39
@groovecoder is currently working on a fix

**Comment by groovecoder** [comment] 2022-02-09 21:00
Fix is in a PR here: https://github.com/mozilla/multi-account-containers/pull/2283

**Comment by Lem** [comment] 2022-02-15 15:01
Hi @groovecoder,

sadly I have to report that the version 8.0.6 (which is available at addons.mozilla.org) does not fix this problem for me. With 8.0.6 traffic is still not going through my proxy (using _http://12.0.0.1:8080_ in the advanced settings).

Verified it by downgrading to 8.0.4, with this version I see traffic on the proxy.

**Comment by Joibel** [comment] 2022-02-15 15:42
I am also seeing 8.0.6 behaving the same as 8.0.5. 8.0.4 works.

**Comment by Gilgamoth** [comment] 2022-02-18 10:00
Another one to add that 8.0.6 and 8.0.5 don't route proxy traffic and downgrading to 8.0.4 resolves this.
O/S: Windows
FF: 97.0 (64-bit)

**Comment by schurig** [comment] 2022-02-19 22:26
Happens on MacOS too

**Comment by Sol-Illadan** [comment] 2022-02-20 15:54
> > Another one to add that 8.0.6 and 8.0.5 don't route proxy traffic and downgrading to 8.0.4 resolves this. O/S: Windows FF: 97.0 (64-bit)
> 
> Just updated FF to 97.0.1 and 8.0.5 & 6 still don't route traffic via proxy

I use Windows 10 with latest FF & add-on v8.0.6, does not work at all.

**Comment by groovecoder** [comment] 2022-03-09 22:41
I WAS able to reproduce this bug while trying to proxy a container thru ZAP https - the traffic did NOT go thru ZAP.
I WAS NOT able to reproduce this bug while proxying a container thru Tor socks - the traffic DID go thru Tor.

So a few things to check to help me get the most reliable STR:

1. Are you running your own proxy on localhost/127.0.0.1?
2. Are you running a socks proxy or http/s proxy?
3. Make sure you have `network.proxy.allow_hijacking_localhost` set to `true`? (see https://bugzilla.mozilla.org/show_bug.cgi?id=1535581)

**Comment by Gilgamoth** [comment] 2022-03-09 23:21
@groovecoder 
In answer to your questions, in my instance:
1. No, it's a remote TinyProxy implementation
2. It's a http/s proxy
3. Not sure this is relevent as I'm not using a local proxy

**Comment by wishbone1138** [comment] 2022-03-09 23:33
@groovecoder 
1. no, it's a remote host, but still on my local subnet RFC 1918 addresses (if that matters)
2. http/s proxy, also using privoxy
3. also not using localhost proxy, seems like a good feature to leave off for security

**Comment by lowlypalace** [comment] 2022-03-20 17:44
I can confirm on MacOS 12.2 running Firefox 98.0.1 and Multi Account Containers Version 8.0.6. The proxy feature stopped working after I upgraded. Just downgraded to 8.0.4 and everything started to work as before.

**Comment by nekno** [comment] 2022-04-20 23:12
Confirming this is still an issue with HTTP proxies in Multi-Account Containers 8.0.6, macOS 12.3.1, Firefox 99.0.1.

Also had to downgrade to 8.0.4 to get the proxy working in the container again.

1. No, not running a proxy on localhost, running it on another machine on the LAN
2. HTTP proxy
3. `network.proxy.allow_hijacking_localhost` set to `false`, but I'm not using localhost, I'm using another local IP

**Comment by rafalkrupinski** [comment] 2022-04-24 13:09
Macos 12.3.1
FF 99.0.1
Containers 8.0.7
http proxy on localhost

doesn't work

**Closed** 2022-04-25 17:52 UTC
Labels: bug, proxy

**Comment by srinidhibs** [comment] 2022-05-09 07:51
Updated to 8.0.7. Proxy settings didn't work - I was using http://localhost:8888 and then changed it to my http://my.local.ip.address:8888 and it still wouldn't work.

Downgraded back to 8.0.4 and disabled auto-update of the add-on. :disappointed:

**Comment by bakulf** [comment] 2022-05-09 13:52
Can somebody help me to reproduce the issue? I'm happy to work on it and include the fix in the next release.
I guess you all are using the latest stable firefox release, right?

**Comment by nekno** [comment] 2022-05-09 19:53
Yes — using the latest stable Firefox, now 100.0, on macOS 12.3.1.

The broken versions (8.0.5, 8.0.6, 8.0.7) try to set a property on an http proxy that's meant for a socks proxy, so they actually break the http proxying functionality of the extension altogether.

When a container is set to route through an http proxy, if the destination is reachable without the proxy, the page will load in Firefox, but the traffic isn't routed through the proxy.

If the destination is unreachable without the proxy, the page will fail to load when a broken version of the extension is installed.

So testing is a matter of seeing a page load and traffic appear in the proxy (working) or not (broken).

1. Run an http proxy somewhere on your LAN, e.g., install [Proxyman](https://proxyman.io) on your localhost
1. Configure the proxy to capture all traffic for all hosts
1. Install Multi-Account Containers v8.0.7
1. Set the proxy for one of your containers to your `http://{host}:{port}`
1. Load any page using the container
   - **Verify:** No network traffic appears in the http proxy
1. Install the fixed version of Multi-Account Containers
1. Reload the page using the container
   - **Verify:** Network traffic appears in the http proxy

**Comment by davidistheuser** [comment] 2022-12-30 17:24
still an issue with running on mac 13.1 and latest firefox with 8.0.9 Firefox Multi-Account Containers

**Comment by davidistheuser** [comment] 2022-12-30 17:25
still an issue with running on mac 13.1 and latest firefox with 8.0.9 Firefox Multi-Account Containers

**Comment by nekno** [comment] 2022-12-31 08:56
For reasons passing understanding, and despite this being a blocker for this use case, the issue was fixed in #2333 and merged to the main branch 8 months ago but has not been included in an official release.

- v8.0.7 was released on Apr 6.
- The issue was resolved on Apr 25.
- v8.0.8, 8.1.0, and 8.1.1 are all still marked as pre-release status.
- v8.0.9 is the only release since the issue was resolved, and it only includes styling updates for Firefox 107.

We wait and we wonder. 🤷

**Comment by dannycolin** [comment] 2022-12-31 16:31
8.0.9 was a hotfix for the broken styling in the confirmation page
8.1.x isn't released because it needs to get the greenlight from the QA team and get reviewed on addons.mozilla.org. However, it's the holidays so the staff isn't working.
