### ISSUE TITLE
Save my choice to open tab in NO container

### ISSUE THREAD

**Issue by PocketSam** [mozilla/multi-account-containers#2105] opened 2021-08-15 06:23 UTC
- Multi-Account Containers Version: 7.3.0
- Operating System + Version: 
Operating System: Manjaro Linux
KDE Plasma Version: 5.22.4
KDE Frameworks Version: 5.84.0
Qt Version: 5.15.2
Kernel Version: 5.13.8-1-MANJARO (64-bit)
Graphics Platform: X11

- Firefox Version: 92.0b3 (64-bit)
- Other installed Add-ons + Version + Enabled/Disabled-Status:

Википедия (ru)	extension	1.1	true	wikipedia@search.mozilla.org
Поиск Mail.Ru	extension	1.0	true	mailru@search.mozilla.org
Яндекс	extension	1.2	true	yandex@search.mozilla.org
Auto Tab Discard	extension	0.4.7	true	{c2c003ee-bd69-42a2-b0e9-6f34222cb046}
DuckDuckGo	extension	1.1	true	ddg@search.mozilla.org
Enhancer for YouTube™	extension	2.0.104.13	true	enhancerforyoutube@maximerf.addons.mozilla.org
Firefox Multi-Account Containers	extension	7.3.0	true	@testpilot-containers
Flagfox	extension	6.1.41	true	{1018e4d6-728f-4b20-ad56-37578a4de76b}
Google	extension	1.1	true	google@search.mozilla.org
Grammarly for Firefox	extension	8.881.0	true	87677a2c52b84ad3a151a4a72f5bd3c4@jetpack
HTTPS Everywhere	extension	2021.7.13	true	https-everywhere@eff.org
KeePassXC-Browser	extension	1.7.9.1	true	keepassxc-browser@keepassxc.org
OZON.ru	extension	1.2	true	ozonru@search.mozilla.org
Price.ru	extension	1.0	true	priceru@search.mozilla.org
ReloadMatic	extension	1.7.0	true	0.id@reloadmatic.webex
Service Worker Control	extension	1.2	true	service-worker-control@qw.thucfb.com
Service Worker Control - Push Notification History	extension	1.0	true	service-worker-control-push-notification-history@qw.thucfb.com
Snooze Tabs	extension	1.1.1	true	snoozetabs@mozilla.com
Terms of Service; Didn’t Read	extension	4.1.1	true	jid0-3GUEt1r69sQNSrca5p8kx9Ezc3U@jetpack
uBlock Origin	extension	1.37.2	true	uBlock0@raymondhill.net
VK Music — скачать музыку с популярных сайтов	extension	0.2.6	true	{9bb4ec92-ebd8-4ce3-8a2f-a57150764720}
Panorama Tab Groups	extension	0.8.12	false	panorama-tab-groups@example.com
Plasma Integration	extension	1.8.0.1	false	plasma-browser-integration@kde.org
SBIS Plugin Extension	extension	20.6100.7	false	sbis_plugin_nmh@tensor.ru
Tampermonkey	extension	4.13.6136	false	firefox@tampermonkey.net
TinEye Reverse Image Search	extension	1.4.1	false	tineye@ideeinc.com
Wayback Machine	extension	1.8.6	false	wayback_machine@mozilla.org
YouTube High Definition	extension	85.0.0	false	{7b1bf0b6-a1b9-42b0-b75d-252036438bdc}

### Actual behavior
When I open the site Extension asks me if I want to always open the site in a suggested container.
I click a tick to remember my choice and open a tab in a current container, which is NO container.
But extension asks for my decision every time I visit this site.

### Expected behavior
Save my choice to open the tab in NO container.

### Steps to reproduce
1. For me it's visiting site https://youla.ru/
2. Checking box "Remember my decision for this site"
3. Select "Open in current container", which is NO container.

**Comment by sbirl** [comment] 2021-08-16 18:55
I second this request, but for a different reason:

I assigned website1.com to Container1.  website1 is told to always open in Container1.
website1 uses sso-middleman.example.com for authentication 
Months ago, I assigned a website sso-middleman.example.com to always open in Container 1.

Recently, I went to website2.com in Container2.
website2.com needs to always open in Container2, but website2 also uses sso-middleman.example.com for authentication.
(  _Im testing website2 with different creds than website1._  )
However, when website2 attempts to forward the request to sso-middleman, the containers are switched (as expected).
Trying to re-assign sso-middleman to NO container is not an option.

**Comment by sbirl** [comment] 2021-08-16 19:06
*facepalm*  Found solution.

Although not straightforward, I did find a way to set the website back to "No Container":
- Go to the website in question
- In the URL bar, there should be the "Multi-Account Containers" icon to the right of the URL (left of the star for bookmarks)
- Right-click on the "Multi-Account Containers" icon
- Un-check "Always Open in This Container"

Not sure if this helps OP.

However, it would be nice to see the option to assign to "No Container" in other locations.

**Comment by aae42** [comment] 2021-08-30 22:26
> _facepalm_ Found solution.
> 
> Although not straightforward, I did find a way to set the website back to "No Container":
> 
>     * Go to the website in question
> 
>     * In the URL bar, there should be the "Multi-Account Containers" icon to the right of the URL (left of the star for bookmarks)
> 
>     * Right-click on the "Multi-Account Containers" icon
> 
>     * Un-check "Always Open in This Container"
> 
> 
> Not sure if this helps OP.
> 
> However, it would be nice to see the option to assign to "No Container" in other locations.

this fix worked for me as well, this is dumb because every time i selected no, and told it to remember my choice, it wouldn't, also when i selected no, that UI element would never show up... so you have to agree to open it up in the old container, then select the checkbox to always open to get it to "forget"

**Comment by francisbarton** [comment] 2021-09-15 14:50
> 
> 
> _facepalm_ Found solution.
> 
> Although not straightforward, I did find a way to set the website back to "No Container":
> 
>     * Go to the website in question
> 
>     * In the URL bar, there should be the "Multi-Account Containers" icon to the right of the URL (left of the star for bookmarks)
> 
>     * Right-click on the "Multi-Account Containers" icon
> 
>     * Un-check "Always Open in This Container"
> 
> 
> Not sure if this helps OP.
> 
> However, it would be nice to see the option to assign to "No Container" in other locations.

When I right-click on the icon it just shows two options:
"Manage Extension..." and "Remove Extension"

**Comment by achernyakevich-sc** [comment] 2021-09-15 15:09
> 
> 
> > _facepalm_ Found solution.
> > Although not straightforward, I did find a way to set the website back to "No Container":
> > ```
> > * Go to the website in question
> > 
> > * In the URL bar, there should be the "Multi-Account Containers" icon to the right of the URL (left of the star for bookmarks)
> > 
> > * Right-click on the "Multi-Account Containers" icon
> > 
> > * Un-check "Always Open in This Container"
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Not sure if this helps OP.
> > However, it would be nice to see the option to assign to "No Container" in other locations.
> 
> When I right-click on the icon in the URL bar it just shows two options:
> "Manage Extension..." and "Remove Extension"

Point 3 should be `* Right-click on the "Multi-Account Containers" icon`.

**Comment by achernyakevich-sc** [comment] 2021-09-15 17:32
@francisbarton Sorry, commented in hurry and didn't update copied text.

It should be `* Left-click on the "Multi-Account Containers" icon`. :)

**Comment by francisbarton** [comment] 2021-09-16 09:23
Tried left-click and there isn't anything I can visibly un-check to turn off the preference.
![image](https://user-images.githubusercontent.com/1819920/133586655-7b19ff68-97e8-45c9-9967-ff3eafd2cbfb.png)

**Comment by achernyakevich-sc** [comment] 2021-09-16 12:01
I have just found that after some of latest updates checkbox is missing in this UI. And generally UI is different now. :)

But it looks I have found the correct way to remove automated opening some URL in some container. It could be done the following way:
* Click to Multi-Account Container (further MAC) button in toolbar.
* In the panel that will be displayed click `Manage Container`.
* Click a container you would like to unassign.
* On updated panel at the bottom there will be the link `Manage Site List...` - click it.
* Find an URL you would like to remove from auto-assignment, move mouse over it and click `Trash Bin` icon to remove it.

**Comment by sbirl** [comment] 2021-09-16 13:42
> 
> 
> @francisbarton Sorry, commented in hurry and didn't update copied text.
> 
> It should be `* Left-click on the "Multi-Account Containers" icon`. :)

@achernyakevich-sc -- Nope, definitely **right-click**.  I wrote out those steps as I was performing them.  This is what I see, when I right-click:
![image](https://user-images.githubusercontent.com/33668651/133622774-3c66b1aa-0f1f-481d-98ad-e34b6f8acedd.png)

**Comment by achernyakevich-sc** [comment] 2021-09-16 13:56
I have checked and found that you are right. :) But not completely.

I could reproduce the case when menu available by right-click will contain **only** `Manage Extensions...` and `Remove Extension` points. It happens when current tab was open without any container. In case it was open assigned to any container then menu will look exactly as on your screenshot and user can easily assign or unassigne container for tab URL by click to `Always Open in This Container` menu item and setting or removing checkbox mark for it. Like on the following screenshot:

 ![image](https://user-images.githubusercontent.com/24388336/133625022-7829424d-4472-4efd-81c9-010a01068c58.png)

In any case by joint efforts we explained two ways how to get achieved initial goal. I think @PocketSam could close this issue as resolved. :)

**Comment by dannycolin** [comment] 2023-01-09 00:07
You need to unassign it https://github.com/mozilla/multi-account-containers/wiki/Frequently-asked-questions#remove-always-open-in-site-from-a-container

There's also #503

**Closed by dannycolin** 2023-01-09 00:07 UTC

**Comment by PocketSam** [comment] 2023-01-09 06:04
> You need to unassign it https://github.com/mozilla/multi-account-containers/wiki/Frequently-asked-questions#remove-always-open-in-site-from-a-container
> 
> There's also #503

Thanks for the #503. I would wait for this function to be implemented.

Unfortunately I can't unassign a site from container as used container is already removed. But I think I can assign it to the other container and unassign it then. :+1:
