### ISSUE TITLE
[Feature Suggestion] Option to auto remove cookies of a specific container.

### ISSUE THREAD

**Issue by drmirk** [mozilla/multi-account-containers#1480] opened 2019-08-15 15:29 UTC
I have set a specific container for duckduckgo(search engine). And from those search results I visit various websites. Some are familiar and have specific container assigned to them. And some are unfamiliar. These unfamiliar website stores cookies, caches etc.

What I want is, whenever all sites of a specific container is closed, then all cookies, caches etc of that container will be automatically deleted.

Thanks, and keep up the good work!

**Comment by HURSSGH** [comment] 2019-09-07 01:14
I agree. This should be a high priority feature.

Specifically, I would like the ability to clear caches, manage cookies and website data, etc. on a per-container basis.

For example, for a container "SearchEngines" I would like to be able to clear all data when I close the last tab of that container. Currently, I have FireFox Preferences configured to clear all data on exit. Rather than having to exit FF, exiting a container should be able to accomplish the same thing.

Ideally, opening preferences in a given container should allow the configuration of ALL preferences for that container. For example, I normally proxy all my web traffic through Privoxy. However, it would be VERY nice to be able to configure a container which has different network settings, and maybe even uses a different proxy.

Thanks for the great add-on!!

**Comment by o-l-a-v** [comment] 2019-11-13 08:54
Agree. Coockies sometimes break in one container only. Would be great if we did not have to clear cookies and other browser data browser wide when this happens.

**Comment by falolaf** [comment] 2019-11-14 07:16
Possibly you could accomplish some of what you want with the Cookie Auto Delete(CAD) addon:
https://addons.mozilla.org/sv-SE/firefox/addon/cookie-autodelete/

There is an option to make CAD container aware. Now,
I have only done a few manual tests to remove cookies for some domains but it seems that cookies are deleted on a container basis. 
The automatic deletion indeed is container aware in any case.

**Comment by kendallcorner** [comment] 2019-12-05 03:15
Hi. This looks like a duplicate of #48 or possibly #318. Please +1 or discuss on those issues so they are more likely to be completed. I'll close this, but feel free to reopen if you think it's a different issue.

**Closed by kendallcorner** 2019-12-05 03:15 UTC
