### ISSUE TITLE
Websites stopped opening in their specified containers + a Sync issue

### ISSUE THREAD

**Issue by ghost** [mozilla/multi-account-containers#1693] opened 2020-03-22 17:42 UTC
- Multi-Account Containers Version: 6.2.3
- Operating System + Version: Windows 7 Ultimate SP1 64-bit; Version 6.1 (Build 7601: Service Pack 1)
- Firefox Version: 74.0 (64-bit)
- Other installed Add-ons + Version + Enabled/Disabled-Status:
Amazon.com	1.1	true	amazondotcom@search.mozilla.org
Bing	1.1	true	bing@search.mozilla.org
DuckDuckGo	1.0	true	ddg@search.mozilla.org
Firefox Multi-Account Containers	6.2.3	true	@testpilot-containers
Google	1.0	true	google@search.mozilla.org
HTTPS Everywhere	2019.11.7	true	https-everywhere@eff.org
Twitter	1.0	true	twitter@search.mozilla.org
uBlock Origin	1.25.2	true	uBlock0@raymondhill.net
Wikipedia (en)	1.0	true	wikipedia@search.mozilla.org
eBay	1.0	false	ebay@search.mozilla.org

### Actual behavior
1. Doesn't open up links in some containers as it used to. Twitter.com links used to open in Twitter container and load up normally, now they don't (Just after the FF 74.0 update). Some Google links too.
2. Removing some containers or websites from containers doesn't work as the websites/containers just readd themselves like 10 seconds later (most likely a sync issue)

### Expected behavior
1. I've assigned Twitter.com links to the Twitter container and Google websites to the Google container, they used to work before. Now, they don't.
2. Removing a container/website should remove it.

### Steps to reproduce
1. I have about 13 containers, most have about 2 or 3 websites assigned to them. Some ones like Google, Facebook and Amazon have a lot. Twitter container has 2 websites assigned to it, which are: twitter.com, mobile.twitter.com
2. Firefox Multi-Account Containers options are: Enable Sync (Enabled), Enable Bookmark Menus (Disabled)
3. Try to open a twitter link.

### Notes
I did try to fix the issue by myself, did some research and found out that editing the containers file in Firefox profile folder and deleting the containers I didn't need, did the trick.
But the Twitter problem still persists.

**Comment by jonhoo** [comment] 2020-03-24 13:09
I'm seeing this too (and with twitter specifically) after upgrading from Firefox Developer Edition 75.0b6 to 75.0b7.

**Comment by jonhoo** [comment] 2020-03-24 13:25
Doing an "Inspect" on the containers extension on about:debugging#/runtime/this-firefox gives me a bunch of errors in the console:
```
sendRemoveListener on closed conduit @testpilot-containers.1236950581256 ConduitsChild.jsm:108
    _send resource://gre/modules/ConduitsChild.jsm:108
    _send self-hosted:976
    removeListener resource://gre/modules/ExtensionChild.jsm:1138
    removeListener resource://gre/modules/ExtensionChild.jsm:1359
    onClicked chrome://browser/content/child/ext-menus.js:282
    removeListener resource://gre/modules/ExtensionCommon.jsm:2542
    revoke resource://gre/modules/ExtensionCommon.jsm:2564
    close resource://gre/modules/ExtensionCommon.jsm:2569
    unload resource://gre/modules/ExtensionCommon.jsm:910
    unload resource://gre/modules/ExtensionPageChild.jsm:261
    unload resource://gre/modules/ExtensionPageChild.jsm:310
    destroyExtensionContext resource://gre/modules/ExtensionPageChild.jsm:494
    observe resource://gre/modules/ExtensionPageChild.jsm:407
UnknownError: The operation failed for reasons unrelated to the database itself and not covered by any other error code. ExtensionStorageIDB.jsm:802
    normalizeStorageError resource://gre/modules/ExtensionStorageIDB.jsm:802
    method chrome://extensions/content/child/ext-storage.js:273
    AsyncFunctionThrow self-hosted:699
    (Async: async)
    callAsyncFunction resource://gre/modules/ExtensionCommon.jsm:1087
    callAsyncFunction resource://gre/modules/ExtensionChild.jsm:1194
    callAndLog resource://gre/modules/ExtensionChild.jsm:1170
    callAsyncFunction resource://gre/modules/ExtensionChild.jsm:1193
    stub resource://gre/modules/Schemas.jsm:2679
    getSyncEnabled moz-extension://35fe757d-ba36-4abd-b466-29faea178710/js/background/assignManager.js:50
    init moz-extension://35fe757d-ba36-4abd-b466-29faea178710/js/background/sync.js:202
    <anonymous> moz-extension://35fe757d-ba36-4abd-b466-29faea178710/js/background/sync.js:314
Error: An unexpected error occurred undefined
UnknownError: The operation failed for reasons unrelated to the database itself and not covered by any other error code. ExtensionStorageIDB.jsm:802
    normalizeStorageError resource://gre/modules/ExtensionStorageIDB.jsm:802
    method chrome://extensions/content/child/ext-storage.js:273
    AsyncFunctionThrow self-hosted:699
    (Async: async)
    callAsyncFunction resource://gre/modules/ExtensionCommon.jsm:1087
    callAsyncFunction resource://gre/modules/ExtensionChild.jsm:1194
    callAndLog resource://gre/modules/ExtensionChild.jsm:1170
    callAsyncFunction resource://gre/modules/ExtensionChild.jsm:1193
    stub resource://gre/modules/Schemas.jsm:2679
    displayBrowserActionBadge moz-extension://35fe757d-ba36-4abd-b466-29faea178710/js/background/badge.js:10
    AsyncFunctionNext self-hosted:695
    (Async: async)
    init moz-extension://35fe757d-ba36-4abd-b466-29faea178710/js/background/badge.js:5
    AsyncFunctionNext self-hosted:695
    (Async: async)
    <anonymous> moz-extension://35fe757d-ba36-4abd-b466-29faea178710/js/background/badge.js:20
```
I see some other extensions also having storage issues with beta 7 (uBlock Origin for example), so this may be different from OP's issue and may even be a beta issue. Sorry for the noise.

**Comment by usermang** [comment] 2020-03-27 14:01
How long does it usually take to get their attention on a bug report?

**Comment by jonhoo** [comment] 2020-03-27 14:47
@usermang :man_shrugging: My other sync/local storage bug also hasn't seen any updates. It might just be due to the state of the world at the moment :)

**Comment by jonhoo** [comment] 2020-04-07 15:06
For me, the solution here was that [I had a file](https://bugzilla.mozilla.org/show_bug.cgi?id=1624586#c25) in `<profile>/storage/default/` without an extension, which apparently [confuses Firefox a lot](https://bugzilla.mozilla.org/show_bug.cgi?id=1621916). That was also what broken local storage, which caused Twitter not to load for me. Maybe try seeing if you have a file like that too?

**Comment by usermang** [comment] 2020-04-21 18:04
Okay this is just stupid. I'm still having the same issue over and over, when the hell do these guys reply/check the issue? holy shit

**Comment by dannycolin** [comment] 2023-01-02 01:20
1. Sounds like you got bite by a variant of [bug 1549204](https://bugzilla.mozilla.org/show_bug.cgi?id=1549204) when the browser updated.
2. Duplicate of #2110

**Closed by dannycolin** 2023-01-02 01:20 UTC
Labels: bug, Component: Sync
