### ISSUE TITLE
Multi-Account Container Sync Creating Additional Containers.

### ISSUE THREAD

**Issue by dylanmorroll** [mozilla/multi-account-containers#1885] opened 2020-10-05 13:57 UTC
- Multi-Account Containers Version: 7.1.0
- Operating System + Version: Debian Buster + Windows 10
- Firefox Version: 81
- Other installed Add-ons + Version + Enabled/Disabled-Status:
Name 	Type 	Version 	Enabled 	ID
Amazon.co.uk	extension	1.3	true	amazon@search.mozilla.org
Amazon.com	extension	1.3	true	amazondotcom@search.mozilla.org
Bing	extension	1.2	true	bing@search.mozilla.org
Chambers (UK)	extension	1.0	true	chambers-en-GB@search.mozilla.org
DuckDuckGo	extension	1.1	true	ddg@search.mozilla.org
eBay	extension	1.2	true	ebay@search.mozilla.org
Firefox Multi-Account Containers	extension	7.1.0	true	@testpilot-containers
Google	extension	1.1	true	google@search.mozilla.org
Wikipedia (en)	extension	1.1	true	wikipedia@search.mozilla.org
English (GB) Language Pack	locale	81.0buildid20200917005511	true	langpack-en-GB@firefox.mozilla.org
Checkmarks	extension	1.6.1	false	{bd97f89b-17ba-4539-9fec-06852d07f917}
DownThemAll!	extension	4.2.6	false	{DDC359D1-844A-42a7-9AA1-88A850A938A8}
DuckDuckGo Privacy Essentials	extension	2020.8.18	false	jid1-ZAdIEUB7XOzOJw@jetpack
Facebook Container	extension	2.1.2	false	@contain-facebook
Forest: stay focused, be present	extension	4.4.0	false	@forest-firefox-addon
GNOME Shell integration	extension	10.1	false	chrome-gnome-shell@gnome.org
HTTPS Everywhere	extension	2020.8.13	false	https-everywhere@eff.org
Joplin Web Clipper	extension	1.0.25	false	{8419486a-54e9-11e8-9401-ac9e17909436}
ModHeader	extension	3.1.9	false	{ed630365-1261-4ba9-a676-99963d2b4f54}
Saka Key	extension	1.26.3	false	{46104586-98c3-407e-a349-290c9ff3594d}
uBlock Origin	extension	1.30.0	false	uBlock0@raymondhill.net
Vue.js devtools	extension	5.3.3	false	{5caff8cc-3d2e-4110-a88a-003cc85b3858}

### Actual behavior
When syncing firefox between linux and windows, a huge amount of 'Banking' and 'Shopping' containers are created.

I have tried modifying 'containers.json' on both machines to remove these containers before syncing, but every time I then sync a bunch more containers are created (sometimes up to 50 containers). This proceeds to massively slow down my firefox making it unusable.

### Expected behavior
Containers would be synced across machines without additional containers being created.

### Steps to reproduce
1. Modify containers.json on both machines so only the containers I have created are available.
2. On one machine click 'Sync Now'.
3. Additional containers are created.
4. On the other machine click 'Sync Now'.
5. Additional containers are transferred to 2nd machine.

### Notes
I just tried it again and all my containers were wiped and replaced with the default containers...

**Comment by isthisrubble** [comment] 2020-10-05 23:44
I have also had this issue although it didn't create as many new containers as yours. hope it can be fixed.

**Comment by brettworks** [comment] 2020-10-15 06:49
I'm getting this too and boy is it annoying. If I disable the sync in settings for the add-on they don't come back, but enabling sync even on one appears to bring them back, and LOTs of duplicates.

**Comment by FlorianWendelborn** [comment] 2020-10-20 16:43
@brettworks @isthisrubble @dylanmorroll did anyone of you find a fast way to delete them? I currently have around 1k "Temporary Containers" from the temporary container addon and I’m pretty sure they’re multiplying due to this same bug. Using the menu is incredibly slow due to the 20 clicks required to delete a single container, so this would take me like a day to clean up that way...

**Comment by dylanmorroll** [comment] 2020-10-20 18:16
@FlorianWendelborn editing the `containers.json` file in your mozilla profile directory.

To find it navigate to `about:profiles` in your address bar and open the root directory folder of the profile in use.

**Comment by joeltimothyoh** [comment] 2020-10-20 21:57
@dylanmorroll Thank you for this. For some reason the sync feature worked in syncing all my containers but in an incorrect order on my other computer. I simply closed Firefox, replaced the `containers.json` with the one from my main computer, and restarted Firefox. The containers are now in the correct order.

It looks like the syncing function has an issue with syncing container IDs. I discovered this through using another extension that works with this extension where the container settings of said extension were applying to the wrong containers. I was trying to find a way to get the containers in the right order but didn't find such a feature available in `v7.1.0`. I then realized the settings were applying to containers in the order of how they are listed in the Multi-Account Containers UI. I suspected there to be an issue with container and container ID mappings that influenced the order of how the containers were listed. I can confirm this to be so based on the contents of the `containers.json` file.

**Comment by joeltimothyoh** [comment] 2020-10-20 22:32
@dylanmorroll I've also a number of new containers created each time the extension was set up on a new windows system, but not nearly as many as you mention. I usually delete them via the GUI before they have a chance to sync to the main computer, though this is only possible because of the unreliability of the sync.

I'm thinking perhaps plenty of duplicates are created when the `containers.json` file is modified on multiple systems at once, and especially with Firefox instances open on either or both machines. Maybe you could try deleting the duplicates only on one machine via the GUI and modifying the `containers.json` file only one machine at a time as a last resort.

**Comment by isthisrubble** [comment] 2020-10-26 10:10
> 
> 
> @brettworks @isthisrubble @dylanmorroll did anyone of you find a fast way to delete them?

I just did it manually because it was less than 10. but they kept coming back until I turned sync off again. after that it worked. luckily I don't sync regularly so it didn't cause too much havoc.

**Comment by barygusey** [comment] 2020-11-06 17:51
this issue is out of hand for me and multiple tries at correcting it have been unsuccessful

**Comment by FlorianWendelborn** [comment] 2021-03-28 13:28
Here’s a fully-automated solution to clear-out duplicate containers from the Temporary Containers addon, for whoever may be affected: <https://github.com/stoically/temporary-containers/issues/371#issuecomment-617626349>

**Comment by dannycolin** [comment] 2023-02-03 16:50
Duplicate of #1839

**Closed by dannycolin** 2023-02-03 16:50 UTC
Labels: bug, Component: Sync
