### ISSUE TITLE
Can you add a function to export all the containers to an .html or .json file or other format so that you can import them into another computer's extension? This makes it possible to export and import data such as bookmarks.

### ISSUE THREAD

**Issue by STVGecko** [mozilla/multi-account-containers#2684] opened 2024-10-25 20:12 UTC
### Before submitting a bug report

- [X] I updated to the latest version of Multi-Account Container and tested if I can reproduce the issue
- [X] I searched for existing reports to see if it hasn't already been reported

### Step to reproduce

Can you add a function to export all the containers to an .html or .json file or other format so that you can import them into another computer's extension? This makes it possible to export and import data such as bookmarks.

### Actual behavior

Can you add a function to export all the containers to an .html or .json file or other format so that you can import them into another computer's extension? This makes it possible to export and import data such as bookmarks.

### Expected behavior

Can you add a function to export all the containers to an .html or .json file or other format so that you can import them into another computer's extension? This makes it possible to export and import data such as bookmarks.

**Comment by kien5436** [comment] 2024-12-15 14:29
If you want to sync your containers, you can sign in and check on enable synchronization
![image](https://github.com/user-attachments/assets/723f8d38-8157-45a5-905b-024cbf1cea0b)

**Comment by dannycolin** [comment] 2024-12-15 15:37
duplicate of #1282

**Closed by dannycolin** 2024-12-15 15:37 UTC
Labels: bug
