### ISSUE TITLE
7.0 default numbered shortcuts conflict with macOS screenshot shortcuts

### ISSUE THREAD

**Issue by eefi** [mozilla/multi-account-containers#1791] opened 2020-07-12 10:49 UTC
Thank you for the new direct keyboard shortcuts to opening new tabs in specific containers in the 7.0 release!

On macOS, it seems that the keyboard shortcuts are mapped by default to Cmd+Shift+number, which works well for Cmd+Shift+1 and Cmd+Shift+2. However, macOS owns the shortcuts for Cmd+Shift+3, Cmd+Shift+4, Cmd+Shift+5, and Cmd+Shift+6 for screenshotting purposes: https://support.apple.com/en-us/HT201361 and https://support.apple.com/guide/mac-help/take-screenshots-or-screen-recordings-mh26782/mac.

Can the numeric shortcuts on macOS be mapped to a different pair of modifiers by default than Cmd+Shift, so that they don't conflict with these screenshotting shortcuts?

**Comment by kendallcorner** [comment] 2020-07-12 19:36
Hi @eefi FYI, you can change the keyboard shortcuts from `about:addons`. Click the gear and select "Manage extension shortcuts"

**Comment by foss-** [comment] 2020-07-13 10:00
Switching e.g. to ⌥⌘Number works. Question is though, if the default should be different for macOS, as all users will run into this conflict.

**Comment by maxxcrawford** [comment] 2020-07-17 02:07
Marking this as a duplicate to an issue that gives details on how to override this. Thanks! 

Duplicate of #1814

**Closed by maxxcrawford** 2020-07-17 02:07 UTC
Labels: as-expected, keyboard-shortcuts
