### ISSUE TITLE
Optional close prompt

### ISSUE THREAD

**Issue by L-GROSS** [mozilla/multi-account-containers#2385] opened 2022-06-29 09:18 UTC
### Before submitting a bug report

- [X] I updated to the latest version of Multi-Account Container and tested if I can reproduce the issue
- [X] I searched for existing reports to see if it hasn't already been reported

### Step to reproduce

Is it possible to add a configuration to open the page without prompting to select a tab to open

![Uploading 图片.png…]()

### Actual behavior

After opening, select

### Expected behavior

Configurable to close, open directly

### Provide a copy of Troubleshooting Information page

```plain text
NO
```

**Comment by L-GROSS** [comment] 2022-06-29 09:19
![图片](https://user-images.githubusercontent.com/42738826/176400983-5005c241-dd49-4a87-8ee9-6f240ac7dc04.png)

**Comment by L-GROSS** [comment] 2022-06-29 09:20
![图片](https://user-images.githubusercontent.com/42738826/176401122-2c165b81-6072-4b51-981f-0518523fdaa7.png)

**Comment by achernyakevich-sc** [comment] 2022-06-29 10:01
@L-GROSS It looks that you create just another duplicate of the other issues related to this part of MAC's functionality. I would propose you:

- [read the following comment](https://github.com/mozilla/multi-account-containers/issues/2293#issuecomment-1044014372)
- vote for #2294
- close this issue as duplicate.

**Comment by dannycolin** [comment] 2022-06-29 21:38
> Is it possible to add a configuration to open the page without prompting to select a tab to open

1. Thick the *Remember my decision for this site* checkbox
2. Click on the right button

The next time you open this URL, it'll automatically open in the specified container.

Closing this issue since it's a support question. If you need more help, please [ask on our support forum](https://support.mozilla.org/questions/new/desktop/form)

**Closed by dannycolin** 2022-06-29 21:38 UTC
Labels: bug
