### ISSUE TITLE
Synchronize our config to several stations ?

### ISSUE THREAD

**Issue by jfbourdeau** [mozilla/multi-account-containers#1076] opened 2018-01-09 19:40 UTC
Is there is sync our config of multi-account-containers on several stations ?
So we don't have to make the add-on learns 20 or 30 sites on 3 differents computers ?
JF

**Comment by jfbourdeau** [comment] 2018-01-09 19:50
Is there a FOLDER we can BackUp to COPY / Paste in on a new station ?

**Comment by groovecoder** [comment] 2018-01-09 21:13
This is a dupe of https://github.com/mozilla/multi-account-containers/issues/339.

**Closed by groovecoder** 2018-01-09 21:13 UTC
Labels: duplicate
