### ISSUE TITLE
[Feature Request] Extended "Always Open This Site In Container"

### ISSUE THREAD

**Issue by Solid-Ice8** [mozilla/multi-account-containers#1893] opened 2020-10-17 20:32 UTC
Thanks to the dev's / contributors for working on this add-on to improve.

I've noticed the option/function **Always Open This Site in Container** seems to only be available in 2 interfaces:
1) From the add-on button > Ctrl + Period
2) Right-click random spot on a site > Firefox Multi-Account Containers > Always Open in this Container

Note: _For step 2 to work, the site should already have existing container: Like already used "Reopen in Container"_.

"Reopen in Container" is already present (in right-clicking tab) since it's part of default FireFox.

[Right-click Tab](https://i.postimg.cc/4yNGV5fD/Right-click-tab.jpg)

Is there a way to add this feature/functionally into right-clicking tab or link(s) directly?

This will save much time clicking on Reopen in Container manually & following up with "Always Open This Site in Container".

**Comment by groovecoder** [comment] 2020-11-11 20:29
I think this is a duplicate of https://github.com/mozilla/multi-account-containers/issues/719.

**Closed by groovecoder** 2020-11-11 20:29 UTC
Labels: duplicate
