### ISSUE TITLE
Icon is hard to see against a dark background (regardless of theme)

### ISSUE THREAD

**Issue by renderedghost** [mozilla/multi-account-containers#1504] opened 2019-09-26 11:06 UTC
### Actual behavior
When placing the icon in the tab bar area —with osx light mode and firefox default theme enabled— the default (dark) extension icon persists, and is difficult to read against the dark background.

<img width="176" alt="image" src="https://user-images.githubusercontent.com/21337875/65682866-22fb0500-e05c-11e9-8524-0262b5d5f429.png">

### Expected behavior
The icon should invert or change to a light/white version when positioned over a dark background. This is different from inverting for dark mode. For example, check the behavour of the `Download` icon using same the steps to reproduce below.

### Steps to reproduce
1. Go to `View` / `Toolbars` > `Customise`
2. Set theme to `Default`
2. Drag the extension icon to the tab bar
3. Press `Done`

### Notes
cc @stoically  (because I see you fixed #1435 )

**Comment by silvererudite** [comment] 2019-10-02 07:49
hey wud like to take a shot at this.

**Comment by silvererudite** [comment] 2019-10-03 08:00
hey... @groovecoder and @maxxcrawford I would like to work on this for my Outreachy contributions. I see there's a PR by @stoically but I don't quite understand yet why the problem still persists. Any directions for me to approach this issue?

**Comment by renderghost** [comment] 2019-10-03 10:19
@silvererudite the previous issues seemed to deal with 'is the browser in dark mode? then invert the icon' but in my reported issue, the browser is in light mode, but the background of the tab bar is dark.

**Comment by silvererudite** [comment] 2019-10-03 11:03
hey @renderghost can you pls help me understand what exactly you mean when you say '**is the browser in dark mode?**  Is there a separate way to make the browser in dark/light mode? because I seem to only be able to change the theme to light/dark/default as you mentioned earlier.

**Comment by renderghost** [comment] 2019-10-03 11:08
Sure! This is what I mean.

When I change OSX to dark mode, my browser looks like this. Both the tool bars are tab bars are dark.

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/21337875/66121873-80540080-e5de-11e9-8265-475cce96c05a.png">

When I change OSX to light mode, my browser looks like this. Only the tab bar is dark.

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/21337875/66121964-c6a95f80-e5de-11e9-9278-547d54b5f304.png">

I have no idea if this is the issue for this ticket, but based on my understanding of other ticket's wordings.

**Comment by silvererudite** [comment] 2019-10-03 11:39
Ohh..thanks a lot for taking the time to clarify @renderghost. 
I guess I got quite confused by the PR reference here.  I really wonder why the PR didn't work. even though the changes were approved.

**Comment by silvererudite** [comment] 2019-10-03 14:49
@maxxcrawford and @groovecoder I believe I would need to modify the particular svg icon being used for dark theme. What do you guys think?

**Comment by groovecoder** [comment] 2019-10-03 14:55
It looks like we just need to deploy our latest version to AMO? @maxxcrawford - did you build and upload a 6.1.1 version to AMO yet?

**Comment by silvererudite** [comment] 2019-10-03 14:58
@groovecoder sorry whats AMO ?

**Comment by silvererudite** [comment] 2019-10-03 15:07
Ahh 😞..if that's the case then @groovecoder can you assign me a good issue to work on please?

**Comment by stoically** [comment] 2019-10-03 15:18
#1435 is a hotfix that only adapts the icon to the theme using the manifest.json [`theme_icons`](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/browser_action#Syntax) property, it doesn't adapt to the actual background color. So if the light theme is active it'll use the dark icon either way. [~Bug 1377302~](https://bugzilla.mozilla.org/show_bug.cgi?id=1377302) once introduced a way for mozilla signed extensions to adapt to the actual background by allowing to use `context-fill`, but it was either removed or there's a regression bug.

[Bug 1367042](https://bugzilla.mozilla.org/show_bug.cgi?id=1367042) would allow all extensions to use context-fill.

**Comment by groovecoder** [comment] 2019-10-03 15:26
@silvererudite have a look thru https://github.com/mozilla/multi-account-containers/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+bug%22+no%3Aassignee - that's the list of "good first bug" issues that are not already assigned.

**Comment by grahamperrin** [comment] 2021-04-30 11:36
> ## … (regardless of theme) 

No problem with `7.3.0` added to Firefox `88` set to Dark `1.1`:

![image](https://user-images.githubusercontent.com/192271/116689543-2ed54880-a9b0-11eb-9e22-2dd105476d38.png)

… no problem with [Computer Terminal](https://addons.mozilla.org/addon/computer-terminal/) `1.0`: 

![image](https://user-images.githubusercontent.com/192271/116689991-adca8100-a9b0-11eb-8a00-36bd1d520f6d.png)

**Comment by dannycolin** [comment] 2023-01-16 00:11
This should be resolved since we now serve a different icon for light/dark themes (See: https://github.com/mozilla/multi-account-containers/blob/main/src/manifest.json#L112).

Closing for now but feel free to let me know if you still have this issue.

**Closed by dannycolin** 2023-01-16 00:11 UTC
Labels: Needs: Mozilla Central, :+1:  Feature Request
