### ISSUE TITLE
Assign Container Directly to Bookmarks (Consistent though Editable)

### ISSUE THREAD

**Issue by MichaelTunnell** [mozilla/multi-account-containers#1142] opened 2018-03-01 04:52 UTC
I think the ability of assigning _Containers_ **directly to Bookmarks** would be absolutely amazing and solve a lot of headaches for a lot of people.

I want to open a single website with multiple sessions, which currently is a pain to do. if I could assign a container to a bookmark then I could accomplish this with so little effort that it would fundamentally change the way I use a web browser to the point that Firefox would take over a wide variety of tasks.

Firefox is my main browser and has been for over a decade but with this it could replace all need for additional browsers.

For example, what about having a _Registered Protocol_ for each container?

Let's say a user has 4 containers, this could be done with IDs like "1, 2, 3, 4" or names like "Personal, Work, TuxDigital, Self-Promotion"

Then you could make a bookmark like this `container-2:http://example.com/page-slug` via ID# or even name like this `container-work:http://example.com/page-slug`

I think the ability to have relatively permanent way to open a bookmark in a particular container would be absolutely game changing.

please add labels: enhancement, vote for me

**Comment by stoically** [comment] 2018-03-01 06:11
Duplicate where you could vote: https://github.com/mozilla/multi-account-containers/issues/323

**Comment by MichaelTunnell** [comment] 2018-03-01 08:09
It is different because the main purpose of that thread was the Context Menu feature . . . there is even a label associated to it exclusively for the context menu.

I created this so there would be a rough idea of how many people who are interested in this specifically not just as a secondary mention of a different idea. Yes he wanted both but the developers focused in on the context menu because that was the main request. Making a separate request allows more data as to how many wanted this rather than it included in the context menu data. For example, I couldn't care less about the context menu option if this was available instead. Even though I voted for that, I really wanted the secondary point but as stated, it was the context menu that took precedence on the issue.

**Comment by groovecoder** [comment] 2018-03-01 19:12
I'll close this as a dupe of #323 which already has lots of upvotes to help get attention to it. Please add an additional comment there and ask the existing up-voters to up-vote for that specific comment too.

**Closed by groovecoder** 2018-03-01 19:12 UTC
Labels: duplicate, enhancement, needs: M-C Platform

**Comment by MichaelTunnell** [comment] 2018-03-01 19:48
@groovecoder I disagree with it being closed as a duplicate because it isn't and the functionality requested is very different.
