### ISSUE TITLE
Lost containers?

### ISSUE THREAD

**Issue by PStaynova** [mozilla/multi-account-containers#1844] opened 2020-08-04 15:20 UTC
- Multi-Account Containers Version: 7.0.2
- Operating System + Version: Windows 7 home premium
- Firefox Version: 79.0
- Other installed Add-ons + Version + Enabled/Disabled-Status: Add-ons
Name 	Type 	Version 	Enabled 	ID
Adblock Plus - free ad blocker	extension	3.9.3	true	{d10d0bf8-f5b5-c8b4-a8b2-2b9879e08c5d}
Amazon.co.uk	extension	1.1	true	amazon@search.mozilla.org
Bing	extension	1.1	true	bing@search.mozilla.org
Chambers (UK)	extension	1.0	true	chambers-en-GB@search.mozilla.org
DownThemAll!	extension	4.2.6	true	{DDC359D1-844A-42a7-9AA1-88A850A938A8}
DuckDuckGo	extension	1.0	true	ddg@search.mozilla.org
eBay	extension	1.1	true	ebay@search.mozilla.org
Firefox Multi-Account Containers	extension	7.0.2	true	@testpilot-containers
Google	extension	1.0	true	google@search.mozilla.org
Metastream Remote	extension	0.6.0	true	{da2b93f0-35d5-461e-9bc7-6ba10aef1af4}
To Google Translate	extension	4.0.6	true	jid1-93WyvpgvxzGATw@jetpack
Video DownloadHelper	extension	7.3.9	true	{b9db16a4-6edc-47ec-a1f4-b86292ed211d}
Wikipedia (en)	extension	1.0	true	wikipedia@search.mozilla.org

### Actual behavior
Containers disappear upon restarting FireFox.

### Expected behavior
Containers (especially custom ones), including their 'hidden' tabs, to still be available every time I restart FireFox. 

### Steps to reproduce
1. Make a custom container
2. Open many tabs in it
3. From the container's menu, select 'Hide This Container'
4. Restart FireFox. 

Sometimes (not all the time!) the custom containers disappear. I had interesting tabs saved in them! Help!

**Comment by groovecoder** [comment] 2020-08-12 19:11
Dupe of https://github.com/mozilla/multi-account-containers/issues/1079 ... we haven't been able to reliably reproduce this though.

**Closed by groovecoder** 2020-08-12 19:11 UTC
Labels: duplicate

**Comment by Synetech** [comment] 2022-02-15 20:35
> Dupe of #1079 ... we haven't been able to reliably reproduce this though.

Hmm, that's funny because everybody else seems to be able to. 🤔
