### ISSUE TITLE
[Feature Requests] Custom Color(s) & Icons

### ISSUE THREAD

**Issue by Solid-Ice8** [mozilla/multi-account-containers#1707] opened 2020-04-13 17:23 UTC
I've added a review on official Firefox Add-On page, please add 2 new features:

1) A colour panel to choose our own custom colour for containers.
2) Add functionally to add more icons into add-on.

edit:
I recently found another excellent add-on: Containers Theme!

As the name implies, it will change your whole theme (top & sidebar) to whatever colour your container tab is. No matter matter the container colour. Purple? It'll match. Switch to different container? It'll follow through.

This even works with Temporary Containers; it'll turn grey-ish black.

**Comment by Dmitresso** [comment] 2020-04-14 08:58
Maybe just allow to upload custom pics for containers?
3. Containers sorting (drg n drop, some custom like Alphabetic, creation time)
4. Containers grouping (folders) 
5. Command-line launching

**Comment by Solid-Ice8** [comment] 2020-04-14 14:29
> 3. Containers sorting (drg n drop, some custom like Alphabetic, creation time)

There's no real way to automatically sort containers. You'd have to manually sort it.
I did this myself too. I read some of the issues here and someone mentioned it (I can't seem to find it)

It's **very** important that you follow the instructions to manually sort it.
In FireFox address bar, type: About:Profiles & open up desired profile. 
_I have multiple profiles, so I had to be extra careful not to mix them up_

Make sure you have a backup copy of your profile(s) in case you make some mistake.

A) **Close FireFox(es)**!! <-- **Very important!!**
B) In the desired %appdata% profile, find 'containers.json'.
C) Open with preferred text editor. You'll notice it's in one really long line. You can organize to look better for now.
D) Use Ctrl+F to find {`"userContextId"` with curly brackets in the front & double quote at the end
E) Press "Enter" to make it drop down one line. It'll look something like this:

```
{"version":4,"lastUserContextId":10,"identities":[

{"userContextId":1,"public":true,"icon":"vacation","color":"green","name":"Container1"},
{"userContextId":2,"public":true,"icon":"gift","color":"blue","name":"Container2"},

```
**The coding for the first 4 will differ slightly, as these are main starting ones. It'll have `accessKey` & all that. Leave them alone, do not remove.**

F) It's important that these all have _commas at the end of the line_; except for the **last one**!
If you forget, it'll ruin everything & you'll have problems after starting FireFox.

Make sure it looks something like this:

```
{"version":4,"lastUserContextId":4,"identities":[
{"userContextId":1,"public":true,"icon":"vacation","color":"green","name":"Container1"},
{"userContextId":2,"public":true,"icon":"gift","color":"blue","name":"Container2"},
{"userContextId":3,"public":true,"icon":"glasses","color":"yellow","name":"Container3"}
]}
```
**_No comma on the last one!_**

G) Save it after re-ordering it & run FireFox. Note you may need to manually click Multi Account Container add-on icon a few times for it to work normally again, this behavior is normal.

> 4. Containers grouping (folders)

Simple Tab Groups is your solution here. This add-on requires container tabs to function so, it'll fit right in.  However, you'll need to manually create groups & sort tabs. I believe when creating a "Group", you're essentially creating container tab.

**Comment by Dmitresso** [comment] 2020-04-15 10:36
@Solid-Ice8, thanks for your description. Does it all means it's possible to create new containers via manipulating with 'containers.json'? Did you try that?
It's great and last one  — starting window with containered new page via command line option — what I mostly need.

**Comment by Solid-Ice8** [comment] 2020-04-15 19:55
Oh, I forgot to mention, you can omit any of usercontextid's with `public:false` lines. When changed to `true` & filled in all fields properly, add-on wasn't able to open up despite clicking many times.

> Does it all means it's possible to create new containers via manipulating with 'containers.json'?

In short, yes, it's possible, but I wouldn't recommend always using the .json file itself. Only for sorting/organizing purposes only.

Even without "Multi-Account Container" add-on, these 'containers' will still exist. In firefox, press Alt+F to open up File menu & you'll see 'New Container Tab' on the second context menu.

This is where you can essentially add/remove containers, Multi-Account Container only 'extends features' to amplify it.

**Comment by sunknudsen** [comment] 2020-04-17 10:18
@Solid-Ice8 Tried your `containers.json` solution and, unfortunately, looks like custom hex colours are not valid. Using colours such as `#000000` breaks the extension. Somehow we have to use colour names such as `black`.

**Comment by Solid-Ice8** [comment] 2020-04-17 15:50
> 
> 
> @Solid-Ice8 Tried your `containers.json` solution and, unfortunately, looks like custom hex colours are not valid. Using colours such as `#000000` breaks the extension. Somehow we have to use colour names such as `black`.

Yes, that is correct. I did include that in my example above. Perhaps you weren't paying attention?

`
> {"version":4,"lastUserContextId":4,"identities":[
> {"userContextId":1,"public":true,"icon":"vacation",**"color":"green",**"name":"Container1"},
> {"userContextId":2,"public":true,"icon":"gift","**color":"blue"**,"name":"Container2"},
> {"userContextId":3,"public":true,"icon":"glasses",**"color":"yellow",**"name":"Container3"}
> ]}
`
I've edit the initial post to reflect that as well. As a former HTML coder, I've forgot about that. Staying home too long isn't a good thing... ;) My brain is frying from not actually working.

**Comment by Solid-Ice8** [comment] 2020-04-26 14:27
Well, I found more advanced features in Simple Tab Groups. You can find it after creating group and editing group settings. It also supports wildcards which some people have been suggesting as well.

**Comment by AlienResidents** [comment] 2020-04-29 01:47
I personally like Tree Style Tabs (TST), and with TST, and a little (or like me, a lot) CSS tweaking in the preferences for TST, you can modify the look of TST.  I am sure there is a way to set the tab colour for TST as well, but I just use the default colours in the containers menu.

E.g.:
![image](https://user-images.githubusercontent.com/366727/80553850-9f98fc00-8a0e-11ea-87e6-8fb730cd38e7.png)
![image](https://user-images.githubusercontent.com/366727/80553896-c8b98c80-8a0e-11ea-9908-0ff84a152c2c.png)

**Comment by Solid-Ice8** [comment] 2020-04-29 13:16
Yes, I use TST as well.

When you installed TST, you would've been given site that lists all other TST side add-ons. In that list, TST-Colour-Tabs is there. It's far from perfect but, better than nothing.

**Comment by Solid-Ice8** [comment] 2020-04-30 01:25
Apparently, the idea of more colours has already been suggested in #1673

**Comment by alexanderadam** [comment] 2020-08-05 18:41
Duplicate of #391

**Comment by grahamperrin** [comment] 2021-04-23 16:12
> Icons

▶ #1907

@Solid-Ice8 please close this duplicate issue. Thank you.

**Comment by grahamperrin** [comment] 2021-04-23 16:38
> Color(s)

▶ 2017 issue #391

> Icons

▶ 2017 issue #843, 2018 issue #1185

@Solid-Ice8 please close this duplicate. Thank you.

**Closed** 2021-05-02 15:41 UTC

**Comment by grahamperrin** [comment] 2021-05-02 17:05
Thanks!
