### ISSUE TITLE
[Feature Request] Add option to disable cookies in all tabs not in a container

### ISSUE THREAD

**Issue by john01dav** [mozilla/multi-account-containers#1277] opened 2018-09-27 23:47 UTC
I have been using this extension for awhile now, and it provides a great way to wrangle multiple accounts. Unfortunately, however, its privacy features are lacking in the area of cookies. The only real reason a user may want to have cookies enabled for a website is to handle (persistent) logins, or to store settings¹. Everything else is just tracking that one may wish to disable. As such, I would like to request that a feature that a setting be added to allow the user to completely disable cookies outside of specific containers. It would be even better if it allowed for incognito-style cookies outside of containers, where the cookies are stored for a single session only. This is also helpful because having this setting enabled gives users a reminder to keep accounts in their specified containers, as opposed to getting a bit lazy when creating new accounts, etc. as I have done.

¹: Even if I missed some legitimate use case for cookies, the point that most websites don't need them stands.

**Comment by samuel-allan** [comment] 2018-09-30 02:57
Perhaps it would be cleaner to allow every container to have a switch that disables cookies, and for the 'default' container (which is when you open any tab without a particular container) to be configurable to disable cookies

**Comment by john01dav** [comment] 2018-09-30 03:02
I agree with that suggestion. Ux is not my specialty.

**Comment by samuel-allan** [comment] 2018-09-30 16:06
I was mostly referring to the underlying model (software design choice), so not UX :D
However, considering this add-on is not currently actively maintained, I'm not sure this will go anywhere. I just almost finished an addition with proxy support, and I might just fork it off into an entirely separate extension with this feature also perhaps. I do however hope very much that this repository will be maintained - I really like the code quality and would much prefer to contribute to it rather than fork it

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by hardhub** [comment] 2019-01-06 10:32
> Perhaps it would be cleaner to allow every container to have a switch that disables cookies

Why only cookies?
I think we need options to specify different settings, even plugin settings.

Let's assume I want to use FoxyProxy and use different proxies depending on site.

Why not to make containers as some sort of profiles?

**Comment by 15495-4** [comment] 2019-01-06 13:47
Mute the threads

**Comment by kendallcorner** [comment] 2019-12-06 21:36
Hi. This looks like a duplicate of #419. Please vote (:+1:) or discuss on that issue to show your interest. I'll close this, but feel free to request a reopen if you think it's a different issue.

**Closed by kendallcorner** 2019-12-06 21:36 UTC
