### ISSUE TITLE
Feature request: open bookmark in container from bookmarks toolbar

### ISSUE THREAD

**Issue by ecmonsen** [mozilla/multi-account-containers#1616] opened 2020-01-17 17:40 UTC
I'd love to be able to right-click a bookmark in the Bookmarks Toolbar, and be given the option to open that bookmark in a specific container, just like when right-clicking a link.

Assigning the website to a container will not work in this case because I want to open the bookmark in different containers on different occasions.

Thanks.

**Comment by gabschne** [comment] 2020-01-18 15:58
Duplicate of #323.

This issue was resolved by #1537, but there has been no new release of the extension since it was merged.

**Comment by kendallcorner** [comment] 2020-02-12 22:17
Closed because of duplication

**Closed** 2020-02-12 22:17 UTC
