### ISSUE TITLE
Lacks Configuration Import/Export Facility

### ISSUE THREAD

**Issue by DilectableBananaButterfly** [mozilla/multi-account-containers#899] opened 2017-10-07 16:03 UTC
Given the complex configurations that will naturally evolve, the lack of a configuration import/export facility is a serious deficiency. Please consider adding this functionality.

**Comment by grahamperrin** [comment] 2017-10-08 08:56
## Export

This was closed four days ago: 

- [Feature request: exporting functionality · Issue #891 · mozilla/multi-account-containers](https://github.com/mozilla/multi-account-containers/issues/891)

> … <https://github.com/mozilla/multi-account-containers/issues/339#issuecomment-331411399>. please follow that thread for more information.

## Import

Please see for example: 

- [bug when importing saved data from Tab Groups addon · Issue #48 · kesselborn/conex](https://github.com/kesselborn/conex/issues/48)

– there'll be follow-up, and at least one spin-off issue, from me, maybe later today.

**Comment by jonathanKingston** [comment] 2017-10-09 13:25
I think #719 is a duplicate of this bug too. I'm going to close this off too for being a dupe to those even if not specifically titled the same.

Other addons exist / will soon too.

**Closed by jonathanKingston** 2017-10-09 13:25 UTC
Labels: assignment, duplicate
