### ISSUE TITLE
Firefox crashes if you attempt to delete a container that is currently open

### ISSUE THREAD

**Issue by robertheadley** [mozilla/multi-account-containers#1724] opened 2020-04-29 20:57 UTC
While this maybe makes sense to a power user or programmer, I feel that most users are going to see this as a problem. Perhaps you could spawn the new tab page when the customer does this to prevent this from happening?

**Comment by dannycolin** [comment] 2023-01-02 00:56
It doesn't "crash" but it simply closes the browser if there's only one tab and that tab is assigned to the container you're trying to delete.

As a workaround, flipping to `false` the preference `browser.tabs.closeWindowWithLastTab` should solve this problem.

Closing as duplicate of #1747

**Closed by dannycolin** 2023-01-02 00:56 UTC
