### ISSUE TITLE
Reordering containers in Manage Containers doesn't apply to other Firefox menus

### ISSUE THREAD

**Issue by emyarod** [mozilla/multi-account-containers#1958] opened 2021-01-31 02:21 UTC
- Multi-Account Containers Version: 7.3.0
- Operating System + Version: Windows 10, macOS, Linux
- Firefox Version: 87 Nightly

### Actual behavior

as reported by @hub2git in #330

> After updating to Firefox 85.0 on Linux, I now can sort the containers -- **as they appear in the toolbar** -- by drag and drop.
> 
> But the changes are not reflected when right-clicking a link on a webpage and hovering over "Open Link in New Container Tab".

### Expected behavior

order of containers in right click context menu should match order in the toolbar

### Steps to reproduce
1. reorder containers
2. observe that the order of containers differs between the context menu and toolbar dropdown

**Comment by hub2git** [comment] 2021-01-31 05:24
@emyarod thanks for creating this new issue and for mentioning me.

**Comment by jonathanKingston** [comment] 2021-01-31 11:15
Duplicate of: https://bugzilla.mozilla.org/show_bug.cgi?id=1333395

**Comment by hub2git** [comment] 2021-02-02 05:34
Is Mozilla spreading itself thin by being on both Github and Bugzilla?

**Comment by macks2008** [comment] 2022-04-29 19:43
> Is Mozilla spreading itself thin by being on both Github and Bugzilla?

that would imply they have enough contributors to cover the number of users & expectations they have in the first place. If I had to guess from the length of time it has taken them to deal with a simple matter of BMO displaying user's email addresses, they are in desperate need of competent contributors.

**Comment by achernyakevich-sc** [comment] 2023-04-05 14:18
I have decided to provide screenshot that visually explain the problem:

![image](https://user-images.githubusercontent.com/24388336/230109205-0f5a02fd-b677-4e29-a6a7-c319b0175ef7.png)

**Comment by Karl-MCS** [comment] 2023-04-24 12:56
If you click the Multi-Account Containers toolbar button and click Manage Containers, you can re-order the containers manually by drag-and-drop.  However, in all other menus (long-click/right-click + tab button, right-click tab or link and hover Open in New Container Tab) the containers retain their original unsorted order in which they were created.

**Comment by jlaundry** [comment] 2023-04-29 05:07
So I had a quick look at this, link to WIP: https://github.com/mozilla/multi-account-containers/compare/main...jlaundry:multi-account-containers:main#files

**Always open this in a Container** (URL bar icon) is relatively easy - we can just create a `getIdentities()` function in Utils.js, replicate the behaviour from `Logic.refreshIdentities()`, and use this instead of a direct `const identities = browser.contextualIdentities.query({})`

**Open in a New Container Tab** (tab right-click menu) and **Container Tabs** (Settings page) seem to be tricker... I've tried brute-forcing it by find/replacing with `Utils.getIdentities()` everywhere, but that doesn't seem to have any effect. I suspect, given the l10n strings are in mozilla-central, that this may be outside this extension? But not sure (I'm just a Firefox fan, not usually a dev!)

**Closed** 2024-08-14 14:31 UTC
Labels: bug, Needs: Mozilla Central

**Comment by groovecoder** [comment] 2024-09-26 11:47
The fix for this has been released. https://github.com/mozilla/multi-account-containers/discussions/2672
