### ISSUE TITLE
[Enhancement/Feature] Add URL prefix to open the URL in a specified container

### ISSUE THREAD

**Issue by E1k3** [mozilla/multi-account-containers#1302] opened 2018-10-28 13:34 UTC
Consider adding a URL tag/prefix/keyword like the ones you can specify for search engines (about:preferences#search). Starting a URL with such a keyword opens the URL in the container with that keyword.

Proposed behavior:
* Container
  * Name: "Banking"
  * Prefix: "bank:"

URL: "bank:https://url.to.my.bank.com" opens in "Banking" Container

**Comment by E1k3** [comment] 2018-10-28 14:09
This can be used in many ways. I would mostly use this to open certain Bookmarks in specified containers.

**Comment by s3rvant** [comment] 2019-08-21 14:34
+1 for containers at bookmark level

Could also use tags or keywords if URL isn't a good option

**Comment by dominik-ba** [comment] 2020-01-20 17:16
I totally support this idea! I was just about to create the same feature request.
I would also be fine for version 1 to just support URLs if bookmarks are more complicated.

**Comment by kendallcorner** [comment] 2020-02-14 04:18
This looks like a dupe of #854. Please comment and/or upvote on that one. Also related: #323 

I'm closing this, but let me know if you think this is different issue from 854

**Closed by kendallcorner** 2020-02-14 04:18 UTC
Labels: enhancement

**Comment by E1k3** [comment] 2020-02-14 11:53
While this is not necessarily a duplicate of that issue, one solution could solve both. So I agree, that this issue can be closed in favor of #854

**Comment by dominik-ba** [comment] 2020-02-18 16:54
I must say this issues title is way more descriptive than #854 since if you only look at the title from that issue one would think this feature is already implemented. But this here clearly asks for something that is not existing. Only as @E1k3 said, the solution that is discussed in that thread (after its purpose was clarified) could solve both.

**Comment by E1k3** [comment] 2021-11-24 13:11
@kendallcorner Ok, since #854 increasingly seems to move towards a bookmark-only solution, I request this issue be reopened.

This issue is not just about always opening a specific bookmark in a selected container, but about adding a container specifier to URLs in general.
This should work similarly to search keywords (as explained in the issue description) or the tabs (%) and history (^) prefixes for URLs, but would be enabled for bookmarks as well.

Assuming # would be the prefix (which is open to debate of course):
`#c1 ddg.com` should open duckduckgo in container c1
and
`#c1 ddg.com` should be a valid bookmark url that opens duckduckgo in container c1 if clicked

Especially since it is now possible to sync container definitions and assignments between devices via Firefox Sync, having synced bookmarks that are assigned to synced containers would synergize really well.

**Comment by eightnoteight** [comment] 2022-12-18 08:04
#854 does seem to be different from this url prefix usecase.

for example I want to open my work github org links in a separate container from every other links, i.e I want "github.com/Zomato/*" links to open in a separate container when compared to every other github.com link
