### ISSUE TITLE
Icons/Colours

### ISSUE THREAD

**Issue by Ulrome-Bardsea** [mozilla/multi-account-containers#1965] opened 2021-02-03 08:15 UTC
Is it possible to add more icons and additional colours in the drop down when creating a new container ?

**Comment by steffenlyng** [comment] 2021-02-05 16:27
perhaps it could be possible to add your own icons, and choose from a color-dropper, which colours to use

**Comment by michaljenicek** [comment] 2021-02-14 06:41
+1

**Comment by luisnabais** [comment] 2021-04-02 17:27
+1

**Comment by weyCC81** [comment] 2021-04-13 13:28
Have a look at https://github.com/mozilla/multi-account-containers/issues/391

**Comment by grahamperrin** [comment] 2021-04-23 16:44
> Icons

▶ 2017 issue #843, 2018 issue #1185

> Colors

▶ 2017 issue #391

@Ulrome-Bardsea please close this duplicate. Thank you.

**Comment by dannycolin** [comment] 2022-05-21 00:24
duplicate of #2368 and #391

**Closed by dannycolin** 2022-05-21 00:24 UTC
