### ISSUE TITLE
Container not working FF 88 Linux Debian

### ISSUE THREAD

**Issue by wisdomlight** [mozilla/multi-account-containers#2034] opened 2021-04-27 11:03 UTC
- Multi-Account Containers Version: 4.7
- Operating System + Version: Debian 11(Bullseye/Sid wih GNOME 3.38)
- Firefox Version: 88.0 64 bit
- Other installed Add-ons + Version + Enabled/Disabled-Status: do you really want me to copy and paste the list of my extenssions?? it looks long.

### Actual behavior
When I try to open a web page in new container - it fails to do so.

### Expected behavior
When I try to open a page in a new container it will allow me to have a fresh login to that service.

### Steps to reproduce
1. Right click on the webpage tab(at the top (where the page's name appears))
2. select open in New Container Tab
3. New page does open - but not in a new container
4. 
### Notes

one thing I noticed: when you open a new page in a different container and the container group has a color say orange.
The newly opening Tab has the orange horizontal line (the coloro of the new container group) but it then quickly looses the color and returns to having no associated color.

**Comment by grahamperrin** [comment] 2021-04-27 20:53
> 2. select open in New Container Tab
> 3. New page does open 

Step 3 is wrong; there should be a **submenu** before a new page. 

![image](https://user-images.githubusercontent.com/192271/116311212-e6950b00-a7a2-11eb-9559-6011093fc791.png)

**Comment by wisdomlight** [comment] 2021-04-28 07:56
@grahamperrin yes you are correct this sub menu does open and I select say shopping (which is my case has a pink magenta colour)

here's a video

https://user-images.githubusercontent.com/14957169/116367689-854f5500-a7ff-11eb-9c36-f8020ec467ca.mp4

**Comment by grahamperrin** [comment] 2021-04-29 06:43
I can not reproduce the issue. 

Is it reproducible in a new profile? Without extensions. 

**about:profiles**

----

If you find the issue reproducible only in the profile with extensions, then (yes) please do provide what's required. 

[Add-on List-o-matic 9000](https://addons.mozilla.org/addon/add-on-list-o-matic-9000/) can provide lists of names of enabled extensions. Like so: 

![image](https://user-images.githubusercontent.com/192271/116511150-ea698000-a8bd-11eb-846b-a812ac4c4b67.png)

Two versions of the list will help: 

* one with names alone
* one with names, versions, home pages and AMO pages.

**Comment by wisdomlight** [comment] 2021-04-29 13:18
Hi, 
Thank you for suggesting about:profiles
With a new profile, I signed in with my FF account, and the Multicontainer addon works.
Strange

**Comment by grahamperrin** [comment] 2021-04-30 06:35
Can you provide the list of extensions?

**Comment by dannycolin** [comment] 2022-05-20 00:39
Closing since Firefox 88 is End of Life. If you still experiment this issue, please file a new bug report. Sorry for the inconvenience.

**Closed by dannycolin** 2022-05-20 00:39 UTC
