### ISSUE TITLE
[Bug] Trying to manually open a tab in a different container when the container is fixed.

### ISSUE THREAD

**Issue by naoliden** [mozilla/multi-account-containers#2013] opened 2021-04-09 14:19 UTC
Trying to manually open a tab in a different container when the container for that site is fixed doesn't work. 
For example:
I have youtube set to always open in a specific container, but if I ever want to open youtube in a different container (with different credentials), it won't work. Even if I do it manually with the option "reopen in this site in ...". It reopens it in the same preset container. 
To go around this I have to sign in in private mode, which is not really a solution.

**Comment by ronzie** [comment] 2021-04-10 23:18
The same thing happened to me on walmart.com. I can find no way to rescind the "always open in this container" setting. I am using version 7.3.0 of the addon with Firefox 87.0 (64bit) on Windows 10 Home, 
Version 20H2, build 19042.870, Windows Feature Experience Pack 120.2212.551.0

**Comment by fuglede** [comment] 2021-04-13 12:31
Another (probably insufficient) workaround is to simply disable the site rule, cf. https://github.com/mozilla/multi-account-containers/issues/1999#issuecomment-808703458

**Comment by ronzie** [comment] 2021-04-13 13:50
"Insufficient" is not the word the word I'd use, but it's a polite version of what I would say! :)

**Comment by TonyGravagno** [comment] 2021-04-19 16:45
@chli I believe your use case is handled with the settings from the toolbar. I believe you can also open the current tab (google.com) in a specific container using some combination with the numeric keypad. See Firefox options > Tabs.
![image](https://user-images.githubusercontent.com/499473/115272203-fd789500-a0f2-11eb-8b70-5752ef2ca2dc.png)

The workaround referenced by @fuglede allows us to remove a URL associated with a container, which is a good solution to a different problem.

The problem reported in this thread is about opening in a different container while leaving the association. The prompt "Open this site in your assigned container" provides us with a temporary or permanent override. The responses to the fields on that page do not seem to be respected. OR There was another issue reported aroun 2017-2019 where JavaScript service workers were being used in sites and people could not open those site in containers. It seems to me that something in that area seems to be happening again, since @ronzie reported it's happening with a specific site.

I hope some of this connecting of dots helps the developers.

**Comment by grahamperrin** [comment] 2021-04-23 14:02
Duplicate of 2019 issue #1442

**Comment by grahamperrin** [comment] 2021-04-23 21:45
▶ #1414, which already seems to have a number of duplicates. 

@naoliden please consider closing this issue, so that others can be more easily managed. Thank you.

**Closed** 2021-04-29 03:28 UTC

**Comment by grahamperrin** [comment] 2021-04-29 07:50
Thanks!
