### ISSUE TITLE
Does not work in private browsing mode 

### ISSUE THREAD

**Issue by stevemiles2** [mozilla/multi-account-containers#1248] opened 2018-08-10 17:18 UTC
The idea of this add on is very good.

However, it does not work in private browsing mode.  People who want to use this add-on are also likely to be the sort of people who only use Firefox in private browsing mode.

**Comment by Paarmita** [comment] 2018-09-24 09:02
@stevemiles2 Look #930

**Comment by groovecoder** [comment] 2018-09-24 19:44
As I remember it, #930 is the bug where the button is click-able in Private Browsing Mode when it shouldn't be click-able.

I think this bug is actually a duplicate of https://github.com/mozilla/multi-account-containers/issues/469. Please up-vote and comment there.

**Closed by groovecoder** 2018-09-24 19:44 UTC

**Comment by voidstarstar** [comment] 2019-06-27 11:55
@groovecoder I think this might be a slightly different issue.  #469 is for **Permanent** Private Browsing Mode but this issue seems to be concerned with regular Private Browsing Mode.  I don't think the [suggested patch](https://bugzilla.mozilla.org/show_bug.cgi?id=1320757) for #469 would allow this extension to work if the user just hits `Ctrl`+`Shift`+`P` since it still checks `PrivateBrowsingUtils.isWindowPrivate()`.
