### ISSUE TITLE
Websites using ServiceWorkers can't be assigned

### ISSUE THREAD

**Issue by spastorino** [mozilla/multi-account-containers#822] opened 2017-09-15 18:26 UTC
Steps to reproduce:
Open a Personal container tab
Visit web.whatsapp.com
Click Firefox Multi-Account Containers icon
Select Always open in Personal
Open a new tab in default container
Visit web.whatsapp.com

Actual results:
It goes to web.whatsapp.com in default container

Expected results:
It should have visited web.whatsapp.com in Personal container

**Comment by jonathanKingston** [comment] 2017-09-15 19:31
I can't reproduce this in the Test Pilot version at the moment which would likely have the same code, I will take another look into this however I don't think the code has changed in the past few versions.

**Comment by spastorino** [comment] 2017-09-18 02:21
It does not work for me using neither the test pilot version and neither the github version.

**Comment by Softvision-MariusComan** [comment] 2017-09-20 12:55
I've managed to reproduce the issue using the steps from the STR on Windows 10 x64 and Mac 10.12. 
The issue is reproducible on Firefox release (55.0.3) with Test Pilot version of "Containers" and on latest Nightly (57.0a1- Build ID 20170918220054) with "Multi-Account Containers" (4.0.2 version) installed.

[Notes]:
- In order to reproduce the issue you have to visit the web.whatsapp.com website before adding it to a container.
- On web.whatsapp.com the "Multi-Account Containers" option is missing from the context menu.

Attached a screen recording of the issue:
![whatsapp](https://user-images.githubusercontent.com/31243259/30644382-da83d66a-9e1a-11e7-9c9a-99465efac8cf.gif)

**Comment by jonathanKingston** [comment] 2017-09-20 16:10
Thanks @Softvision-MariusComan!

**Comment by hoorzad** [comment] 2017-11-22 08:41
I have encountered the same issue with Firefox Stable (v57.0 64-bit) with Multi-Account Containers (v4.1.0) on Kubuntu 17.10. However the issue is not present in Firefox Developer Edition (v58.0b5 64-bit) on the same OS and witht the same version of addon.

The issue is not limited to _web.whatsapp.com_. I initially encountered it on _web.telegram.org_. I suspected that it gets triggered by any _web_ subdomain, but that proved not to be the case as _web.archive.org_ and _web.google.com_ open in their assigned containers without issues.

**Comment by ssipos90** [comment] 2017-12-04 16:56
+1
I'm experiencing this issue too

**Comment by melon3r** [comment] 2017-12-20 19:33
I'm experiencing the same on https://app.wire.com.

Verified this:
> EDIT: I noticed that this bug only occurs when starting from a non-container tab. So if I open a new tab in Shopping container and type in web.whatsapp.com, the website correctly opens in Personal container. However, if I open a new non-container tab (or is it called default container?) and do the same thing, the bug gets triggered and the website opens outside of its assigned container.

FF 57.0.1 (64-bit)
openSUSE Tumbleweed

**Comment by Sprinting** [comment] 2018-02-22 16:11
here to complain about https://web.whatsapp.com
from the default container -it won't open in the `Whatsapp` container even if it set to 'always open in specific container'
from other containers the prompt is triggered 
here's my details: 
```
{
  "Operating System": "Windows NT 10.0 amd64",
  "language": "en-US",
  "software": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:58.0) Gecko/20100101 Firefox/58.0"
}
```

**Comment by platelminto** [comment] 2018-04-26 16:04
Can confirm that this still happens, is it going to ever be fixed? I'd like to use Multi-Account Containers, but having already encountered 3 different issues in the first 10 minutes of setting up the extension, I don't feel like it's worth it :/

**Comment by ferdynice** [comment] 2018-06-21 09:59
Verified bug present on Firefox 60.0.1 (Kubuntu 18.04) and Firefox Multi-Account Containers 6.0.0

**Comment by geotheory** [comment] 2018-08-05 11:02
Still not defaulting https://web.whatsapp.com to specified container (Firefox 62.0b14). This is the only site for me with this behaviour.

**Comment by anupam207** [comment] 2018-08-05 11:30
Not sure whether my  experience would help reproduce this issue with web.telegram.org, but I would like to share it here.

1.Opened web.telegram.org in container1, logged in, and checked the option to "always open in container1". Now web.telegram.org keeps opening in container1 without any glitches.
2.  After a few days I bookmarked (in bookmarks toolbar) web.telegram.org.
3. Right clicked the bookmark in bookmarks toolbar and selected properties.
4. Checked the "load this bookmark in the sidebar" option. Now web.telegram.org opens in the sidebar but doesn't respect the container choice.
5. Undid step 4 (unchecked "load this bookmark in the sidebar" option).
6. Now web.telegram.org opens in the current container instead of container1 when it's launched from bookmarks or addressbar. But if it's launched from a telegram notification (I've enabled notification from web.telegram.org), it correctly opens in container1.

**Comment by z3dm4n** [comment] 2018-09-01 08:55
Same bug here with FF 61.0.1 on Ubuntu Bionic and Multi-Account Containers 6.0.0. Is there any workaround?

**Comment by yungslime** [comment] 2018-09-19 15:05
Bug is still present on Win8.1 running FF 62.0 and Multi-Account Containers 6.0.0

**Comment by GiuseppeGiacoppo** [comment] 2018-09-23 11:15
Bug still present with Whatsapp site, on Win10, FF 62.0.2, Multi-Account Containers 6.0.0

**Comment by MauroMombelli** [comment] 2018-12-21 20:57
Still present in FF 64.0

**Comment by elamperti** [comment] 2019-01-07 20:21
For everyone having this issue, follow this steps to fix the issue locally:

1) Close all whatsapp web tabs
2) Navigate to `about:debugging#workers`
3) Unregister all service workers for whatsapp (`ctrl`+`F` "whatsapp" should help you find them)
![screenshot](https://user-images.githubusercontent.com/910672/50791329-41d42400-12a0-11e9-9cb4-4eb3d6553295.jpg)
4) Go to https://web.whatsapp.com/ again, it should open in your desired container now :slightly_smiling_face:

**Comment by ShivangiKakkar** [comment] 2019-01-07 20:32
@spastorino @elamperti  I am not able to reproduce this. Is this still reproducible?

**Comment by MauroMombelli** [comment] 2019-01-07 20:38
Still does not work form me, i have no watsapp worker, and if i right cloick and select open in caontaner XXX, i see it loading for a moment and then it "reload" in the default container.
Smae if i right click on the tab and select "reopen in container", it will always open a new tab but using default container (arch linux, firefox 64.0.1)

**Comment by elamperti** [comment] 2019-01-07 20:39
@ShivangiKakkar Yes, I've had this issue up until now with Firefox 64 on Ubuntu, addon version 6.0.1.

The fix I propose is based on the research by @stoically (apr/18) on related issue #101.
This may have been fixed by PR #116, but I can't confirm that.

**Comment by rohitshriwas** [comment] 2019-03-20 07:44
I had the same issue and the local workaround suggested by @elamperti worked for me on Firefox 65.0.2 (64-bit). Thank you!

**Comment by spastorino** [comment] 2019-03-20 12:54
@ShivangiKakkar I'm not having this issue anymore since a while. With whatsapp I'm having a different one but unsure if it's related to containers.

Mainly after cleaning temps, cookies, offline data, everything that it's removable from the clean recent history menu, when I visit whatsapp it shows the QR code, I scan that and get logged in as usual. When I close the tab and at some point in the future I go back I'm not logged in anymore. This happens kind of in a random fasion, of course it's probably not random but it's nothing obvious. The most amazing thing is that after a long while playing this log out/login game I'm never logged out anymore unless I clean history again. It's really weird and I'm not sure if it's related to containers or what.

**Comment by stoically** [comment] 2019-03-20 13:05
@elamperti The fix introduced in https://github.com/mozilla/contain-facebook/pull/116 would work for Facebook Container on Firefox >=61, though the WhatsApp domains didn't make it into an official release yet.

It's not that easy to introduce the same fix in MAC, because:

What FC does is
1. Add-on initializes and clears serviceworkers for all contained domains (in all containers)
2. Visiting a contained domain in a non-Facebook container now fires as `main_frame` request and reopens in the Facebook container (if a serviceworker is registered, the request fires as `script` and can't be reopened, leading to the behavior described in this issue)
3. The serviceworker is registered in the Facebook container
4. All following requests in non-Facebook containers repeat step 2 because no serviceworker is registered in non-Facebook containers

In MAC however we have the concept of the confirm page, which lets you choose between the current container and the assigned container - so with the same fix we could end up with
1. Add-on initializes and clears serviceworkers for all assigned domains (in all containers)
2. Visiting an assigned domain opens the confirm page
3. Choosing the current container opens the domain and registers serviceworker in that container (could be the default container)
4. Open the assigned domain again in the same container will not show the confirm page, since a serviceworker is registered (no `main_frame` request)

It would work if, after the serviceworkers are cleared, "Remember my choice" is selected or the assigned container is always selected, since MAC would behave like FC in that case. @spastorino Is that by chance the case for you?

To fix it in MAC we probably would need to clear serviceworkers on a regular basis somehow.

**Comment by J-a-n-u-s** [comment] 2019-04-11 20:37
Solution that works for wire.com at least, disable tracker blocking (e.g. ublock origin). That was the only one I had to turn off to get wire.com to work in it's own container.

**Comment by kendallcorner** [comment] 2019-12-04 16:18
Hi, everyone. We're currently triaging the Multi Account Container issues. I can't reproduce this. Is it fixed? If I don't hear back, I'll close it in a few days.  If it's not fixed, can someone give updated steps to reproduce? Thanks!

**Comment by stoically** [comment] 2019-12-04 16:23
It's not fixed. What's missing in OPs STR is that you need to visit `web.whatsapp.com` once before following the described steps, so that the service worker is registered.

**Comment by maxxcrawford** [comment] 2019-12-04 19:52
I walked through the steps with no issue. It registered both workers in about:debugging. Is anything else outside of those steps needed to reproduce the error? 

![image](https://user-images.githubusercontent.com/2692333/70175939-38645f00-169d-11ea-8b0e-b50260fa17f8.png)

**Comment by kendallcorner** [comment] 2019-12-04 19:54
I also made sure to open web.whatsapp,com in a default container and then followed OP's STR. It opens for me in the correct assigned container.  @stoically are you seeing 2 service workers in about:debugging, or just one?

**Comment by stoically** [comment] 2019-12-05 02:22
@maxxcrawford @kendallcorner My bad, you're right, its working for me as well. The `webRequest.onBeforeRequest` now event fires for ServiceWorkers, so it got fixed in Firefox directly. Cool stuff!

I guess we could remove [the workaround in Facebook Container](https://github.com/mozilla/contain-facebook/blob/b44431b66a60ce70acd3978bb944fe302603cd83/src/background.js#L201-L202) then too.

**Comment by kendallcorner** [comment] 2019-12-05 03:36
Great!! Closing.

**Closed by kendallcorner** 2019-12-05 03:36 UTC
Labels: bug, site assignment

**Comment by MauroMombelli** [comment] 2019-12-29 19:58
firefox 71.0 on linux, still does not work for me.
If i open we.watsapp.com in a container, it will "escape", looks like opening a new tab and closing the old one.
Same if i try to "reopen in container", it will end up in a tab without container.

I am a bit puzzled how i am supposed to make it work

**Comment by kendallcorner** [comment] 2019-12-31 15:46
Try this: https://github.com/mozilla/multi-account-containers/issues/822#issuecomment-452068677 and see if it works. On a fresh install, we can't reproduce and it appears to be fixed, so if that doesn't work, you can try clearing your cache and cookies.

**Comment by kvdnberg** [comment] 2020-01-07 07:52
FYI I was having a similar problem on Atlassian Confluence - going to the main page opened in the correct container but following a link to any sub page (same domain, just different page after /) opened in default. Unregistering the Service Workers for that page as suggested above worked to fix the problem. Thanks!

**Comment by MauroMombelli** [comment] 2020-01-07 08:20
Fixed by disabling the "Facebook container" extension, that AFAIK come by
default in FF.
Is this expected?

**Comment by groovecoder** [comment] 2020-01-07 16:58
Facebook Container should not come by default in Firefox. Firefox does sometimes recommend it, but it shouldn't be installed by default.
