### ISSUE TITLE
Feature Request: regular expression support

### ISSUE THREAD

**Issue by tux-box** [mozilla/multi-account-containers#1984] opened 2021-03-04 23:13 UTC
I would rather use wild cards like *.domain.tdl or regular expressions to assign sites to containers than to add every possible subdomain to a list.

**Comment by btsimon97** [comment] 2021-03-12 03:42
This seems to be related to #1909 .

**Comment by rektide** [comment] 2021-06-23 18:05
This could be a fix for #691. Would love it so much. :heartbeat:

**Comment by dannycolin** [comment] 2022-06-14 17:52
Duplicate of #691

**Closed by dannycolin** 2022-06-14 17:52 UTC
