### ISSUE TITLE
Customized containers lose their color and icon when extension disabled

### ISSUE THREAD

**Issue by nkestrel** [mozilla/multi-account-containers#398] opened 2017-03-20 08:38 UTC
STR:
1. Enable Containers Experiment.
2. Edit container colors and icons to something different.
3. Create container tabs (must be done after editing containers).
4. Disable Containers Experiment.
5. Note color of previously created container tabs.
6. Go to `about:preferences#containers`

![Containers in about:preferences](https://i.imgur.com/T47nsH5.png)

This can be very confusing because it makes container tabs look like non-container tabs, although #userContext-label is still visible in the location bar. Re-customizing the containers brings back their color and icon.

**Comment by groovecoder** [comment] 2017-03-20 16:08
To be clear - these are custom colors & icons you assigned to the built-in containers? (I.e., Personal, Work, Banking, Shopping)

**Comment by kjozwiak** [comment] 2017-03-29 02:18
> To be clear - these are custom colors & icons you assigned to the built-in containers? (I.e., Personal, Work, Banking, Shopping)

@groovecoder correct, this happens when you either:

* change the colour/icon of a built-in container via the Test Pilot Containers icon
* create a new custom container via the Test Pilot Containers icon

I actually noticed this happening a few weeks ago but didn't bother creating a bug due to the fact that in #114, we decided to disable access to `about:perferences#containers` by changing `privacy.userContext.ui.enabled;false` which removes the "Containers Tab" section under `about:preferences#privacy`. However, users can still access that portion of the preferences via manually typing `about:perferences#containers` into the awesome bar.

As @nkestrel mentioned above (I didn't think about this case earlier), this is going to negatively affect users who install the test pilot, change the icons and colours of the built-in containers, and than revert back to the platform implementation of the feature. Once the user visits `about:perferences#containers`, they'll run into the same problem. 

@groovecoder, we should probably fix this in the next sprint. Thoughts?

I created [bug#1345643](https://bugzilla.mozilla.org/show_bug.cgi?id=1345643) weeks back which is similar to this issue and will hopefully address this on the platform side of things. If someone as containers disabled, we shouldn't allow access to `about:perferences#containers`.

**Comment by nkestrel** [comment] 2017-03-30 15:44
This doesn't just affect `about:preferences#containers`, it affects all references to container color and icon, including the appearance of container tabs themselves.

![Customized container](https://i.imgur.com/q2NMjsd.png)

**Comment by kjozwiak** [comment] 2017-03-30 16:15
Thanks @nkestrel, looks like this bug actually affects all container access points as well. We should fix this in the next sprint as this is going to affect users who edit the built-in containers and eventually return to using the platform implementation.

**Comment by groovecoder** [comment] 2017-04-04 17:13
When the user un-installs the add-on, restore the containers to the colors & icons they had before the add-on was installed.

**Comment by kendallcorner** [comment] 2019-12-03 21:04
Hi. We're currently triaging the Multi Account Container issues. This appears to have been fixed, so I'm going to close it. If you don't feel the underlying issue has been resolved, feel free to reopen it with updated steps to reproduce.

**Closed by kendallcorner** 2019-12-03 21:04 UTC
Labels: bug
