### ISSUE TITLE
Can't rename containers including specific numbers in the container name.

### ISSUE THREAD

**Issue by LittleMonkeyMojo** [mozilla/multi-account-containers#1104] opened 2018-01-29 18:41 UTC
By Default I have the containers:
Default
Personal
Work
Banking
Shopping
Read Me Later

If I try to rename any of these and include a number between 1 and 6 it will exit our of settings/edit mode and create a new "New Tab" and do nothing with the name of my Container.
If I try to rename any of these containers and include the number 7, it will instead of changing the name of my container, it will switch the interface instead create a new "Container #01".  Pressing "Cancel" or "<" buttons do not work.  Pressing "OK" appears to do nothing, but actually does (noted in a second).  At this point, the only way exit the menu is not within the menu, but to click elsewhere.  I mentioned that clicking "OK" appears to do nothing, but once you get back into the Multi-Account-Containers interface, you will see a "Container #01" present.  If you happened to click "OK" multiple times, you will see as many "Container #01" as you clicked.
Now, with an added container (for example, "Container #01") in addition to the Default containers mentioned above, the issue changes slightly.  Now, when you try and edit a container name and use a number between 1 and 7 (the count of the number of containers (plus Default)), it will not change the name of the Container, but will instead create a new "New Tab". Trying to rename a container and, now, using 8 (number of containers +1) will create a new Container, i.e. "Container #02".

Also, when you try and edit the container name, use a number (within the count of existing containers), the "New Tab" which is created will be created within the container of (the number you tried to use - 1).  So, if I try and modify "Shopping" to be named 1-Shopping, my "New Tab" will be created in the "Default" container.  If I try to modify "Shopping" to be named "Shopping-5" my "New Tab" will be created in the "Banking" Container.

Seems to not have issues with the number 0 or numbers greater than number of containers +2.

**Comment by groovecoder** [comment] 2018-01-29 19:45
I think this is a dupe of https://github.com/mozilla/multi-account-containers/issues/1084. We just merged a fix for that for the next release.

**Closed by groovecoder** 2018-01-29 19:45 UTC
