### ISSUE TITLE
Hiding container loses all tab history

### ISSUE THREAD

**Issue by thetoastcaper** [mozilla/multi-account-containers#1411] opened 2019-05-10 02:21 UTC
- Multi-Account Containers Version: 6.1.0
- Operating System + Version: Linux 4.15.0-48-generic
- Firefox Version: 66.0.4

### Actual behavior
Hiding and re-showing a container loses the navigation history (Back/Forward buttons) of all tabs contained

### Expected behavior
Tabs should retain their navigation history when their container is hidden and re-shown

### Steps to reproduce
1. Open a container tab
2. Navigate to two or more webpages in the tab
3. Hide the tab's container
4. Re-show the container

### Notes
#802 could probably offer a sound solution here

**Comment by grahamperrin** [comment] 2021-04-30 11:08
Loss – confirmed – feels more like a **bug**, than an enhancement.

**Comment by dannycolin** [comment] 2022-12-20 01:56
Duplicate of #802

**Closed by dannycolin** 2022-12-20 01:56 UTC
Labels: bug, Needs: Testing

**Comment by dannycolin** [comment] 2022-12-20 01:58
This is caused by the fact that the tab is in reality closed instead of only hided. If we fix 802, this should also fix this one and so I'm closing in favor of 802.
