### ISSUE TITLE
Feature request: toggle to move tabs to container

### ISSUE THREAD

**Issue by Mar-vo** [mozilla/multi-account-containers#1923] opened 2020-12-19 05:52 UTC
### Overview
Instead of merely being able to open a COPY of existing tabs to existing containers, i would like the option to MOVE existing tabs to containers (existing or new) from the tab context menu. This would allow for a lot more flexibility while browsing and is something i was used to from Google Chrome's group feature. Honestly, i don't see a reason to open an existing tab again (in a container), but i could be alone in that. In a previous feature request, issues with privacy were raised, so an option to toggle between this behaviour and the default "open in container" functionality would be applicable.

### Detailed description of feature

- An option in the extension settings to change the context menu item from "open in context" to "move to context" as [Context Plus](https://addons.mozilla.org/nl/firefox/addon/context-plus/) provides.
- "Send to container" will give a submenu listing existing containers and optionally a "new" option.
- Upon selecting a container, the selected tabs will be sent to the container (ideally without reloading).

### Optional secondary "new container" subfeature
Optionally, quicker creation and closure of containers could be supported through this menu, by allowing for the moving of tabs to a _new container._ This is part of what makes chrome groups somewhat more flexible.

- Upon selecting "new container" within the submenu, a popup for quick container creation will show, with the same options as the normal creation method. This could just use the same code as the "new container" part of the main dropdown since that would work fine as a popup.
- Since this feature would introduce more easy creation of containers, a context menu option to "close container" (also as in chrome) could be useful.

This "new container" item would also make a lot of sense under the current "open in container" context menu list item.

Perhaps there is a technical limitation that doesn't let task bar items be modified without reopening or reloading, but i would happily accept this feature if it meant my tabs get reloaded on sending them to a different container.

**Comment by Mar-vo** [comment] 2020-12-19 18:26
Since posting this request, i have learned that it is impossible for one extension to have more then one top-level context menu item. Having the option to toggle the context menu item between "move" and "open" would be a way to still have this functionality.

The [Context Plus](https://addons.mozilla.org/nl/firefox/addon/context-plus/) extension has a basic version of this feature with no "open in new" option.

I have also found that this feature request is somewhat of a duplicate of [this issue](https://github.com/mozilla/multi-account-containers/issues/311). I do not agree that containers should be only a privacy function, i think users should have the choice to take this privacy risk. I for one do not care about the "privacy impact" and i think many would agree. The choice to take this risk would be very useful to a large portion of the users of this extension.

I will adjust this request to reflect this optionality that is not reflected in the other feature request.

**Comment by julie777** [comment] 2021-10-04 18:45
I would much prefer move to container instead of open duplicate in container. Currently I open duplicate in container and then close the original tab.

**Comment by rloutrel** [comment] 2022-02-01 14:10
@julie777  / @Mar-vo : Is the "Switch container" extension, what you are looking for? I am looking for such a feature also and it would be better if I only use one Group-Managment extension (the other extension has not seen activity for 3 years, and starts getting obsolete: no sorting, bug with local html files, ...) and I  want to follow the appropriate feature request of the excellent "multi-account container" to give it more visibility.

**Comment by rloutrel** [comment] 2022-02-01 15:41
Actually is this ticket not a duplicate of https://github.com/mozilla/multi-account-containers/issues/1852

**Comment by dannycolin** [comment] 2022-12-29 03:01
Duplicate of #1852

**Closed by dannycolin** 2022-12-29 03:01 UTC

**Comment by dannycolin** [comment] 2022-12-29 03:02
If you want the moved tab to keep the original context (history, etc) that's impossible with the current API (See #1029)
