### ISSUE TITLE
Edit Container panel: "default" favicons render as missing images

### ISSUE THREAD

**Issue by groovecoder** [mozilla/multi-account-containers#1314] opened 2018-12-05 18:38 UTC
See https://github.com/mozilla/multi-account-containers/pull/1292#issuecomment-444521831

**Comment by richa031** [comment] 2019-01-23 08:59
i'm new to open source please help me find the details for this bug

**Comment by ryandrew14** [comment] 2019-03-14 20:56
@groovecoder I can't reproduce this, has this been fixed elsewhere?

**Comment by ryandrew14** [comment] 2019-03-16 19:43
Reproduced -- diving into this now.

**Comment by kendallcorner** [comment] 2019-07-25 19:41
Hi there, I used the other place the favicons were working.

**Comment by kendallcorner** [comment] 2019-08-21 13:50
That PR should close this.

**Comment by maxxcrawford** [comment] 2019-10-01 20:49
Resolved by #1470

**Closed by maxxcrawford** 2019-10-01 20:49 UTC
Labels: Container Panel, bug, good first bug, help wanted
