### ISSUE TITLE
Deleted containers keep coming back

### ISSUE THREAD

**Issue by hmlendea** [mozilla/multi-account-containers#2098] opened 2021-08-07 08:19 UTC
- Multi-Account Containers Version: 7.4.0
- Operating System + Version: Arch Linux
- Firefox Version: 90
- Other installed Add-ons + Version + Enabled/Disabled-Status:

### Actual behavior

Delete a container.
Wait anywhere between a few seconds and a few days, and they will be added back.

### Expected behavior

Delete a container.
It will never come back unless I manually add it again from scratch.

### Steps to reproduce
1. Open Manage Conteiners
2. Open a container
3. Delete that container
4. Confirm that it's gone
5. Check back later to see it is there again

### Notes

I've had more than a dozen containers in the past. And at some point a few months after I deleted all of them, they kept coming back, haunting me.
I've deleted them at least 10 times already. I even tried manually deleted all associated sites from them before deleting the containers themselves.
Now, just before writing this issue, I was deleting those containers, and just as I've been doing it, they've started reappearing.

I think this needs to be addressed quickly. It's very annoying and affects my work. It happened multiple times while sharing the screen with my coworkers that I had to stop what I was doing and disable the extension, because those containers interfered and caused pages to loop between containers, or in milder cases just had me have to log back into everything again.

**Comment by hmlendea** [comment] 2021-08-07 08:20
Note: Just when I pressed the submit button for this issue, the page opened in a new tab in a container I've just deleted before writing it, and had me log back into GitHub.

This is getting out of hand.

**Comment by JR-bva** [comment] 2021-08-19 16:07
I have the same problem. In addition, if I don't manually delete the container, a clone of it appears and then another and another. I left a container intentionally undeleted for about 3 days and got to about 70 identical containers. Which wasn't wise, because now I delete them manually :(

**Comment by hmlendea** [comment] 2021-08-23 08:16
@JR-bva the workaround I applied was to disable sync for the extension (although this makes it mighty annoying as I use Firefox across 3 different systems, sometimes 4).

And in regards to avoiding the manual deletion of dozens of containers, you can edit (Linux) `~/.mozilla/firefox/[profile-id]/containers.json` and make your changes there quickly and easily with a text editor. The catch is that there is surely another file that has those containers (e.g. storing the linked domains and other settings) but I can't find it.

**Comment by kdmcguire** [comment] 2022-02-22 22:01
Also experiencing this. Unfortunately I also used to use Temporary Containers, so I have 50+ old, deleted temporary containers (and duplicates) being brought back from the graveyard by synchronisation.

Have disabled container synchronisation for now.

We need a way to manage what's stored at the source, even if it's just an 'overwrite' button on about:preferences#containers.

**Comment by couladin** [comment] 2022-06-07 18:01
I see this long-running issue is gaining no traction, so maybe some more data may help. The versions/patch-level for everything below are the latest available as of this moment.

I've been seeing this since _at least_ 2021, and has persisted through to the current versions of the Firefox MAC extension (8.0.7) and Firefox (100.0.2) on PC. I use these on 2 installations of Linux (Kubuntu 20.04 LTS, x86_64) and 2 installations of Windows 10 (Pro, 64-bit). Syncing: MAC, Bookmarks, and Open Tabs.

I also use Firefox Mobile 101.1.1 on my phone (Samsung S9, stock Android 10) and 101.0 on my tablet (iPad Air 2, stock iPadOS 15.5. Syncing: Bookmarks and Open Tabs.

On Windows or Linux, if I click on MAC in the toolbar, Manage Containers > [Container_Name] > Manage Site List, manually delete the unwanted entries, and wait for or manually cause Firefox to sync, it will stay that way for a while. (Have not tested if it appears again on the same session/device, or after what delay.)

If I open any of the other 3 PC installations and wait for a sync, the old entries are still there. If I then go back to the installation where I deleted it and wait for a sync, the deleted entries are back again after a sync. (Feels like the sync logic only allows for local edits, and won't allow sync-based deletion.)

Other Firefox extensions installed:

- PC: Allow Right Click, Awesome RSS, BetterTTV, Bitwarden, Bot Sentinel, Bypass Paywalls Clean, Cookie Autodelete, Cookie-editor, History Cleaner, Imagus, Keepa, NordVPN, Privacy Badger, Reddit Enhancement Suite, Reddit PGN Viewer, Redirect AMP to HTML, Tampermonkey (1 userscript: Reddit Flair Linkifier), TinEye Reverse Image Search, uBlock Origin, Web Extension for Shaarli. (Disabled: Dark Reader, FoxyProxy Standard.)
- Android: uBlock Origin, Privacy Badger, Bitwarden. (Disabled: None.)
- iPad: Apple + Mozilla = no extensions.

**Comment by carljdp** [comment] 2022-10-23 13:33
I can confirm this behavior on Firefox Developer 107.0b3 64-bit (aurora update channel) on Windows 10 Pro.

*Expected behavior*
- With sync enabled, when I delete containers and restart the browser, the deleted containers should no longer be present.

*Actual behavior*
- With sync enabled, when I delete containers and restart the browser, all the containers I just deleted are still there, and duplicated.

**Comment by dannycolin** [comment] 2022-12-28 00:49
Duplicate of #1696

**Closed by dannycolin** 2022-12-28 00:49 UTC
