### ISSUE TITLE
Inconsistent Container Ordering in Context Menu 

### ISSUE THREAD

**Issue by dingwen07** [mozilla/multi-account-containers#2561] opened 2023-08-07 07:17 UTC
After updating the order of containers within the extension, the new order isn't reflected in Context Menu. Specifically, when I right-click a link in a webpage and choose 'Open Link in New Container Tab', the order of the containers listed still adheres to the original order based on the containers' creation time.

Steps to reproduce:

- Rearrange the order of the containers in the Multi-Account Container extension.
- Right-click a link on any webpage.
- Select 'Open Link in New Container Tab'.
- Observe that the order of the containers listed in the context menu doesn't match the order set within the extension.

The ordering is also not synced to Firefox account.

**Comment by dannycolin** [comment] 2023-08-07 14:18
Duplicate of #1958

**Closed by dannycolin** 2023-08-07 14:18 UTC
