### ISSUE TITLE
Default home page for each container

### ISSUE THREAD

**Issue by jernst** [mozilla/multi-account-containers#1221] opened 2018-06-05 17:55 UTC
Multi-account containers are a great feature. But when I activate a container, it comes up empty. Just like for regular tabs, I'd like to specify a URL that automatically opens, and I should be able to give a different URL for each container.

Result: when I open the banking tab, my (main) bank's website comes up.

**Comment by iinc** [comment] 2018-06-05 23:41
There is an issue for setting a bookmark to always open in a specific container. #323 
It's similar to what you are looking for. Sadly I can't figure out if it has actually been added to firefox or how to use it.

**Comment by jonathanKingston** [comment] 2018-07-04 09:05
This is a duplicate of: https://github.com/mozilla/multi-account-containers/issues/375 Please subscribe there.

> Sadly I can't figure out if it has actually been added to firefox.
It hasn't to my knowledge

Thanks

**Closed by jonathanKingston** 2018-07-04 09:05 UTC
