### ISSUE TITLE
(feature) Assign container to window

### ISSUE THREAD

**Issue by grnassar** [mozilla/multi-account-containers#1494] opened 2019-09-18 19:15 UTC
I've noticed a number of feature requests that pertain to sites being able to be assigned to multiple different containers or conditionally assigned, etc.  I think there is a suggestion that would fulfill 80% of the use cases where this sort of thing comes up.

When I need a particular account (and therefore cookie) on a site I use with multiple containers, typically it's because I'm on that container's "task," and so I have a number of tabs already opened in that container -- usually all within a particular window.

It strikes me that, just like I can assign a container to an existing tab, if I could assign it to the entire window that would neatly solve that problem.

By assigning a container to a window I would mean that all new tabs opened in the container without a parent (so Ctrl+N, opening a bookmark, opening an external link from another application into that window, etc) would be assigned to the window's container rather than to no-container.  Existing behavior for opening links from other pages would remain the same -- so if a window is tagged to container A, and I manually open a tab in that window that I assign to container B, any links on that page that would create a new tab would also be assigned to B.

Along with simplifying a workflow that I imagine is likely to be common among users anyway (of having a majority of tabs in a particular window be of a single certain container), this would give an user an easy and logical way to handle a "conditional" or "option" themselves, as rather than the extension doing the "heavy lifting" of managing and offering options to the user, the user would simply open the tab in the window associated with their wanted container -- which would most probably be the window that would have their other related resources within that container available regardless.

Thank you for the incredibly useful extension (and all the work of the Mozilla project).  I hope someone with more coding savvy and knowledge of the Mozilla codebase than I agrees with the suggestion as being a natural, intuitive extension of the feature set the extension already has and thus something that would be highly appreciated across much of the user base.

**Comment by groovecoder** [comment] 2019-09-19 14:58
I think this is a dupe of https://github.com/mozilla/multi-account-containers/issues/319 ? Please upvote & comment there.

**Closed by groovecoder** 2019-09-19 14:58 UTC
