### ISSUE TITLE
Can't 'hide this container group'

### ISSUE THREAD

**Issue by rpedrica** [mozilla/multi-account-containers#1596] opened 2019-12-06 18:31 UTC
- Multi-Account Containers Version: 6.1.1
- Operating System + Version: Slackware Linux -current/15 64bit
- Firefox Version: 71
- Other installed Add-ons + Version + Enabled/Disabled-Status:

Adblock Plus - free ad blocker	3.7	true	{d10d0bf8-f5b5-c8b4-a8b2-2b9879e08c5d}
Amazon.co.uk	1.1	true	amazon@search.mozilla.org
Amazon.com	1.1	true	amazondotcom@search.mozilla.org
Bing	1.0	true	bing@search.mozilla.org
Chambers (UK)	1.0	true	chambers-en-GB@search.mozilla.org
Country Flags & IP Whois	0.3.1	true	{802a552e-13d1-4683-a40a-1e5325fba4bb}
DuckDuckGo	1.0	true	ddg@search.mozilla.org
eBay	1.0	true	ebay@search.mozilla.org
Firefox Lightbeam	2.1.0	true	jid1-F9UJ2thwoAm5gQ@jetpack
Firefox Multi-Account Containers	6.1.1	true	@testpilot-containers
Google	1.0	true	google@search.mozilla.org
Google Translator for Firefox	3.0.3.3	true	translator@zoli.bod
HTTPZ	0.11.2	true	httpz@cm.org
KeePassXC-Browser	1.5.3	true	keepassxc-browser@keepassxc.org
Mailvelope	4.2.0	true	jid1-AQqSMBYb0a8ADg@jetpack
Netcraft Extension	1.15.2	true	{0e10f3d7-07f6-4f12-97b9-9b27e07139a5}
Search by Image	1.22.0	true	{2e5ff8c8-32fe-46d0-9fc8-6b8986621f3c}
SQRL	0.0.56	true	sqrl@pass.dog
To Google Translate	4.0.6	true	jid1-93WyvpgvxzGATw@jetpack
Twitter	1.0	true	twitter@search.mozilla.org
Video DownloadHelper	7.3.7	true	{b9db16a4-6edc-47ec-a1f4-b86292ed211d}
Wikipedia (en)	1.0	true	wikipedia@search.mozilla.org
Bitwarden - Free Password Manager	1.41.0	false	{446900e4-71c2-419f-a6a7-df9c091e268b}
Tab Groups	2.1.4	false	tabgroups@quicksaver

### Actual behaviour

In the last day, this plugin has shown strange behaviour - specifically, 'close this container' is no longer available. I only have the option to  'show this container' even though all tabs from this container are already open.

### Expected behaviour 

If the container and related tabs are open, the "close this container' should be visible and not the 'show this container' option.

### Steps to reproduce
1. 'show this container'
2. all tabs relating to this tab open
3. 'close this container'
4. all tabs relating to this container close

### Notes

An additional problem is that there is a greyed-out copy of all tabs in each container list.

**Comment by rpedrica** [comment] 2019-12-06 18:31
A quick note that they only recent change related to the browser is the upgrade to Firefox 71.

**Comment by rpedrica** [comment] 2019-12-06 18:44
More information: I tested creating a new container, adding a few tabs and now it showed the "hide this container" option except it does nothing when you click it.

**Comment by tglman** [comment] 2019-12-08 20:47
Hi,

Got the same issue for me clearly happened since i migrated to firefox 71, so probably is caused by some API changes from firefox 71.

Regards

**Comment by kendallcorner** [comment] 2019-12-09 16:30
By "close this container", you mean "hide this container," right? If so, can you edit the title of this issue?

I can't reproduce this. Does it happen every time you hide, then show, then try to hide containers? If not, can you provide more detailed steps to reproduce when it does happen?

**Comment by rpedrica** [comment] 2019-12-09 16:49
Apologies I didn't have this option (hide this container) so couldn't quite remember the exact text ...

I have 3 containers that I typically use beyond normal tabs. I only open these containers (show this container) when I need 1 or more of the tabs in the container. I then 'hide this container' when I don't need the tabs any more.

I noticed on the day after I updated Firefox 71, that even though I had a container open, there was no longer an option to 'hide this container' and instead only 'show this container' was available. If a container group is open, it should indicate 'hide this container' and not 'show this container'. Maybe the extension doesn't understand that the container is open?

I have all 3 containers' tabs open now and none of the containers have 'hide this container' as an option, only 'show this container'.

As mentioned in a previous comment:

_More information: I tested creating a new container, adding a few tabs and now it showed the "hide this container" option except it does nothing when you click it._

Steps:

1. click 'show this container' for an existing container
2. all tabs for the container open
3. when trying to close the related tabs, 'hide this container' is not available, only 'show this container' again

Not sure what other info I can provide. I'm including an image here:

[image](https://www.xstore.co.za/multi-container.png)

The container groups is open but as you can see, there is no option to 'hide this container', only 'show this container'.

Also, you can see that my 4 tabs are reproduced but greyed out in this container's list. Let me know if there is any other info I can give you.

**Comment by tglman** [comment] 2019-12-09 20:24
Hi,

One additional information, in my case I'm running on linux(debian sid) with gnome shell desktop environment (tried both X11 and Wayland).

Regards

**Comment by quertrakt** [comment] 2019-12-10 09:22
i can confirm that it started when upgrading firefox to 71. i'm on fedora31. 
it seems everyone commenting this issue who gave information about his/her operating system was running a linux.

**Comment by AlexZheleznyakov** [comment] 2019-12-10 21:36
Same for me on Fedora 31 after upgrade to Firefox 71.0

**Comment by kendallcorner** [comment] 2019-12-11 14:50
Possibly related https://github.com/mozilla/multi-account-containers/issues/1597#issuecomment-564118985

**Comment by kendallcorner** [comment] 2019-12-11 15:49
I think I have reproduced this. It looks like it is only happening on the version of FF that comes with the OS (though other linux distros are also affected) and is related to these platform bugs (i.e. can't fix it in the add on itself):

https://bugzilla.mozilla.org/show_bug.cgi?id=1601365
and
https://bugzilla.mozilla.org/show_bug.cgi?id=1601707

You can follow along there. 

To fix now, you can downgrade FF on Fedora, or download FF71 (or beta, dev, or nightly) directly from Mozilla (that version is not affected). These solutions should work in the mean time, so I'm going to close this bug. Let me know if these options do not fix it.

**Closed by kendallcorner** 2019-12-11 15:49 UTC
Labels: bug

**Comment by kendallcorner** [comment] 2019-12-11 15:51
Comment about downgrading: https://github.com/mozilla/multi-account-containers/issues/1597#issuecomment-564602915

**Comment by rpedrica** [comment] 2019-12-11 19:23
I quick note to say that I'm not using the OS provided FF; I've self-compiled FF71 from official source so "It looks like it is only happening on the version of FF that comes with the OS " is not quite correct. Should I try the binary version from Mozilla?

**Comment by kendallcorner** [comment] 2019-12-11 19:55
Interesting, yeah I would definitely try the binary.

**Comment by rpedrica** [comment] 2019-12-12 08:40
An update: the binary release from Mozilla does not have this issue - containers can be opened and closed without issue. This release had created a new profile on my machine so to test if this is a profile issue, I added a new profile to my existing FF71 however when clicking the multi-containers icon in the toolbar, I can't proceed past the Getting Started 1st screen ...

I guess I could use the binary blob but will need to transfer all my settings. Grrrrr.

**Comment by kendallcorner** [comment] 2019-12-12 15:32
Yeah, that's the same issue as #1597 caused by the same bug. Sounds like a compiler bug.

**Comment by kendallcorner** [comment] 2019-12-12 15:33
FYI: https://github.com/mozilla/multi-account-containers/issues/1597#issuecomment-564978186

So there appears to be a workaround.

**Comment by rpedrica** [comment] 2019-12-12 19:00
I've gotten the patch from the linked mozilla bug report and applied it to 72b5 (this version source from Mozilla did not solve the issue solely) whereafter the plugin is now working correctly again.

Patch added here for ease of access.

[ff.actorsparent.diff.gz](https://github.com/mozilla/multi-account-containers/files/3957376/ff.actorsparent.diff.gz)

**Comment by tglman** [comment] 2019-12-13 00:22
hi, 

Got an update of firefox from debian today that fixed the problem, not sure what was the fix, but for me is fixed.

Thanks
