### ISSUE TITLE
Add more icons

### ISSUE THREAD

**Issue by Nudin** [mozilla/multi-account-containers#1185] opened 2018-04-06 15:12 UTC
There are not enough icons and the choice of icons matches only some peoples needs. There are several tickets proposing to allow usage of arbitrary icons via unicode/etc but it seems they won't be implemented, at least not in short term.
So please add more icons.

We could use this ticket to collect icons-topics:
- audio (A speaker or a music note)
- video (A filmroll or playbutton)
- pictures (A camera)
- A question mark
- A book
- a gear
- Social media (connected graph)
- mail symbol
- a clock

**Comment by vibhas77** [comment] 2018-04-10 14:33
Please see #843 and #984

**Comment by grahamperrin** [comment] 2021-04-23 17:09
Mozilla bug [1533542 - Tab containers: Need more icons to choose from](https://bugzilla.mozilla.org/show_bug.cgi?id=1533542)

**Comment by felixbecker2** [comment] 2021-05-06 20:31
I would then make it general from the beginning -- let users select an arbitrary image (PNG, GIF, with appropriate size) from their harddisk or unicode character.

**Comment by santo998** [comment] 2021-06-03 00:02
Will you add more icons to the containers?
i.e.: a government icon (building), an education icon (graduated student).

**Comment by dannycolin** [comment] 2022-05-21 00:22
duplicate of #2368

**Closed by dannycolin** 2022-05-21 00:22 UTC
Labels: Feature request
