### ISSUE TITLE
Syncronize or move containers to new PC

### ISSUE THREAD

**Issue by T3chminator** [mozilla/multi-account-containers#1379] opened 2019-04-20 02:43 UTC
I've been using Multi Containers for quite some time now and have many containers for various websites. I recently got a new PC and despite having checked everything to sync Firefox, the containers have not been brought over. Just the Multi-fox extension and other stuff is synchronized.

Any way either manually or otherwise I can bring over all my containers from my old PC?

**Comment by groovecoder** [comment] 2019-04-20 13:14
Duplicate of https://github.com/mozilla/multi-account-containers/issues/339. Please upvote and check comments there.

**Closed by groovecoder** 2019-04-20 13:14 UTC
Labels: duplicate
