### ISSUE TITLE
[Feature Request]  Add the possibility of setting passwords per container and / or a master password for containers.

### ISSUE THREAD

**Issue by Atreyu-94** [mozilla/multi-account-containers#2454] opened 2022-11-24 15:07 UTC
### Before submitting a bug report

- [X] I updated to the latest version of Multi-Account Container and tested if I can reproduce the issue
- [X] I searched for existing reports to see if it hasn't already been reported

### Step to reproduce

1.  Open extension

### Actual behavior

 Anyone with access to the browser will have access to the containers.

### Expected behavior

 It would be very useful to have the possibility to add a master password to all containers and / or individual passwords for each container.
Sometimes several people use the same computer, it would be interesting to protect containers from  intruders.

**Comment by dannycolin** [comment] 2022-11-24 19:17
Duplicate of #1002

**Closed by dannycolin** 2022-11-24 19:17 UTC
Labels: bug
