### ISSUE TITLE
How do you add an already-opened tab to some container?

### ISSUE THREAD

**Issue by fujisan43** [mozilla/multi-account-containers#1001] opened 2017-11-24 12:59 UTC
Right now, I have to open a tab from the container menu and then copy the link from the already-opened tab and paste it in the newly opened container tab.
We should be able to select a container from that already-opened tab.

**Comment by SoftVision-EmilPasca** [comment] 2017-11-24 15:09
Hi @fujisan43, thanks for reporting this issue. However, this is a duplicate of https://github.com/mozilla/multi-account-containers/issues/311.

**Closed by SoftVision-EmilPasca** 2017-11-24 15:09 UTC
