### ISSUE TITLE
[Feature Request] Option to prevent unassigned domains from opening within a container 

### ISSUE THREAD

**Issue by RealDrGordonFreeman** [mozilla/multi-account-containers#1334] opened 2019-01-31 14:02 UTC
**This request is for the multi-account container extension to provide an option which restricts a container to select domains, so that no other domains can open within a given container.**

**Example:** A user is logged in to Twitter within a container called 'Twitter' and clicks a link within a Tweet for an external site. Currently, the site will open in another tab within a Twitter container. This behavior is contrary to one of the container extension's goals.

**Solution:** Include an option to 'restrict container to assigned domains'. This way, as an example, a user could choose to open all *.twitter.com domains only within the select container and redirect other domains to either another container, or the extension's internal page. Thus, upon clicking an external non-assigned link, the user should then be presented with the extension's internal page which allows the user to open that external link either within a non-container page, or within another container, such as 'External', or within an incognito window.

**Comment by RealDrGordonFreeman** [comment] 2019-01-31 14:16
Very similar request here: https://github.com/mozilla/multi-account-containers/issues/1318#issue-391171516

This feature is clearly in demand.

**Comment by RealDrGordonFreeman** [comment] 2019-02-26 23:16
@groovecoder This issue requires attention.

**Comment by lhorace** [comment] 2019-03-22 03:48
Hey there,

Unfortunately, if someone is willing and able to pick up the work and submit a PR, then:

> ... but we are currently focused on other projects right now, so we may not be landing an significant changes or features in this project for a while

https://github.com/mozilla/multi-account-containers/issues/1343#issuecomment-473309397

**Comment by groovecoder** [comment] 2019-03-22 12:17
Please move upvotes & comments to https://github.com/mozilla/multi-account-containers/issues/1318. We have few opportunities to develop any enhancements or new features for this project, so we like to conslidate all upvotes & comments into as few issues as possible. It will help us prioritize when we have a chance to work on something.

**Comment by groovecoder** [comment] 2019-03-22 12:18
Closing as dupe of #1318.

**Closed by groovecoder** 2019-03-22 12:18 UTC
