### ISSUE TITLE
Hide Container quits Firefox if last container 

### ISSUE THREAD

**Issue by stevenwalton** [mozilla/multi-account-containers#904] opened 2017-10-10 18:43 UTC
If you only have a single container shown and click "Hide this container" it starts hiding from the right and once it reaches the left most unpinned tab FF quits. Restoring this session only unhides the last non-pinned container that was hidden. Hidden containers do also restore even if not in the last container that was hidden . 

I thought this was interesting behavior. A suggestion might be that in this case to just open a new empty tab. 

Behavior produced on Ubuntu 16.04 FF56.0

**Comment by SoftVision-EmilPasca** [comment] 2017-10-11 08:10
Hi @stevenwalton, thanks for reporting this, however, this is a duplicate of https://github.com/mozilla/multi-account-containers/issues/624

**Closed by SoftVision-EmilPasca** 2017-10-11 08:10 UTC
