### ISSUE TITLE
installed addon does not create icon on toolbar

### ISSUE THREAD

**Issue by TitaniumHorse** [mozilla/multi-account-containers#1986] opened 2021-03-07 16:33 UTC
Also please make sure that: I CHECKED ALL THIS.
  - "Firefox will: Never remember history" in the Firefox Preferences/Options under "Privacy & Security > History" is NOT selected
  - You are NOT using Firefox in a Private Window
  - You can see a grayed out but ticked Checkbox with the description "Enable Container Tabs" in the Firefox Preferences/Options under "Tabs"

- Multi-Account Containers Version: 7.3.0
- Operating System + Version:  Microsoft Windows 10 Professional (x64) Build 19042.804
- Firefox Version: 86.0 64 bit
- Other installed Add-ons + Version + Enabled/Disabled-Status:
- 
AdBlocker Ultimate	extension	3.7.10	true	adblockultimate@adblockultimate.net
Amazon.com	extension	1.3	true	amazondotcom@search.mozilla.org
Bing	extension	1.3	true	bing@search.mozilla.org
Bookmark Notes	extension	1.2.1	true	bookmark-notes@winter.coffee
Cookie AutoDelete	extension	3.6.0	true	CookieAutoDelete@kennydo.com
Copy PlainText	extension	1.12	true	copyplaintext@eros.man
Disconnect	extension	20.3.1.1	true	2.0@disconnect.me
DuckDuckGo	extension	1.1	true	ddg@search.mozilla.org
eBay	extension	1.3	true	ebay@search.mozilla.org
Enhancer for YouTube™	extension	2.0.103.2	true	enhancerforyoutube@maximerf.addons.mozilla.org
Firefox Multi-Account Containers	extension	7.3.0	true	@testpilot-containers
Flash and Video Download	extension	1.0.9.87	true	{adeadebb-fedc-4180-a7f4-cfdd87496551}
Ghostery – Privacy Ad Blocker	extension	8.5.5	true	firefox@ghostery.com
Google	extension	1.1	true	google@search.mozilla.org
HP Sure Click Secure Browsing	extension	4.1.8.34	true	firefoxhpsureclicksecurebrowsing@bromium.com
HTTPS Everywhere	extension	2021.1.27	true	https-everywhere@eff.org
NoScript	extension	11.2.3	true	{73a6fe31-595d-460b-a920-fcc0f8843232}
PersistentPin	extension	1.0.2	true	{b8f5b973-7a28-4787-8e94-fdb7504e3991}
Privacy Badger	extension	2021.2.2	true	jid1-MnnxcxisBPnSXQ@jetpack
Take Webpage Screenshots Entirely - FireShot	extension	0.98.98	true	{0b457cAA-602d-484a-8fe7-c1d894a011ba}
uBlock Origin	extension	1.33.2	true	uBlock0@raymondhill.net
Wikipedia (en)	extension	1.1	true	wikipedia@search.mozilla.org
YouTube Classic	extension	1.6.0	true	{6acd0f4d-ab79-4b79-9b28-8bde65ae355c}
Adblock Plus - free ad blocker	extension	3.10.2	false	{d10d0bf8-f5b5-c8b4-a8b2-2b9879e08c5d}
Cookie Quick Manager	extension	0.5rc2	false	{60f82f00-9ad5-4de5-b31c-b16a47c51558}
visitedlinkenabler	extension	0.3.0	false	jid1-yDnsmkBoiRtgNA@jetpack

### Actual behavior
Addon fails to install icon on toolbar after repeatedly tries. In FF options this occurs: "An extension, Firefox Multi-Account Containers, requires Container Tabs."  FF File menu shows container tabs.

### Expected behavior
I expect an icon, just as appears on my Win 7 desktop, which has the addon installed.

**Comment by groovenectar** [comment] 2021-03-08 23:28
This started happening to me suddenly after a recent update, Linux Mint 20.

The containers still exist in tabs that were *already open*, but it seems they are no longer accessible and the icon is gone. The toolbar icon is not showing. I tried disabling every other extension, and the issue persists

**Comment by groovenectar** [comment] 2021-03-09 02:38
Wow! When I tried disabling the option in Preferences, `"Enable Container Tabs"`, then restarting the browser -- the option is gone from Preferences entirely!

Is this a weird way of phasing out a security feature?

**Comment by TitaniumHorse** [comment] 2021-03-17 14:48
After installing the extension yet again, I find that it now enables me to put the needed icon on the toolbar.  I had to do it manually, customizing the toolbar by dragging the icon to it.  A quick check indicates the add-on is working correctly and now permits permanent assignment of  containers to websites.  No idea what the problem could have been.

**Comment by grahamperrin** [comment] 2021-03-18 01:18
> No idea what the problem could have been.

Thanks, would you like to close the issue? 

The issue is not reproducible with a clean profile: 
![image](https://user-images.githubusercontent.com/192271/111559060-be6bc280-8787-11eb-97e3-c8eeb3c6d946.png)
![image](https://user-images.githubusercontent.com/192271/111559091-cc214800-8787-11eb-9cef-4d458c8988c1.png)
```text
% pkg query '%o %v %R' firefox
www/firefox 86.0.1,2 FreeBSD
% freebsd-version -kru
14.0-CURRENT
14.0-CURRENT
14.0-CURRENT
% 
```

**Closed** 2021-03-18 19:28 UTC

**Comment by TitaniumHorse** [comment] 2021-03-18 19:31
Since the problem resolved on its own for me, I do not need any solution. Thanks for the opportunity to post.  It is a very useful add-on.

**Comment by groovenectar** [comment] 2021-03-29 20:25
I was able to work around this for a few weeks by enabling the menubar and opening from there, but two issues persisted:

1) Icon not present in toolbar or in "customize toolbar"

2) Accounts that were configured to auto-open, didn't...

I remembered that there were comments saying that uninstalling and reinstalling fixed it... So I went to try that today from: https://addons.mozilla.org/en-US/firefox/addon/multi-account-containers/

I uninstalled, but when I go to reinstall there is a message on the page that says: `Installation aborted because the add-on appears to be corrupt.`

Sadly I'm having some unfortunate luck with this, and the current state is that the plugin is gone entirely and I'm unable to restore it... I also tried directly installing the past few releases with the same issue. Any ideas of what could be going wrong? Also edited a previous post to remove a tinfoil hat some, I had been intending to update that

Linux Mint 20, Firefox 86.0 (64-bit)

**Comment by groovenectar** [comment] 2021-03-31 00:02
This error ended up being related to something else: `Installation aborted because the add-on appears to be corrupt.`

I had to go to `about:config` and disable `extensions.allowPrivateBrowsingByDefault` (found [here](https://bugzilla.mozilla.org/show_bug.cgi?id=1582107#c3))

So then I could reinstall Multi-Account Containers, which did get it back up and running normally
