### ISSUE TITLE
Clicked "Get Started" on fresh install. Nothing happens.

### ISSUE THREAD

**Issue by cquickstad** [mozilla/multi-account-containers#1597] opened 2019-12-06 18:54 UTC
- Multi-Account Containers Version: 6.1.1
- Operating System + Version: Fedora release 31 (Thirty One), 5.3.14-300.fc31.x86_64 
- Firefox Version: 71.0 (64-bit)
- Other installed Add-ons + Version + Enabled/Disabled-Status:
Name 	Version 	Enabled 	ID
Amazon.com	1.1	true	amazondotcom@search.mozilla.org
Bing	1.0	true	bing@search.mozilla.org
DuckDuckGo	1.0	true	ddg@search.mozilla.org
eBay	1.0	true	ebay@search.mozilla.org
Facebook Container	2.0.3	true	@contain-facebook
Firefox Multi-Account Containers	6.1.1	true	@testpilot-containers
GNOME Shell integration	10.1	true	chrome-gnome-shell@gnome.org
Google	1.0	true	google@search.mozilla.org
HTTPS Everywhere	2019.11.7	true	https-everywhere@eff.org
LastPass: Free Password Manager	4.38.0.4	true	support@lastpass.com
Twitter	1.0	true	twitter@search.mozilla.org
uBlock Origin	1.24.2	true	uBlock0@raymondhill.net
Wikipedia (en)	1.0	true	wikipedia@search.mozilla.org
Zoom Scheduler	2.1.6	true	{bf855ead-d7c3-4c7b-9f88-9a7e75c0efdf}

### Actual behavior
After installing extension and restarting Firefox, I click on the extension icon. The dialogue box appears with a "Get Started" button.  Clicking the button does nothing. I can't progress past the dialogue box and the extension is not usable.

### Expected behavior
I should be able to click "Get Started" and actually be able to get started.

### Steps to reproduce
1. Install extension
2. Click "Get Started"
3. Don't get started because it's broken

**Comment by DanielValahul** [comment] 2019-12-07 10:06
Same issue here on Fedora 31/Firefox 71

**Comment by UrbanInvader** [comment] 2019-12-07 18:54
I just had this on Fedora 31 / Firefox 71 also. downgrading to firefox-69.0.1-3.fc31.x86_64 allowed me to click past the intro screen, seems to work fine after going back to firefox-71.0-8.npgo.fc31

**Comment by kendallcorner** [comment] 2019-12-09 16:46
Hi all. Can someone with Fedora debug the addon while trying to click through the getting started screens?

Go to : about:debugging#/runtime/this-firefox

and click "Inspect" on the MAC addon, and you should be able to see the addon's console.

Can you paste or send me a screenshot of that info? Thanks!

**Comment by fmhirtz** [comment] 2019-12-09 17:23
Let's see if this works:

[console-export-2019-12-9_12-20-38.txt](https://github.com/mozilla/multi-account-containers/files/3940942/console-export-2019-12-9_12-20-38.txt)

**Comment by MarekPikula** [comment] 2019-12-09 21:07
Here is console export from me:
[console-export-2019-12-9_22-5-55.txt](https://github.com/mozilla/multi-account-containers/files/3941730/console-export-2019-12-9_22-5-55.txt)

Some errors were there already when I opened the console. Then I clicked the _Getting started_ button twice.

**Comment by kendallcorner** [comment] 2019-12-09 22:34
Looks like a problem with extension storage, but I can't reproduce on Fedora 31/FF71

**Comment by stoically** [comment] 2019-12-10 16:36
Seems like there was/is a problem with the FF binary for fedora: https://bugzilla.redhat.com/show_bug.cgi?id=1779570

**Comment by fmhirtz** [comment] 2019-12-10 16:48
Confirmed, with the dev build in the bz this is working for me now. Thanks!

**Comment by syrkuit** [comment] 2019-12-11 01:34
FYI- same problem on Debian/sid w/ 71

**Comment by kendallcorner** [comment] 2019-12-11 15:05
Ah, it's the version that comes with Fedora. I've reproduced it, but it's a platform bug.

If it helps anyone, it doesn't happen on FF71 release (direct from Mozilla).

**Comment by syrkuit** [comment] 2019-12-11 15:07
Oh weird then, thanks for the note. I just downloaded a 72 beta where this doesn't happen either.

**Comment by kendallcorner** [comment] 2019-12-11 15:29
Platform bug:

https://bugzilla.mozilla.org/show_bug.cgi?id=1601365
and
https://bugzilla.mozilla.org/show_bug.cgi?id=1601707

You can follow along there. To fix now, you can downgrade FF on Fedora, or download FF71 (or beta, dev, or nightly) from Mozilla, and all these solutions should work in the mean time, so I'm going to close this bug.

**Closed by kendallcorner** 2019-12-11 15:29 UTC
Labels: P1 bug, bug

**Comment by kendallcorner** [comment] 2019-12-11 15:42
FYI, this is how I successfully downgraded: `yum downgrade firefox-69.0.1-3.fc31.x86_64`

But use at your own peril, I'm no Fedora expert :joy:

**Comment by MarekPikula** [comment] 2019-12-12 12:00
FYI patched Firefox landed in Fedora updates. Now it works.
