### ISSUE TITLE
"Reopen in Container" doesn't work when "Always open in [container]" is enabled

### ISSUE THREAD

**Issue by victorz** [mozilla/multi-account-containers#1636] opened 2020-02-14 09:30 UTC
- Multi-Account Containers Version:
- Operating System + Version:
- Firefox Version:
- Other installed Add-ons + Version + Enabled/Disabled-Status:

### Actual behavior

If I have set a site to "Always open in [container X]", I can't use the "Reopen in Container" function from right-clicking a tab to open the site in a container other than X.

### Expected behavior

I expect to be able to make an exception in my "Always open in" rule, since I use that mainly as a convenience at work for this particular site, but sometimes I'd like to be able top open the site in another container (personal vs work).

### Steps to reproduce

1. Set site to always open in a certain container.
2. Open site in said container.
3. Right-click tab and select "Reopen in Container" and attempt to open in another container.

Tab will open in container in which is the site is set to always open, rather than the chosen container.

### Notes

Maybe this is not meant to work this way, but in that case the menu option "Reopen in Container" should be disabled or something.

**Comment by vadimcn** [comment] 2020-02-28 20:47
I think this used to work before?   In any case, the desired behavior here should be "Default to ...", rather than "Always open in ...".

**Comment by staffanmowitz** [comment] 2020-04-24 11:23
Same as https://github.com/mozilla/multi-account-containers/issues/1442

**Comment by grahamperrin** [comment] 2021-03-18 01:09
Where the user prefers to **always** use a particular container at the time of opening – avoiding the need to reopen: 

> "Reopen in Container" should be disabled

True.

**Comment by grahamperrin** [comment] 2021-04-23 21:06
This is essentially a duplicate of 2019 issue #1414. 

@victorz please consider closing this #1636 ; see the other cross-references from #1414. Thank you.

**Closed** 2021-05-10 12:11 UTC
Labels: enhancement
