### ISSUE TITLE
Always Open This Site In: Default Container

### ISSUE THREAD

**Issue by xkr47** [mozilla/multi-account-containers#2036] opened 2021-04-28 07:51 UTC
### Actual behavior
From the toolbar popup menu, it is possible to reopen a tab in the `Default Container` but it is not possible to choose to always open it in the `Default Container`

### Expected behavior
In the popup menu, choosing `Always Open This Site in...` should present `Default Container` as an option.

### Steps to reproduce
1. Click the multi-account containers icon in the toolbar to get the popup menu
2. Click the `Reopen This Site in...` option
3. See there is a `Default Container` option at the top
4. Close the popup
5. Click the multi-account containers icon in the toolbar again
6. Click `Always Open This Site in...` option
7. See there is no `Default Container` option

### Notes
* [The code for the "Always Open This Site in..." submenu](https://github.com/mozilla/multi-account-containers/blob/4b56a2f0bb91cd9a12b95121fcff0c8e96ff66bd/src/js/popup.js#L1205)
* [The code for the "Reopen This Site in..." submenu presenting the "Default Container" option](https://github.com/mozilla/multi-account-containers/blob/4b56a2f0bb91cd9a12b95121fcff0c8e96ff66bd/src/js/popup.js#L1124)

**Comment by joelostblom** [comment] 2021-06-05 22:52
I would love to see this feature as well! However, I think you can close this issue at it has been suggested several times before, I believe originally in https://github.com/mozilla/multi-account-containers/issues/503. Unfortunately it looks like the discussion there didn't produce a clear path forward.

**Comment by dannycolin** [comment] 2022-12-28 03:13
Duplicate of #503

**Closed by dannycolin** 2022-12-28 03:13 UTC
