### ISSUE TITLE
Reordering containers in the extension doesn't adhere to new order when selecting a new container for a tab

### ISSUE THREAD

**Issue by aexley** [mozilla/multi-account-containers#2471] opened 2022-12-08 20:19 UTC
### Before submitting a bug report

- [X] I updated to the latest version of Multi-Account Container and tested if I can reproduce the issue
- [X] I searched for existing reports to see if it hasn't already been reported

### Step to reproduce

Reorder the containers in the extensions menu option by left clicking the extension icon and selecting the "manage containers" option at the bottom of the menu. Use the grabs on the right of the containers to drag a container to a new place in the menu.

Then exit the menu by clicking outside of it.

Then try selecting a new container for a tab in the following scenarios:

1. right click menu on new tab
2. right click menu "Open in new container tab"
3. File > New Container tab

it doesn't display the containers in the order as changed, it displays as the default order as containers are added.

### Actual behavior

Changing the containers order isn't being replicated to the various options where a container can be selected.

### Expected behavior

Using one of the selection options for creating a tab in a new container should reflect the current ordering as set in the extension.

**Comment by aexley** [comment] 2022-12-08 20:26
While this bug has been reported before and marked as a duplicate of [Bugzilla 1333395](https://bugzilla.mozilla.org/show_bug.cgi?id=1333395). This ticket hasn't had any progress on it and the latest commentary discusses whether it is still relevant. I'm flagging this as still a relevant bug that needs addressing otherwise the feature of resetting the order is not useful at this point in time.

**Comment by dannycolin** [comment] 2022-12-08 21:14
Duplicate of #1958

**Closed by dannycolin** 2022-12-08 21:14 UTC
Labels: bug

**Comment by dannycolin** [comment] 2022-12-08 21:17
I do understand that you want to raise awareness that this is still an issue. However, filing duplicate bugs won't make it happens sooner and increase the triage work done by volunteers. Thanks for considering this.
