### ISSUE TITLE
Firefox Android : Can't manage containers

### ISSUE THREAD

**Issue by dballesg** [mozilla/multi-account-containers#2609] opened 2024-01-24 17:43 UTC
### Before submitting a bug report

- [X] I updated to the latest version of Multi-Account Container and tested if I can reproduce the issue
- [X] I searched for existing reports to see if it hasn't already been reported

### Step to reproduce

1. Can't add new containers.
2. I tried opening from Extensions > Multi-account Containers > Settings
3. Included image of what I get. 
![Screenshot_2024-01-24-18-40-01-974_org mozilla firefox](https://github.com/mozilla/multi-account-containers/assets/13033276/b0ff5d60-fa61-423a-b3d4-01cc4e3d2ca3)

### Actual behavior

This is a screenshot of what I get :

![Screenshot_2024-01-24-18-40-01-974_org mozilla firefox](https://github.com/mozilla/multi-account-containers/assets/13033276/b0ff5d60-fa61-423a-b3d4-01cc4e3d2ca3)
 

### Expected behavior

Be able to manage, add or delete containers and links inside containers

**Comment by dannycolin** [comment] 2024-01-24 18:15
Duplicate of #1929

**Closed by dannycolin** 2024-01-24 18:15 UTC
Labels: bug
