### ISSUE TITLE
[Mac OS] The Containers "New Tab" menu wrongly opens behind other Firefox toolbar doorhangers / menus

### ISSUE THREAD

**Issue by SoftVision-PaulOiegas** [mozilla/multi-account-containers#616] opened 2017-06-21 15:53 UTC
[Affected versions]:
- Firefox 54.0 and up
- Containers Experiment Build: 2.3.0

[Affected Platforms]:
- All Mac OS

[Prerequisites]:
- Containers Experiment is installed on a new browser profile.

[Steps to reproduce]:
1. Start Firefox with the profile from prerequisites.
2. Depending on the window size, open several tabs until the "+" button reaches the Firefox Toolbar area.
3. Click on the "Containers" toolbar button to open its doorhanger.
4. Hover the "+" (new tab) button and observe the Containers new tab menu behavior. 

[Expected results]:
- The new tab menu is displayed always on top of other menus.

[Actual results]:
- The new tab menu is displayed underneath the doorhanger, making some of the containers selection impossible.

[Notes]:
- This issue also occurs when the Firefox menu is opened.
- This also happens on Windows and Linux, but only under context menus (right click).
- The current behavior forces the user to first close the doorhanger, before opening a specific container type.
- Here is a screenshot of the issue:

![behind doorhanger](https://user-images.githubusercontent.com/17258026/27392823-58c95750-56b0-11e7-8a19-410444772b79.png)

**Comment by kjozwiak** [comment] 2017-06-21 23:23
We've known about these type of issues since we started the containers test pilot experiment and decided that due to limited resources, there were other UI issues that were more important to fix than these type of bugs.

`This issue also occurs when the Firefox menu is opened.`

I reported the same issue under @95 before we launched but decided not to fix the issue.

I don't think we need to have this fixed for the shield study launch as we've had this in the test pilot for sometime now.

**Comment by jonathanKingston** [comment] 2017-06-22 12:33
Yeah I'm not sure if this is Mac specific at all. I can reproduce this with multiple windows. I think this might even be a dupe.

**Comment by SoftVision-PaulOiegas** [comment] 2017-06-22 15:42
The exact problem with the doorhangers (eg: Containers button doorhanger) is only reproducing on Mac OS because I verified this also on Windows 10 and Ubuntu 14.04. 
But as I've mentioned in the "Notes" section, something similar is happening with the context menu that is reproducible also on Windows and Ubuntu. Haven't checked with multiple windows though.

**Comment by kendallcorner** [comment] 2019-12-04 15:52
Hi. We're currently triaging the Multi Account Container issues. This appears to have been fixed, so I'm going to close it. If you don't feel the underlying issue has been resolved, feel free to reopen it with updated steps to reproduce.

**Closed by kendallcorner** 2019-12-04 15:52 UTC
Labels: bug
