### ISSUE TITLE
Synchronization accross multiple devices (firefox sync or 'export config file')

### ISSUE THREAD

**Issue by JetseBrouwer** [mozilla/multi-account-containers#1303] opened 2018-10-30 13:41 UTC
I'm currently using two machines (desktop and laptop) with the multi-account-containers. Every time I add a container, or a website to a container I have to do this one both machines, which can become tedious over a while.
it would be really nice if the settings would be synchronized using Firefox sync, or otherwise an import/export settings button would be very convenient.
(This would also prevent losing all the settings after enabling and disabling the plugin)

With kind regards,
Jetse

**Comment by JetseBrouwer** [comment] 2018-10-30 13:44
I forgot to label this as a feature request, and don't know how to this retroactively

**Comment by groovecoder** [comment] 2018-10-30 19:28
I think this is a dupe of https://github.com/mozilla/multi-account-containers/issues/339 - can you add upvote and/or comments there? We're about to start digging into our outstanding bugs & enhancement requests in order of upvotes.

**Closed** 2018-10-30 19:28 UTC
Labels: duplicate
