### ISSUE TITLE
[RFI] Add a UI to edit/change choices

### ISSUE THREAD

**Issue by TriMoon** [mozilla/multi-account-containers#1075] opened 2018-01-09 09:23 UTC
Currently you can make a check mark to always open in an assigned container, both using the context menu and popup of the extension-button.
When you open same website again you land on a page with a dialog to indeed open in previously chosen container.
On this landing page there is also an option to bypass this landing page by forcing the choice...
Everything nice and dandy so far 👍 

But now the next steps are needed...
  - There should be an UI to change/modify the choice to bypass that landing page, **without** removing the chosen container for it.
  - There should be an UI to change/modify the choice of container for a website, **without** the need to navigate to said website.

**Comment by groovecoder** [comment] 2018-01-09 15:01
Closing as dupe of https://github.com/mozilla/multi-account-containers/issues/719; please copy your ideas to comments on that issue.

**Closed by groovecoder** 2018-01-09 15:01 UTC
Labels: duplicate, enhancement, site assignment

**Comment by TriMoon** [comment] 2018-01-13 10:07
@groovecoder although it is related to #719 this issue is actually about the force-open functionality, not the tagging of the site for first use...

**Comment by groovecoder** [comment] 2018-01-15 15:35
True, but since GitHub doesn't let us mark issues as depending on each other (create a "bug tree" like we have in bugzilla), we try to keep UX issues together.

Whenever someone takes on #719 they will take on the UX/UI work to improve site assignments overall, so we will want the ideas from this issue over there.

**Comment by TriMoon** [comment] 2018-01-19 14:04
@groovecoder Then please keep this issue "open" so they will know to check it :wink:
