### ISSUE TITLE
"Open this site in your assigned Container?" Nag Needs Disable Toggle

### ISSUE THREAD

**Issue by jklappenbach** [mozilla/multi-account-containers#2414] opened 2022-09-14 16:30 UTC
### Before submitting a bug report

- [X] I updated to the latest version of Multi-Account Container and tested if I can reproduce the issue
- [X] I searched for existing reports to see if it hasn't already been reported

### Step to reproduce

Using 8.0.7

Many of us at Amazon use this extension.  In any complex environment, you're going to have two or three redirects to load a specific resource (Console dash, etc).  We're confronted with having to acknowledge where we want to open each redirect in the assigned container.  While some users operating in simple environments may appreciate this function, for power users operating in a security token environment, it's an unwanted source of friction.

### Actual behavior

We're getting "Open this site in your assigned Container?" prompts for each redirect, with a prompt to remember behavior for URLs that contain request specific data, and couldn't possibly be cached.

### Expected behavior

A toggle in the settings to turn off this nag.  All loads should just occur, by default, in the existing container in which they were launched.  Users can right click to open a link in a new container.

**Comment by lawsontech** [comment] 2022-09-18 01:02
I thought i would be smart and disable the plugin to stop this temporarily, when I re-enabled the plugin I had lost all my containers.

**Comment by shtrom** [comment] 2022-09-19 11:52
Would this be related to #2294?

**Comment by matlo607** [comment] 2022-09-21 12:58
Same issue as @jklappenbach.
As mentioned by @lawsontech, disabling the plugin and re-enable it made me lose all the containers configuration. I have not found any open issue tracking this problem.

**Comment by franciskafieh** [comment] 2022-12-04 13:42
> Would this be related to #2294?

No, because implementing that does not add any new feature, just changes UI. I would love for this specific fix to be implemented globally, that way I do not need to check the "do not ask again" button every time I add a new site to open in a container.

**Comment by kxc0re** [comment] 2022-12-07 13:28
a simple toggle in the extensions settings to just open sites in whatever container they are opened in would be very nice

"ignore assigned containers" or something like that

**Comment by dannycolin** [comment] 2022-12-07 23:52
Duplicate of #796

**Closed by dannycolin** 2022-12-07 23:52 UTC
Labels: bug
