### ISSUE TITLE
"Always open site in this Container" overrides action: right click on Tab > "Open in new Container Tab" > "No Container"

### ISSUE THREAD

**Issue by mihai-gabriel** [mozilla/multi-account-containers#2681] opened 2024-10-19 13:44 UTC
### Before submitting a bug report

- [X] I updated to the latest version of Multi-Account Container and tested if I can reproduce the issue
- [X] I searched for existing reports to see if it hasn't already been reported

### Step to reproduce

1. Assign website to a particular container: "Always open site in this container" 
2. Open a new tab
3. Navigate to that website
4. Check "remember my choice" when prompted for what container to use (the assgined one vs the current one)
5. Choose to open it in the assigned container
6. Right-click on the current Tab.
7. Select "Open in new Container Tab"
8. Select "No Container"

### Actual behavior

By selecting "No container" I expect the website to open normally, bypassing the "Always open site in Container".

### Expected behavior

The website is opened in the assigned container, not in "No container".

### Additional informations

I find it's important to allow users to bypass the "Always open site in container" once, if they need it.
Without this, I need to disable the extension, navigate to that tab and enable the extension back once again, which creates a lot of friction.

**Comment by dannycolin** [comment] 2024-10-19 16:05
Duplicate of #1442

**Closed by dannycolin** 2024-10-19 16:05 UTC
Labels: bug
