### ISSUE TITLE
Keyboard shortcut to reopen current tab in container

### ISSUE THREAD

**Issue by pH142857** [mozilla/multi-account-containers#2208] opened 2021-11-22 09:57 UTC
Quite often, I click on a URL from another app and it opens in Firefox in the default container. When that happens, I would like to be able to perform the same action as: right click on tab > "_open in a new container tab_" > select container, but with a keyboard shortcut, similarly to the ones for opening a brand new tab in a container (`Ctrl` + `Shift` + number).

**Comment by lopis** [comment] 2021-12-01 07:54
I want this too, but what would be a good shortcut? `Ctrl` + `Shift` + `number` is really awkward to use. `Alt` + `Shift` + `number` + `click` on the link would be better.

**Comment by pH142857** [comment] 2021-12-01 08:28
@lopis In my use case, the shortcut would be used once the default tab has opened in Firefox, to fix it. The shortcut you describe, `Alt` + `Shift` + `number` + `click`, would be to open a link immediately in the good container and it wouldn't cover the case of a link in another app (since this is a Firefox extension which has no power in another app).

As for which shortcut it could be, I think an extension team member would be a better fit to determine that. What comes to my mind is a 4-key shortcut extended from `Ctrl` + `Shift` + `number`, so something like `Ctrl` + `Alt` + `Shift` + `number`, even though it seems a bit heavy.

**Comment by ndrewtl** [comment] 2022-01-14 20:29
Maybe we could implement this feature as an initially unbound shortcut, and then users could choose which binding they prefer?

**Comment by Neil20170220** [comment] 2022-03-20 04:36
I have two github account, and ofen i need to open current tab with another container

**Comment by chenshengzhi** [comment] 2022-03-20 04:37
I have two github account, and ofen i need to open current tab in another container

**Comment by xplosionmind** [comment] 2022-11-22 09:28
Duplicate of #1792

**Comment by dannycolin** [comment] 2023-01-19 01:15
> Maybe we could implement this feature as an initially unbound shortcut, and then users could choose which binding they prefer?

That sounds like the best solution since there's already a lot of used shortcuts in Firefox.

**Comment by dannycolin** [comment] 2023-01-19 01:16
Duplicate of #1792

**Closed by dannycolin** 2023-01-19 01:16 UTC
Labels: :+1:  Feature Request, Component: Shortcuts
