### ISSUE TITLE
Lost containers when disabling, then re-enabling

### ISSUE THREAD

**Issue by VersionThis** [mozilla/multi-account-containers#1935] opened 2021-01-01 15:43 UTC
- Multi-Account Containers Version:  **7.1.0**
- Operating System + Version:  **OSX 10.15.7**
- Firefox Version:  **84.0.1**
- Other installed Add-ons + Version + Enabled/Disabled-Status:  
- Adblock Plus - free ad blocker	extension	3.10.1	true	{d10d0bf8-f5b5-c8b4-a8b2-2b9879e08c5d}
Amazon.com	extension	1.3	true	amazondotcom@search.mozilla.org
AutoFullscreen	extension	1.0.0.2	true	{d320c473-63c2-47ab-87f8-693b1badb5e3}
Bing	extension	1.2	true	bing@search.mozilla.org
DuckDuckGo	extension	1.1	true	ddg@search.mozilla.org
eBay	extension	1.2	true	ebay@search.mozilla.org
Element Blocker	extension	1.5	true	element-blocker@lukepeters.me
Firefox Multi-Account Containers	extension	7.1.0	true	@testpilot-containers
Google	extension	1.1	true	google@search.mozilla.org
Media Helper	extension	1.17.1	true	{85603edc-044f-4391-9a95-a94682f449b4}
Mile Wide Back	extension	0.2.7	true	{3117b8b0-9eb4-4274-abfb-bdc2ec48d363}
Old Reddit Redirect	extension	1.2.0	true	{9063c2e9-e07c-4c2c-9646-cfe7ca8d0498}
OneTab	extension	1.39	true	extension@one-tab.com
Search by Image	extension	3.4.2	true	{2e5ff8c8-32fe-46d0-9fc8-6b8986621f3c}
Stop AutoPlay Next for YouTube™	extension	0.2.1	true	jid1-nbzaq9ol2hyY64gGe@jetpack
Video DownloadHelper	extension	7.4.0	true	{b9db16a4-6edc-47ec-a1f4-b86292ed211d}
View Image	extension	3.3.1	true	{287dcf75-bec6-4eec-b4f6-71948a2eea29}
Wikipedia (en)	extension	1.1	true	wikipedia@search.mozilla.org
YouTube™ Repeat Button	extension	0.1.3	true	{28c18e92-ab27-403f-973d-49d1d0fa7665}
Zoom Page WE	extension	17.11	true	zoompage-we@DW-dev

### Actual behavior
Extension forgets previously defined containers, in between disabling & re-enabling cycles

### Expected behavior
Extension should remember containers, _as it used to do in earlier versions_

### Steps to reproduce
1.  Define custom container
2.  Disable extension
3.  Reenable extension
4. Observe custom container has disappeared

**Comment by groovecoder** [comment] 2021-01-13 18:35
Duplicate of https://github.com/mozilla/multi-account-containers/issues/1236

**Closed by groovecoder** 2021-01-13 18:35 UTC
Labels: duplicate

**Comment by Synetech** [comment] 2022-02-15 20:33
Duplicate of a _lot_ of issues, because it's _still_ a bug. 😒
