### ISSUE TITLE
Long Names Word wrap are overlapping with other entries

### ISSUE THREAD

**Issue by gw-bcharboneau** [mozilla/multi-account-containers#2544] opened 2023-06-19 13:40 UTC
### Before submitting a bug report

- [X] I updated to the latest version of Multi-Account Container and tested if I can reproduce the issue
- [X] I searched for existing reports to see if it hasn't already been reported

### Step to reproduce

using for AWS Organizations
1. Name set as "{OrgName} {RoleName}" where in my case both names can be 23-25 characters long. the space causes it to word wrap.

### Actual behavior

Line spacing of the wordwrapped lines is too large causing the top line to overlap with the container name above it and the bottom line to overlap with the container name below it.
![image](https://github.com/mozilla/multi-account-containers/assets/58750574/2bdc11de-b911-4722-89a3-65e14eaa278f)

### Expected behavior

decreasing line spacing between wordwrapped lines should fix the issue.

**Comment by dannycolin** [comment] 2023-06-19 14:28
Duplicate of #1904

**Closed by dannycolin** 2023-06-19 14:28 UTC
Labels: bug
