### ISSUE TITLE
[BUG] Sync - Containers list order is not synced

### ISSUE THREAD

**Issue by o-l-a-v** [mozilla/multi-account-containers#1697] opened 2020-03-29 15:21 UTC
* When syncing containers from between PCs, the order of the containers in the list of Multi Account Containers is not synced/ remembered. 

What makes this even worse is that there is no way of manually or automatically re-order/ sort the containsers. I want them to be alphabetically.

**Comment by andrew-jacob** [comment] 2020-06-07 16:53
I just wanted to support troubleshooting this issue; this bug is making CookieAutoDelete unable to be synced between computers. The expressions are syncing up with the wrong container because the list order is not synced. Frustrating oversight by containers to sync in a seemingly random order... not even alphabetical or identical to my other computer.

Here is the referenced issue: https://github.com/Cookie-AutoDelete/Cookie-AutoDelete/issues/579

**Comment by alexanderadam** [comment] 2020-08-05 18:33
Duplicate of #330

**Comment by o-l-a-v** [comment] 2020-08-06 09:22
@alexanderadam 
No, it's not the same issue as 330 IMO. This issue is about the sync not actually syncing the same settings/ setup.

**Comment by alexanderadam** [comment] 2020-08-06 09:29
Sorry, maybe your comment

> there is no way of manually or automatically re-order/ sort the containsers. I want them to be alphabetically.

mislead me.

**Comment by dannycolin** [comment] 2022-12-08 05:30
Duplicate of #1625

**Closed by dannycolin** 2022-12-08 05:30 UTC
Labels: Component: Sync
