### ISSUE TITLE
Left-click navigation leaves behind undesired tabs

### ISSUE THREAD

**Issue by MOFTAD** [mozilla/multi-account-containers#1837] opened 2020-07-29 06:49 UTC
- Multi-Account Containers Version: 7.0.2
- Operating System + Version: Windows 10
- Firefox Version: 79.0
- Other installed Add-ons + Version + Enabled/Disabled-Status: None

### Actual behavior

Left-click opening a link to a domain assigned to a different container (through use of the "Limit to Designated Sites" and "Always Open This Site in" options) opens the site in a new tab, leaving the original tab behind.

### Expected behavior

Left-click opening such a link should convert the current tab's container to that of the new domain or automatically close the origin tab.

### Steps to reproduce
1. Set domains _A_ and _B_ to always open in containers _1_ and _2_, respectively.
2. Ensure that both of the aforementioned containers have been limited to designated sites.
3. From domain _A_, left-click open a link to domain _B_.

**Comment by Moonloard** [comment] 2020-07-30 10:56
Duplicate of #1765 #1704 #1590.
Pull request #1835 should solve this issue.

**Comment by groovecoder** [comment] 2020-08-12 19:15
Closing as dupe, as mentioned by @Moonloard.

**Closed by groovecoder** 2020-08-12 19:15 UTC
Labels: duplicate
