### ISSUE TITLE
[Feature Request]: Option to re-arrange the order of containers displayed in the list

### ISSUE THREAD

**Issue by ameliorate-droid** [mozilla/multi-account-containers#1804] opened 2020-07-14 00:56 UTC
Hi guys, 

 This is a feature request. I would like to see an option to drag and re-arrange the containers in the list. Currently, they are listed in the order they were created. 
After a while, if a user is not using that 'X' container much they may want to still keep it, but towards the bottom of the list.
A burger menu style icon next to each container could be a UI option to drag and re-arrange.
I, for example, use 30+ containers and do not use tabs without a container. It becomes quite an exercise to search for a right one, when required.
Similarly, an option to sort the container list alphabetically could also be useful to some.

**Comment by alexanderadam** [comment] 2020-08-05 18:31
Duplicate of #330

**Comment by Solid-Ice8** [comment] 2020-08-13 13:28
You can manually arrange the order to your specific ordering manually with containers.json file.

You may use my reference: #1707 mid-way down the post where I explain the steps to do so.

**Comment by groovecoder** [comment] 2021-01-22 17:29
#330 was fixed in https://github.com/mozilla/multi-account-containers/pull/1608 and 7.3.0 release is pushed to AMO waiting for review and publish.

**Closed by groovecoder** 2021-01-22 17:29 UTC
Labels: duplicate
