### ISSUE TITLE
Feature request: Default profile for new tabs + New tab with profile of current tab

### ISSUE THREAD

**Issue by Je4hel** [mozilla/multi-account-containers#1000] opened 2017-11-24 09:37 UTC
Hello,

I find this extension quite useful to handle several profiles but I have two requests that would make it really easier to use every day. For context, let me add that I use 3 different profiles at the same time all day long, switching back and forth between my personnal profile, my work/organization profile, and my work/client profile (which all use a different Microsoft account for instance).

They may seem to be exclusive but if they are implemented as options, I think it would be nice :-).

**Default profile for new tabs**
As a user, I want to have the option to select a specific profile to use as default when I click on the new tab button, so that I don't always have to long-press the new tab button everytime I want to open a new tab.

**New tab with current tab profile**
As a user, when I am using profile A in a tab and I click on the new tab icon, I want my new tab to also use profile A so that I don't have to long-press the new tab button everytime I want to open a new tab.

Thank you!

**Comment by christophetd** [comment] 2017-11-28 13:07
Big +1. That would make the extension much more usable.

**Comment by beatgammit** [comment] 2017-11-28 18:51
I like both of these suggestions, but just doing the second one would be enough 90% of the time IMO. I marked this as 3 stars in the FIrefox addon site due to this issue, but I'd likely give it a solid 5 stars if this issue is solved.

My workflow is very keyboard driven, and not having a way to open a new tab in a given container is really annoying and honestly makes the feature too cumbersome to use on all of my computers, so I only use it on my laptop where I absolutely need the separation (I used to have Chrome for work and Firefox for personal, but this has allowed me to ditch Chrome almost entirely).

If this issue can be resolved in some way, I can recommend this extension to friends. For now, however, I only mention it if it comes up because it's a little annoying to use.

**Comment by vkareh** [comment] 2017-11-29 14:46
@Je4hel - You can `Ctrl+Click` on the new tab button and the new tab will use the same profile as the currently-selected tab.

@beatgammit - I agree with you about the keyboard-driven workflow. I'm a heavy keyboard user and I hate whenever I need to switch to mouse. In playing with the extension, it seems like you can work around it (awkwardly, though) by doing the following sequence: `Ctrl+.` -> `Tab` -> `Enter`. The Ctrl+period opens the Container menu, Tab cycles through your containers, Enter opens a new tab with it. Definitely not as easy as Ctrl+something, but allows you to keep your hands on the keyboard 🙂

**Comment by beatgammit** [comment] 2017-11-29 15:39
@vkareh Nice, I didn't know about that `Ctrl+.` shortcut. How did you find that keyboard shortcut? Is there some documentation somewhere?

**Comment by vkareh** [comment] 2017-11-29 15:50
@beatgammit - I stumbled upon it by looking at the source code: https://github.com/mozilla/multi-account-containers/blob/master/webextension/manifest.json#L34-L42

**Comment by falolaf** [comment] 2017-11-30 04:49
This addon opens a new tab, via keyboard shourtcut, in the same container as the current tab:
https://addons.mozilla.org/sv-SE/firefox/addon/new-container-tab/

**Comment by jonathanKingston** [comment] 2017-12-05 20:47
This is a duplicate of #356 and we are going to add a new pref to change the default tab based on the existing tab the user is in too:  [Bugzilla 1406371](https://bugzilla.mozilla.org/show_bug.cgi?id=1406371)

> awkwardly, though) by doing the following sequence: Ctrl+. -> Tab -> Enter

The tab in this sequence will be removed soon and it will go straight to container 1. Tab and Down/Up will move through the menu.

**Closed by jonathanKingston** 2017-12-05 20:47 UTC
