### ISSUE TITLE
Feature Request: Always Open links from Email Programm on PC / Email Website in selected container

### ISSUE THREAD

**Issue by immortaliseORdie** [mozilla/multi-account-containers#1995] opened 2021-03-18 13:27 UTC
- Multi-Account Containers Version:
- Operating System + Version:
- Firefox Version:
- Other installed Add-ons + Version + Enabled/Disabled-Status:

### Steps to reproduce
1.
2.
3.

**Comment by grahamperrin** [comment] 2021-04-23 21:29
Please try **Always In Container**. See the screenshot at https://bugzilla.mozilla.org/show_bug.cgi?id=1692124#c1

**Comment by dannycolin** [comment] 2023-01-06 21:17
Duplicate of #1727

**Closed by dannycolin** 2023-01-06 21:17 UTC
