### ISSUE TITLE
Feature request: grey, black, and white options for container colors.

### ISSUE THREAD

**Issue by jessamynwest** [mozilla/multi-account-containers#2274] opened 2022-01-21 21:35 UTC
For fussy palette reasons, I'd really like to be able to have colors like black, grey, and white, be available to assign to containers, or have there be an assignable hex code. Right now there are eight colors and they're all pretty bright and none of them match my browser color palette. Alternately, maybe this color stripe could be removed from the container tabs? I appreciate that the intent is so people are clear about which tabs are using containers, I'd just like more options for how it looks. Example below, nothing against blue, green or fuschia. Thanks.

<img width="340" alt="suggestion for how this could look with extra selectable color options for black, grey and white" src="https://user-images.githubusercontent.com/698448/150603161-d7815911-0a0f-4cc2-8229-d242f7237fc0.png">

**Comment by dannycolin** [comment] 2022-05-20 00:31
Duplicate of #391.

**Closed by dannycolin** 2022-05-20 00:31 UTC
