### ISSUE TITLE
Closing all tabs after uninstall

### ISSUE THREAD

**Issue by inoyakaigor** [mozilla/multi-account-containers#910] opened 2017-10-16 11:37 UTC
When i uninstall add-on, pinned tab in personal container was closed

**Comment by SoftVision-EmilPasca** [comment] 2017-10-16 11:57
Hi @inoyakaigor thanks for reporting this issue. It sounds like a duplicate of https://github.com/mozilla/multi-account-containers/issues/864, please follow along on that thread for further details.

**Closed by SoftVision-EmilPasca** 2017-10-16 11:57 UTC
