### ISSUE TITLE
Question: shortcut to open tab in same account

### ISSUE THREAD

**Issue by ivanperez-keera** [mozilla/multi-account-containers#2143] opened 2021-10-02 14:47 UTC
Is there a shortcut to open a tab in the same account I am in? I mean a fixed, key combination that you can always press to open a new tab in the exact same account you are using.

Example of what I am looking for:
- Press Ctrl+shift+u to open tab in same account.
- A setting I can enable so that Ctrl+t will ALWAYS open new tabs in the same account.

Example of what I'm *not* looking for:
- Press Ctrl+. then look at the accounts in the menu that opens and use a number to select. 
- Press Ctrl+. then look at the accounts in the menu that opens and use the mouse to select an account.

_Reasoning_

I'm finding myself pressing Ctrl+t to open a new tab out of habit, only to see that the link I try to open requires logging in whatever web app I was using again. This is because Ctrl+t will open a tab without an associated account.

To me, this really breaks my mental flow. I think a fixed key combination would be less distracting. When you are working and concentrated, you normally do not keep which account you are using present. You can look it up. You can use color codes. But that requires thinking. When you bring up the menu, then you also have to go through the list. That, again, requires thinking, and it breaks mental flow.

I'm looking for a fixed key shortcut that allows me to quickly open a new tab and keep my mind fully focused.

**Comment by kalenmike** [comment] 2021-10-04 12:27
:+1:  +1

**Comment by dannycolin** [comment] 2022-08-06 00:57
The only solution currently is to middle click on the new tab button. To change the behavior of `ctrl + t`, we'd need to implement it directly in Firefox. However, we could implement a customizable shortcut for that. I'll close this as a duplicate of #462.

**Closed by dannycolin** 2022-08-06 00:57 UTC

**Comment by kalenmike** [comment] 2022-08-06 11:34
@dannycolin Middle click is a pretty good solution. Thanks.
