### ISSUE TITLE
Configuration to disable "achievements"

### ISSUE THREAD

**Issue by rrix** [mozilla/multi-account-containers#1085] opened 2018-01-20 23:55 UTC
Badging the add-on icon with "NEW" for the achievements feature in #921 is a dark-UX pattern that I would like to disable on my Firefox installations. A way to disable them entirely or at least not badge the icon would be very much appreciated.

**Comment by groovecoder** [comment] 2018-01-22 13:30
Duplicate of #994. Please add upvotes and comments there.

**Closed by groovecoder** 2018-01-22 13:30 UTC
Labels: duplicate
