### ISSUE TITLE
NewTab page middle click opens in No-Container

### ISSUE THREAD

**Issue by ghost** [mozilla/multi-account-containers#390] opened 2017-03-17 16:43 UTC
If I open a newTab page in a given container and middle-click on one of the links, it opens another tab but with No-Container, whereas a middle-click on a link on a website open a new tab in same container (logical behavior).

(I first thought it's because I use an Add-On with fast dial bookmarks, but I disabled it and used default Firefox New Tab page and noted the same incoherent behavior).

**Comment by groovecoder** [comment] 2017-03-17 17:26
This sounds like a duplicate of https://github.com/mozilla/testpilot-containers/issues/327? If so, can you close this and add a 👍 to that issue?

**Comment by bakulf** [comment] 2017-03-20 13:04
I think the reason why we have this bug is because newTab is loaded using a systemPrincipal who doesn't have the userContextId set to the container ID. Probably it's also platform bug.

**Comment by bakulf** [comment] 2017-03-20 13:48
This is not a duplicate. The other bug involves the context menu.

**Comment by JohnLGalt** [comment] 2017-03-20 17:09
In response to the OP, I opened a new tab page in a particular container, and then I middle-clicked on one of the links on the new tab page, and it opened in the same container, not container-free.

Could it be something else that is interfering with the behavior on your end, such as another addon (TMP comes to mind, as it has all sorts of handling settings for middle-, alt-, ctrl- and shift-clicking)?

**Comment by Drouchka** [comment] 2017-03-21 16:01
Could totally be that I have an interfering add-on. That's why I had tested without my start newtab page addon (userlogos.org/extensions/fastdial) and it still didn't work.

Now I even tried disabling all my addons and still does not have the correct behavior. I understand disabling is probably not sufficient.

How can I test a clean install on my system without loosing all my addons, history, etc.?
Is there any info you might need?

Platform: W7
Firefox 52.0.1 (32-bit)

**Comment by Drouchka** [comment] 2017-03-21 16:11
Could totally be that I have an interfering add-on. That's why I had tested without my start newtab page addon (userlogos.org/extensions/fastdial) and it still didn't work.

Now I even tried disabling all my addons and still does not have the correct behavior. I understand disabling is probably not sufficient.

How can I test a clean install on my system without loosing all my addons, history, etc.?
Is there any info you might need?

Platform: W7
Firefox 52.0.1 (32-bit)

**Comment by JohnLGalt** [comment] 2017-03-21 18:09
Since I run the Nightly channel, I always edit the shortcut in Windows to start the Firefox Profile Manager by default.  So, for me, running 64bit Nightly, I edit the target line of the shortcut to read as 

**"C:\Program Files\Nightly\firefox.exe" -profilemanager**

The key is to add the **-profilemanager** after the commandline to run firefox.  In the same way, if you do not want to always open it, you can simply run the entire command from the run dialog in Windows.

IIRC, the same should apply for other OSs as well.

If you want the Profile manager to always open, but not have to run it via the commandline, then when the profile manager opens, be sure to **uncheck** the button beside the text _Use the selected profile without asking at startup_ and you should then automatically load profile manager from then on, allowing you to pick a profile.

Once Profile manager is open, all you need to do is create a new profile, and you'll have a pristine profile to play with.

HTH

**Comment by Drouchka** [comment] 2017-03-22 16:21
I opened Firefox with a brand new profile and still get that bug.

Test: Open a brand new window in a brand new profile. Open NewTab in Personal Container.
Click on 4th link in first row. 
First picture: while loading, the tab is not in Personal Container.
So I waited. Maybe it only shows later. Second picture: open tab is is No-Container.

![loading](https://cloud.githubusercontent.com/assets/26488067/24208032/d1c8b02c-0f22-11e7-8afd-284f32a92319.png)

![opentab](https://cloud.githubusercontent.com/assets/26488067/24208165/34ce5082-0f23-11e7-8d02-809b7bd3ffa9.png)

Anything I can add to help? Some log file? Some command I can run, or other test I can do?

Windows 7 Professional / 64bits / Service Pack 1
Firefox 52.0.1 (32-bit)


Drouchka

**Comment by jonathanKingston** [comment] 2017-03-24 17:39
@kjozwiak to check if this is a dupe of #327 as it doesn't seem to be an issue of the context menu as @bakulf stated.

**Comment by JohnLGalt** [comment] 2017-03-25 03:41
Could this be another bug that is fixed in newer builds?  It works as intended on Firefox Nightly 55.0a1

**Comment by androuchka** [comment] 2017-05-08 13:22
I think I found the problem, by mistake.
For some reason, I had the privacy config key _**privacy.usercontext.about_newtab_segregation.enabled**_ set to **true**. After setting it to false, the problem disappears.

The thing is I have no clue as to who set that key in the first place, but its name seems clear: the newtab is segregated in some sense.

Hope you guys know what's going on.

Keep on the good work,
Drouchka

**Comment by groovecoder** [comment] 2017-12-05 16:56
Seems to be fixed on newer builds.

**Closed by groovecoder** 2017-12-05 16:56 UTC
Labels: bug, needs: M-C Platform
