### ISSUE TITLE
Bug: Does not remember "Always Open" settings for multiple accounts on same site

### ISSUE THREAD

**Issue by FuzzeeDee** [mozilla/multi-account-containers#1764] opened 2020-06-09 18:58 UTC
I use multiple accounts for GMail and YouTube. When I select "always open in this container" it wipes out that decision for every other tab that has me logged into Gmail under a different account. This causes issues when I quite Firefox and open it again.

The whole reason I use containers is so that I can keep separate tabs open in Gmail each logged into it's own account. Same goes for YouTube. It keeps them separated just fine during use, it is when I reopen Firefox that I then have to go through the process all over again of having to select which containers to open the tabs in again, then I have to once again pin the tabs and put them all in the right order.

- Multi-Account Containers Version: 6.2.5
- Operating System + Version: Mac OS 10.15.5
- Firefox Version: 77.0.1 - 64 bit

Add ons: Auto Update: ON
<img width="456" alt="Add ons manager list" src="https://user-images.githubusercontent.com/66695395/84188124-53e76280-aa50-11ea-9401-a2cd2a6072c6.png">

**Comment by Solid-Ice8** [comment] 2020-06-20 15:54
Why so many add-ons in Private/Incongo Mode? _Container Tabs_ **does not work** in Private Mode...maybe that's why you're having problems?

I have never had any problems exiting (Alt+F4) FireFox. And I close it regularly to experiment. 

All my containers tabs and my pinned tabs remain in place. I just continue where I left off (where ever that is)

**Comment by FuzzeeDee** [comment] 2020-06-20 16:53
I don't use my browser in private mode very often, this is just my normal
primary usage. The problem is that I have multiple gmail accounts and
YouTube channels. Every time I quit my browser, the next time I start it, I
have to go through the process of telling each tab that was used for gmail
or YouTube except one set, which container to open in. The setting that
tells it to always open a tab in a particular container only remembers that
setting for one login account. The container system does not see a
difference between the different logins for each site. Because it stops
loading the page to ask which container to load it in, it breaks it out of
being pinned. I need the container system to see which account I am logged
into that site under and treat it as a new version or different site.

For example:
gmail logged in as Dave Reid = gmail site one
gmail logged in as Integrated Healing = gmail site two
gmail logged in as Fuzzee Tutorials = gmail site three.

Whenever I set the container to "always load this site in this container
under this login it wipes out the last site/login where I told it to always
open in it's container. So the workaround I use currently is to open my
sites in the right containers, then turn off the container plugin. Then I
can close firefox and reopen it without issues until something happens that
closes a tab, then I have to turn it on again. Luckily for me, when I turn
off the container plugin it still keeps the actual containers open and in
use.
_____________________________
*Regards, Fuzzee Dee (David Reid)*
*YouTube <https://www.youtube.com/channel/UCGwmrf2yFE-gIxCbdf1vBCQ>* *-
Personal Channel: *My Aquarium, General and Healing Playlists
*YouTube <https://www.youtube.com/channel/UC0tSDolHeB-LtQOcJTo-20g> -
FuzzeeDee Tutorials:* In depth guides, Quick tips, Tech news & Advice
*Website <https://reviews.ihaservices.ca> - Reid's Product Reviews*
*FaceBook* <http://www.facebook.com/FuzzeeDee>
*- FuzzeeDee's Timeline*
*FaceBook <https://www.facebook.com/FuzzeeTutorials/> - FuzzeeDee
Tutorials: *Quick tips, Tech news & Advice, YouTube links

*Twitter <https://www.twitter.com/fuzzeedee> - Personal Stuff, Integrated
Healing*
*BLOG <Https://fuzzeedeeintegratedhealing.blogspot.com>* - *Integrated
Healing Alliance (IHA)*

**Comment by maxxcrawford** [comment] 2020-07-08 19:23
Unfortunately, this is as-expected behavior. If you're going to use the same site in different containers, you will not be able to use the "Always open in…" feature. (Specifically, because the uniqueness of the URL is what is hooked into the specific "Open in…" logic.)

**Closed by maxxcrawford** 2020-07-08 19:23 UTC
Labels: expected-behavior
