### ISSUE TITLE
Duplication error on list all tabs dropdown menu

### ISSUE THREAD

**Issue by JohnLGalt** [mozilla/multi-account-containers#394] opened 2017-03-18 18:25 UTC
I originally posted this at discourse, ref:  https://discourse.mozilla-community.org/t/duplication-error-on-list-all-tabs-dropdown-menu/14438

I noticed that this occurred in the previous version, but decided to wait until this new version 2 was released before reporting in case it was fixed. Alas, it is not.

Upon pressing the list all tabs button at the top of my Firefox window, I get a normal display of the opened tabs and a sub-menu item for container tabs, as so:

![containers error 1](https://cloud.githubusercontent.com/assets/7432512/24074823/8a2d0cac-0be6-11e7-832e-ddd859960c5c.PNG)

However, if I then mouse over the area where it says **New container tab** it duplicates all of the opened tabs showing in the list, as so:

![containers error 2](https://cloud.githubusercontent.com/assets/7432512/24074824/913393f4-0be6-11e7-98d3-2c769d5d0ab5.PNG)

If I move the mouse _off_ the **New container tab** menu item, it then reverts to showing none of the opened tab entries, as so:

![containers error 3](https://cloud.githubusercontent.com/assets/7432512/24074828/95ab8aae-0be6-11e7-89ad-a191e7ef675e.PNG)

This is reproducible for me 100% of the time.

**Comment by kjozwiak** [comment] 2017-04-04 15:06
This is still easily reproducible using the STR that @JohnLGalt added above using 2.1.1. However, we've talked about removing this container access point several times in the past. We originally added this access point because we only have the File Menu at the time so we wanted to make it easier for users to access/open containers. However, we now have several other access points that are a lot easier to reach.

**Comment by kendallcorner** [comment] 2019-12-03 21:41
Hi. We're currently triaging the Multi Account Container issues. This issue does not appear to be relevant any more, so I'm going to close it. If you don't feel the underlying issue has been resolved, feel free to reopen it with an updated description of the issue.

**Closed by kendallcorner** 2019-12-03 21:41 UTC
Labels: bug

**Comment by JohnLGalt** [comment] 2019-12-06 20:50
Fx Nightly 73.0a1 (2019-12-06) (64-bit)
MAC 6.1.1

Can confirm not occurring for me.
