### ISSUE TITLE
Syncing tmp containers after deleting the Temporary Containers extension several months ago

### ISSUE THREAD

**Issue by coyotefoxtrot** [mozilla/multi-account-containers#1853] opened 2020-08-23 12:09 UTC
- Multi-Account Containers Version: 7.0.2
- Operating System + Version: Manjaro 20.1 Mikah
- Firefox Version: 79.0
- Other installed Add-ons + Version + Enabled/Disabled-Status: uBlock 1.29.2, Wikiwand 1.0, NoScript 11.0.39, Enhancer for Youtube 2.0.101. Decentraleyes 2.0.14, Dark Reader 4.9.16, CanvasBlocker 1.3, Bitwarden 1.45.0 [all enabled]

### Actual behavior
Several dozen tmp containers are being synced even though I do not have the Temporary Containers extension anymore. I deleted it 2 or 3 months ago along with all the synced tmp containers because of the bug of syncing tmp containers, and they haven't returned until 3 days ago. I delete them all and then after the next reboot they return. 

### Expected behavior
No tmp containers being synced since I do not have the tmp extension and syncing has been normal for several months

### Steps to reproduce
1. Delete the tmp containers
2. reboot computer
3. open Firefox and check Multi-Account Containers extension to see tmp containers have returned

### Notes
Why are these all of a sudden coming back after several months of no issues and not having the Tmp containers extension? Is there a way to access the sync data at the source and delete them?

**Comment by maxxcrawford** [comment] 2020-08-25 15:39
Duplicate of #1675

**Closed by maxxcrawford** 2020-08-25 15:39 UTC
