### ISSUE TITLE
Option "Open in new container tab" does not work for pages marked as "Always open this site in..."

### ISSUE THREAD

**Issue by lukasheinz92** [mozilla/multi-account-containers#2496] opened 2023-02-01 16:28 UTC
### Before submitting a bug report

- [X] I updated to the latest version of Multi-Account Container and tested if I can reproduce the issue
- [X] I searched for existing reports to see if it hasn't already been reported

### Step to reproduce

1. I marked a web page as "always open this site in" container "A", for example gmail.com always open in Private container
2. I saved the web page as bookmark
3. Then I needed to open the page in a container "B" so I clicked with right mouse button on the saved bookmark and chose "open in a new container" -> container "B", for example to open the gmail in Work container
4. Unfortunately, the page was opened in container A, not B

### Actual behavior

If I set a page to "always open this site in ..." then I am not able to use "open in a new container tab" option to change the default container.

### Expected behavior

I would expect that using the "always open this site in ..." option will open a web page in a chosen container by default but using the option "open in a new container tab" would change the default behavior so I could open the page in a different container.

**Comment by dannycolin** [comment] 2023-02-01 17:49
Duplicate of #1442

**Closed by dannycolin** 2023-02-01 17:49 UTC
Labels: bug, Status: Expected
