### ISSUE TITLE
Sort containers doesn't work into all menus

### ISSUE THREAD

**Issue by myset** [mozilla/multi-account-containers#2481] opened 2022-12-28 11:30 UTC
### Before submitting a bug report

- [X] I updated to the latest version of Multi-Account Container and tested if I can reproduce the issue
- [X] I searched for existing reports to see if it hasn't already been reported

### Step to reproduce

1. Open Firefox Container Manager -> Manage Containers
2. Sort containers with your own order 

### Actual behavior

Containers are well sorted only in Firefox Container Manager.
The other contextual menu or a Tab -> Open in new Container Tab is not.
The rest remain in the creation sort order.

### Expected behavior

It will be nice to be a consistent sort approach as it is chosen across all the menus.

### Additional informations

Thank you, community, for the great work in maintaining this featured/unique extension

**Comment by dannycolin** [comment] 2022-12-28 14:10
Duplicate of #1958

**Closed by dannycolin** 2022-12-28 14:10 UTC
Labels: bug

**Comment by myset** [comment] 2022-12-28 18:36
Oldie but goldie

**Comment by dannycolin** [comment] 2022-12-28 18:58
Indeed. The joy of software development where something is more complexe to implement than it seems. See: https://bugzilla.mozilla.org/show_bug.cgi?id=1333395
