### ISSUE TITLE
Container has no title displayed, if the container's name is a blank space

### ISSUE THREAD

**Issue by Softvision-MariusComan** [mozilla/multi-account-containers#764] opened 2017-08-25 11:48 UTC
**Notes**
- If in the container's "Name" field we use only a "blank space" without any other characters, the name will be displayed blank in the "Containers" panel. However if we try to create a container without any characters in the "Name" field, the container's name will autocomplete itself.
- Also if the container's name contains multiple 'blank spaces", its name in the address bar looks out of place.

**[Affected versions]:**
- Firefox release 55 and up

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- Have a Firefox profile with the latest version of the containers add-on (3.1.0) installed.

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites.
2. Click the "Containers" button under the toolbar;
3. Click the "Create new Container" (+) from the bottom-right corner of the "Containers" panel;
4. Select all the text from the "Name" field and press the space key once.
5. Observe the OK button.

**[Expected result]:**
- "OK" button is inactive.

**[Actual result]:**
- "OK" button is active and clickable.

**[Additional Notes]:**
- Attached a screen recording of the issue:
![001](https://user-images.githubusercontent.com/31243259/29712687-b5670964-89a3-11e7-8e2f-6fbfdb9637e0.gif)

- Attached a screenshot of the "address bar":
![blank space](https://user-images.githubusercontent.com/31243259/29712694-be6087c0-89a3-11e7-901d-9e2cd8c61354.png)

**Comment by jonathanKingston** [comment] 2017-09-26 02:24
Duplicate of #731

**Closed by jonathanKingston** 2017-09-26 02:24 UTC
Labels: duplicate
