### ISSUE TITLE
Ability to sort containers.

### ISSUE THREAD

**Issue by unlimitedfear** [mozilla/multi-account-containers#1199] opened 2018-04-23 13:15 UTC
Hello
Thank you for the wonderfull add-on. very usefull
please add ability to sort containers. for example If a user creates a new container, he cannot move it to the top of list.

**Comment by falolaf** [comment] 2018-04-24 04:07
Not very convenient but you can manually rearrange the containers in the containers.json in your profile folder. Close FF before changing that file though.

**Comment by v00p** [comment] 2018-04-24 23:39
@falolaf Thanks for sharing !

**Comment by v00p** [comment] 2018-04-25 00:02
Dup #979

**Comment by unlimitedfear** [comment] 2018-04-26 06:07
@falolaf Thanks dude, will try.

**Comment by v00p** [comment] 2018-04-29 23:30
@falolaf can't modifying the containers.json file reset all containers to default (event if you set the file Read-Only .

**Comment by falolaf** [comment] 2018-04-30 07:34
@v00p 
I have not had that behaviour. Tested with FF59 on Win7 and openSUSE 42.3. What happens if you restore the file from backup?

**Comment by v00p** [comment] 2018-05-02 21:37
@falolaf   A. It does brings all my containers back when I restore my initial container.js file. But applying any change to it (firefox not running) will reset itself to stock state on next FF launch. 

(note that, I do use the Mozilla Multi-Account Firefox addon (ie firefox_multi_account_containers-6.0.0-an+fx-windows.xpi), even thought its totally optional for using and managing containers.  Reason I still use it is because there is not any other FF Containers management addon yet, and its currently the only way to have the Container/Domain's assignation feature working (that "Open this site in your assigned container?" trigger _moz-extension://87b72371-5f79-468a-b6ec-4baae3316131/confirm-page.html?_ page)

**Comment by falolaf** [comment] 2018-05-03 04:31
@v00p In what way do you change the contrainer.json file? You are not changing any userContextIds? Just rearranging whole entries like:
{"userContextId":37,"public":true,"icon":"briefcase","color":"blue","name":"<a name>"},

I'm curious what could be the difference in our setups.

**Comment by msdobrescu** [comment] 2019-07-08 06:38
This is a long awaited feature by me. Regular users might understand the containers, but might not start learning json to sort it manually. Please add such feature in the UI.

**Comment by kendallcorner** [comment] 2019-12-05 21:57
Hi. This looks like a duplicate of #330. Please vote (:+1:) or discuss on that issue to show your interest. I'll close this, but feel free to reopen if you think it's a different issue.

**Closed by kendallcorner** 2019-12-05 21:57 UTC
