### ISSUE TITLE
Address bar icon doesn't respect theme settings

### ISSUE THREAD

**Issue by RoccoDev** [mozilla/multi-account-containers#2339] opened 2022-04-24 18:55 UTC
- Multi-Account Containers Version: 8.0.7
- Operating System + Version: GNU/Linux 5.16.19-201.fsync.fc35.x86_64 (Fedora)
- Firefox Version: 99.0
- Other installed Add-ons + Version + Enabled/Disabled-Status:
```
Add-ons Search Detection	extension	2.0.0	true	addons-search-detection@mozilla.com
Facebook Container	extension	2.3.2	true	@contain-facebook
Firefox Color	extension	2.1.7	true	FirefoxColor@mozilla.com
Firefox Multi-Account Containers	extension	8.0.7	true	@testpilot-containers
Google	extension	1.2	true	google@search.mozilla.org
Translate Web Pages extension	9.4.2	true	{036a55b4-5e72-4d05-a06c-cba2dfcc134a}
uBlock Origin	extension	1.42.4	true	<email redacted>
```

### Actual behavior
![immagine](https://user-images.githubusercontent.com/13873938/164991716-bd8b97a3-c35b-4ee1-ae9f-7c4438f661d8.png)
(The translate icon is from [another extension](https://addons.mozilla.org/en-US/firefox/addon/traduzir-paginas-web/))

The "Always open this in a container" icon is white.

### Expected behavior
The "Always open this in a container" icon uses the theme's color.

### Steps to reproduce
1. Use the extension
2. Switch to a different theme (I'm using [this theme](https://color.firefox.com/?theme=XQAAAAIxAQAAAAAAAABBqYhm849SCia2CaaEGccwS-xNKlhQL4XYVPWQD0o18i14GBq2yGoswcQpU0pDpo5CHhTWe8KPh7aVdcfcAicK-V96QOzWMpW4cGgaNCrl8f3eNenSi1dmsnl4zeKiG9UkWjqJHv9C1UUYx5wk5dhLVs1BQB7IYlAQQyLGuZGxY92LKwb23HyDMELvvPFctuJOM7aPkFwryBvNBbSWoT7oAlprsaMZKxRTNPL79oM3mbonquq_UduhMK5C8ycROa00UJHmGAcpvUiZSK3RAz2UaoxRq_8DKAoA) from Firefox Color)

**Comment by dannycolin** [comment] 2022-06-09 00:54
See #1797.

**Comment by dannycolin** [comment] 2023-01-01 00:25
Duplicate of #1797

**Closed by dannycolin** 2023-01-01 00:25 UTC
Labels: bug, Needs: Mozilla Central
