### ISSUE TITLE
Feature Request: Add ability to open urls and their query parameters in specific containers

### ISSUE THREAD

**Issue by thisisshi** [mozilla/multi-account-containers#959] opened 2017-11-14 00:38 UTC
Example:
www.example.com/login?account-type=development would open in "Development" container
www.example.com/login?account-type=qa would open in "QA" container

Currently opening www.example.com for either of the urls will open in the same container.

**Comment by jtzero** [comment] 2017-11-16 23:13
would this be related? https://github.com/mozilla/multi-account-containers/issues/426

**Comment by jtzero** [comment] 2017-11-16 23:14
I think this is related https://github.com/mozilla/multi-account-containers/issues/426

**Comment by groovecoder** [comment] 2018-01-09 18:57
Dupe of https://github.com/mozilla/multi-account-containers/issues/691

**Closed by groovecoder** 2018-01-09 18:57 UTC
