### ISSUE TITLE
Enter key in edit-view, not saving

### ISSUE THREAD

**Issue by puggan** [mozilla/multi-account-containers#341] opened 2017-03-06 12:16 UTC
If I add a new container, or renaming a current one, pressing enter close that view, but dosn't save it, so have to redo it and with the mouse click the ok-button.

Reprodce:
1. open container menu
2. press "+"
3. Set a name
4. Press enter

Expected:
Adding the new container.

Current:
Closing the view, without adding it.

**Comment by Softvision-MariusComan** [comment] 2017-08-24 13:10
I still manage to reproduce the issue on Windows 10 x64, MacOS 10.12.6 and Ubuntu 14.04 x64 on latest Nightly (57.0a1 - 20170823100553 ). On Windows the issue is reproducible exactly as in the description, same on MacOS and Ubuntu, only difference is that the "Containers panel" is not closing after pressing the "Enter" key.

**Comment by Softvision-MariusComan** [comment] 2017-08-29 15:32
After more investigation, I have found that this is a Firefox issue, because I can't reproduce it on Firefox release. As such, I've have searched for a regresion window:

Last good revision: 392ed89ec2730a48d10b1cec741e86a242d28aa3
First bad revision: a625a2e9b3333a8e76982ea65f077cfded6ac224
Pushlog:
https://hg.mozilla.org/integration/mozilla-inbound/pushloghtml?fromchange=392ed89ec2730a48d10b1cec741e86a242d28aa3&tochange=a625a2e9b3333a8e76982ea65f077cfded6ac224

Also I've filed a bug related to this issue on Bugzilla: 
https://bugzilla.mozilla.org/show_bug.cgi?id=1394832

**Comment by kendallcorner** [comment] 2019-12-03 20:51
Hi. We're currently triaging the Multi Account Container issues. This appears to have been fixed, so I'm going to close it. If you don't feel the underlying issue has been resolved, feel free to reopen it with updated steps to reproduce.

**Closed by kendallcorner** 2019-12-03 20:51 UTC
Labels: bug
