### ISSUE TITLE
Export-Import container names and assigned sites

### ISSUE THREAD

**Issue by drmirk** [mozilla/multi-account-containers#1959] opened 2021-02-01 07:17 UTC
Right now syncing has some issue. So, an option to manually export/import with current configuration would really help us.

**Comment by Valtarien** [comment] 2021-02-23 15:01
I second this suggestion. Especially since I would like to erase all my containers and start over, then export my setup in case of future problems. I know I could delete them manually, but I have dozens, if not hundreds, of containers added by the "Temporary Containers" add-in. We need some way to export, import, & reinstall manually.

**Comment by o-l-a-v** [comment] 2021-03-23 08:41
Sync is so broken right now it would be better to have it disabled.

**Comment by Saimyx** [comment] 2021-03-25 18:02
I agree, I would also like to have this function. We don't necessarily use firefox sync

**Comment by maxxcrawford** [comment] 2021-08-03 15:39
Duplicate of #1427

**Closed by maxxcrawford** 2021-08-03 15:39 UTC
