### ISSUE TITLE
Broken extension after deleting a container

### ISSUE THREAD

**Issue by DamienCassou** [mozilla/multi-account-containers#827] opened 2017-09-18 13:05 UTC
1. Assign youtube.com to always open in 'youtube' container
2. Delete youtube container
3. Try to visit youtube.com

![screenshot from 2017-09-18 15-04-43](https://user-images.githubusercontent.com/217543/30543296-d0a77c80-9c82-11e7-81d0-1f8b43491956.png)
![screenshot from 2017-09-18 15-04-49](https://user-images.githubusercontent.com/217543/30543297-d0a7c7ee-9c82-11e7-8c11-8d35bce7a39c.png)

**Comment by DamienCassou** [comment] 2017-09-18 13:07
I don't know if that is meaningful, but I'm using Cookie Autodelete

**Comment by jonathanKingston** [comment] 2017-09-18 19:19
I think this is a duplicate of #803, will check as this might be the cause of it.

**Comment by jonathanKingston** [comment] 2017-09-19 22:21
I also think I fixed this case in 57 too from memory.

**Comment by DamienCassou** [comment] 2017-09-20 06:35
I'm using Test Pilot Containers 3.1.0 on top of Firefox Nightly.

**Comment by jonathanKingston** [comment] 2017-09-26 12:54
@DamienCassou if you haven't got the update for the 4.x branch you might need to manually update yourself.

https://github.com/mozilla/multi-account-containers/releases/latest

**Comment by DamienCassou** [comment] 2017-09-26 13:39
I've updated to 4.0.2, but the behavior is still the same.

**Comment by jonathanKingston** [comment] 2017-09-26 16:26
That being said the current version only caters for new deletions. I think we should query prior to displaying this page to remove extensions from assignment also.

Thanks for checking, I'll get to work on this now.

**Closed** 2017-09-29 16:06 UTC
Labels: assignment, bug, has PR, Priority: Medium
