### ISSUE TITLE
Suggestion: Cloud Based or Export utility

### ISSUE THREAD

**Issue by louddesignstudios** [mozilla/multi-account-containers#1628] opened 2020-02-03 06:18 UTC
Hello,

Can you make the addon connect to personal email account to sync Containers automatically across
Computers?

Or

At Least Add Import/Export Settings
Had to reconfigure it each time I install on a computer.

All The Best

**Comment by nnnnicholas** [comment] 2020-02-11 21:31
You're in luck. This is solved in a recent update rolling out now.
https://blog.mozilla.org/security/2020/02/06/multi-account-containers-sync/
https://github.com/mozilla/multi-account-containers/pull/1611

**Comment by kendallcorner** [comment] 2020-02-12 20:13
Duplicate of #339

**Closed by kendallcorner** 2020-02-12 20:13 UTC
