### ISSUE TITLE
Changing the order of containers

### ISSUE THREAD

**Issue by pervoj** [mozilla/multi-account-containers#1898] opened 2020-11-01 10:47 UTC
- Multi-Account Containers Version: 7.1.0
- Operating System + Version: Linux Mint 20 Ulyana, Kernel x86_64 Linux 5.4.0-47-generic
- Firefox Version: 82.0

Please, add possibility to change the order of containers. Tanks.

**Comment by groovecoder** [comment] 2020-11-11 20:20
Duplicate of https://github.com/mozilla/multi-account-containers/issues/330

**Closed by groovecoder** 2020-11-11 20:20 UTC
Labels: duplicate
