### ISSUE TITLE
[Feature Request] Add "Open current Tab/Link in New Container Tab" menu in Tab context menu.

### ISSUE THREAD

**Issue by i486** [mozilla/multi-account-containers#1124] opened 2018-02-18 22:36 UTC
Please look at this screenshot if you don't understand (my english is bad) the title. 
https://imgur.com/a/Goooa

**Comment by stoically** [comment] 2018-02-19 02:45
You might want to check out the [Context Plus Add-on](https://addons.mozilla.org/firefox/addon/context-plus/), it adds a tab context menu to reopen tabs in containers.

**Comment by badeas** [comment] 2018-02-19 17:23
@stoically 
Actually, everything can be done with add-ons, but native support will always be better and help to have a more trustworthy environment.
I'd rather prefer official implementations than relay onto third parties

**Comment by stoically** [comment] 2018-02-19 18:25
It's [encouraged](https://github.com/mozilla/multi-account-containers/issues/929#issuecomment-340777846) by the Multi-Account Containers maintainers to develop Add-ons to provide more container-functionality. If you personally don't want to use Add-ons that's perfectly fine - I just wanted to point you to something that already works. And actually, not everything can be done with WebExtension Add-ons anymore - it was another story with legacy Add-ons.

Also, there was an extended discussion about providing the possibility of [Moving between Containers](https://github.com/mozilla/multi-account-containers/wiki/Moving-between-containers) directly in MAC and the decision at the time was against it. Though it [seems that it might get considered](https://github.com/mozilla/multi-account-containers/pull/986#issuecomment-361309849) to get implemented.

**Comment by groovecoder** [comment] 2018-03-01 18:29
@stoically provides all the right links to the wiki pages and other issues & comments on this topic. Closing this as a dupe of those.

**Closed by groovecoder** 2018-03-01 18:29 UTC
Labels: duplicate, enhancement
