### ISSUE TITLE
Can't remove a site from list and sync this change to server

### ISSUE THREAD

**Issue by ameaninglessname** [mozilla/multi-account-containers#1841] opened 2020-08-01 06:28 UTC
- Multi-Account Containers Version:7.0.2
- Operating System + Version:windows 10 19041.388
- Firefox Version:79.0
- Other installed Add-ons + Version + Enabled/Disabled-Status:

I wanna update my site list of these containers(adding or deleting some sites).
### Actual behavior
sites not deleted. it's still there.

### Expected behavior
sites are correctly deleted and synced to all devices.

### Steps to reproduce
1.I delete some sites of a container on another computer
2.re-sync container(I reset Firefox Container extension by "Reset onbaording panels")
3.deleted sites come back...

**Comment by mrwensveen** [comment] 2020-09-04 21:33
I can confirm this. I want some sites to open in the default container again, so I removed them from the list of the container they were assigned to. A few minutes later, the sites were added to the container again.

**Comment by gfeun** [comment] 2020-10-12 15:39
I can also confirm. 

I had a website "example.com" assigned to "container1".
I then wanted to also open "example.com" in "container2" under another identity so i remove the domain assignment to "container1".
I can then open "example.com" under "container2" for a while.
But after some time, my "example.com" tab on "container2" is closed and reopened on "container1" and i can see that the "example.com" assignment to Container1 is back... 
So i have to remove it again, reopen "example.com" under "container2" etc

**Comment by xeruf** [comment] 2021-12-16 19:17
This is so damn annoying, and I didn't think that this would have been open for so long already...

Any workaround?

**Comment by dannycolin** [comment] 2023-01-06 03:42
Duplicate of #2110

**Comment by dannycolin** [comment] 2023-01-06 03:43
@Elaborendum Interesting finding and thanks for sharing.

**Closed by dannycolin** 2023-01-06 03:42 UTC
