### ISSUE TITLE
Sorting tab containers ignores order in containers.json

### ISSUE THREAD

**Issue by DrButthead** [mozilla/multi-account-containers#1510] opened 2019-10-03 08:55 UTC
- Multi-Account Containers Version: 6.1.0
- Operating System + Version: Windows 10 Pro 1903
- Firefox Version: 69.0.1 (64-bit)
- Other installed Add-ons + Version + Enabled/Disabled-Status: 
Dark Mode	0.3.4	true	
Firefox Multi-Account Containers	6.1.0	true	
GNOME Shell integration	10.1	true	
Honey	11.6.3	true	
I don't care about cookies	3.0.4	true	
Reddit Enhancement Suite	5.18.2	true	
Stylus	1.5.6	true	
Twitter	1.0	true	
uBlock Origin	1.22.4	true	
Wikipedia (en)	1.0	true	
Wikiwand: Wikipedia Modernized	5.0.2	true	
Cookie Manager	1.5	false	
Firefox Color	2.1.5	false	
Greasemonkey	4.9	false	

### Actual behavior
Pressing "Sort Tabs" in the extension causes all container tabs to sort based on the first-created order

### Expected behavior
They should sort based on the order set in containers.json

### Steps to reproduce
1. Create a few container tabs (at least 3)
2. Close Firefox
3. Go to containers.json, re-order the identities
4. Open Firefox
5. Open the container tabs menu and open an instance of each container
6. Re-order the tabs in the tab bar
7. Open the container tabs menu and click "Sort tabs"

### Notes
Related: #330

**Comment by axisfold** [comment] 2019-12-17 02:00
I can't figure it out. What is the actual order or key that "Sort Tabs" uses to sort the tabs?

**Comment by kendallcorner** [comment] 2019-12-17 15:11
Hi. Are you trying to sort the browser tabs or trying to change the order of the containers as displayed in the addon popup? (or is it some combination of both?)

**Comment by axisfold** [comment] 2019-12-17 15:25
> Hi. Are you trying to sort the browser tabs or trying to change the order of the containers as displayed in the addon popup? (or is it some combination of both?)

I'm literally clicking on the "Sort Tabs" button and trying to understand how the browser tabs themselves are sorted i.e. what ordering logic the extension uses to sort the tabs.

**Comment by kendallcorner** [comment] 2019-12-17 16:14
ah, I believe they are sorted in the order that the containers were created. The containers are named sequentially in Firefox, so it uses this order

**Comment by axisfold** [comment] 2019-12-18 01:23
Is it possible to amend the internal naming of these containers within Firefox, by say, editing a configuration file?

**Comment by kendallcorner** [comment] 2019-12-18 16:00
Unfortunately not right now. I think the only way you could do this would be to delete all your containers and remake them in the order that you would like.

**Comment by UnicodeTreason** [comment] 2021-03-17 02:00
Any progress on this issue?

**Comment by dannycolin** [comment] 2022-05-19 01:34
Duplicate of #938

**Closed by dannycolin** 2022-05-19 01:34 UTC
Labels: enhancement
