### ISSUE TITLE
If there's just one tab opened, the "Sort tabs" option moves the "new tab" button to the left

### ISSUE THREAD

**Issue by dunca** [mozilla/multi-account-containers#919] opened 2017-10-25 18:31 UTC
Hello.

If there's just one tab opened, the "Sort tabs" option moves the "new tab" button to the left

See the before and after image:
![pic](https://user-images.githubusercontent.com/11199802/32016108-b551c844-b9cb-11e7-8622-cef6c7e56402.png)

**Comment by SoftVision-EmilPasca** [comment] 2017-10-26 08:41
Hi @dunca, thanks for reporting this. However, this is a duplicate of https://github.com/mozilla/multi-account-containers/issues/813.

**Closed by SoftVision-EmilPasca** 2017-10-26 08:41 UTC
