### ISSUE TITLE
Container escape when using search engines

### ISSUE THREAD

**Issue by kolargol** [mozilla/multi-account-containers#1359] opened 2019-03-14 08:34 UTC
Hello everyone, 

Containers are great things but they have severe problem with search engines like google. 
When you container "google.com" and keep searches inside container all works as it suppose to - unless you click result link - link is opened in current container making container isolation uneffective... 

To workaround it I need to click on every link "Open in (...) no context" - which is something that even when trying hard to remember - I fail to do it. As a result even when using containers with Google - all my clicks and relates stuff is still tracked by Google as all results are opened in Google container.

Solution I see is to detect links out-of-container domain and by default open them without context OR add option to Multi-Account-Containers 

Thanks for listening.

**Comment by groovecoder** [comment] 2019-03-15 14:44
I'm closing this as a duplicate of https://github.com/mozilla/multi-account-containers/issues/847, which would effectively solve this issue by letting someone create a google.com-only Container. Please upvote https://github.com/mozilla/multi-account-containers/issues/847 if you like that approach to this problem, or re-open this issue if you think this is different.

**Closed by groovecoder** 2019-03-15 14:44 UTC
Labels: duplicate
