### ISSUE TITLE
multi account containers breaks sso auth

### ISSUE THREAD

**Issue by tr3buchet** [mozilla/multi-account-containers#1333] opened 2019-01-29 00:19 UTC
Let's say I open a company resource, that page then redirects to company SSO url, which redirects like 2-3 times before landing at the actual URL I opened. I am only able to add the final URL to a specific container by clicking the MAC icon, but I do not get a chance to add any of the intermediary auth URLs to the container.

This results in acceptable behavior when opening a URL from within the container, but if I click a link in another app, such as email, the intermediate steps end up being opened in the default container, while the final link opens in the container I have assigned it to, which obviously causes problems when it comes to cookies, and prevents authentication.

So my question is, how do I set something like  `*.auth.someworkurl.com` to always open in a specific container when I cannot visit the specific URL in question. If you have any familiarity with cookie auto delete, the exact thing I am looking for is the "list of expressions" that cookie auto delete has in settings. Here you can set cookie URL grey/white list rules for each multi account container.

Much the same, it is necessary to specify the rules for which URLs open in which container, but I cannot find anything like this in settings, even in about:config. If you click around through the MAC icon it seems like you can sortof see a list of URLs that map to the container, but it shows specific web pages like `https://this.that.com/dir/dir/something/page.html`. I want to add `*.that.com` to always open in the container vs not that specific page.

**Comment by tr3buchet** [comment] 2019-01-29 02:52
additional info found:
there is a json file `/Users/REDACTED/Library/Application Support/Firefox/Profiles/REDACTED.default/browser-extension-data/@testpilot-containers/storage.js`. This file has a ridiculous format, but with some coaxing you can get at the domains and their respective containers, and whether MAC will ask you to open the domain in its container or do so by default.

Sadly, if you edit this file to add your domains in, it will not matter. MAC ignores this file altogether, only dumping state to it at some unknown interval. Adding domains, even in the ridiculous format, has no effect whatsoever, and any added domains will disappear when MAC overwrites the file. I tried editing the file while firefox was closed. When I opened firefox, MAC acted as though I did not edit the file, and then shortly afterward overwrote the file.

When firefox opens, MAC has to be pulling its state somewhere, anyone know where?

**Comment by tr3buchet** [comment] 2019-01-29 02:58
I found [a random person's addon](https://addons.mozilla.org/en-US/firefox/addon/containerise/?src=search) called "containerise" that sortof does what I want, but lacks wildcards, is misspelled, and I'd much prefer to use an official mozilla extension given the security implication.

**Comment by lhorace** [comment] 2019-01-29 03:07
This odd, as I've actually transported that file and made changes to it 
in the past. As far as `Containerise` is concerned, many people use it, 
you could perhaps submit the limations to them to see if they would 
implement them?


As far as official support, AFAIK this is still a test pilot program, no 
official statement that Mozilla will take it on.

**Comment by tr3buchet** [comment] 2019-01-31 22:56
interesting. maybe it's weird on osx? I was hopefully editing that file would work, cause then I could write a quick cli interface for it and solve the problem in a jiffy.

**Comment by lhorace** [comment] 2019-01-31 23:19
Making edit's why Firefox is running is bad idea. I'm aware you mentioned that you closed Firefox, but since Firefox is multiprocess, perhaps there was a running process? AFAIK, that's the place where the containers reads it's configuration, unless there was a commit that change the location.

**Comment by tr3buchet** [comment] 2019-02-05 07:03
iirc, I command Q'd the whole thing down while i was editing the file.

**Comment by GonePh1shing** [comment] 2019-02-10 07:24
> 
> 
> I found [a random person's addon](https://addons.mozilla.org/en-US/firefox/addon/containerise/?src=search) called "containerise" that sortof does what I want, but lacks wildcards, is misspelled, and I'd much prefer to use an official mozilla extension given the security implication.

That extension has supported subdomain wildcards since 2.1.0.

If you do use it, just note that the current version (2.5.1) breaks the 'Temporary Containers' extension. The developer of temp containers has submitted a [pull request](https://github.com/kintesh/containerise/pull/49) that has been merged, so this should be fixed in the next release of Containerise.

Also, it's not misspelled. One would only use 'Containerize' in the US; everywhere else would spell it as written in the extension name.

**Comment by stoically** [comment] 2019-05-04 12:35
Duplicate of https://github.com/mozilla/multi-account-containers/issues/719 - please vote there. Thanks!

**Closed by stoically** 2019-05-04 12:35 UTC
