### ISSUE TITLE
Allow deletion of cookies and current logins for a container

### ISSUE THREAD

**Issue by happylynx** [mozilla/multi-account-containers#1742] opened 2020-05-17 22:36 UTC
Please implement part of "Clear Recent History" dialog functionality - allow deleting all cookies and active logins in selected container.

Current global "Clear Recent History" dialog:
![image](https://user-images.githubusercontent.com/8846779/82161733-72b66700-989f-11ea-87b8-c15ae98e5d53.png)

**Comment by Solid-Ice8** [comment] 2020-05-21 13:03
Have you tried Cookie AutoDelete? This add-on supports Container Tabs so, it should work with MAC.

I also know Temp Containers has this functionality (logins, cookies & cache clear out), but only for temp containers and not perm containers like MAC.

**Comment by happylynx** [comment] 2020-05-25 09:47
Thank you for the tip, [Temporary Containers](https://addons.mozilla.org/en-US/firefox/addon/temporary-containers/) is an amazing extension.

I installed both Cookie AutoDelete and Temporary Containers however AFAIK neither of them is able to do deletion in selected period of time (e.g. "Last Hour").

**Comment by Solid-Ice8** [comment] 2020-05-25 20:54
Yeah, that's true, there's no way for them to know the "duration of browsing". It's quite different from FireFox's standard cleaning.

I don't know if TC uses Web Extensions (it's not listed in their GitHub page), but I know MAC, Cookie AutoDelete and a handful of other add-ons use it.

Perhaps Web Extensions aren't able to detect it. AFAIK, Web Extensions can't even handle changing directories using relative path. I learned this from using a different add-on. I thought to myself, "Wow, even the most simplest thing can't be done?" You'd be surprised.

In case you weren't aware: To clear active logins, go to Settings & tick "LocalStorage CleanUp".


Personally, I just enable auto-clean with it's default 15 second delay of the actual clean. I guess you can also use the official add-on page to see if there's any other add-ons that might actually do it.

**Comment by dannycolin** [comment] 2023-01-02 00:20
Duplicate of #303

**Closed by dannycolin** 2023-01-02 00:20 UTC
