### ISSUE TITLE
Translation for Traditional Chinese(Taiwan)

### ISSUE THREAD

**Issue by toto6038** [mozilla/multi-account-containers#1842] opened 2020-08-03 07:46 UTC
Hello, thanks for such a great extension. I want to contribute to the translation for Traditional Chinese(Taiwan), is there any way to do this?

**Comment by Small-Ku** [comment] 2020-08-06 16:04
See #529

**Comment by groovecoder** [comment] 2020-08-12 19:12
Marking as dupe of #529.

**Closed by groovecoder** 2020-08-12 19:12 UTC
Labels: duplicate
