### ISSUE TITLE
Some problems

### ISSUE THREAD

**Issue by hightower5** [mozilla/multi-account-containers#1422] opened 2019-05-23 10:41 UTC
There are some problems and missing features:

- different number of icons in firefox setting and plugin setting
- in firefox setting is missing whitespace between icon and text
- need more icons e.g. email, multimedia, forum, filesharing, vpn
- open this site in assigned container doesn't work
- sort containers themself
- multi language support e.g. german

**Comment by lhorace** [comment] 2019-05-23 17:13
> open this site in assigned container doesn't work

What browser version and OS? I can't reproduce this here on Firefox 67.0 and Ubuntu 18.04?

> sort containers themself

See #1377 and #1347 

> multi language support e.g. german

You can help by translating and submitting a PR for review.

> need more icons e.g. email, multimedia, forum, filesharing, vpn

You have my thumbs up for this, this would really help in organize containers.

> different number of icons in firefox setting and plugin setting
in firefox setting is missing whitespace between icon and text

Please show examples, e.g. screen shots?

**Comment by lhorace** [comment] 2019-05-23 17:31
> open this site in assigned container doesn't work

> What browser version and OS? I can't reproduce this here on Firefox 67.0 and Ubuntu 18.04?

I somewhat was able to reproduce this, once the site is assigned to a container and you open link in a new tab. Clicking `Open in **Example** container` appear to do nothing. Clicking `Always remember my choice` on and off and clicking `Open in **Example** container` multiple times did it finally succeed.

**Comment by Hultan** [comment] 2019-05-24 10:36
Talking about icons, I would like to add that a setting for the main icon would be awesome. The current icon does not match my current theme at all. See the image below, the upper part is the default look, and it is barely visible. The lower part is when I have the mouse over the icon, and then it is visible. I would love if I could choose another icon that fits my current theme better.

![multi-account](https://user-images.githubusercontent.com/24316220/58322004-fb7efc00-7e1f-11e9-885e-e154c91f44a4.png)

**Comment by hightower5** [comment] 2019-05-24 12:28
> 
> 
> > open this site in assigned container doesn't work
> 
> > What browser version and OS? I can't reproduce this here on Firefox 67.0 and Ubuntu 18.04?
> 
> I somewhat was able to reproduce this, once the site is assigned to a container and you open link in a new tab. Clicking `Open in **Example** container` appear to do nothing. Clicking `Always remember my choice` on and off and clicking `Open in **Example** container` multiple times did it finally succeed.

Hi,
I don't know why I had yesterday some problems. Today it works sometimes.

Yesterday I checked the option "Always open in **Banking**".  Closed tab. And entered the url in the address field. After this I got a new window with the question: Open this site in your assigned container?
-> Open in this Current Container? or Open in this Banking Container?
-> I have tried Open in this Banking Container? But nothing happened.
Today I need sometimes 2 or more clicks. If I select the option "Remember my decision for this site", then it works very well.

my sysytem: Windows 10 Pro Build 1809 x64, Mozilla Firefox Quantum 67.00 x64

**Comment by hightower5** [comment] 2019-05-24 12:49
> > multi language support e.g. german
> 
> You can help by translating and submitting a PR for review.

What means PR for review? Are there some strings to translate, link?
> > need more icons e.g. email, multimedia, forum, filesharing, vpn
> 
> You have my thumbs up for this, this would really help in organize containers.
> 
> > different number of icons in firefox setting and plugin setting
> > in firefox setting is missing whitespace between icon and text
> 
> Please show examples, e.g. screen shots?
Missing whitespace:
https://abload.de/img/container-tabs4zjwb.png

Different number of icons:
https://abload.de/img/settingsm1kii.png
https://abload.de/img/plugin4lj4m.png

**Comment by lhorace** [comment] 2019-05-24 15:49
> What means PR for review? Are there some strings to translate, link?

PR stands for Pull Request, see the Tabs above. I am not sure if the developers have any documentation for translating. I would presume one would need to dig into the code or you could wait for developers response and contribute; which may take some time as they are currently busy with other stuff atm.

For future reference, you can drag and drop images into the text box. This makes it easier to review the images.

> Missing whitespace:

![container-tabs4zjwb](https://user-images.githubusercontent.com/12678456/58339707-2ebd8d00-7e18-11e9-8cf4-b5b9c38fa34e.png)

> Different number of icons:

![settingsm1kii](https://user-images.githubusercontent.com/12678456/58339957-b3101000-7e18-11e9-8b7d-a9e51898e3b6.png)
![plugin4lj4m](https://user-images.githubusercontent.com/12678456/58339966-b60b0080-7e18-11e9-95df-1e7e93038e96.png)

**Comment by lhorace** [comment] 2019-05-24 16:22
@Hultan You might want to combine your report with this issue #1424 ?

**Comment by Hultan** [comment] 2019-05-24 16:28
Thank you @lhorace, glad to see that this issue is already opened. I thought I could be lazy and add another icon issue with your issue, but I realize now that you were talking about other icons. Sorry :-)

**Comment by lhorace** [comment] 2019-05-24 16:33
Actually, it was open hour ago, heheh

**Comment by hightower5** [comment] 2019-05-31 21:07
Please [Support different Languages](https://github.com/mozilla/multi-account-containers/issues/529). 
And Vote for an internationalized extension.

**Comment by ciato** [comment] 2019-06-14 07:06
> Hi,
> I don't know why I had yesterday some problems. Today it works sometimes.
> 
> Yesterday I checked the option "Always open in **Banking**". Closed tab. And entered the url in the address field. After this I got a new window with the question: Open this site in your assigned container?
> -> Open in this Current Container? or Open in this Banking Container?
> -> I have tried Open in this Banking Container? But nothing happened.
> Today I need sometimes 2 or more clicks. If I select the option "Remember my decision for this site", then it works very well.
> 
> my sysytem: Windows 10 Pro Build 1809 x64, Mozilla Firefox Quantum 67.00 x64

It seems like the clickable part is only on the left side of the button text. If you click there, the button works fine.

**Comment by hightower5** [comment] 2019-07-03 11:17
You are right. The highlighted text isn't clickable in the middle of the button text.

**Comment by kendallcorner** [comment] 2019-12-08 04:34
Thanks for the input. I'm going to close this, because the items you've submitted have all either already been submitted (in which case, please vote (:+1:) or discuss on that issue to show your interest), or have been fixed.

> * different number of icons in firefox setting and plugin setting
> * in firefox setting is missing whitespace between icon and text

These were fixed if I'm understanding them correctly.

> * need more icons e.g. email, multimedia, forum, filesharing, vpn

This has already been submitted #1185 

> * open this site in assigned container doesn't work

This should also have been fixed, but let me know if it's not.

> * sort containers themself

This has already been submitted #330 

> * multi language support e.g. german

This has already been submitted: #529

**Closed by kendallcorner** 2019-12-08 04:34 UTC
