### ISSUE TITLE
Customise menu breaks new tab menu

### ISSUE THREAD

**Issue by jonathanKingston** [mozilla/multi-account-containers#197] opened 2017-02-16 22:01 UTC
STR
1. Open customise menu
2. Open select for themes and hover over some themes
3. Press the "Restore Defaults" button
4. Hover over the new tab button

![selection_498](https://cloud.githubusercontent.com/assets/338988/23043198/744e084c-f493-11e6-85f5-634c11ae9551.png)

**Comment by bakulf** [comment] 2017-02-17 09:19
I don't think my patch is related to this. I confuse this with another issue.

**Comment by kjozwiak** [comment] 2017-02-17 19:57
I could only reproduce this on Ubuntu. It doesn't seem to be affecting macOS/Windows.

> Example: https://youtu.be/hmurQ4BtJas

As per per our conversation in the weekly container meeting, I've added more detailed STR:

* click on the "Hamburger Menu -> Customize"
* Click on "Themes" and go through several of the previews
* While you're previewing a theme, select "Restore Defaults"
* Once the defaults have been restored, click on "Exit Customization"
* hover over the new tab "+" button

You might have to repeat this process twice to finally reproduce the issue. See the video that I've added above for an example.

**Comment by kjozwiak** [comment] 2017-03-30 19:55
@jonathanKingston, can you see if you can still reproduce this? I tried reproducing the issue under `fx52, fx53, fx54 and fx55` using `Ubuntu 16.04.2 LTS x64` but couldn't reproduce it anymore.

If you're not seeing this either, we can just close this off.

**Comment by groovecoder** [comment] 2017-12-05 16:53
Hasn't been reproduced since March.

**Closed by groovecoder** 2017-12-05 16:53 UTC
Labels: bug
