### ISSUE TITLE
Strict mode to isolate everything (Always open unassigned pages in the default container)

### ISSUE THREAD

**Issue by mothlyme** [mozilla/multi-account-containers#1318] opened 2018-12-14 16:09 UTC
For example I have a Google Container and in the search I would open something that is not yet in a container. This site also gets opened in the google container. 
Is it possible to implement a setting where you can choose a strict mode where it changes to the default container when a website is not yet in another container?

**Comment by lhorace** [comment] 2018-12-20 22:50
I'm not sure I should open a new issue, but I'd like to extend this issue by suggesting, always open new tabs in a default container? IE, when launching `firefox` or when clicking on the `+` symbol.

**Comment by kevgk** [comment] 2018-12-21 21:00
I'm looking for that functionality aswell.
Maybe give us an option like "open external links in temporary container".

**Comment by Llaves** [comment] 2018-12-25 15:40
Another vote in favor of this request

**Comment by RealDrGordonFreeman** [comment] 2019-01-31 14:18
Opened a similar request. A clear demand for this feature!

https://github.com/mozilla/multi-account-containers/issues/1334

**Comment by GonePh1shing** [comment] 2019-02-09 09:11
This functionality is already available in the [Temporary Containers](https://github.com/stoically/temporary-containers) extension. However from a usability and security/privacy standpoint this should really be the default behaviour.

**Comment by RealDrGordonFreeman** [comment] 2019-02-28 18:39
@groovecoder Similar request here.

**Comment by ZerofeniX** [comment] 2019-03-04 23:19
It would be nice if this were an option on a per container basis. Similar to the prior request. I mainly use containers to segregate site that I use that are notorious for tracking me but sites like google I would still like to use. However whenever I use google I'd prefer if the new tabs I start from searching would open in my default container and not the google container.

But this might not be true for all container usages.

**Comment by oryband** [comment] 2019-04-28 10:21
> This functionality is already available in the [Temporary Containers](https://github.com/stoically/temporary-containers) extension. However from a usability and security/privacy standpoint this should really be the default behaviour.

It is very confusing to set this up in in that add-on. I haven't succeeded in doing so up till now. I agree this should be the default behavior.

**Comment by stoically** [comment] 2019-05-04 12:06
Duplicate of https://github.com/mozilla/multi-account-containers/issues/847 - please vote there. Thanks!

**Closed by stoically** 2019-05-04 12:06 UTC

**Comment by floriensk** [comment] 2020-05-12 18:47
_I think this issue describes the case better than #847, since we're not talking about restricting to a single domain but to all assigned domains._

This should get much more attention though, the purpose of the containers is to prevent for instance Google from tracking on other sites, but we open a great portion of the other sites from a Google search.
The best would be to be able to set for **each specific container** if it is a „_strict_” container, only allowing sites to open in it which were specifically assigned to it.
