### ISSUE TITLE
Alternating attempts to open extension are hidden

### ISSUE THREAD

**Issue by nthomas20** [mozilla/multi-account-containers#1821] opened 2020-07-17 19:41 UTC
- Multi-Account Containers Version: 7.0.2
- Operating System + Version: Kubuntu 20.04
- Firefox Version: 78.0.2 (64-bit)
- Other installed Add-ons + Version + Enabled/Disabled-Status:
  * I'm also running Firefox in `strict` protection mode 

![Screenshot_20200717_143928](https://user-images.githubusercontent.com/15067067/87824737-703ea200-c83b-11ea-9312-58db58ee51fb.png)

### Actual behavior
Every alternating attempt to try to open the extension either via a direct click or ctrl + . yields an unopened container. I must close it and try again to be successful.

### Expected behavior
To successfully open and interact with the extension every time.

### Steps to reproduce
1. Click to open (it's hidden), click to close, click to open (it's open)
2. `ctrl.` to open (it's hidden), `esc` to close it, `ctrl.` to open (it's open)

### Screenshot of open "hidden" state
![87671152-76972600-c736-11ea-8fd3-2cbc509cf8a1](https://user-images.githubusercontent.com/15067067/87824341-b5ae9f80-c83a-11ea-8e78-3f607c14f539.png)

**Comment by MisterDoobDoob** [comment] 2020-07-18 15:35
Seconded, I have this issue too. Pasting data from about:support, 
OS + Version: Windows 10, 1909, 18363.959
  "application": {
    "name": "Firefox",
    "osVersion": "Windows_NT 10.0",
    "version": "78.0.2",
    "buildID": "20200708170202",
    "distributionID": "",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:78.0) Gecko/20100101 Firefox/78.0",
    "safeMode": false,
    "updateChannel": "release",
    "supportURL": "https://support.mozilla.org/1/firefox/78.0.2/WINNT/en-US/",
    "numTotalWindows": 11,
    "numRemoteWindows": 11,
    "launcherProcessState": 0,
    "remoteAutoStart": true,
    "autoStartStatus": 1,
    "policiesStatus": 0,
    "keyLocationServiceGoogleFound": true,
    "keySafebrowsingGoogleFound": true,
    "keyMozillaFound": true
  },
 "extensions": [
    {
      "name": "Decentraleyes",
      "version": "2.0.14",
      "isActive": true,
      "id": "jid1-BoFifL9Vbdl2zQ@jetpack"
    },
    {
      "name": "DuckDuckGo",
      "version": "1.0",
      "isActive": true,
      "id": "ddg@search.mozilla.org"
    },
    {
      "name": "Firefox Multi-Account Containers",
      "version": "7.0.2",
      "isActive": true,
      "id": "@testpilot-containers"
    },
    {
      "name": "Google",
      "version": "1.0",
      "isActive": true,
      "id": "google@search.mozilla.org"
    },
    {
      "name": "HTTPS Everywhere",
      "version": "2020.5.20",
      "isActive": true,
      "id": "https-everywhere@eff.org"
    },
    {
      "name": "uBlock Origin",
      "version": "1.28.2",
      "isActive": true,
      "id": "uBlock0@raymondhill.net"
    },

No experimental features!
It's the same actual/expected behavior, as well as steps to reproduce
**Screenshots**
"Hidden" But open:
![image](https://user-images.githubusercontent.com/54680156/87856086-1cbd7880-c94f-11ea-9ef2-2528d3cc51c5.png)
Open!
![image](https://user-images.githubusercontent.com/54680156/87856093-29da6780-c94f-11ea-94af-6edc6c86b186.png)

**Comment by dannycolin** [comment] 2023-01-07 01:29
Closing since this is an issue with Firefox itself and should have been resolved in recent versions. If you still encounter this issue, please file a bug report on bugzilla.mozilla.org.

**Closed by dannycolin** 2023-01-07 01:29 UTC
