### ISSUE TITLE
Feature Request: easily add lists of sites handled by specific containers

### ISSUE THREAD

**Issue by Hermholtz** [mozilla/multi-account-containers#2271] opened 2022-01-19 15:40 UTC
I would like to be able to add/edit sites easily by entering them into a list. Right now trying to set up a container for Google, I'd like to add https://docs.google.com, ideally *.google.com to be opened in this container. Now it's very painful, sites need to be added one by one, and the login redirections don't make that easy (I've managed to get accounts.google.com already in the container, but docs.google.com is in the default container...)

**Comment by achernyakevich-sc** [comment] 2022-01-19 16:26
Probably https://addons.mozilla.org/en-US/firefox/addon/containerise/ could help you.

**Comment by Hermholtz** [comment] 2022-01-19 16:38
It seems so, it has globbing and editing. It would be awesome to incorporate that code into this official addin.

**Comment by wolfferine** [comment] 2022-01-29 10:50
@achernyakevich-sc 
Thanks for sharing that addon to multi-account-containers, at 1st glance looks to be a good alternative while we waiting that this feature will be added

**Comment by alex-devg** [comment] 2022-02-01 16:16
> Probably https://addons.mozilla.org/en-US/firefox/addon/containerise/ could help you.

Thanks for that, solved my problem with google maps, as maps.google.ab is just redirecting and I could never assigned it to my google container therefore prompting a cookies management page before loading maps

**Comment by dannycolin** [comment] 2022-06-10 00:34
Closing as duplicate of #839. We also have a PR #2352 for wildcard domains (e.g. *.google.com)

**Closed by dannycolin** 2022-06-10 00:34 UTC
Labels: Feature request
