### ISSUE TITLE
Reopen in container - No container doesn't work

### ISSUE THREAD

**Issue by Kjwon15** [mozilla/multi-account-containers#1467] opened 2019-07-22 08:42 UTC
- Multi-Account Containers Version:6.1.0
- Operating System + Version: Ubuntu 19.04
- Firefox Version: 68.0
- Other installed Add-ons + Version + Enabled/Disabled-Status:

<details><summary>Click here</summary>
<pre>
Amazon.com	1.1	true	amazondotcom@search.mozilla.org
Bing	1.0	true	bing@search.mozilla.org
DuckDuckGo	1.0	true	ddg@search.mozilla.org
eBay	1.0	true	ebay@search.mozilla.org
Enhancer for YouTube™	2.0.93	true	enhancerforyoutube@maximerf.addons.mozilla.org
Firefox Color	2.1.2	true	FirefoxColor@mozilla.com
Firefox Multi-Account Containers	6.1.0	true	@testpilot-containers
Google	1.0	true	google@search.mozilla.org
h264ify	1.0.9	true	jid1-TSgSxBhncsPBWQ@jetpack
History Cleaner	1.2.3	true	{a138007c-5ff6-4d10-83d9-0afaf0efbe5e}
hotfix-update-xpi-intermediate	1.0.6	true	hotfix-update-xpi-intermediate@mozilla.com
HTTPS Everywhere	2019.6.27	true	https-everywhere-eff@eff.org
KeePassXC-Browser	1.4.6	true	keepassxc-browser@keepassxc.org
Mastodon – Simplified Federation!	1.2	true	mastodon-auto-remote-follow@rugk.github.io
Media Keys	2.2.6	true	jid1-4GP7z3tkUd3Tzg@jetpack
MetaMask	6.7.3	true	webextension@metamask.io
NoScript	11.0	true	{73a6fe31-595d-460b-a920-fcc0f8843232}
Privacy Badger	2019.7.1.1	true	jid1-MnnxcxisBPnSXQ@jetpack
Shinigami Eyes	1.0.19	true	shinigamieyes@shinigamieyes
Stylus	1.5.4	true	{7a7a4a92-a2a0-41d1-9fd7-1e92480d612d}
Tampermonkey	4.9.5941	true	firefox@tampermonkey.net
Tree Style Tab	3.1.5	true	treestyletab@piro.sakura.ne.jp
Tridactyl: No New Tab	1.16.2pre3025	true	tridactyl.vim.betas.nonewtab@cmcaine.co.uk
Twitter	1.0	true	twitter@search.mozilla.org
uBlock Origin	1.20.2	true	uBlock0@raymondhill.net
Wappalyzer	5.8.3	true	wappalyzer@crunchlabz.com
Wikipedia (en)	1.0	true	wikipedia@search.mozilla.org
Collapsed Mastodon	0.8.3	false	{9cd61e5a-4ddb-496c-af15-0938d2767f28}
GNOME Shell integration	10.1	false	chrome-gnome-shell@gnome.org
Greasemonkey	4.9	false	{e4a8a97b-f2ed-450b-b12d-ee082ba24781}
KeePass Tusk - Password Access and Autofill	2018.11.28	false	brandon@subdavis.com
Laboratory	3.0.5	false	1b2383b324c8520974ee097e46301d5ca4e076de387c02886f1c6b1503671586@pokeinthe.io
React Developer Tools	3.6.0	false	@react-devtools
Stylish - Custom themes for any website	3.1.8	false	{46551EC9-40F0-4e47-8E18-8E5CF550CFB8}
Tridactyl: Beta	1.16.2pre3025	false	tridactyl.vim.betas@cmcaine.co.uk
User-Agent Switcher	0.2.6	false	{75afe46a-7a50-4c6b-b866-c43a1075b071}
Video DownloadHelper	7.3.7	false	{b9db16a4-6edc-47ec-a1f4-b86292ed211d}
Vim Vixen	0.23	false	vim-vixen@i-beam.org
<pre>
</details>

### Actual behavior
 
It opens a new tab without container, But it closes immedietly and opens "new tab" page with original container

### Expected behavior

It navigates to same address with no container

### Steps to reproduce
1. Open some tab in a container
2. Right click onto that tab and select "Reopen in container" - "No container"
3.

### Notes

Reopen in some other container works fine. It only happened when select "No container"

**Comment by TriMoon** [comment] 2019-07-30 13:39
I am using Kubuntu 19.04, which is based on your Ubuntu version and using FF-Nightly.
I don't experience the behavior of the "new tab" page.

That said: Check if the tab you are trying to open this way is **not set to "always open in"**...

**Comment by Kjwon15** [comment] 2019-08-05 04:31
Tree Style Tab was the problem. I disabled it and works fine.

**Comment by grnassar** [comment] 2019-08-06 19:13
Can confirm issue.  Are we sure this is a TST issue and not an issue with this extension?  Does an issue need to be opened with TST?

**Comment by martinthomson** [comment] 2019-09-27 00:32
I'm not seeing the option to reopen in no container, though I would like the capability.

**Comment by dveditz** [comment] 2019-10-17 18:53
@martinthomson do you see the "Reopen in Container" menu when you right click on a tab in the tab strip? If you're in the default "no container" the sub-menu should have a list of your containers. If the tab is already in a container then at the top a "no container" option should be present.

I'm here because it's not working for me, though it's a much more recent problem than suggested by the age of this issue (I commonly open gdocs links in bugs, and need them in my default container rather than the bugzilla container to be logged in). I will check out the suggestion that it's a bad interaction with Tree-Style Tabs, which I also use. I've used that for a while, too, though. Maybe the recent containers update to 6.1.1 changed the load order?

**Comment by dveditz** [comment] 2019-10-17 19:05
It's definitely interaction with TST: when I disabled TST "no container" option works fine

disabled/enabled TST -- still broken
removed/reinstalled TST -- still broken
disabled/enabled containers -- IT WORKS CORRECTLY AGAIN!

Not sure how I got in the broken state given the above since MAC updated more recently than TST.

**Comment by kendallcorner** [comment] 2019-12-05 15:20
Hi. We're currently triaging the Multi Account Container issues. This appears to have been fixed, so I'm going to close it. If you don't feel the underlying issue has been resolved, feel free to reopen it with updated steps to reproduce.

**Comment by martinthomson** [comment] 2019-12-05 23:26
@kendallcorner it's not so much that this doesn't work, it's that the option just doesn't *exist*:

![image](https://user-images.githubusercontent.com/67641/70282737-db8ab500-1812-11ea-8368-bd5582b83950.png)

That was from a fresh profile with no extensions.

**Comment by kendallcorner** [comment] 2019-12-06 04:43
Interesting. I don't have this problem. What version of Firefox is this? And you say no other extensions were installed?

**Comment by martinthomson** [comment] 2019-12-06 04:46
Nightly. I begin to wonder if this is just core functions though.

**Comment by kendallcorner** [comment] 2019-12-06 16:15
Can you confirm that the tab you are right clicking on is not in the default container? For me on nightly, the default container does not show reopen in no container, but any other container does.

![MACreopen](https://user-images.githubusercontent.com/3195251/70337679-33c0b780-1811-11ea-84d4-7e8e656a712c.png)

**Comment by martinthomson** [comment] 2019-12-09 00:25
Ahh, that's a problem with another extension.  I'll go sort it out with them.

**Closed** 2019-12-09 15:36 UTC
