### ISSUE TITLE
Restrict domains to containers ''manually''

### ISSUE THREAD

**Issue by iliadaili** [mozilla/multi-account-containers#2095] opened 2021-08-05 18:56 UTC
Couldn't we be able to restrict sites to certain containers ''manually''? By that I mean restricting sites by typing the domain, without the need to access them. This would be very useful for situations with sites that you want to restrict to a container that is limited to them, but that have a bunch of different domains (like something.example.com, somethingelse.example.com...). This happens a lot to me with some shopping sites, and it's incredibly annoying and tricky to restrict all of the different domains in the same container.

**Comment by Tim-Magee** [comment] 2021-08-05 21:10
Came here to make the same point and ask this same question.

I have a 'Google' container and would like to be able to check the 'only listed sites' box in the container settings, so non-Google sites don't bleed in to my Google container.

During login, however, a redirection occurs to a Google-controlled site which is not in the container's list and which I guess is consequently unable to see enough cookies/whatnot, so the redirected page fails and the browser gets sent back to referer. A redirection loop ensues.  On the plus side, I got the "you have visited 100 sites in a container" cheevo in no time flat ;)

That needs to stop happening though.

I don't see "just uncheck the 'only listed sites'" as a solution to the problem. If I have to do that, what's the point in the checkbox's existing?

I've also read in other tickets that there are google/FB/Amazon/etc container add-ons, but I don't see adding all those as a solution, and in any case these are only the domains which most urgently need containing. _Several_ other websites exist, or so I'm told.

I've also seen that there's a container manager that allows wildcarding of container-domain assignments. I imagine I could do some real damage with that, especially on domains whose subdomains are controlled by different individuals (some ISPs for example). I don't think wildcarding is a good solution.

How about a training mode? I'd throw a 'record' switch and then when I stop recording I get a list of all the domains visited in this container since I started recording, which weren't already on the container's list, and the option to select the ones I want permanently added? Saves typing, but it's still a bit 'power user' because you need to be able to tell which domains are relevant.

Um, that's it. Good luck!

**Comment by lisphacker** [comment] 2021-08-10 12:18
Came here for the same issue. It would be nice if there was some place where I could manually add, say '*.google.com' and '*.google.co.uk' to a Google container. At the moment, if I open maps.google.com (added to the google container), it opens up consent.google.com (also added to the google container). Clicking on Agree opens up a new tab for consent.google.co.uk (which is not in the google container and I can't add it to the container since it does not stay onscreen very long), which fails and gets sent back to consent.google.com in the google container. This then loops forever, unless I temporarily use the "just uncheck the 'only listed sites'" workaround.

**Comment by Mortivor** [comment] 2021-08-31 12:02
Same here. I too would like a table listing alle sites and which container they a configured to open in. To have an overview. Currently have to open a site explicitly to see if I somewhen have configured it to open in a container.
This Table/List could then allow for addition, removal or change of the assigned container.

**Comment by coelmay** [comment] 2021-11-18 10:05
Another +1 to having a *wildcard* feature to say **Open *\*.example.com* in [container]**

**Comment by grahamperrin** [comment] 2021-11-28 14:53
This is almost certainly a duplicate (maybe a triplicate) of an earlier issue. @iliadaili please, can you seek a match and then move your comment? Thanks.

**Comment by gregghz** [comment] 2022-07-27 17:13
https://github.com/mozilla/multi-account-containers/issues/1803

https://github.com/mozilla/multi-account-containers/issues/1670

https://github.com/mozilla/multi-account-containers/issues/1619

https://github.com/mozilla/multi-account-containers/issues/1227

This is a relatively frequently requested feature. It would be really nice to be able to do this. For me, clicking zoom links in slack does a redirect starting in the wrong container so when the redirect finished I wouldn't be logged in to zoom anymore.

**Comment by kurahaupo** [comment] 2022-09-03 09:13
@gregghz see also #2114

**Comment by dannycolin** [comment] 2022-10-11 00:59
duplicate of #1670

**Closed by dannycolin** 2022-10-11 00:59 UTC
