### ISSUE TITLE
Feature request: include all tabs from all containers in the address bar tab search

### ISSUE THREAD

**Issue by giogt** [mozilla/multi-account-containers#2068] opened 2021-06-11 21:26 UTC
### Current behavior

When searching for tabs in the address bar (using %), the search result shows only the tabs belonging to the current container matching the search query. Tabs from other containers are filtered out from the search result.

### Proposed behavior

When searching for tabs in the address bar (using %), the search result shows all the tabs from all the containers that match the search query. Add the container name and icon for each result entry to make it easier to pick a result, especially when the same URL is open in different containers.
This can either be the new behavior, or it can be enabled via a configuration setting.

### Notes

I understand that this extension is meant to isolate the different containers. But the tab search is a functionality that is normally used to switch to any of the open tabs and it's particularly useful when you have a lot of tabs open, potentially in a lot of different containers.

Last but not least, I love this extension: it's one of the reason that brought me back to Firefox after trying other browsers for a while. Keep up the great work!

**Comment by dannycolin** [comment] 2022-07-12 18:23
duplicate of #1705

**Closed by dannycolin** 2022-07-12 18:23 UTC
