### ISSUE TITLE
PLEASE ADD THE 1 AND 2 SYNC OPTION,, I HAVE 20 COMPUTESR AND I WANT SYNC CAN ALSO SYNC THE CONTAINERS PRESETED OPTIONS

### ISSUE THREAD

**Issue by adrianpza** [mozilla/multi-account-containers#1332] opened 2019-01-27 22:30 UTC
- Is "Firefox will: Never remember history" in the Firefox Preferences/Options under "Privacy & Security > History" selected? Yes/No:
- Are you using Firefox in a Private Window? Yes/No:
- Can you see a grayed out but ticked Checkbox with the description "Enable Container Tabs" in the Firefox Preferences/Options under "Tabs"? Yes/No:
- Multi-Account Containers Version:
- Operating System + Version:
- Firefox Version:
- Other installed Add-ons + Version + Enabled/Disabled-Status:

### Actual behavior
..

### Expected behavior
..

### Steps to reproduce
1. ..
2. ..
3. ..

### Notes
..

**Comment by groovecoder** [comment] 2019-01-28 15:40
Duplicate of https://github.com/mozilla/multi-account-containers/issues/339

**Closed by groovecoder** 2019-01-28 15:40 UTC
Labels: duplicate
