### ISSUE TITLE
Allow user to set container for empty (new) tab

### ISSUE THREAD

**Issue by nekromoff** [mozilla/multi-account-containers#937] opened 2017-11-09 00:16 UTC
Currently it is impossible to set container context before website is loaded.

Allow user to set container context on opening a blank, new tab (and before loading a URL).

**Comment by tactidact** [comment] 2017-11-09 14:16
This works for me on FF56.0.2, all you have to do is hold click on the new tab button and a context menu appears that lets you select the container to launch the new tab in.

**Comment by nekromoff** [comment] 2017-11-09 14:21
Does not work for me. Context menu of course appears, but selection is not
uphold on entering URL and default no context container is used.

**Comment by Softvision-CristinaBadescu** [comment] 2017-11-09 14:48
@nekromoff, thanks for the report. However, this is a dupe of #311.

**Closed by Softvision-CristinaBadescu** 2017-11-09 14:48 UTC

**Comment by nekromoff** [comment] 2017-11-09 14:57
Possibly, but I am unable to dissect the too long discussion that focuses
on many different points and is not clear about the *new tab* context.
