### ISSUE TITLE
Add search field to search containers

### ISSUE THREAD

**Issue by kassemz** [mozilla/multi-account-containers#2321] opened 2022-03-30 16:25 UTC
Hi!

Can you please add a search field in the containers menu so user can search/filter containers by keyword? I have a lot of containers and finding the right container gets difficult with a lot of containers so a search field will be immensely helpful.

Thank you.

**Comment by maxiedaniels** [comment] 2022-04-04 20:19
This would be huge!

**Comment by dannycolin** [comment] 2022-07-13 01:21
Duplicate of #1103

**Closed by dannycolin** 2022-07-13 01:21 UTC
