### ISSUE TITLE
Make possible to assign a whole firefox window to a container

### ISSUE THREAD

**Issue by 3v1n0** [mozilla/multi-account-containers#1258] opened 2018-09-07 15:56 UTC
It would be really nice to make sure that each container could be associated to one or more windows, so that a single window is used only for a specified container by default or for the sites assigned to that container only.

**Comment by kendallcorner** [comment] 2019-12-06 21:09
Hi. This looks like a duplicate of #319. Please vote (:+1:) or discuss on that issue to show your interest. I'll close this, but feel free to request a reopen if you think it's a different issue.

**Closed by kendallcorner** 2019-12-06 21:09 UTC
