### ISSUE TITLE
[Question] How do you make a container the default for new tabs?

### ISSUE THREAD

**Issue by es50678** [mozilla/multi-account-containers#1860] opened 2020-09-08 22:59 UTC
- Multi-Account Containers Version: 7.0.2
- Operating System + Version: MacOS Catalina 10.15.6
- Firefox Version: 80.0.1 (64-bit)
- Other installed Add-ons + Version + Enabled/Disabled-Status:
  - 1Password extension [4.7.5.90]
  - Ad Block Plus [3.9.4]
  - React Developer Tools [4.8.2]

### Actual behavior
With the setting `Select a container for each new tab` turned on:
- `Command + t` opens up a new tab without a container set

Without the setting `Select a container for each new tab` turned on:
- `Command + t` opens up a new tab without a container set

### Expected behavior
Should be able to set one container as a `default` that `Command + t` opens up a new tab in

### Steps to reproduce
1. Use `Command + t` to open up a new tab
2. No container will be set

### Notes
Workaround:
- using the extension shortcuts set for a given profile to open up a new tab works(`Command + Shift + 1`)

Coming from chrome it would be nice if opening a new tab opened it a given default container. If there's already a way to do this please let me know. Definitely want to move over to FF but chromes "People" feature is very useful to me. This extension is the best replacement I've found for it(there's also https://support.mozilla.org/en-US/kb/profile-manager-create-remove-switch-firefox-profiles but I prefer this extension).

https://github.com/mozilla/multi-account-containers/issues/1678 seems to cover my other request to have containers by instances of isolated firefox windows.

Thank you so much for this amazing add-on!

**Comment by groovecoder** [comment] 2020-09-09 19:17
I believe this is a dupe of either https://github.com/mozilla/multi-account-containers/issues/319 or https://github.com/mozilla/multi-account-containers/issues/462 ?

**Closed by groovecoder** 2020-09-09 19:17 UTC
Labels: duplicate

**Comment by es50678** [comment] 2020-09-09 22:53
@groovecoder YES! sorry for not being able to find it before. definitely a duplicate of https://github.com/mozilla/multi-account-containers/issues/462

**Comment by moontails** [comment] 2021-03-03 14:44
@groovecoder is this on the roadmap? if its feasible, i volunteer to work on this! 

about me : decent dev experience, but not intricately familiar with front-end or any firefox architecture. 

following the thread in #319 and the linked issue there indicates this needs to be built in at platform level and needs core changes. are volunteer devs able to do this or is it not feasible ?
