### ISSUE TITLE
Show only tabs from the current container (part II)

### ISSUE THREAD

**Issue by maverick74** [mozilla/multi-account-containers#2459] opened 2022-11-29 15:29 UTC
### Before submitting a bug report

- [X] I updated to the latest version of Multi-Account Container and tested if I can reproduce the issue
- [X] I searched for existing reports to see if it hasn't already been reported

### Step to reproduce

Set multiple tabs to multiple containers.

### Actual behavior

All tabs from all containers are all shown at once, all mixed up!

### Expected behavior

The idea is to have an option in preferences that would allow one to see only the tabs from the current container so that one could get into the "shop" container (for example) and see only the tabs from that container (Instead of having them all mixed up). Upon switch to another container it would hide the "shop" tabs and show only the tabs of the selected container.

### Additional informations

This is a followup from #328 which was agreed to be closed in favor of #336 , which was then closed without addressing this issue. Since no reply from either concerning this (and since i can't reopen 328) i'm submitting this again.

**Comment by dannycolin** [comment] 2022-11-29 21:19
Duplicate of #1195

**Closed** 2022-11-29 21:20 UTC
Labels: bug

**Comment by maverick74** [comment] 2022-11-30 12:40
I sure wouldn't find 1195 with that name!!!

Thank you for pointing it out :)
