### ISSUE TITLE
It is possible to open Firefox with a selected container?

### ISSUE THREAD

**Issue by ema-pe** [mozilla/multi-account-containers#1301] opened 2018-10-25 11:43 UTC
Hi, I have a question: is it possible to open Firefox via command line (like `firefox https://github.com`) with a specified container, for example `Shopping` or `Work` instead of default one?

**Comment by groovecoder** [comment] 2018-10-26 17:03
I don't think this is possible. @jonathanKingston ?

**Comment by kendallcorner** [comment] 2019-12-05 15:51
Hi. This looks like a duplicate of #365. Please vote (:+1:) or discuss on those issues so they are more likely to be completed. I'll close this, but feel free to reopen if you think it's a different issue.

**Closed by kendallcorner** 2019-12-05 15:51 UTC
Labels: question
