### ISSUE TITLE
Feature request: temporary containers

### ISSUE THREAD

**Issue by gitthehubs** [mozilla/multi-account-containers#1973] opened 2021-02-24 13:23 UTC
I really like this multi-account container add-on, but it is alot of configuration if you want to seperate as many websites as you can. The solution is temporary containers, already in the add-on https://github.com/stoically/temporary-containers
But it seems this project is not maintained anymore. Could you implement a few features of temporary containers in multi-account containers? The General tab configurations would be appreciated, like the Automatic Mode and automatically delete containers when the last tab is closed. 😄 

Thanks!

**Comment by logos88** [comment] 2021-02-25 08:07
I'd also like Multi-Account Containers to have the option to create temporary containers for new pages. Temporary Containers in conjunction with Multi-Account Containers is the best way to deal with cookies and other tracking issues, but allowing persistent logins to websites you specify too.

Having both options in Multi-Account Containers would reduce our entropy improving defense against fingerprinting, and would give us direct support from Mozilla, since Temporary Containers may stop working and being supported one day.

**Comment by dngray** [comment] 2021-02-28 02:20
> But it seems this project is not maintained anymore. 

Not sure where you got that idea, but I have to admit support for this upstream would be *really neat*. Especially if it was possible to use it Android etc.

**Comment by gitthehubs** [comment] 2021-02-28 12:20
@dngray 
I haven't seen much activity on the project and lots of open issues and just a few fixes in new releases. Although the last updates was 8 february, before that was august 2020. So it looks like it is not actively maintained anymore. But I could be wrong of course.

I understand maintaining a project can consume alot of time and every free project is very appreciated, but an actively maintained add-on, and even from Mozilla itself, would ensure more continuity in this much needed and appreciate feature. A temporary container option is what MAC misses and really needs in my opinion and I really don't want to lose this feature in a not maintained add-on. That is why I made the feature request(with all respect to stoically from temporary containers).

**Comment by stoically** [comment] 2021-03-01 18:09
> So it looks like it is not actively maintained anymore.

I guess it depends on the definition of "maintenance". It's true that I'm not actively developing TC, which means that I'm not working on features or minor bugs - however, I do check issues and would try to fix breaking / critical bugs.

However, I'd very much appreciate a viable alternative to TC that is actively developed, in the best case something from Mozilla directly. I feel like that Total Cookie Protection introduced in Firefox 86 pushes in that direction by basically exposing FirstPartyIsolation as user-facing preference.

**Comment by dannycolin** [comment] 2022-08-01 14:45
Duplicate of #929

**Closed by dannycolin** 2022-08-01 14:45 UTC
