### ISSUE TITLE
Limit to Designated Websites button doesn't work on Linux

### ISSUE THREAD

**Issue by FlooferLand** [mozilla/multi-account-containers#2059] opened 2021-05-31 10:45 UTC
- Multi-Account Containers Version: 7.3.0
- Operating System + Version: Fedora 34
- Firefox Version: 88.0.1 (64-bit)

- Other installed Add-ons + Version + Enabled/Disabled-Status:
dGuard AdBlocker	extension	3.6.6	true	adguardadblocker@adguard.com
Amazon.co.uk	extension        1.4	true	amazon@search.mozilla.org
Amazon.com	extension	1.3	true	amazondotcom@search.mozilla.org
Bing	extension	1.3	true	bing@search.mozilla.org
Chambers (UK)	extension	1.0	true	chambers-en-GB@search.mozilla.org
Dark Reader	extension	4.9.33	true	addon@darkreader.org
DuckDuckGo	extension	1.1	true	ddg@search.mozilla.org
eBay	extension	1.3	true	ebay@search.mozilla.org
Firefox Multi-Account Containers	extension	7.3.0	true	@testpilot-containers
Google	extension	1.1	true	google@search.mozilla.org
MetaMask	extension	9.5.5	true	webextension@metamask.io
Privacy Badger	extension	2021.2.2	true	jid1-MnnxcxisBPnSXQ@jetpack
UnloadTabs	extension	0.8.5	true	@unload-tabs
Wikipedia (en)	extension	1.1	true	wikipedia@search.mozilla.org
Honey	extension	12.4.5	false	jid1-93CWPmRbVPjRQA@jetpack
(not sure why removed search engines are there but oh well)

### Actual behavior
The checkbox works until i go out of the "Manage this container" section using the < button in the top left corner, when going back into the "Manage this container" section the checkbox goes back to whatever it was before clicking it.

### Expected behavior
The checkbox being able to remember it's set state

### Steps to reproduce
1. Clicking the multi-account containers addon icon to configure it
2. Clicking the > on a container
3.  Clicking "Manage this container"
4. Clicking "Limit to Designated Sites" checkbox
5. Going back using the arrow in the top left
6. Clicking "Manage this container" again (checkbox wouldn't be to what you've set it to be)

### Notes
I'm using the Cinnamon desktop environment but i'm not sure if that's why the issue is happening or not.

**Comment by dannycolin** [comment] 2022-07-13 01:43
I can't reproduce on the latest version 8.0.7. Do you still experiment on it on the latest?

**Comment by dannycolin** [comment] 2023-01-09 00:24
Closing in favor of #2437

**Closed by dannycolin** 2023-01-09 00:24 UTC
