### ISSUE TITLE
Container becomes unusable

### ISSUE THREAD

**Issue by KORA-ch** [mozilla/multi-account-containers#2657] opened 2024-08-07 15:54 UTC
### Before submitting a bug report

- [X] I updated to the latest version of Multi-Account Container and tested if I can reproduce the issue
- [X] I searched for existing reports to see if it hasn't already been reported

### Step to reproduce

Hard to know, I just open the container normally and once per week/month it becomes unusable. Haven't managed to see a pattern or find a reason why it gets blocked.

### Actual behavior

The container is open, and it shows Show this container with the icon to hide the container. I cannot hide the container anymore, and the tabs get duplicated. It only happens to one container at a time (the other containers continue working normally)

![image](https://github.com/user-attachments/assets/e44f0e90-f4cd-4e31-a586-77beca9f403f)

Also, for example now I have 4 tabs open in the bugged container, but when I click on the arrow there are 30+ and it's constantly creating duplicates. I don't know how, but sometimes they all get opened at once. It's impossible to remove them afterwards
![image](https://github.com/user-attachments/assets/aafb30b8-f4dd-482b-91b6-5d3613adb397)

![image](https://github.com/user-attachments/assets/d31c0ec5-32d3-42d2-98c1-c9a5a0a0bd41)
(that's just a small percent of all the tabs open)

### Expected behavior

When a container is open, it should show hide this container.

![image](https://github.com/user-attachments/assets/5934bc5e-50db-468b-8bfd-85b99c97d002)

### Additional informations

The only fix I found is to remove and remake the container, which can be slightly bothersome since I have to relog in all my accounts and I have lost track of tabs because of this error.

**Comment by juanmatias** [comment] 2024-09-25 19:29
Hey, same here. 
I can add some sort of reproducibility.

It happens to me in my banking-related container.

When I do a transaction in my bank and open PDF with operation ticket, the container hangs.

As you can see here:
![Untitled](https://github.com/user-attachments/assets/e2635cc8-f5a5-4727-bb75-61532f440916)

I have the bank sites and other tabs related to opening PDFs.

Now the plugin always shows "Show This Container" and those tabs can not be removed from the container.

When this happens... I uninstall and install the plugin and all starts working ok... for a while.

Could you guide me to debug this so I can help with a solution?

Thanks!

**Comment by achernyakevich-sc** [comment] 2024-09-25 20:49
@juanmatias 

Could you next time provide the URL of the tab that on your screen is partially visible as `form1 - Tra`.

@dannycolin I have a hypothesi that it could be somehow related to opening PDF after downloading using `file:///` protocol. BTW: probably just released 8.2.0 has fixed this problem due to adding `file:` protocol to non-permissible protocol.

**Comment by juanmatias** [comment] 2024-09-26 13:01
Hey, @achernyakevich-sc , thanks for answering.

Shure, indeed it is a `file://` that's opening a PDF:
![Untitled](https://github.com/user-attachments/assets/a2d61d09-1997-43e7-9ff6-08c8865d2c0b)

Btw, right now I have the version:
```
Version
8.2.0
Last Updated
September 25, 2024
```

But the container was like this for more than a week (at least prev to 25th).... I will recreate the container and give it a try.

**Comment by juanmatias** [comment] 2024-09-26 13:49
@achernyakevich-sc It worked!

```
Version
8.2.0
Last Updated
September 25, 2024
```

Steps:
* I opened my bank site
* Requested a document (PDF)
* PDF downloaded and opened in the container (address `file://`)
* Closed the container
* Tab with `file://` was not saved in the container
* Opened the container
* It opened all the tabs except the `file` one (that was not saved)
* When click on containers icon, for this container it correctly show "Hide this container"

Thanks!!!

*Note:*
So for anyone coming here because the same problem, try Plugin version `>=8.2.0`.

**Comment by dannycolin** [comment] 2024-09-27 02:48
Glad that #2509 fixed your issue! Closing for now.

**Closed by dannycolin** 2024-09-27 02:48 UTC
Labels: bug, Component: Tab, Component: Performance
