### ISSUE TITLE
Always Open in this container does not work using Google Mail Inbox Bookmark 

### ISSUE THREAD

**Issue by caltheon** [mozilla/multi-account-containers#1320] opened 2018-12-19 22:57 UTC
### Actual behavior
When clicking on a link in the Bookmarks Toolbar for Gmail, Gmail does not open in the proper container that is set to Always Open in this Container.  The bookmark link in question is https://mail.google.com/mail/u/0/#inbox .  Changing the target of the bookmark to https://mail.google.com/mail results in Gmail opening up in the proper container.

### Expected behavior
Gmail should open in the proper container when Always Open in this Container is set regardless of the subfolders in the bookmark link

### Steps to reproduce
1. Create a new container called "Google"
2. Create a bookmark in the bookmarks toolbar for Google Mail (https://mail.google.com/mail/u/0/#inbox)
2. Navigate to Google Mail homepage (https://mail.google.com/mail/u/0/#inbox)
3. Add site to container "Google" and enable "Always Open in this Container"
4. Close Firefox
5. Open Firefox (to blank tab)
6. Click on the icon in the bookmarks toolbar for Google Mail created in step 2.
7. Google Mail loads, but is not in the "Google" container.
8. Modify Bookmark to have a target of https://mail.google.com/mail.
9. Click on the bookmark for Google Mail modified in previous step.
10. Google Mail loads in the correct container, "Google".

### Notes
Just Installed this extension, so MAP is brand new.  
Running Firefox Quantum 64.0 (64-bit)
Addons:
DS Sidekick
F.B. Purity
Firefox Multi-Account Containers
Ghostery - Privacy Ad Blocker
Greasemonkey
LastPass
Reddit-SIdebar-Hider
uBlock Origin
Reddit Enhancement Suite (disabled)

Plugins:
OpenH264 Video Codec provided by Cisco Systems, inc
Widevine Content Decryption Module provided by Google Inc.
Shockwave Flash (32.0 rc0)  (Ask to Activate)

**Comment by stoically** [comment] 2019-05-04 12:46
The underlying issue here is that gmail loads a serviceworker, so marking this as duplicate of https://github.com/mozilla/multi-account-containers/issues/822 - please track progress there, thanks.

**Closed by stoically** 2019-05-04 12:46 UTC
