### ISSUE TITLE
Multi-Account Containers - a Container for all Google Webpages does not Work with 'Limit to Designated Sites'

### ISSUE THREAD

**Issue by amirdagan** [mozilla/multi-account-containers#2156] opened 2021-10-13 19:55 UTC
[Bug 1733832](https://bugzilla.mozilla.org/show_bug.cgi?id=1733832)

User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:92.0) Gecko/20100101 Firefox/92.0

Firefox Multi-Account Containers version 7.4.0

Other extensions: Dark, Reader, uBlock Origin, Facebook Container, Open GNOME Shell

Steps to reproduce:
1. Use the Multi-Account Containers add-on with a Google container for all *.google.com and *.youtube.com websites.
2. Click the Multi-Account Containers add-on button > Manage Containers > Google > check the 'Limit to Designated Sites' checkbox.
3. Try to open a *.google.com webpage

Actual results:

First possibility:
The Google webpage (mail.google.com, calendar.google.com) is opened in no container and an error is shown:
"
400. That’s an error.
The server cannot process the request because it is malformed. It should not be retried. That’s all we know.
"

Second possibility:
youtube.com and play.google.com are loaded with no errors

Third possibility:
drive.google.com is stuck in a blinking deadlock - does not load but doe not show an error.

Expected results:

All *.google.com webpages should load successfully within the Google container.

**Comment by securingmom** [comment] 2021-10-16 11:22
This is the only active extension?

**Comment by amirdagan** [comment] 2021-10-17 10:57
Thanks @securingmom - updated the original description with all other extensions.

**Comment by macks2008** [comment] 2022-08-15 15:43
I'm not sure if it's related but I just got error 400 under similar circumstances. I'm only getting the error when I open certain URLs in my Google container, not if I open with no container. The affected URLs all involve "myaccount.google.com/accounts/SetOSID?", with arguments varying depending on what "recent activity" I'm trying to view. I believe both the Google account and the "default container" (that is, no container) are login to the Google account I was trying to manage, so I'm not really sure what could be causing this.

**Comment by dannycolin** [comment] 2022-12-02 00:01
Duplicate of #1882

**Closed by dannycolin** 2022-12-02 00:01 UTC
