### ISSUE TITLE
Feature Request: Ability to add/select additional icons - & introduce underline patterns

### ISSUE THREAD

**Issue by QuixoticJoe** [mozilla/multi-account-containers#1907] opened 2020-11-17 12:08 UTC
It would be great if **additional icons** could be included (& ideally added to). 
Making it possible to **show these icons in the tab** would be helpful.

To make it easy to associate icons with the coloured underlines, **line variation** (broken line / double line / triple line) could help - although we will undoubtedly only use it to find similar opened tabs

**Varying the tab background colours** could also help

It will be great to find a solution to the overload of tabs that we face in trying to research multiple projects with multiple components over longer periods of time

Account Containers is an excellent extension - thank you for building it

**Comment by ideophone** [comment] 2021-03-25 09:12
I agree: I'd appreciate having..:
- **more icons** available
- varying the tab background colors (or, just: **more colors** available)
(- _if more colors are not doable_: maybe some feature to **distinguish tabs not only by color but also by icon** -> some way to recognize what icon belongs to what color - e.g., **variation** of the style of the colored **line** on the tabs)

**Comment by grahamperrin** [comment] 2021-04-23 16:43
> icons

▶ 2017 issue #843, 2018 issue #1185

**Comment by dannycolin** [comment] 2022-05-21 00:23
duplicate of #2368

**Closed by dannycolin** 2022-05-21 00:23 UTC

**Comment by mathstuf** [comment] 2022-05-21 13:43
Why would you close the *older* one with more discussion? Now anyone interested (likely far more than on that issue) need to re subscribe over there (because GitHub still sucks at handling duplicates). Please consider making this one the one (or any of the other older ones, really) that stays open.

**Comment by dannycolin** [comment] 2022-05-21 17:03
@mathstuf I'm used to bugzilla auto-subscribing you when an issue is closed as duplicate. 

Anyway folks still get notified so it's easy to subscribe to the other bug. Also discussions aren't really revelant in this case since it's something that should be fixed upstream and this issue is only there to track it from this repo. Finally, since it's already done, I prefer not to annoys people again. Will keep that in mind for next time tho. Sorry for the inconvenience.

**Comment by mathstuf** [comment] 2022-05-21 18:27
Hmm. The "closed as fixed" conflicts with the comment that it's a duplicate of an open issue.

**Comment by dannycolin** [comment] 2022-05-21 18:57
> Hmm. The "closed as fixed" conflicts with the comment that it's a duplicate of an open issue.

I closed it as duplicate. The open issue will remain open until Firefox fixes it on their side. No worries, it still something we'd like to implement but currently it isn't possible without upstream doing some work.

**Comment by mathstuf** [comment] 2022-05-21 19:36
> I closed it as duplicate.

If you did, GitHub still treats them as simple closings:

> [dannycolin](https://github.com/dannycolin) closed this as [completed](https://github.com/mozilla/multi-account-containers/issues?q=is%3Aissue+is%3Aclosed+archived%3Afalse+reason%3Acompleted) [19 hours ago](https://github.com/mozilla/multi-account-containers/issues/1907#event-6654150798)
