### ISSUE TITLE
Support for directory path based containers

### ISSUE THREAD

**Issue by justmarks** [mozilla/multi-account-containers#1254] opened 2018-09-05 18:05 UTC
I have a service whose URL structure is similar to GitHub where there is a common domain and the individual instances of the service are determined by the directory path, e.g. https://github.com/google/tink where Google is an organization container and tink is the open source project.

My ideal is to use your extension and have each tab run under the context of a different identity.  Unfortunately, this extension doesn't support the directory path containers.

Scenario:
I want to access http://myservice.com/OrgA/Proj1 with identity A and http://myservice.com/OrgB/Proj2 with identity B

**Comment by dscho** [comment] 2018-10-03 14:54
@justmarks I fear that we would have to implement this feature ourselves (see https://github.com/mozilla/multi-account-containers/issues/1259).

Also, this seems to be a duplicate at *least* of #976 (which was marked as a duplicate of #473, although I disagree that it is: path-based distinction is a much more specific thing than full URL-based distinction).

**Comment by kendallcorner** [comment] 2019-12-06 20:39
Hi, yes this looks like a duplicate of (or heavily related to) the above references as well as #691. Please vote (:+1:) or discuss on those issues to show your interest. I'll close this, but feel free to request a reopen if you think it's a different issue.

**Closed by kendallcorner** 2019-12-06 20:39 UTC
