### ISSUE TITLE
All container config reset

### ISSUE THREAD

**Issue by djmitche** [mozilla/multi-account-containers#1420] opened 2019-05-20 21:04 UTC
- Multi-Account Containers Version: 6.1.0
- Operating System + Version: Fedora 29
- Firefox Version: 66.0.4
- Other installed Add-ons + Version + Enabled/Disabled-Status:
 * Facebook Container
 * Firefox Color
 * Firefox Multi-Account Containers
 * React Developer Tools

### Actual behavior

Containers menu shows "Personal", "Work", "Banking", etc., and not my Google Cloud container.

### Expected behavior

https://console.cloud.google.com/ and a few related pages were configured to open in a dedicated container.  They no longer do -- and I don't even see that container in my preferences.

### Notes

Could this have been caused by the add-on cert issue a few weeks ago?

**Comment by y0lopix** [comment] 2019-05-22 19:16
I have the same issue since I updated to Firefox stable 67.0

**Comment by NenoLoje** [comment] 2019-05-22 19:59
> I have the same issue since I updated to Firefox stable 67.0

Same here, after upgrading to 67.0 the configuration was reset.

**Comment by lhorace** [comment] 2019-05-23 04:01
Hello everyone,

What OS did this happen on?

Cheers

**Comment by freewil** [comment] 2019-05-23 04:02
MacOS

**Comment by lhorace** [comment] 2019-05-23 04:05
That's MacOS for everyone? I can't reproduce here on Ubuntu 18.04 after upgrading to Firefox 67.0, however it's useful information for the developers.

**Comment by djmitche** [comment] 2019-05-23 04:17
> Operating System + Version: Fedora 29

**Comment by falolaf** [comment] 2019-05-23 04:35
I have seen reports that FF67 creates a new profile. Could that be the issue here? Have a look in about:profiles.

**Comment by NenoLoje** [comment] 2019-05-23 06:17
> That's MacOS for everyone?

It's Windows 10 here.

**Comment by NenoLoje** [comment] 2019-05-23 06:19
> Have a look in about:profiles.

Good idea, but it only shows the default profile.

However, FF67 has now the ability to disable selected extensions for InPrivate mode. It seems like when you start using this, the container settings reset.

**Comment by y0lopix** [comment] 2019-05-23 12:49
> However, FF67 has now the ability to disable selected extensions for InPrivate mode. It seems like when you start using this, the container settings reset.

It could be that. I disabled and I re-enabled the Firefox containers addon in private browsing mode just before I realized that my containers were reset

**Comment by y0lopix** [comment] 2019-05-24 13:26
Also, when disabling the module for Firefox in `about:addons` with this button :
![Screenshot 1](https://user-images.githubusercontent.com/13918281/58330759-e2824500-7e37-11e9-9db7-b6b5201ce84e.png)
All containers are reset and this does not happen when enabling the module. You can see the list of containers in `about:preferences#containers`

**Comment by MisterT87** [comment] 2019-05-28 16:11
> 
> 
> Also, when disabling the add-on for Firefox in `about:addons` with this button :
> ![Screenshot 1](https://user-images.githubusercontent.com/13918281/58330759-e2824500-7e37-11e9-9db7-b6b5201ce84e.png)
> All containers are reset and this does not happen when enabling the add-on. The list of containers is available in `about:preferences#containers` even when the add-on is disabled.

+1 - On Windows 10 x64 (1809) and Firefox 67.0 I have the exact same problem

**Comment by julien-garrigue** [comment] 2019-05-29 16:20
I think this is related to this feature request: https://github.com/mozilla/multi-account-containers/issues/1427

**Comment by dannycolin** [comment] 2022-10-11 22:48
The Armagadd-on (certificat incident) did disable the addons and must have trigged #1236 so I'm closing in favor this one.

**Closed by dannycolin** 2022-10-11 22:48 UTC
Labels: bug
