### ISSUE TITLE
Odd alignment of edit arrow in Ubuntu

### ISSUE THREAD

**Issue by jonathanKingston** [mozilla/multi-account-containers#198] opened 2017-02-16 22:15 UTC
![selection_499](https://cloud.githubusercontent.com/assets/338988/23043760/5a62c510-f495-11e6-8d9c-9de5343185ba.png)

See the "Exit Edit Mode" arrow alignment.

**Comment by kjozwiak** [comment] 2017-02-16 22:35
This is affecting the other platforms as well... It doesn't look aligned correctly. However, it seems like it's a lot worse on Ubuntu.

**macOS 10.12.3 x64:**

<img width="287" alt="macos" src="https://cloud.githubusercontent.com/assets/2602313/23044415/19298f74-f46e-11e6-8936-331ea40ecdb3.png">

Windows 10 Pro x64:

![windows](https://cloud.githubusercontent.com/assets/2602313/23044423/23c2b384-f46e-11e6-83eb-590ca4547d06.png)

**Comment by pdehaan** [comment] 2017-02-17 18:26
Possibly fixed by #204?

**Comment by kjozwiak** [comment] 2017-02-17 21:43
Pulled #204 and it looks like it's fixed under Ubuntu/macOS, however, it still looks a bit uneven under Windows 10...

**Windows 10 Pro x64:**

<img width="355" alt="windows" src="https://cloud.githubusercontent.com/assets/2602313/23083617/87c31ae0-f52c-11e6-9a31-16feb49ed93e.png">

**macOS 10.12.3 x64:**

<img width="331" alt="macos" src="https://cloud.githubusercontent.com/assets/2602313/23083626/95408680-f52c-11e6-8537-92621bafcbab.png">

**Ubuntu 16.04.1 LTS x64:**

<img width="333" alt="ubuntu" src="https://cloud.githubusercontent.com/assets/2602313/23083644/b45821fe-f52c-11e6-9a6d-f5ba10a8d45c.png">

**Comment by Paarmita** [comment] 2018-09-21 05:29
@jonathanKingston Is this issue still open? Can I take this up?

**Comment by yatri1609** [comment] 2018-09-23 18:29
@groovecoder @jonathanKingston Can I take this up as I think it will help or get familiar with the project too ?

**Comment by groovecoder** [comment] 2018-09-24 19:56
@Paarmita - if you can reproduce this issue, yes - it seems like a good first bug.

**Comment by kushinauwu** [comment] 2018-10-06 14:41
Can I take this issue up?

**Comment by groovecoder** [comment] 2018-10-07 13:15
I think @Paarmita or @yatri1609 may already be working on this one?

**Comment by revealtheweb** [comment] 2019-10-02 14:43
Improve Firefox CoHi @groovecoder, I'm an applicant from Outreachy, and I would like to work on this feature with your guide. Please I would appreciate all relevant information to begin work on this.
Thanks.

**Comment by revealtheweb** [comment] 2019-10-02 14:44
Hi @groovecoder, I'm an applicant from Outreachy, and I would like to work on this feature with your guide. Please I would appreciate all relevant information to begin work on this.
Thanks.

**Comment by maxxcrawford** [comment] 2019-10-03 16:10
@revealtheweb Please see the [wiki](https://github.com/mozilla/multi-account-containers/wiki/Outreachy-(Round-19)-Applicant-Contribution-Process) for more information. This issue is all yours!

**Comment by revealtheweb** [comment] 2019-10-03 21:57
Thanks @maxxcrawford. I will be working on the issue now. Will update as I progress

**Comment by revealtheweb** [comment] 2019-10-22 11:08
Hello @maxxcrawford, I've just sent a PR for this issue. Please check and give feedback.
PS. I'm also available to more issues.

**Comment by revealtheweb** [comment] 2019-10-25 13:23
@maxxcrawford @groovecoder

**Comment by groovecoder** [comment] 2019-12-09 22:02
Fixed in https://github.com/mozilla/multi-account-containers/pull/1601/commits/b0661f79aac0d47be35b20b951f24d6454c4b53f

**Closed by groovecoder** 2019-12-09 22:02 UTC
Labels: bug, good first bug, outreachy-assigned
