### ISSUE TITLE
[Feature Request] Provide way to associate a URL that redirects with a container.

### ISSUE THREAD

**Issue by zepplen** [mozilla/multi-account-containers#1335] opened 2019-01-31 16:16 UTC
I love the multi-account-containers plugin except for one issue.

I am using it to log into multiple AWS accounts. AWS provides an account specific url to allow you to more easily log into your account. When you hit that url it will re-direct you to the default login page (w/o any account specific information) and set a cookie to allow the login page to prefill your "account name" on the login page.

The issue I am running into is the only way to assicate a url to a container is to have landed on the page and check the "Always open in <container>" check box in the container widget. This is not possible if the URL I want to associate returns a 30x redirect (as I never truely land on the page).

I have found a workaround by setting the network.http.redirection-limit to 0, which means I "land" on the account specific url, and can check the box!

I would love a way to associate this url with out having to muck about with the network.http.redirection-limit.

Example Url:
https://my-aws-account-alias.signin.aws.amazon.com/console

**Comment by groovecoder** [comment] 2019-01-31 17:34
I think this is close enough to https://github.com/mozilla/multi-account-containers/issues/719 to close this as a duplicate. If the approach described there doesn't work for you, you can re-open this issue. If it's okay, add a 👍 and/or comment there please.

Duplicate of #719

**Closed by groovecoder** 2019-01-31 17:34 UTC

**Comment by ianlewisau** [comment] 2023-08-12 11:36
This was closed as a duplicate, but #719 does not address the problem. Indeed, it is now 4 years later and this problem still exists. I see it with URLs that require microsoft authentication, which redirects those URLs to login.microsoftonline.com.  The container needs to be set before the redirect occurs.
