### ISSUE TITLE
disable/enable multi container addon resets extension to default state (deletes all containers) 

### ISSUE THREAD

**Issue by gkrawiec** [mozilla/multi-account-containers#2515] opened 2023-03-06 22:14 UTC
### Before submitting a bug report

- [X] I updated to the latest version of Multi-Account Container and tested if I can reproduce the issue
- [X] I searched for existing reports to see if it hasn't already been reported

### Step to reproduce

1. I had the addon configured with multiple containers, each with name, icon, color, etc
2. I disabled the addon for a couple of minutes while debugging (trying to fin addon causing high cpu)
3. I enabled the addon
4. all configuration was deleted. The containers displayed were the default one (personal, shopping, etc)

### Actual behavior

disabling then enabling the addon resets the extension to its default settingss

### Expected behavior

disabling and then enabling the  extension should maintain previous configuration

**Comment by dannycolin** [comment] 2023-03-06 22:30
duplicate of #1236

**Closed by dannycolin** 2023-03-06 22:30 UTC
Labels: bug
