### ISSUE TITLE
Ctrl-. key binding collides with 1password

### ISSUE THREAD

**Issue by sdague** [mozilla/multi-account-containers#2078] opened 2021-07-14 13:13 UTC
### Actual behavior

1password's key binding for opening up the master password prompt on Firefox is Ctrl-. 

Multi account containers binds the same key binding to pop up it's own menu, which blocks 1password from working as expected.  It would be really great to be able to configure this key binding so that it does not collide. Or to turn it off entirely, as popping up the main menu for multi account containers is something I need to do far less often then enter my master password.

### Expected behavior

Some way that 1password and multi account containers don't collide. 

### Steps to reproduce
1. Install 1password addon
2. Install multi account containers addon
3.

**Comment by rpl** [comment] 2021-07-14 15:14
@sdague you can configure the shortcuts from about:addons.

See the following support page to learn how to reach the "Manage Extension shortcuts" view available in about:addons:
- https://support.mozilla.org/en-US/kb/manage-extension-shortcuts-firefox

**Comment by openjck** [comment] 2022-04-10 18:58
This sounds like a duplicate of my issue, #1454, which, to be fair, might also be a duplicate of an earlier issue about customizable keyboard shortcuts.

**Comment by dannycolin** [comment] 2022-07-18 16:43
Closing since someone already pointed out to the documentation to change the default shortcuts of an addon.

**Closed by dannycolin** 2022-07-18 16:43 UTC
