### ISSUE TITLE
Allow user to set default Container to open pages in

### ISSUE THREAD

**Issue by nekromoff** [mozilla/multi-account-containers#936] opened 2017-11-09 00:15 UTC
Steps to reproduce:
Currently, there is 'no content' container used by default.
Allow user set which container should be used by default to open URLs.

Actual results:
No content container is used

Expected results:
User default container is used

**Comment by SoftVision-EmilPasca** [comment] 2017-11-13 10:06
Hi @nekromoff , thanks for reporting this. However, this looks like a duplicate of https://github.com/mozilla/multi-account-containers/issues/906.

**Closed by SoftVision-EmilPasca** 2017-11-13 10:06 UTC
