### ISSUE TITLE
Container list should be reorderable

### ISSUE THREAD

**Issue by psychoslave** [mozilla/multi-account-containers#979] opened 2017-11-17 13:24 UTC
If there is any way to change the order in which containers are displayed, I didn't find it. So at minimum the UX might gain a better discoverability factor of this feature, if it exists.

**Comment by groovecoder** [comment] 2017-11-17 14:54
Duplicate of https://github.com/mozilla/multi-account-containers/issues/330, please upvote and comment there.

**Closed by groovecoder** 2017-11-17 14:54 UTC
Labels: duplicate
