### ISSUE TITLE
[Suggestion] Set a default container

### ISSUE THREAD

**Issue by seniorm0ment** [mozilla/multi-account-containers#1343] opened 2019-02-14 18:12 UTC
So my suggestion is to have the option to set a default container that all web pages default open in.
So if I have two containers, say "Personal" and "Work". Any new tab I open in firefox, I can set it to open in "Personal" and then if I want to open a work tab, I can manually do that. 
(I know there is an option per site, but I'm talking a browser wide default).

This would be good for people who mainly use one container, and don't want to have to keep opening that container. And users who don't they simply won't have to worry about this feature, as they would obviously leave it off.

**Comment by gilgamesh3** [comment] 2019-03-05 08:28
I'm start using the **multi-account-conteiners** just now and this is a feature I really want and need.

**Comment by lhorace** [comment] 2019-03-05 16:13
Seems like a Dup/Related #1318.

**Comment by Z3ROGRAV1TYx** [comment] 2019-03-08 20:12
> 
> 
> Seems like a Dup/Related #1318.

I hadn't seen that I guess just due to the naming scheme. Any clue if there are any plans to implement a feature as such?

**Comment by lhorace** [comment] 2019-03-15 02:50
With votes and someone willing to work on it and submit a PR? AFAIK, this repository is in maintenance mode and patches only.

**Comment by groovecoder** [comment] 2019-03-15 14:34
Yes - votes will help us prioritize. And PRs are welcome, but we are currently focused on other projects right now, so we may not be landing an significant changes or features in this project for a while.

**Comment by NiklasBr** [comment] 2020-01-18 16:35
I would absolutely vote for this to be implemented, but I would very mush like one addition first:

Please allow the ability to set the default container to different containers depending on the computer I am currently using. E.g on my work computer I would like *Container **X*** and on my home computer (both signed in with the same account) I would like default *Container **Y***.

**Comment by mkielg11** [comment] 2020-05-11 08:44
I would also really appreciate this functionality. 
If the feature is to be device-specific, it would be great. I have devices I mainly use for work, and some I mainly use for personal stuff.

**Comment by MatMercer** [comment] 2021-12-26 03:43
Every time I open a link from an external application I want it to go to a default container, not the no container one.

I would really appreciate this functionality.

**Comment by MatMercer** [comment] 2021-12-26 18:10
Looks like this is something that can't be done in this codebase.

This implementation must be made in a lower layer, the ContextualIdentity itself, aka, containers. I created a comment in the META bug from bugzilla and will try to take a look into it in my free time.

https://bugzilla.mozilla.org/show_bug.cgi?id=1191418#c20

**Comment by dannycolin** [comment] 2022-06-13 13:57
Duplicate of #356

**Closed by dannycolin** 2022-06-13 13:57 UTC
Labels: vote for me, Feature request
