### ISSUE TITLE
Container tabs no longer marked with a color

### ISSUE THREAD

**Issue by kuba-orlik** [mozilla/multi-account-containers#747] opened 2017-08-21 13:32 UTC
It used to be the case that container tabs were marked with a color bar, so when I had multiple tabs for the same site but with different accounts opened, I could at a glance tell which tab was related to which account. It would be nice to at least have an option to enable tab coloring

**Comment by jonathanKingston** [comment] 2017-08-22 02:20
Can you provide what version of firefox and the experiment you are using?
Both of this and other details is available in about:support

**Comment by nkestrel** [comment] 2017-08-22 10:43
@kuba-orlik If you are using FF56 trying switching to the default theme.

**Comment by zsaur** [comment] 2017-08-22 11:01
I don't know if this is related but recently the color of the tabs moved from a very visible position at the bottom to a small coloring at the top. And with some full themes the coloring is even less visible

Before:
![containers before](https://user-images.githubusercontent.com/29492330/29562476-fb9dd700-8728-11e7-8bf1-8ebe3f897555.png)

After:
![containe after](https://user-images.githubusercontent.com/29492330/29562491-0a9efdce-8729-11e7-94b3-4837f07470f3.png)

**Comment by jonathanKingston** [comment] 2017-08-22 11:06
@zsaur that looks like 55, this is going to be fixed soon.

As for 56 I can't replicate dark theme issues but others can, so it could be worth testing.

**Comment by zsaur** [comment] 2017-08-22 12:24
Thanks @jonathanKingston . I can confirm it is just a firefox 55 thing (tested with 56.0b4 64-bit)

**Comment by kuba-orlik** [comment] 2017-08-23 18:16
I'm on `55.0b14`.  Switching to the default theme doesn't fix it for me

**Comment by jonathanKingston** [comment] 2017-09-26 02:21
Can someone confirm if this has been resolved?

**Comment by kuba-orlik** [comment] 2017-09-27 16:51
I confirm it works in `55.0b14 (64-bit)` :)

**Comment by kendallcorner** [comment] 2019-12-03 20:41
Hi. We're currently triaging the Multi Account Container issues. This appears to have been fixed, so I'm going to close it. If you don't feel the underlying issue has been resolved, feel free to reopen it with updated steps to reproduce.

**Closed by kendallcorner** 2019-12-03 20:41 UTC
Labels: question
