### ISSUE TITLE
Reordering containers in Manage Containers doesn't apply to new tab context menu.

### ISSUE THREAD

**Issue by itprofessional74** [mozilla/multi-account-containers#1952] opened 2021-01-25 14:40 UTC
### Actual behavior
You can drag and drop containers in the extension menu in the top right corner but it is visual only.  When you click to open a new tab the order remains the same and when you click to manage your containers and the full browser window opens there is no way to change the order there.

### Expected behavior
When you change the order of the containers in the extensions menu they should appear the same way when you choose to open a new container.

### Steps to reproduce
1. Click extension
2. Choose manage containers
3. Change order
4. Click back arrow to save (Why no save button?)
5. Shows correct order (Visual only)
6. Click new tab
7. Order is still the same as it appears in the full extension preference page and not representative of the changes done in the extensions button

### Notes

Also to note when you try to drag a container to the bottom of the sort it doesn't allow you to drag the the complete bottom.  You basically have to drag down to "almost" the bottom and then drag the bottom selection up so it's on the bottom of the list.

Hope this can be fixed easily, or if there is something I should do to try and resolve would be glad to help.

Tested on 84.0.2 (64-bit)

**Comment by ideophone** [comment] 2021-03-25 09:50
also see: _Feature Request / Suggestion: Sorted Container List #1866_

**Comment by chun-yi-chang** [comment] 2022-06-27 11:16
Firefox 101.0.1
Add-ons: uBlock Origin and Multi Container 8.0.7
Re-arranging container order was working correctly. That is, re-arranging in the "Manage Containers" section does reflect in the "+" tab drop down menu.

As soon as I "Enable sync" in the container options, any further re-arrangement stop to be reflected in the "+" drop down menu.

Go back and un-check the "Enable sync" option does not fix this issue.

**Comment by dannycolin** [comment] 2022-07-27 02:34
Since there's no upvote and it is a variant of #1958, I'll close this issue so we avoid duplicates.

**Comment by dannycolin** [comment] 2022-07-27 02:34
duplicate of #1958

**Closed by dannycolin** 2022-07-27 02:34 UTC
Labels: needs: Mozilla Central, Feature Request
