### ISSUE TITLE
The "web.whatsapp.com" website is not opened in the assigned container if it was previously opened in a normal tab

### ISSUE THREAD

**Issue by Softvision-MariusComan** [mozilla/multi-account-containers#1307] opened 2018-11-13 15:03 UTC
**[Affected versions]:**
- Firefox 63.0.1 and above

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- Have a new Firefox profile with the latest version of the "Firefox Multi-Account Containers" add-on (6.0.0) installed from https://goo.gl/GzWFnr.

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites.
2. Open a new tab and navigate to "web.whatsapp.com".
3. Open any container (eg.Work) and navigate to "web.whatsapp.com".
4. Click the "Firefox Multi-Account Containers" toolbar button and check the "Always open in..." option.
5. Open a new tab and navigate to the "web.whatsapp.com" again.
6. Observe the behavior.
 
**[Expected result]:**
- The "web.whatsapp.com" website is opened in the assigned container.

**[Actual result]:**
- The "web.whatsapp.com" website is opened in a normal tab.

**[Notes]:**
- This issue is not reproducible is the "web.whatsapp.com" website was not previously opened in a normal tab before assigning it to a container.
- Attached a screen recording of the issue:
![rec of the issue](https://user-images.githubusercontent.com/31243259/48421560-665ec480-e765-11e8-80c3-a2c57dc2dc4c.gif)

**Comment by mothlyme** [comment] 2018-12-31 11:54
I can confirm this issue persists in most scenarios tested

**Comment by stoically** [comment] 2019-05-04 11:04
Duplicate of https://github.com/mozilla/multi-account-containers/issues/822

**Closed by stoically** 2019-05-04 11:04 UTC
