### ISSUE TITLE
container doesn't stuck to https://www.puzzles-mobile.com/ 

### ISSUE THREAD

**Issue by vsrawat** [mozilla/multi-account-containers#1376] opened 2019-04-18 06:18 UTC
all other sites open from bookmarks in correct containers,
but container doesn't stuck to https://www.puzzles-mobile.com/ 

I have assigned this site a 100 times to a gmail id container, but whenever I open, this open in a new non-gmail container. then, I have to open the container first in a new tab, go there, and open this site from bookmarks. The association is showing "always open in default container" ticked, but the next time it again 

Your assigning containers to current site feature is bugsy and very confusing, once a site is open in a tab, there is no way we can assign a container to it, You should provice some method that an open site can be assigned to a defined container.

I am on w10-64 bit, ff 64 bit 64.0 and add ons updated yesterday.
Thanks.

**Comment by stoically** [comment] 2019-05-04 11:04
Duplicate of https://github.com/mozilla/multi-account-containers/issues/822 - please vote there. Thanks!

**Closed by stoically** 2019-05-04 11:04 UTC
