### ISSUE TITLE
Containers Disappeared!!!

### ISSUE THREAD

**Issue by syberknight** [mozilla/multi-account-containers#2058] opened 2021-05-25 01:38 UTC
- Multi-Account Containers Version: 7.3.0
- Operating System + Version: macOS 11.3.1
- Firefox Version: 88.0.1
- Other installed Add-ons + Version + Enabled/Disabled-Status: none.

### Actual behavior
was needing to troubleshoot a site not working in Containers, so i temporarily disabled the containers extension in the addons page. restarted firefox. then re-enabled the containers plugin. and ALL my custom containers are gone! reset to the default ones.

**Comment by dannycolin** [comment] 2023-01-09 00:25
Duplicate of #1236

**Closed by dannycolin** 2023-01-09 00:25 UTC
