### ISSUE TITLE
New tab button right-click menu "No Container" not working

### ISSUE THREAD

**Issue by Zander671** [mozilla/multi-account-containers#2067] opened 2021-06-08 04:58 UTC
- Multi-Account Containers Version: 7.3.0
- Operating System + Version: Manjaro GNU/Linux 5.12.8
- Firefox Version: 89
- Other installed Add-ons + Version + Enabled/Disabled-Status: None

### Actual behavior
Nothing happens when "No Container" is selected.

### Expected behavior
A new tab with no container is opened.

### Steps to reproduce
1. Right-click on the new tab '+' button
2. Select "No Container"

### Notes
* [support-info.txt](https://github.com/mozilla/multi-account-containers/files/6613518/support-info.txt)

**Comment by JayAndCatchFire** [comment] 2021-06-10 16:47
Duplicate of https://github.com/mozilla/multi-account-containers/issues/1762 from a year ago.

**Comment by JayAndCatchFire** [comment] 2021-07-14 03:00
Try upgrading to Firefox 90 and see if it works now.  It mysteriously started working for me.

**Comment by dannycolin** [comment] 2022-12-28 01:08
Closing. If you still experience this issue, please file a bug on bugzilla.mozilla.org since this menu is generated in Firefox itself.

**Closed by dannycolin** 2022-12-28 01:08 UTC
