### ISSUE TITLE
Manage containers doesn't allow editing list of sites that automatically open in container

### ISSUE THREAD

**Issue by julie777** [mozilla/multi-account-containers#2151] opened 2021-10-08 16:37 UTC
I have a container that I originally set to open google sites. 
I have multiple google accounts so I wanted to create a different container for another google account. 

1. I can't find any way to edit the list of URLs for a given container.
2. which implies that I can't remove google.com from the first container I created.
3. I don't know how to assign google.com + google account to a container.
4. if I have a page open in a container and that page's URL is assigned to that container then choosing to open in new container tab doesn't work. I would think that if I want to force a tab into a different container I should be able to.

Currently I have some tabs that I open to gmail for example, then I switch the google account for that tab. Which allows me to have two different gmail accounts open in different tabs. It would be so much better to actually have a container for each google account.

**Comment by dannycolin** [comment] 2022-07-31 21:58
Closing this issue since @jaoltr explained how to remove a website from a container and that there's alrady another issue opened to manually add a website (See next comment)

**Comment by dannycolin** [comment] 2022-07-31 21:58
Duplicate of #1670

**Closed by dannycolin** 2022-07-31 21:58 UTC

**Comment by boczpeter** [comment] 2023-10-01 17:52
This should be reopened.
The indicated method no longer works. No "Manage Site list" in the options, so I cannot edit my sites list.
FF 117

**Comment by pb6** [comment] 2023-11-10 06:47
https://github.com/mozilla/multi-account-containers/issues/1730#issuecomment-997430333 worked for me today.

> This should be reopened. The indicated method no longer works. No "Manage Site list" in the options, so I cannot edit my sites list. FF 117
