### ISSUE TITLE
Feature request - open a FF tab in completely unique and temporary container.

### ISSUE THREAD

**Issue by tkforbes** [mozilla/multi-account-containers#2011] opened 2021-04-09 14:05 UTC
## Limited list of containers is not a convenient method of isolating activities.

My most common use-case for containers is as a privacy enhancement while browsing the Internet. I have a list of labelled containers that somewhat serve their purpose, such as "work", "news", etc. However, I have found that these do not always accomplish the separation that I am looking to maintain. Here is an example using banking to illustrate. Assume I use a VPN:

I maintain accounts at multiple financial institutions. I do not want any of them (or some tracking service) to detect these relationships. If I associate the domain of those institutions with a common "Banking" container, any visit to one institution could be known by the other and a relationship inferred.

To counter this, I often find myself selecting a container with an unrelated name which is not currently in use each time I open a new tab. I have avoided associating some domains or URLs with container labels so that they do not open in a common environment.

Outside of this example, I almost always open an unused container for any new search or bookmark when using FF.

##  Suggestion.

I suggest that holding down the **+** button to open a new tab and which lists the currently defined containers have an option to create a randomly named container such as 4c210ef9-738d (from the first two parts of uuidgen). The container and its label only exist for the lifetime of the tab. If this was thought to be confusing for new users, it could be enabled as an option in the add-on's settings.

**Comment by tkforbes** [comment] 2021-11-04 13:35
I discovered another FF add-on named Temporary Containers that does what I have suggested. The functionality could be added to Multi Account Containers, but I have an alternative to use for the moment.

**Comment by dannycolin** [comment] 2022-12-28 03:30
Duplicate of #929

**Closed by dannycolin** 2022-12-28 03:30 UTC
