### ISSUE TITLE
Google Redirects - Add specific URLs to a container without going to them and saying open in this container every time

### ISSUE THREAD

**Issue by bcb44** [mozilla/multi-account-containers#1909] opened 2020-11-20 16:23 UTC
- Multi-Account Containers Version: 7.1.0
- Operating System + Version: macOS Big Sur v11.0.1
- Firefox Version: 83.0 (64-bit)
- Other installed Add-ons + Version + Enabled/Disabled-Status: 
AdBlock — best ad blocker	extension	4.24.0	true	jid1-NIfFY2CA8fy1tg@jetpack
DuckDuckGo Privacy Essentials	extension	2020.10.21	true	jid1-ZAdIEUB7XOzOJw@jetpack
Default search engine extensions

### Actual behavior
Downloading a file from Google Drive. Downloading redirects me through a set of intermediate sites that I can't navigate to and add to container because they're automatic redirects. I have my "Google" container so that its "Limited to designated sites". Because I can't whitelist these sites, it directs me outside my container and gets me stuck in a redirect loop.

### Expected behavior
Either ability to add sites to a container by typing in a URL or some other way that I can limit google cookies to only google sites and handle redirect from those sites easily

### Steps to reproduce
1. Install Multi-Account Container Add-On
2. Make a new "Google" container
3. Navigate to google.com, myaccount.google.com, drive.google.com, docs.google.com and sheets.google.com and while on each site, add them to a "Google" container and hit the "Always open this site in ..." option and select the "Google" container
4. Navigate back to all of these sites and check the box for "yes, I want to always open this site in ..."
5. Open the settings for the "Google" container and select the "Limit to designated sites" option
6. Navigate to drive.google.com
7. Log in to your google account
8. Click on a file and attempt to download it
9. Redirects outside of container to accounts.google.com or some other url that I can't see and gets stuck in redirect loop, where I'm not able to close the tab because its constantly closing itself and reopening itself

### Notes
I think I'm having this problem with some of my banking accounts too, basically anything where a log in redirects me to a different url and I can't access that URL because its an automatic redirect. I want specific sites to run only in their container and not have access to my other browsing, or not let cookies from my other browsing exist on specific sites. An easy solution in my mind is to add a field in the "Manage site list" option so that you can type in urls there instead of having to actually navigate to them but open to suggestions.

I would really prefer to have the "Limit to designated sites" checked because I don't want to have to actively close and open containers when I want them

Love this idea though, really cool product. Definitely very happy that this exists.

**Comment by xdpirate** [comment] 2020-11-26 09:19
This could easily be solved by having a + button and a text field in the "manage site list" submenu for each container. I can't log in to Google/YouTube because of this and have to manually fiddle with turning off the limit option, trying to log in, adding the subdomain then reenabling the limit option. You should not have to navigate to a domain to add it to a container, typing in the domain name should be possible. Why this wasn't one of the very first implemented features in the first place is beyond me.

**Comment by ShaunaGordon** [comment] 2020-11-30 21:13
As an additional piece of the underlying requested feature, we should be able to do a certain amount of pattern matching.

So `*.google.com` would get all Google subdomains, while `!oauth.google.com` would exclude the OAuth subdomain so it doesn't break other containers (I don't know if that's the subdomain for it, but you get the idea).

**Comment by ShonFrazier** [comment] 2020-12-01 13:46
I would personally find URL pattern matching very useful. `https://bitbucket.org/MyCompany` needs to open in a MyCompany container, while `https://bitbucket.org/SomeOrg` needs to open in another container.

**Comment by moocan** [comment] 2020-12-13 01:09
Hello,

I was looking for a way to add or edit site listed inside `Multi-Account Container`.

It would be very useful to add and edit site directly inside the `Multi-Account Container` add-on using glob pattern as suggested by @ShaunaGordon and/or url matching patterns as suggested by @ShonFrazier without needing to visit each site to add them to a specific container.

As a workaround, it is not perfect but, I'm using `Containerise` add-on on which I can add and affect directly site to specific container using "special" glob patterns (seems to not support negate pattern) and then when a related site is visited, add it to `Multi-Account Container` using `Always open this in a Container` (required if you are using `Teporary Containers` to avoid conflict between `Multi-Account Container` and `Teporary Containers`). But do not enable `Limit to Designated Site` in `Multi-Account Container` because if `Containerise` is matching a site not listed in `Multi-Account Container` for container `A` this will generate an infinite loop with `Containerise` opening container `A` and `Multi-Account Container` closing this container `A` and so on ... needing to click on `close tab` as fast as possible :)

I hope such a feature could be added to `Multi-Account Container`.

Kind Regards

**Comment by utopianknight** [comment] 2021-03-05 07:30
A temporary workaround is to 
1. Uncheck 'Limit to Designated Sites'.
2. Visit the site in question that's causing the redirection loop.
3. Add the site to the container.
4. Recheck 'Limit to Designated Sites'.

It would be better if the addon detects redirection loop, prevent it and ask the user if they want to add it to a container.

**Comment by rkaminsk** [comment] 2021-09-18 09:07
I went to <about:config> and set `network.http.redirection-limit` to `1`. Then I added the sites one by one to the container.

**Comment by dannycolin** [comment] 2022-10-11 00:57
Duplicate of #1670

**Closed by dannycolin** 2022-10-11 00:57 UTC

**Comment by ghjnut** [comment] 2023-10-30 21:55
> I went to about:config and set `network.http.redirection-limit` to `1`. Then I added the sites one by one to the container.

I actually set it to '0' which seemed to catch my redirect auth issue for contacts.google.com
