### ISSUE TITLE
Feature request: always open this site in default

### ISSUE THREAD

**Issue by dgwalter** [mozilla/multi-account-containers#1840] opened 2020-07-31 20:00 UTC
It would be useful to be able to say "Always open this site in default" or where default refers to not opening in a specified container.

**Comment by AnttiBoman** [comment] 2020-08-07 07:54
I came here to report on this bug/feature, and found out it had been done already. So, please, I need this thing about once a week. AFAIU, it should be a very simple change. Thanks!

**Comment by oshanz** [comment] 2020-08-12 01:54
Solution is at here:
https://github.com/mozilla/multi-account-containers/wiki/How-to-remove-a-%22Awlays-open-in%E2%80%A6%22-site-from-a-Container

**Comment by AnttiBoman** [comment] 2020-08-12 07:19
@oshanz The problem is different. For example, if I browse in a "contained" tab and click a link that leads to a site that I want to be decontained, it opens the link within the current container, and I have to manually decontain it. I cannot specify it to always switch to default container. The OP's solution would work. It's also in line with the "Reopen This Site In..." option, so UI-wise it's a good choice.

**Comment by dgwalter** [comment] 2020-08-12 13:01
Not a duplication of #1829, from the way I read it.

If I'm browsing in a custom Reddit container and open a link to YouTube it opens it in the Reddit container, where I am not signed in to YouTube and don't want to be.  (I also don't intend to create a custom YouTube container to avoid this, though that would be a solution.)  I just want to tell it to always open YouTube in default, where I am signed in to YouTube.

**Comment by maxxcrawford** [comment] 2020-08-12 19:13
Marking this as a duplicate of #356 - Specifically, you're looking for the default container to behave like a custom container.

**Closed** 2020-08-12 19:13 UTC
