### ISSUE TITLE
Emoji for Container Icon

### ISSUE THREAD

**Issue by ximex** [mozilla/multi-account-containers#843] opened 2017-09-20 19:56 UTC
Let define the container icon with all the emojis. So there should be no more problems that there is no icon for a situation

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/MAC-599)

**Comment by jonathanKingston** [comment] 2017-09-20 20:35
This likely isn't going to happen as not all platforms support emoji's natively and part of the reason we use the icons is so you can see the tab highlight colour also.

**Comment by Madis0** [comment] 2018-03-24 09:36
To my knowledge, all platforms with proper Unicode support can display emoji in it's colorless mode. That could be taken advantage of in order to color the same emoji with different Container colors.

See also my similar (unfortunately closed) request: #984

**Comment by shmerl** [comment] 2019-12-03 19:29
What platforms don't support Unicode these days? If that's a problem, there can be a fallback for them, but otherwise it should be fine to use any Unicode symbol there really.

I also find the current set of icons very limiting.

**Comment by grahamperrin** [comment] 2021-04-23 17:08
See also: 

* Mozilla bug [1533542 - Tab containers: Need more icons to choose from](https://bugzilla.mozilla.org/show_bug.cgi?id=1533542)

**Comment by felixbecker2** [comment] 2021-05-06 20:30
What is if users can select an arbitrary image (PNG, GIF, with appropriate size)?

**Comment by pandruszkow** [comment] 2021-09-09 11:07
I'm in favour of more customisation. Any .png/.gif/.svg image file should be possible to set as the container image. It would be useful to be able to load the image from a favicon of a particular site too (e. g. download the favicon from Spotify's website if the container is set aside for Spotify only).

**Comment by dannycolin** [comment] 2022-05-21 00:22
duplicate of #2368

**Closed by dannycolin** 2022-05-21 00:22 UTC
Labels: vote for me, Feature request
