### ISSUE TITLE
Allow adding a URL pattern automatically opening in a container

### ISSUE THREAD

**Issue by gelraen** [mozilla/multi-account-containers#1238] opened 2018-07-25 10:04 UTC
In addition to #1227, there is another use case that would be good to have covered: corporate intranet pages. It's usually put under one or very few subdomains, and it would be very useful to just add those to automatically open in Work container, instead of doing it on one-by-one basis as you try opening them.

**Comment by ChaosFreak** [comment] 2019-10-16 20:49
This appears to be a duplicate of https://github.com/mozilla/multi-account-containers/issues/691

**Comment by kendallcorner** [comment] 2019-12-06 20:11
Hi. This looks like it is covered by either #473, #691, or both. Please vote (:+1:) or discuss on those issues to show your interest. I'll close this, but feel free to request a reopen if you think it's a different issue.

**Closed by kendallcorner** 2019-12-06 20:11 UTC
