### ISSUE TITLE
Custom containers no icons displayed

### ISSUE THREAD

**Issue by glasco61** [mozilla/multi-account-containers#928] opened 2017-10-30 12:15 UTC
Container menu displayed with Long press on "Open a new Tab", does not display an icon for the additional containers that I defined.

Icons appear in:
"Multi-Account Containers" Button context menu (Image 1). 
Containers were set up using "+" button in "Multi-Account Containers" context menu. This offers a selection of predefined icons (Image 2).

Icons not displayed in:
"Open a new Tab" long-press context menu (Image 3).
"Manage Containers" page (Image 4), accessed from "Open a new Tab" long-press context menu "Manage Containers" option.

Smaller selection of icons displayed in "Add New Container" pop up (Image 5), activated from button on "Manage Containers" page.

OS Version: Windows 10 Home, Version 1709, build 16299.19
Firefox Version: 56.0.2 (64-bit)

![contissue 171030-1](https://user-images.githubusercontent.com/11871481/32170250-cbd4028c-bd6b-11e7-9ade-31a998f59ef2.jpg)
![contissue 171030-2](https://user-images.githubusercontent.com/11871481/32170251-cbf7fe3a-bd6b-11e7-9693-87a9f2c99226.jpg)
![contissue 171030-3](https://user-images.githubusercontent.com/11871481/32170252-cc123a3e-bd6b-11e7-9232-9903615bd3d3.jpg)
![contissue 171030-4](https://user-images.githubusercontent.com/11871481/32170253-cc33ef6c-bd6b-11e7-9930-b64b25b7b6a7.jpg)
![contissue 171030-5](https://user-images.githubusercontent.com/11871481/32170254-cc5b57b4-bd6b-11e7-8a1a-f733d5fe9433.jpg)

**Comment by SoftVision-EmilPasca** [comment] 2017-10-30 12:26
Hi @glasco61, thanks for reporting this. However, this looks like a duplicate of https://github.com/mozilla/multi-account-containers/issues/745.

**Closed by SoftVision-EmilPasca** 2017-10-30 12:26 UTC
