### ISSUE TITLE
Borring confirmation "Open this site in your assigned container?"

### ISSUE THREAD

**Issue by RredCat** [mozilla/multi-account-containers#2032] opened 2021-04-25 18:33 UTC
I got the latest update of Multi-Account Containers v7.2.0. It has new functionality that added extra boring steps. 

Actual behavior:
I open some siteA in the container1 (I am logged with a work account there).
I'm trying to open siteA in the container2 (I am logged with a private account there). The M-A Containers advice me to open this tab in the container1. Each time I have to confirm - that I want to open siteA in contetainer1 or container2. It is really boring. 

Expected behavior:
I open some siteA in the container1 (I am logged with a work account there).
I'm trying to open siteA in the container2 and it is opened there without any advice.

I am using Multi-Account Containers for separating work and private environments in my browser. I am sharing the same sites in both modes. I understand that somebody needs this feature. But the option's checkbox will be enough for me.

**Comment by grahamperrin** [comment] 2021-04-27 21:00
> Each time I have to confirm - that I want to open siteA in contetainer1 or container2. 

Is this essentially a duplicate of 2017 issue #796? Please see my comment there four days ago.

**Closed** 2021-05-06 09:15 UTC

**Comment by grahamperrin** [comment] 2021-05-06 21:34
Thank you
