### ISSUE TITLE
An extra favicon is wrongly displayed under the last tab, in the container's tabs list when more than 15 tabs are opened

### ISSUE THREAD

**Issue by Softvision-MariusComan** [mozilla/multi-account-containers#956] opened 2017-11-13 14:28 UTC
**[Affected versions]:**
- Nightly 58.0a1

**[Affected Platforms]:**
- All Windows

**[Prerequisites]:**
- Have a Firefox profile with the latest "Multi-Account Containers" add-on version (4.0.3 custom built on 11.08.2017) installed.
- Have at least 15 websites opened in the same container.

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites.
2. Click the "Multi-Account Containers" button from the browser toolbar and choose to view the container from the prerequisites.
3. Scroll down the tabs list.
4. Observe the bottom part of the panel right under the favicon of the last tab

**[Expected result]:**
- The bottom part of the panel is correctly rendered.

**[Actual result]:**
- Part of an extra favicon is displayed.

**[Regression window]:**
Last good revision: a4fb78381ea0fe9fddd36a8ea7b74a63062a1bf3
First bad revision: 66ef885f0b66cb680a3f0734bfbfd8fd385fa104
Pushlog:
https://hg.mozilla.org/integration/autoland/pushloghtml?fromchange=a4fb78381ea0fe9fddd36a8ea7b74a63062a1bf3&tochange=66ef885f0b66cb680a3f0734bfbfd8fd385fa104

**[Notes]:**
- The extra favicon disappears after ~5 second.
- Attached a screen recording of the issue:
![rec of the issue](https://user-images.githubusercontent.com/31243259/32730417-b41e5e92-c88f-11e7-9643-d145a5936de0.gif)

**Comment by Paarmita** [comment] 2018-09-24 08:19
@groovecoder @jonathanKingston Can I take this up ?

**Comment by kushinauwu** [comment] 2018-10-06 14:58
Is this issue still up? I will try to reproduce it and work on it.

**Comment by groovecoder** [comment] 2018-10-07 13:16
@Paarmita if you can reproduce, yes - you can work on this one.

**Comment by olsenme** [comment] 2019-10-03 15:58
If this falls through, could I please work on it?

**Comment by maxxcrawford** [comment] 2019-10-03 16:11
@olsenme I assigned issue #441 to you. If you would prefer this one, let me know and I can switch it for you. Thanks!

**Comment by AlbionaHoti** [comment] 2019-10-03 17:04
@maxxcrawford I am an Outreachy applicant, I would like to work on this task.

**Comment by olsenme** [comment] 2019-10-03 17:49
@maxxcrawford I can do either or both of them.

**Comment by maxxcrawford** [comment] 2019-10-03 19:19
@olsenme We would like to start with a single contribution point to start. Feel free to take on another one after you have a PR submitted for #441. 😄

**Comment by maxxcrawford** [comment] 2019-10-03 19:20
@AlbionaHoti Assigning this to you. Good luck!

**Comment by olsenme** [comment] 2019-10-03 21:30
@maxxcrawford  alright sounds good. Will work on #441 first. Thanks

**Comment by maxxcrawford** [comment] 2019-10-15 19:35
@AlbionaHoti How's this going? Let us know if we can help!

**Comment by kendallcorner** [comment] 2019-12-04 18:00
Hi. We're currently triaging the Multi Account Container issues. I couldn't reproduce this, and I'm thinking it has been fixed, so I'm going to close it. If you don't feel the underlying issue has been resolved, feel free to reopen it with updated steps to reproduce.

**Closed by kendallcorner** 2019-12-04 18:00 UTC
Labels: bug, good first bug, help wanted, outreachy-assigned
