### ISSUE TITLE
Default `Shopping` and `Banking` containers spaw randomly

### ISSUE THREAD

**Issue by benediktms** [mozilla/multi-account-containers#2010] opened 2021-04-09 08:18 UTC
- Multi-Account Containers Version: 7.3.0
- Operating System + Version: Linux (Manjaro)
- Firefox Version: 87.0
- Other installed Add-ons + Version + Enabled/Disabled-Status:
```
1Password – Password Manager	extension	1.24.0	true	{d634138d-c276-4fc8-924b-40a0ea21d284}
Amazon.co.uk	extension	1.4	true	amazon@search.mozilla.org
Bing	extension	1.3	true	bing@search.mozilla.org
Dark Scroll	extension	2.0.0	true	{759d3eb8-baf1-49e0-938b-0f963fdac3ae}
Decentraleyes	extension	2.0.15	true	jid1-BoFifL9Vbdl2zQ@jetpack
DuckDuckGo	extension	1.1	true	ddg@search.mozilla.org
eBay	extension	1.3	true	ebay@search.mozilla.org
Facebook Container	extension	2.1.2	true	@contain-facebook
Firefox Multi-Account Containers	extension	7.3.0	true	@testpilot-containers
Google	extension	1.1	true	google@search.mozilla.org
Grammarly for Firefox	extension	8.872.0	true	87677a2c52b84ad3a151a4a72f5bd3c4@jetpack
Nord Theme	extension	1.3	true	{26e789e7-acf2-4346-9381-ad473c245e43}
React Developer Tools	extension	4.10.1	true	@react-devtools
uBlock Origin	extension	1.34.0	true	uBlock0@raymondhill.net
Vimium	extension	1.66	true	{d7742d87-e61d-4b78-b8a1-b469842139fa}
Wikipedia (en)	extension	1.1	true	wikipedia@search.mozilla.org
ColorZilla	extension	3.3	false	{6AC85730-7D0F-4de0-B3FA-21142DD85326}
DuckDuckGo Privacy Essentials	extension	2021.3.26	false	jid1-ZAdIEUB7XOzOJw@jetpack
JetBrains Toolbox Extension	extension	1.19.7559	false	{bf9e77ee-c405-4dd7-9bed-2f55e448d19a}
New Tab Override	extension	15.0.0	false	newtaboverride@agenedia.com
Redux DevTools	extension	2.17.1	false	extension@redux.devtools
Web Search Navigator	extension	0.4.17	false	{ffadac89-63bb-4b04-be90-8cb2aa323171}
```

### Actual behavior
For some reason, the default `Shopping` and `Banking` containers will get infinitely duplicated:

![image](https://user-images.githubusercontent.com/48836135/114150021-76b60200-9913-11eb-8f97-b95fd0ddb60a.png)

This could have something to do with setting up containers on a new browser (e.g. in a VM or just a different machine), or when setting up containers on Firefox Nightly and enabling sync. Deleting them works but they will simply respawn after browsing/opening a few tabs.

### Expected behavior
Containers should sync normally and not cause themselves to replicate.

### Steps to reproduce
1. Install containers and enable sync on a Firefox browser
2. Install and enable sync on a Firefox Nightly browser
3. Browse on the Nightly browser for a bit
4. Switch back to the standard firefox and browse.

### Notes
It would be good to be able to choose if you want to start with the 4 default containers, or possibly add some check to ensure that only one container with a given name can exist at a time.

**Comment by grahamperrin** [comment] 2021-04-29 02:45
Is this a duplicate of #1912?

If so, please close. Thank you.

**Comment by dannycolin** [comment] 2022-12-28 03:31
Variant of #1696

**Closed by dannycolin** 2022-12-28 03:31 UTC
