### ISSUE TITLE
Defaulting to no container not possible after setting default container for website

### ISSUE THREAD

**Issue by samo296** [mozilla/multi-account-containers#2320] opened 2022-03-27 09:07 UTC
Once you set "always open in container xyz", you cannot go back. If you open a new tab and go to a site for which you set a default container, you're asked if you want to open it in the assigned container, or in "Container" (which means _no_ container, lol, did someone test this shit?). If you choose (no) "Container" and check "remember decision", it's not remembered but instead you're asked again and again. You cannot go back to defaulting to no container.

**Comment by shtrom** [comment] 2022-03-28 23:24
Somewhat related to #2314?

**Comment by achernyakevich-sc** [comment] 2022-04-02 08:43
@samo296 It looks like your issue is just another duplicate of others that could be related to misunderstanding of the related MAC feature. :)

I would like to recommend to carefully read [this comment](https://github.com/mozilla/multi-account-containers/issues/1741#issuecomment-1067194288) that will bring understanding how it works.

Yes, current implementation of this feature is not good and I would ask you to check #2294 and vote for it. Maybe after collecting many likes MAC developers will detect it and implement. :)

As well if you just need to cancel your decision to open some site in some container then there are several solutions for it. Probably the simplest for you would be - click MAC button in Firefox toolbar, click Manage Containers at the bottom of panel, select container that the site configured to be open in by default, click `Manage Site List..` and delete the site from the list by click to trash button. After that the site will be open in the container you try to open it in without switching to the assigned on.

At the end, as this issue looks as duplicate, could you close it and this will shows other that it is not a bug and comments point to valuable information. :)

And... more votes for #2294 - more chance that soon this feature will receive more reasonable interface.

**Comment by samo296** [comment] 2022-04-05 12:40
@achernyakevich-sc I guess you're right. This dialog is basically a delayed "Are you sure?" after setting a default container, with a UI that is nearly impossible to decrypt. It is anticipating the pretty likely circumstance that someone confuses the almost identically looking button for the "Always open in" with the MAC extension button, erroneously setting a default container, only to offer no way to revert it... and on top of that  it is even disguising itself as an option to do exactly that. It's actually kinda funny.

**Comment by dannycolin** [comment] 2023-01-08 20:56
You need to remove the assignment. See https://github.com/mozilla/multi-account-containers/wiki/Frequently-asked-questions#remove-always-open-in-site-from-a-container

There's also a feature request (#1442) to honor manually reopening a tab in the select (no) container. Closing in favor of this.

**Closed by dannycolin** 2023-01-08 20:56 UTC
