### ISSUE TITLE
"Always open this in a container" breaks history

### ISSUE THREAD

**Issue by ChrisTheCat** [mozilla/multi-account-containers#1934] opened 2020-12-30 05:13 UTC
I have set a number of sites to "Always open this in a container" and then chose "Remember my decision for this site."

So, for example, I have www.nytimes.com set to always open in the News container, and to remember that decision. I spend some time searching the web, and then I go to my bookmarks and choose the New York Times homepage. The current browser tab briefly flashes, then loads the NYT in the container. There is no history - the back button is disabled. There doesn't appear to be any way to get back to the thing I was looking at before I loaded NYT from a bookmark. Reopen closed tab doesn't work either.

**Comment by securingmom** [comment] 2021-01-01 21:01
> the back button is disabled

Because the tab did not previously exist.

Once opened:  open different articles by clicking.  Is that history present?

**Comment by ChrisTheCat** [comment] 2021-01-01 23:05
I don't think you understood what I was saying. I don't really care that the new tab did not previously exist. What i care about is that the current tab is closed and unrecoverable.

Load web page A
Load web page B 
Load web page C
Load web page D
--> History works, two back arrows returns to web page B

Load web page A
Load web page B
Load web page C
Load web page D
Load web page E that always opens in a container
--> History does not work, it is impossible to use the back arrows or the Undo Closed Tab tool to get back to web page B.

Why does opening page E in a container mean that the tab with pages A, B, C, D gets closed and becomes unrecoverable?

**Comment by naoliden** [comment] 2021-04-09 14:11
This is so important! Hopefully it'll get fixed, but no one seems give an official reply to these issues.

**Comment by ncallaway** [comment] 2021-04-29 02:07
This is also a problem when leaving "isolated containers".

Using the same example, if we make nytimes.com assigned to a container, and then mark that container as "limited to designed sites", then the back button will break when I leave nytimes.com (and switch back to the default container)

**Comment by bdrewery** [comment] 2021-06-03 23:41
#1029 is where other issues like this were sent.

**Comment by dannycolin** [comment] 2022-12-29 02:48
Duplicate of #1029

**Closed by dannycolin** 2022-12-29 02:48 UTC

**Comment by dannycolin** [comment] 2022-12-29 02:50
This is the expected behavior for the current API. There's nothing we can do on the addon side to fix this.
