### ISSUE TITLE
[Feature Request] Show one container, hide all others

### ISSUE THREAD

**Issue by z-nexx** [mozilla/multi-account-containers#1304] opened 2018-11-01 18:21 UTC
It would be nice to be able to hide all containers except one with only one action. This would enable the usage of Multi-Account Containers as a more intuitive session handler. The ability to show/hide containers is already present, so I figured this would be a matter mostly of UI/UX.

Solutions for the UI could be:
- An menu entry below "Show/Hide this container" called "Show only this container"
- A button or link adjacent to the "Edit Containers" button called "Show only this container" which would allow the user to select a container similarly to when selecting a container to edit
- A button or link next to the "Sort Tabs" button called "Hide all other containers"
- Clicking on the container label in the address bar hides all shown containers except the one that the tab belongs to
- A configuration option to only show one container at a time. Interacting with another container (showing it, opening a tab in it, or such) hides all containers except that container (which is ensured to be shown)

Best regards

**Comment by atomsmith** [comment] 2018-11-20 04:50
The [Conex extension](https://addons.mozilla.org/en-US/firefox/addon/conex/) is built on containers, and might provide some of the user interface you are seeking. I have found that its "Only show tabs of the current container" setting works well as long as you confine most of your browsing to one window. Perhaps this will be improved if the extension is developed beyond its current "preview" state.

**Comment by somethingGoneWrong** [comment] 2018-12-10 10:04
come here for the same reason :)
it would be enough an option to activate to be able to show only one container at a time. thx

**Comment by maverick74** [comment] 2018-12-12 15:30
I was here for the same thing as well.

Would be awesome to have this feature in an official Mozilla addon (conex, apparently is not being updated anymore...)

**Comment by grahamperrin** [comment] 2021-04-30 11:49
Implemented by [Conex](https://addons.mozilla.org/addon/conex/).

**Comment by dannycolin** [comment] 2022-11-29 21:21
Duplicate of #1195

**Closed by dannycolin** 2022-11-29 21:21 UTC
Labels: :+1:  Feature Request
