### ISSUE TITLE
Allow us to set the 'new tab URL' per container.

### ISSUE THREAD

**Issue by bluelightzero** [mozilla/multi-account-containers#1219] opened 2018-05-28 13:01 UTC
For example opening a new tab with container B could automatically load "www.websiteB.com" into that new tab.

**Comment by dveditz** [comment] 2018-06-05 17:55
This is also issue #375

**Comment by groovecoder** [comment] 2018-07-16 17:57
Closing as duplicate of #375.

**Closed by groovecoder** 2018-07-16 17:57 UTC
