### ISSUE TITLE
Exclusive use containers - Feature Request

### ISSUE THREAD

**Issue by Llaves** [mozilla/multi-account-containers#1218] opened 2018-05-25 18:56 UTC
Create container mode where container can be used ONLY for the sites specified. Attempts to open other sites will create a new tab.

eg. Let's say I create a container for my gmail account. When I'm done reading my email, I carelessly reuse that tab for other purposes. I've now "contaminated" that account. With this feature, any site visited after gmail would open in a new tab (or the current tab could be reused tied to the default container.

**Comment by ysalmon** [comment] 2018-08-06 06:52
I think a way to implement this without too much trouble would be to decide (optionally) that all websites not associated to a specific container should open in the default container.

A more convoluted way, and a harsher one for the user but also more secure, would be to open each site not assigned to a container in a new and temporary container ; the user would have to assign a container if wishing to visit the site on a regular basis.

**Comment by ysalmon** [comment] 2018-08-06 07:11
It appears that extension https://github.com/stoically/temporary-containers has a setting to do the latter proposal. However, we are lacking a way to specify that sites should be opened in a specific container, as mentioned in https://github.com/mozilla/multi-account-containers/issues/1227 and https://github.com/stoically/temporary-containers/issues/170

**Comment by kendallcorner** [comment] 2019-12-06 05:02
Hi. This looks like a duplicate of #473. Please vote (:+1:) or discuss on that issue to show your interest. I'll close this, but feel free to request a reopen if you think it's a different issue.

**Comment by risen** [comment] 2019-12-08 12:09
@kendallcorner I checked #473 but it looks like this issue is about something else; it's not about including subdomains, it's about **only** being able to use a container for a individual or particular set of domains. As soon as you move off these domains, you would be switched to the default or another container.

Please reopen…

**Comment by kendallcorner** [comment] 2019-12-09 15:56
Yeah, you're right. That was the wrong one. How about this one #914? Just trying to get input directed towards one place so we can prioritize wanted features. Thanks!

**Comment by risen** [comment] 2019-12-16 09:31
@kendallcorner Apologies for the late reply, but yes, I'd consider this a duplicate of #914 - so please feel free to mark it as such. Thank you!

**Comment by kendallcorner** [comment] 2019-12-16 18:17
perfect, thanks!

**Closed by kendallcorner** 2019-12-16 18:17 UTC
Labels: enhancement
