### ISSUE TITLE
Pinned container tab with ambigious container prompt unpinning it on Firefox restart

### ISSUE THREAD

**Issue by andmagdo** [mozilla/multi-account-containers#2272] opened 2022-01-20 04:31 UTC
- Multi-Account Containers Version:  8.0.4 (December 15, 2021)
- Operating System + Version: Ubuntu 21.10 x86_64
- Note: Running with firejail sandbox
- Firefox Version:  96.0.1 (64-bit) - Ubuntu Repository version (however, this occurs on the official PPA as well)
- Other installed Add-ons + Version + Enabled/Disabled-Status:  Ignoring search extensions and such

CanvasBlocker 1.7
Cookie AutoDelete 3.6.0
Dark Reader 4.9.43
FastForward 0.1934
LessPass 9.6.5
uBlock Origin 1.40.9b2  (in nightmare mode, but that shouldn't affect anything)

### Actual behavior

When a pinned tab that is under a domain set to always open in x container, but not set to ignore the prompt, in a container that is not x container (in my case, set to open in x, but using default), when Firefox restarts, the extension page that asks which container to use is not pinned.

### Expected behavior

The extension page that pops up is a pinned tab. I understand that the method is to close the tab and open an extension tab, but (I have no experience with webextensions) possibly detect if the tab is pinned before and open the tab accordingly.

### Steps to reproduce
1. Set domain to always open in a container
2. Open said domain in another container and ignore the prompt
3. Pin that tab
4. Restart Firefox

### Notes

Similar to other bugs that do this, #1921
I think this should be a separate bug due to both the age of that bug and the slight different behavior.

**Comment by dannycolin** [comment] 2022-12-29 03:26
Duplicate of #1921

**Comment by dannycolin** [comment] 2022-12-29 03:27
It has been fixed upstream (See comment on the bug mentioned above).

**Closed by dannycolin** 2022-12-29 03:26 UTC
