### ISSUE TITLE
can't open new tab in default container

### ISSUE THREAD

**Issue by terrizgit** [mozilla/multi-account-containers#1020] opened 2017-12-02 00:09 UTC
In this article https://blog.mozilla.org/tanvi/2017/10/03/update-firefox-containers/

it says "With the plus button (or ctrl+T), you will get a tab in the Default Container." This was working for me. However, now, whether I use the plus button or cmd-T (I'm on a Mac), or cmd-plus button, it opens in the same container. I can't get a new tab to open in the default container.

**Comment by groovecoder** [comment] 2017-12-05 18:59
I can't reproduce this. Do you maybe have some other add-on that changes your new tab behavior?

**Comment by terrizgit** [comment] 2017-12-05 22:16
I have Conex also, but currently it won't open new tabs at all.

**Comment by kendallcorner** [comment] 2019-12-05 20:12
Hi. We're currently triaging the Multi Account Container issues. This can't be reproduced, so I'm going to close it. If you don't feel the underlying issue has been resolved, feel free to reopen it with updated steps to reproduce.

**Closed by kendallcorner** 2019-12-05 20:12 UTC
Labels: needs STR
