### ISSUE TITLE
After the certificate issue disabled the extensions, the containers were reset to default

### ISSUE THREAD

**Issue by ialima** [mozilla/multi-account-containers#1395] opened 2019-05-04 11:31 UTC
Lost everything.
Issue: https://discourse.mozilla.org/t/certificate-issue-causing-add-ons-to-be-disabled-or-fail-to-install/39047

**Comment by stoically** [comment] 2019-05-04 11:32
Sorry about your containers.

Duplicate of #864

**Closed by stoically** 2019-05-04 11:32 UTC

**Comment by ialima** [comment] 2019-05-04 11:39
Sure it's the same question? There the problem seems to be about tabs that were closed when deactivating the extension. Not about containers reset after disabling forced by a failure of Mozilla itself.

**Comment by stoically** [comment] 2019-05-04 11:43
The underlying problem is the same - the tabs are closed because the containers are removed upon deactivating the last Add-on with container permissions (contextualIdentities).

**Comment by ialima** [comment] 2019-05-04 12:01
Is that my problem has no relation to the tabs, but okay, I think I understood that the mechanism that closes the tabs is the same that resets the containers, when the extension is disabled.

It's a problem that should get more attention from developers. From scratch, lose all containers and logins saved, no way to recover... It is a very unpleasant thing.

**Comment by LeLobster** [comment] 2019-05-04 16:14
Where is the cookie data stored? I have a backup of my profile from a month ago and would like to restore the containers but I can't find where the container cookies are stored.

**Comment by ramast** [comment] 2019-05-04 16:15
So this problem has affected virtually every user of firefox containers today. With no warning of any kind.
I understand this is open source and is provided as is but is there really no solution whatsoever to this? Have I really lost all my containers and all saves sessions of all websites ?

**Comment by stoically** [comment] 2019-05-04 16:20
@LeLobster They are in `storage/default/<scheme>+++<website-url>^userContextId=<container-id>`

@ramast If you don't have a backup of your profile then the container data is unfortunately gone. IMHO it'd be great if containers would behave like Add-ons and only delete data if the Add-on is actually removed, not just disabled.

**Comment by LeLobster** [comment] 2019-05-04 16:32
@stoically Would I need to copy over something else besides
```
containers.json
/browser-extension-data/@testpilot-containers
```
and `storage/default/....` for the previously containered domains?  
I've restored all those files from backup but I still get a login prompt, though all containers and their settings are successfully restored.

**Comment by stoically** [comment] 2019-05-04 16:37
Sounds about right, though I've never tried manually restoring container data that way. Do you see your containers in Firefox? And opening an "old" container gives you a login page though the cookie should be there?

**Comment by LeLobster** [comment] 2019-05-04 16:38
Exactly, all the containers with their correct icon and name are there. Even whitelisted websites open in their previously selected container. It's just not "reading" the cookies because I'm not logged in anywhere.

**Comment by stoically** [comment] 2019-05-04 16:42
Maybe the storage needs to be referenced in some internal db somewhere then. I'm afraid I'm unable to help here. Only alternative that comes to mind is restoring the whole old profile and porting "missing" data from the new profile to the old one.

**Comment by LeLobster** [comment] 2019-05-04 16:56
This whole certificate debacle turns out to be a little more inconvenient than I at first thought, but thank you for the quick replies either way. I'll see what I can salvage.  

Container data is completely separate from Mozilla's `cookies.sqlite` right?

**Comment by stoically** [comment] 2019-05-04 17:08
Oh. It's quite possible that cookies, also from containers, are actually in that `.sqlite` and not in `storage/default`. Sorry for the confusion.

**Comment by LeLobster** [comment] 2019-05-04 17:37
Yeah looks like it is. If I use the `cookies.sqlite` from my old backup I am logged in on the containered websites but as soon as I copy over the `.sqlite` file from my recent profile it logs me out everywhere.

**Comment by mrjohnjones** [comment] 2020-03-22 21:15
This is dumb. Thanks a lot. The developers on this one need their head checked.
