### ISSUE TITLE
Can you make the tab colors more prominent?

### ISSUE THREAD

**Issue by stanfieldr** [mozilla/multi-account-containers#1584] opened 2019-11-20 16:39 UTC
Hey guys really like this extension. My use case is for differentiating my development environments from production. Currently there is only an underline on tabs that contain production sites. My whole idea behind this is if I come back to the browser after being in the code editor for a while, it will help remind me I'm currently focusing a production tab, not dev.

I think it would be pretty useful to emphasis the container you are currently working in. If the color was more in your face like this extension: https://addons.mozilla.org/en-US/firefox/addon/colorfultabs/?src=search

Perhaps some people may prefer something more subtle, so a style option could be added for how to indicate what container you're in.

This could also be great from a privacy perspective. You wouldn't accidentally want to leak data in the wrong container.

**Comment by GrantorShadow** [comment] 2019-11-22 10:18
+ 1 to that, also can we have the option to choose our own colors ? 
Any reply would be appreciated, 

Thanks

**Comment by kendallcorner** [comment] 2019-12-05 17:08
Hi. This looks like a duplicate of #1145 . Please vote (:+1:) or discuss on those issues so they are more likely to be completed. I'll close this, but feel free to reopen if you think it's a different issue.

**Closed by kendallcorner** 2019-12-05 17:08 UTC
Labels: enhancement
