### ISSUE TITLE
[Feature Req] sites without container rule to open in a "default" container 

### ISSUE THREAD

**Issue by andrewcrook** [mozilla/multi-account-containers#1641] opened 2020-02-16 20:34 UTC
When I open links from a site which is containerised in its own container say Twitter the links open under the same container (Twitter) as the original site, unless they have their own container rule.

It would be beneficial to have  a "default" container in which all sites which don't have a container rule, assigned to them, are automatically opened in.

**Comment by kendallcorner** [comment] 2020-02-16 22:02
This is a dupe of #356 . Please comment and upvote there.

**Closed by kendallcorner** 2020-02-16 22:02 UTC
