### ISSUE TITLE
Launching in specific container from command line?

### ISSUE THREAD

**Issue by Dmitresso** [mozilla/multi-account-containers#1710] opened 2020-04-14 08:46 UTC
Does ability of launching some website in some sontainer exist?
It could work the following way: if container with specified name exists, website will be opened inside it. If doesn't exist, opened "by default".
It's also to be a nice feature to replace containers between themselves.

**Comment by psinh** [comment] 2020-07-28 00:52
This will be nice feature. 
My use case is to launch different containers with the same saml login endpoint for AWS console from cli.
This will enable me to script logging to aws consoles (one per container) with different logins.

**Comment by perlancar** [comment] 2020-09-18 04:08
+1. However, I've never encountered any add-on with CLI hooks.

**Comment by webframp** [comment] 2021-12-16 01:48
Agreed, this feature is one of the primary reasons I use FF these days.

I have several cli apps that use oidc auth and it would be super useful to be able to launch a url in a specific container tab via the command line

**Comment by dannycolin** [comment] 2022-12-06 05:13
Duplicate of #365

**Closed by dannycolin** 2022-12-06 05:13 UTC
