### ISSUE TITLE
Feature Request: Option to automatically exit container

### ISSUE THREAD

**Issue by antoni-k** [mozilla/multi-account-containers#1434] opened 2019-06-08 11:41 UTC
This is a feature request for an option that would allow a container to act much like the Facebook Container extension - it would only activate when a listed site is opened, and deactivate when you navigate to a site which is not on that list.

**Comment by antoni-k** [comment] 2019-06-08 12:01
Something like [this addon](https://addons.mozilla.org/en-US/firefox/addon/container-outgoing-links/) would be great.

**Comment by SamSirry** [comment] 2019-07-12 22:38
With this requested feature, following links from Facebook may still expose you, because Facebook appends the ClientID to the URLs which you click to from its site, and when you land on another container, trackers can link this container with the Facebook container, defeating the usefulness of using containers in the first place.
P.s.: Even if you disable 3rd party cookies, that doesn't help. However, disabling trackers *might* help.

**Comment by Dormann** [comment] 2019-08-02 16:28
Then, all you need is an option to allow sanitization of URL like these addons do : 
- https://addons.mozilla.org/en-US/firefox/addon/link-cleaner/
- https://addons.mozilla.org/en-US/firefox/addon/clean-links-webext/

In fact, this would be very intersting if paired with the feature request #691 (Always open URLs that match a pattern in a container).

**Comment by mikepurvis** [comment] 2019-09-08 03:01
I think what this request boils down to is that there are two mental models of what a container is— there are site containers (like Google, Facebook, etc) and session containers (private browsing is like this).

Right now the extension treats everything as a session container, but it really shouldn't, or should be explicit about what the differences are in behaviour. But yes, it should be possible to supply a list of URL patterns that will _always_ open in container X, where any links which are opened from within an X container that don't match the list are opened in a private, temporary, or non-container tab.

**Comment by kendallcorner** [comment] 2019-12-09 15:59
Hi. This looks like a duplicate of #914. Please vote (:+1:) or discuss on that issue to show your interest. I'll close this, but feel free to request a reopen if you think it's a different issue.

**Closed by kendallcorner** 2019-12-09 15:59 UTC
