### ISSUE TITLE
Root domain or domain template in the Site List

### ISSUE THREAD

**Issue by emuzychenko** [mozilla/multi-account-containers#1833] opened 2020-07-27 14:02 UTC
The "Always open this site in..." function always adds the entire domain of the current URL to the Site List. In many cases, only the root domain should be added instead.

For example, I wanted to open all Live Journal blogs in the same container to keep my session authorization. Each blog has the "<username>.livejournal.com" domain name in the URL. If I add my own blog (emuzychenko.livejournal.com) to the Site List, using the "Open Link in New ... tab" function with any other LJ user opens the new tab with no container. Default container for the root domain is not available.

I wanted to open any *.livejournal.com URL in the appropriate container. Maybe adding the root domain to the Site List would be enough, but I unable to do that. If I try to open livejournal.com, it redirects to www.livejournal.com, and there is no way to correct domain name before adding it to Site List.

The same problem occurs with some other sites (docs.microsoft.com, msdn.microsoft.com etc.) that share cookies for the logon session.

The simplest way to solve the problem is to add the ability to edit the domain name before/after adding it to the Site List, and allow a kind of template (*.livejournal.com) to be added to the Site List.

I use FireFox 78.0.2 ESR and Multi-Account Containers 7.0.2.

**Comment by Rasmis** [comment] 2020-10-04 11:48
+1. I want to reserve the Google container to Google products, but that breaks the Google calendar, because it requires scripts from hundreds of *.google.com-domains. E.g. people-pa.clients6.google.com

**Comment by ChrisTheCat** [comment] 2020-12-30 05:14
+1 this would be great.

**Comment by fabianski7** [comment] 2021-02-05 02:52
[containerise](https://addons.mozilla.org/pt-BR/firefox/addon/containerise) supports wildcards domains, as trash.fuckgoogle.com. Although it does not have some functions of this extension, he can at least do that

**Comment by grahamperrin** [comment] 2021-04-23 21:26
Some overlap with 2017 issue #839

**Comment by grahamperrin** [comment] 2021-04-25 13:27
From opening post <https://github.com/mozilla/multi-account-containers/issues/1833#issue-666320259>:

> … no container. … any `*.livejournal.com` URL in the appropriate container. … `livejournal.com`, …

https://livejournal.com/ with **Always In Container**: 

![image](https://user-images.githubusercontent.com/192271/115994677-eabcff00-a5cf-11eb-8fea-b8637f34419f.png)

It's not a panacea – it can not add a domain to a Multi-Account Containers site list – however: 

* it **can** prevent the _no container_ scenario
* it should help you to open URLs in appropriate containers. 

If you like, test the extension with this `man.freebsd.org` address: 

* https://man.freebsd.org/hier(7)

Either: 

1. use the **link context menu** to attempt _no container_ for the link; or 
2. open the link in a **new window**. 

The extension should intercept, and offer a choice of containers. 

After the page loads, there'll be redirection to a page at the `www.freebsd.org` site. 

----

https://github.com/tiansh/always-in-container/issues/6

**Comment by kurahaupo** [comment] 2021-08-29 07:10
Since this issue is pinned, I'll note that it seems to highlight the same underlying limitation that has given rise a very large number of similar requests:

**You can't add a domain without first loading a page from that domain.**

1. Having to load the first page from a domain _without_ container protection exposes the user in the very way that containers are intended to prevent. We need a more prophylactic process, ideally allowing wildcards.
2. Having to load a page and then add the domain is quite slow and cumbersome when dealing with a large number of related domains. We need a bulk handling process.
3. Pages may include components in domains outside the container, particularly JS. Without using the "Network" inspector in the Developer Tools, this can be quite hard to find. We need still need "open this page in container", but it should offer _all_ the domains connected to this page, not just the top-level one.
4. Pages may redirect through a domain outside the container; and often redirections occur (or fail to occur) precisely because session cookies are in the "other" container. This can result in looping reloading when `Limit to Designated Sites` is on. Because it's not possible to get a stable page load in the other domain, there's no opportunity to add its domain to any container.

In particular I note the connection with requests #640, #691,  #719, #837, #839, #1057, #1075, #1180, #1227, #1317, #1335, #1670, #1688, #1833, #1991.

PS: You can in most cases simply load a nonexistent page from the domain, but in some cases that will result in a redirection.

**Comment by nylimited** [comment] 2021-11-19 19:29
I only installed the multi-accunt containers addon yesterday and took me no time at all to find this problem. Lots and lots of sites use multiple servers, espcially banks, and they all miss the container my login page was opened in.

Why on earth is such a simple issue still here, looked at by nobody, after all this time??

**Comment by domigi** [comment] 2022-03-13 12:46
I have been waiting for years for this feature, is there a technical reason why it can't be implemented?
As it is a pinned issue I am optimistic that it should be getting the attention it deserves.

**Comment by achernyakevich-sc** [comment] 2022-03-13 13:21
@emuzychenko I quite carefully track this repo's issues and have found several that have the same problem that you described in your issue. My tracking make me feel that MAC developers will never implement this "quite complicated" because their goal is containers but everything else could be implemented by somebody else in their add-ons as MAC itslef provide great capability for integration (integration with Simple Tab Groups could used as a sample).

In my everyday life I have exactly the same scenario as you initially described. I have resolved it by installing and using of [Containerise](https://addons.mozilla.org/en-US/firefox/addon/containerise/) add-on. It feet perfect for your scenario. So I would like to propose you to try.

As well if it will resolve your issue them probably it would have a reason to close this one and this way show other users that Containerise add-on really helps. :)

**Comment by krisu5** [comment] 2022-03-13 15:31
@achernyakevich-sc But Containerise has this issue instead: https://github.com/kintesh/containerise/issues/172

**Comment by achernyakevich-sc** [comment] 2022-03-13 15:52
> @achernyakevich-sc But Containerise has this issue instead: [kintesh/containerise#172](https://github.com/kintesh/containerise/issues/172)

I have checked the issue you point to. It looks that you search functionality that never was implemented in both add-ons. Both of these use positive matching approach for opening matching URL in certain container. No one of them has anything about prohibition of opening URL in some container. So you case just do not match expectation of both add-ons.

I'm afraid that this will be never implemented by add-ons developers as not matching their vision. :(

**Comment by krisu5** [comment] 2022-03-13 16:00
> No one of them has anything about prohibition of opening URL in some container.

The OP on that issue even says "Something like [Firefox Multi-Account Containers](https://addons.mozilla.org/en-US/firefox/addon/multi-account-containers/) has."

And MAC had this feature for months now, it's called "Limit to Designated Sites"

**Comment by achernyakevich-sc** [comment] 2022-03-13 16:08
> > No one of them has anything about prohibition of opening URL in some container.
> 
> The OP on that issue even says "Something like [Firefox Multi-Account Containers](https://addons.mozilla.org/en-US/firefox/addon/multi-account-containers/) has."
> 
> And MAC does had this feature for months now, it's called "Limit to Designated Sites".

Looks like I have missed this feature. :)

But in this case more correct will be pushing Containerise developer to implement black list support in addition to white list they have implemented.

**Comment by dannycolin** [comment] 2022-06-14 18:06
I'm surpised no one mentioned it before but this seems a duplicate of #473. :) We're also actively working on a PR that'd support this basic use case of `*.domain.tld` in #2352.

Also, for more advanced use cases, we have #691 to support complexe patterns. I'll close this issue and invite all of you to upvote the issues I just mentioned.

**Comment by dannycolin** [comment] 2022-06-14 18:06
duplicate of #473

**Closed by dannycolin** 2022-06-14 18:06 UTC

**Comment by kurahaupo** [comment] 2022-06-15 07:54
@dannycolin this issue was pinned and so had discussion on several related issues.

If this issue is closed, we lose sight of the connection between these issues, and in particular lose track of the fact that wildcards (or subdomains) only solve _some_ of them.

In particular, the last linked PR does not solve the problem with websites that perform redirection when they require authentication getting stuck in an endless loop. (See [notes above](#issuecomment-907741666) for fuller explanation.) This would be addressed by #839 so is there any chance that _that_ issue might be pinned in place of this one?

**Comment by dannycolin** [comment] 2022-06-15 12:15
@kurahaupo The issue related to redirection has also been mentioned on #839 so we haven't lose sight of it. 

If there's any other issue that aren't already addressed by another bug report, please feel free to open a new bug report. This is a better solution than having suggestions buried in a thread like this one.

**Comment by xanoni** [comment] 2023-02-05 06:11
Potential workaround by forcing a `404` response or simply disabling redirects in Firefox: https://github.com/mozilla/multi-account-containers/issues/1670#issuecomment-1416930533
